-- Generated by TypescriptToLua v0.2.0
-- https://github.com/Perryvw/TypescriptToLua
require("typescript_lualib")
modifier_not_on_minimap_mutator = {}
modifier_not_on_minimap_mutator.__index = modifier_not_on_minimap_mutator
function modifier_not_on_minimap_mutator.new(construct, ...)
    local instance = setmetatable({}, modifier_not_on_minimap_mutator)
    if construct and modifier_not_on_minimap_mutator.constructor then modifier_not_on_minimap_mutator.constructor(instance, ...) end
    return instance
end
function modifier_not_on_minimap_mutator.constructor(self)
end
function modifier_not_on_minimap_mutator.IsPermanent(self)
    return true
end
function modifier_not_on_minimap_mutator.IsHidden(self)
    return true
end
function modifier_not_on_minimap_mutator.CheckState(self)
    return {[MODIFIER_STATE_NOT_ON_MINIMAP] = true}
end
