--=======================================================================================
-- Generated by TypescriptToLua transpiler https://github.com/Perryvw/TypescriptToLua 
-- Date: Sun May 13 2018
--=======================================================================================
require("typescript_lualib")
--LinkLuaModifier("modifier_random_spell_mutator","",LUA_MODIFIER_MOTION_NONE)
modifier_random_spell_mutator = {}
modifier_random_spell_mutator.__index = modifier_random_spell_mutator
function modifier_random_spell_mutator.new(construct, ...)
    local instance = setmetatable({}, modifier_random_spell_mutator)
    if construct and modifier_random_spell_mutator.constructor then modifier_random_spell_mutator.constructor(instance, ...) end
    return instance
end
function modifier_random_spell_mutator.IsPermanent(self)
    return true
end
function modifier_random_spell_mutator.IsPurgable(self)
    return false
end
function modifier_random_spell_mutator.IsHidden(self)
    return true
end
function modifier_random_spell_mutator.CheckState(self)
    return {[MODIFIER_STATE_INVISIBLE]=true,[MODIFIER_STATE_INVULNERABLE]=true,[MODIFIER_STATE_TRUESIGHT_IMMUNE]=true,[MODIFIER_STATE_NO_UNIT_COLLISION]=true}
end
function modifier_random_spell_mutator.OnCreated(self)
    if IsClient() then
        return
    end
    self.level_up_duration=5
    self.cast_interval=60
    self.warning_time=(self.cast_interval-5)
    self.random_spells={"bloodseeker_rupture","zuus_lightning_bolt","invoker_sun_strike","kunkka_torrent","bounty_hunter_track","ancient_apparition_cold_feet","disruptor_glimpse","rubick_telekinesis"}
    local unit = self:GetParent()

    TS_forEach(self.random_spells, function(spell)
        local ability = unit:AddAbility(spell)

        ability:SetLevel(1)
    end
)
    self:StartIntervalThink(1)
end
function modifier_random_spell_mutator.OnIntervalThink(self)
    if math.floor(GameRules:GetDOTATime(false,false)%60)==self.warning_time then
        local unit = self:GetParent()

        TS_forEach(self.random_spells, function(spell)
            local ability = unit:FindAbilityByName(spell)

            ability:SetLevel(math.min(math.floor(GameRules:GetGameTime()/5),ability:GetMaxLevel()))
        end
)
    end
    if math.floor(GameRules:GetDOTATime(false,false)%60)==self.cast_interval then
        local unit = self:GetParent()

        local rnd = RandomInt(0,#self.random_spells-1)

        local ability = unit:FindAbilityByName(self.random_spells[rnd+1])

        local targets = FindUnitsInRadius(DOTA_TEAM_GOODGUYS,Vector(0,0,0),nil,10000,DOTA_UNIT_TARGET_TEAM_BOTH,DOTA_UNIT_TARGET_HERO,DOTA_UNIT_TARGET_FLAG_NONE,FIND_ANY_ORDER,false)

        TS_forEach(targets, function(hero)
            if (bit.band(ability:GetBehavior(),DOTA_ABILITY_BEHAVIOR_UNIT_TARGET))==DOTA_ABILITY_BEHAVIOR_UNIT_TARGET then
                unit:SetCursorCastTarget(hero)
                ability:OnSpellStart()
            else
                if (bit.band(ability:GetBehavior(),DOTA_ABILITY_BEHAVIOR_POINT))==DOTA_ABILITY_BEHAVIOR_POINT then
                    unit:SetCursorPosition(hero:GetAbsOrigin())
                    ability:OnSpellStart()
                else
                    if (bit.band(ability:GetBehavior(),DOTA_ABILITY_BEHAVIOR_NO_TARGET))==DOTA_ABILITY_BEHAVIOR_NO_TARGET then
                        ability:OnSpellStart()
                    end
                end
            end
        end
)
    end
end
