--=======================================================================================
-- Generated by TypescriptToLua transpiler https://github.com/Perryvw/TypescriptToLua 
-- Date: Sun May 13 2018
--=======================================================================================
require("typescript_lualib")
--LinkLuaModifier("modifier_resurrection_mutator","",LUA_MODIFIER_MOTION_NONE)
modifier_resurrection_mutator = {}
modifier_resurrection_mutator.__index = modifier_resurrection_mutator
function modifier_resurrection_mutator.new(construct, ...)
    local instance = setmetatable({}, modifier_resurrection_mutator)
    if construct and modifier_resurrection_mutator.constructor then modifier_resurrection_mutator.constructor(instance, ...) end
    return instance
end
function modifier_resurrection_mutator.IsPermanent(self)
    return true
end
function modifier_resurrection_mutator.IsPurgable(self)
    return false
end
function modifier_resurrection_mutator.IsHidden(self)
    return true
end
function modifier_resurrection_mutator.DeclareFunctions(self)
    return {MODIFIER_EVENT_ON_DEATH}
end
function modifier_resurrection_mutator.OnDeath(self,kv)
    local killedUnit = self:GetParent()

    if kv.unit==killedUnit then
        local newItem = CreateItem("item_tombstone",killedUnit:GetPlayerOwner(),killedUnit:GetPlayerOwner())

        newItem:SetPurchaseTime(0)
        newItem:SetPurchaser(killedUnit)

        local tombstone = SpawnEntityFromTableSynchronous("dota_item_tombstone_drop",{})
        tombstone:SetContainedItem(newItem)
        tombstone:SetAngles(0,RandomFloat(0,360),0)
        tombstone:SetAbsOrigin(killedUnit:GetAbsOrigin())
    end
end
