--=======================================================================================
-- Generated by TypescriptToLua transpiler https://github.com/Perryvw/TypescriptToLua 
-- Date: Sun May 13 2018
--=======================================================================================
require("typescript_lualib")

modifier_random_lane_creep_mutator_ai = {}
modifier_random_lane_creep_mutator_ai.__index = modifier_random_lane_creep_mutator_ai
function modifier_random_lane_creep_mutator_ai.new(construct, ...)
    local instance = setmetatable({}, modifier_random_lane_creep_mutator_ai)
    if construct and modifier_random_lane_creep_mutator_ai.constructor then modifier_random_lane_creep_mutator_ai.constructor(instance, ...) end
    return instance
end
function modifier_random_lane_creep_mutator_ai.IsPermanent(self)
    return true
end
function modifier_random_lane_creep_mutator_ai.IsPurgable(self)
    return false
end
function modifier_random_lane_creep_mutator_ai.IsHidden(self)
    return true
end

function modifier_random_lane_creep_mutator_ai.OnCreated(self)
    if IsClient() then
        return
    end

    self:StartIntervalThink(FrameTime())
end

function modifier_random_lane_creep_mutator_ai.OnIntervalThink(self)
    local unit = self:GetParent()
    for i=0,1 do
        local ability = unit:GetAbilityByIndex(i)
        if ability and not ability:IsPassive() and ability:IsCooldownReady() and unit:GetMana() >= ability:GetManaCost(-1) then
            if ability:GetAbilityName() == "dark_troll_warlord_raise_dead" and unit:IsAttacking() then
                unit:CastAbilityNoTarget(ability,-1)
                break
            end

            if ability:GetAbilityName() == "enraged_wildkin_tornado" then 
                break 
            end
            -- Cast stomps
            if ability:GetCastRange(unit:GetAbsOrigin(),nil) < 50 then
                local units = FindUnitsInRadius(unit:GetTeamNumber(),unit:GetAbsOrigin(),nil,ability:GetSpecialValueFor("radius"),DOTA_UNIT_TARGET_TEAM_ENEMY,DOTA_UNIT_TARGET_HERO,DOTA_UNIT_TARGET_FLAG_NONE,FIND_ANY_ORDER,false)
                if #units > 0 then
                    unit:CastAbilityNoTarget(ability,-1)
                end
                break
            end

            local units = FindUnitsInRadius(unit:GetTeamNumber(),unit:GetAbsOrigin(),nil,GetCastRange(unit:GetAbsOrigin(),nil),DOTA_UNIT_TARGET_TEAM_ENEMY,DOTA_UNIT_TARGET_HERO,DOTA_UNIT_TARGET_FLAG_NONE,FIND_NEAREST,false)
            if #units > 0 then
                unit:CastAbilityOnTarget(units[1],ability,-1)
            end
        end
    end
end






