--=======================================================================================
-- Generated by TypescriptToLua transpiler https://github.com/Perryvw/TypescriptToLua 
-- Date: Sun May 13 2018
--=======================================================================================
require("typescript_lualib")

modifier_cooldown_reduction_mutator = {}
modifier_cooldown_reduction_mutator.__index = modifier_cooldown_reduction_mutator
function modifier_cooldown_reduction_mutator.new(construct, ...)
    local instance = setmetatable({}, modifier_cooldown_reduction_mutator)
    if construct and modifier_cooldown_reduction_mutator.constructor then modifier_cooldown_reduction_mutator.constructor(instance, ...) end
    return instance
end
function modifier_cooldown_reduction_mutator.IsPermanent(self)
    return true
end
function modifier_cooldown_reduction_mutator.IsPurgable(self)
    return false
end
function modifier_cooldown_reduction_mutator.IsHidden(self)
    return true
end
function modifier_cooldown_reduction_mutator.OnCreated(self)
    self.reduction_pct=50
    self.mana_regen_pct=0.75
end
function modifier_cooldown_reduction_mutator.DeclareFunctions(self)
    return {MODIFIER_PROPERTY_MANA_REGEN_TOTAL_PERCENTAGE,MODIFIER_PROPERTY_COOLDOWN_PERCENTAGE_STACKING}
end
function modifier_cooldown_reduction_mutator.GetModifierTotalPercentageManaRegen(self)
    return self.mana_regen_pct
end
function modifier_cooldown_reduction_mutator.GetModifierPercentageCooldownStacking(self)
    return self.reduction_pct
end
