--=======================================================================================
-- Generated by TypescriptToLua transpiler https://github.com/Perryvw/TypescriptToLua 
-- Date: Sun May 13 2018
--=======================================================================================
require("typescript_lualib")
--LinkLuaModifier("modifier_no_healthbar_mutator","",LUA_MODIFIER_MOTION_NONE)
modifier_no_healthbar_mutator = {}
modifier_no_healthbar_mutator.__index = modifier_no_healthbar_mutator
function modifier_no_healthbar_mutator.new(construct, ...)
    local instance = setmetatable({}, modifier_no_healthbar_mutator)
    if construct and modifier_no_healthbar_mutator.constructor then modifier_no_healthbar_mutator.constructor(instance, ...) end
    return instance
end
function modifier_no_healthbar_mutator.IsPermanent(self)
    return true
end
function modifier_no_healthbar_mutator.IsPurgable(self)
    return false
end
function modifier_no_healthbar_mutator.IsHidden(self)
    return true
end
function modifier_no_healthbar_mutator.CheckState(self)
    return {[MODIFIER_STATE_NO_HEALTH_BAR]=true}
end
