--=======================================================================================
-- Generated by TypescriptToLua transpiler https://github.com/Perryvw/TypescriptToLua 
-- Date: Sun May 13 2018
--=======================================================================================
require("typescript_lualib")
LinkLuaModifier("modifier_death_explosion_mutator","",LUA_MODIFIER_MOTION_NONE)
modifier_death_explosion_mutator = {}
modifier_death_explosion_mutator.__index = modifier_death_explosion_mutator
function modifier_death_explosion_mutator.new(construct, ...)
    local instance = setmetatable({}, modifier_death_explosion_mutator)
    if construct and modifier_death_explosion_mutator.constructor then modifier_death_explosion_mutator.constructor(instance, ...) end
    return instance
end
function modifier_death_explosion_mutator.IsPermanent(self)
    return true
end
function modifier_death_explosion_mutator.IsPurgable(self)
    return false
end
function modifier_death_explosion_mutator.IsHidden(self)
    return true
end
function modifier_death_explosion_mutator.OnCreated(self)
    self.damage_base=150
    self.damage_per_level=25
    self.aoe=300
    self.delay_ms=900
end
function modifier_death_explosion_mutator.DeclareFunctions(self)
    return {MODIFIER_EVENT_ON_DEATH}
end
function modifier_death_explosion_mutator.OnDeath(self,kv)
    if self:GetParent()==kv.unit then
        local p = ParticleManager:CreateParticle("particles/units/heroes/hero_undying/undying_tombstone_spawn.vpcf",PATTACH_POINT,self:GetParent())

        ParticleManager:SetParticleControl(p,0,self:GetParent():GetAbsOrigin())
        ParticleManager:ReleaseParticleIndex(p)
        local damageTable = {damage=self.damage_base+(self.damage_per_level*self:GetParent():GetLevel()),attacker=self:GetParent(),victim=self:GetParent(),damage_type=DAMAGE_TYPE_MAGICAL}

        local units = FindUnitsInRadius(DOTA_TEAM_NEUTRALS,self:GetParent():GetAbsOrigin(),nil,self.aoe,DOTA_UNIT_TARGET_TEAM_BOTH,DOTA_UNIT_TARGET_HERO+DOTA_UNIT_TARGET_BASIC,DOTA_UNIT_TARGET_FLAG_NONE,FIND_ANY_ORDER,false)

        TS_forEach(units, function(unit)
            damageTable.victim=unit
            ApplyDamage(damageTable)
        end
)
    end
end
