rmdir /S /Q "bin"
mkdir "lod_bin"
mkdir "lod_bin/lod"
copy "manifest.kv" "lod_bin/manifest.kv"
copy "lod/addoninfo.txt" "lod_bin/lod/addoninfo.txt"
echo d | xcopy /S "lod/resource" "lod_bin/lod/resource"
echo d | xcopy /S "lod/scripts" "lod_bin/lod/scripts"
echo d | xcopy /S "lod/particles" "lod_bin/lod/particles"
