"Abilities" {
    // These are the skill categories
    // The numbers are used for sending skills over the network, as well as encryptions
    "skills" {
        // The main skills, usually always avaiable
        "main" {
            
            "morph_int_str_redux"                     "1"
            "morph_str_int_redux"                     "1"
            "morph_agi_int_redux"                     "1"
            "morph_int_agi_redux"                      "1"
            "keeper_of_the_light_innate_redux"              "1"
            "night_stalker_innate_redux"                    "1"
            "skywrath_mage_concussive_break"               "1"
            "slark_essence_shift_strength_lod"            "1"
            "slark_essence_shift_intellect_lod"            "1"
            "slark_essence_shift_agility_lod"            "1"
            "slark_shadow_dance_redux"  "1"
            "ursa_fury_swipes_lod"              "1"
            "ursa_enrage_old"                  "1"
            "pudge_flesh_heap"            "1"
            "silencer_global_break"            "1"
            "silencer_global_disarm"            "1"
            //"juggernaut_healing_ward_mana"      "1"
            "ogre_magi_multicast_lod"            "1"
            "death_prophet_witchcraft"            "1"
            "earthshaker_aftershock_lod"            "1"
            "tinker_rearm_lod"            "1"
            
            "abaddon_aphotic_shield"            "1"
            "abaddon_borrowed_time"            "1"
            "abaddon_borrowed_time_redux"            "1"
            "abaddon_death_coil"            "1"
            "abaddon_frostmourne"            "1"
            "abyssal_underlord_atrophy_aura"            "1"
            "abyssal_underlord_dark_rift"            "1"
            "abyssal_underlord_firestorm"            "1"
            "abyssal_underlord_pit_of_malice"            "1"
            "alchemist_acid_spray"            "1"
            "alchemist_chemical_rage"            "1"
            "alchemist_chemical_rage_redux"     "1"
            "alchemist_goblins_greed"            "1"
            "alchemist_unstable_concoction"            "1"
            "alchemist_transmuted_scepter"      "1"
            "alchemist_aghnaim_magic_redux"     "1"
            "ancient_apparition_chilling_touch"            "1"
            "ancient_apparition_cold_feet"            "1"
            "ancient_apparition_ice_blast"            "1"
            "ancient_apparition_ice_vortex"            "1"
            "antimage_blink"            "1"     
            "antimage_blink_redux"  "1"
            "antimage_mana_break"            "1"
            "antimage_mana_void"            "1"
            "antimage_spell_shield"            "1"
            "antimage_counterspell"        "1"
            "axe_battle_hunger"            "1"
            "axe_berserkers_call"            "1"
            "axe_counter_helix"            "1"
            "axe_culling_blade"            "1"
            "bane_brain_sap"            "1"
            "bane_enfeeble"            "1"
            "bane_fiends_grip"            "1"
            "bane_nightmare"            "1"
            "batrider_firefly"            "1"
            "batrider_flamebreak"            "1"
            "batrider_flaming_lasso"            "1"
            "batrider_sticky_napalm"            "1"
            "beastmaster_call_of_the_wild_boar"            "1"
            "beastmaster_inner_beast"            "1"
            "beastmaster_primal_roar"            "1"
            "beastmaster_wild_axes"            "1"
            "beastmaster_call_of_the_wild_hawk" "1"
            "bloodseeker_blood_bath"            "1"
            "bloodseeker_bloodrage"            "1"
            "bloodseeker_rupture"            "1"
            "bloodseeker_thirst_lod"            "1"
            "bloodseeker_blood_bath2"           "1"
            "bounty_hunter_jinada"            "1"
            "bounty_hunter_shuriken_toss"            "1"
            "bounty_hunter_track"            "1"
            "bounty_hunter_wind_walk"            "1"
            "brewmaster_drunken_brawler"            "1"
            "brewmaster_drunken_haze"            "1"
            "brewmaster_primal_split"            "1"
            "brewmaster_thunder_clap"            "1"
            "brewmaster_cinder_brew"            "1"
            "bristleback_bristleback"            "1"
            "bristleback_quill_spray"            "1"
            "bristleback_viscous_nasal_goo"            "1"
            "bristleback_warpath"            "1"
            "broodmother_incapacitating_bite"            "1"
            "broodmother_insatiable_hunger"            "1"
            "broodmother_spawn_spiderlings"            "1"
            "broodmother_spin_web"            "1"
            "centaur_double_edge"            "1"
            "centaur_hoof_stomp"            "1"
            "centaur_return"            "1"
            "centaur_stampede"            "1"
            "chaos_knight_chaos_bolt"            "1"
            "chaos_knight_chaos_strike"            "1"
            "chaos_knight_phantasm"            "1"
            "chaos_knight_reality_rift"            "1"
            "chen_hand_of_god"            "1"
            "chen_holy_persuasion"            "1"
            "chen_penitence"            "1"
            "chen_test_of_faith"            "1"
            "chen_divine_favor"                 "1"
            "clinkz_death_pact"            "1"
            "clinkz_searing_arrows"            "1"
            "clinkz_strafe"            "1"
            "clinkz_wind_walk"            "1"
            "clinkz_burning_army"         "1"
            "crystal_maiden_brilliance_aura"            "1"
            "crystal_maiden_crystal_nova"            "1"
            "crystal_maiden_freezing_field"            "1"
            "crystal_maiden_frostbite"            "1"
            "dark_seer_ion_shell"            "1"
            "dark_seer_surge"            "1"
            "dark_seer_vacuum"            "1"
            "dark_seer_wall_of_replica"            "1"
            "dazzle_poison_touch"            "1"
            "dazzle_shadow_wave"            "1"
            "dazzle_shallow_grave"            "1"
            "dazzle_weave"            "1"
            "dazzle_bad_juju" "1"
            "dazzle_bad_juju_redux" "1"
            "death_prophet_carrion_swarm"            "1"
            "death_prophet_exorcism"            "1"
            "death_prophet_silence"            "1"
            "disruptor_glimpse"            "1"
            "disruptor_kinetic_field"            "1"
            "disruptor_static_storm"            "1"
            "disruptor_thunder_strike"            "1"
            "doom_bringer_doom"            "1"
            "doom_bringer_devour_lod"     "1"
            "doom_bringer_scorched_earth"            "1"
            "doom_bringer_infernal_blade"            "1"
            "dragon_knight_breathe_fire"            "1"
            "dragon_knight_dragon_blood"            "1"
            "dragon_knight_dragon_tail"            "1"
            "dragon_knight_elder_dragon_form"            "1"
            "drow_ranger_frost_arrows"            "1"
            "drow_ranger_marksmanship"            "1"
            "drow_ranger_marksmanship_redux"        "1"
            "drow_ranger_wave_of_silence"            "1"
            "drow_splitshot"            "1"
            "drow_ranger_multishot"            "1"
            "marksmanship_int"                        "1"
            "marksmanship_str"                        "1"     
            "earth_spirit_boulder_smash"            "1"
            "earth_spirit_geomagnetic_grip"            "1"
            "earth_spirit_magnetize"            "1"
            "earth_spirit_rolling_boulder"            "1"
            "earthshaker_echo_slam"            "1"
            "earthshaker_enchant_totem"            "1"
            "earthshaker_fissure"            "1"
            "elder_titan_ancestral_spirit"            "1"
            "elder_titan_earth_splitter"            "1"
            //"elder_titan_echo_stomp"            "1"             // channels but doesnt stomp
            "elder_titan_echo_stomp_spirit"           "1"         // doesnt cast
            "elder_titan_natural_order"            "1"
            //"ember_spirit_activate_fire_remnant"            "1"
            "ember_spirit_fire_remnant"            "1"
            "ember_spirit_flame_guard"            "1"
            "ember_spirit_searing_chains"            "1"
            "ember_spirit_sleight_of_fist"            "1"
            "enchantress_enchant"            "1"
            "enchantress_impetus"            "1"
            "enchantress_natures_attendants"            "1"
            "enchantress_untouchable"            "1"
            "enchantress_bunny_hop"            "1"
            "enigma_black_hole"            "1"
            "enigma_demonic_conversion"            "1"
            "enigma_malefice"            "1"
            "enigma_midnight_pulse"            "1"
            "faceless_void_chronosphere"            "1"
            "faceless_void_time_lock"            "1"
            //"faceless_void_time_lock_redux"            "1"
            "faceless_void_time_walk"            "1"
            "faceless_void_backtrack"           "1"
            "furion_force_of_nature"            "1"
            "furion_sprout"            "1"
            "furion_teleportation"            "1"
            "furion_wrath_of_nature"            "1"
            "gyrocopter_call_down"            "1"
            "gyrocopter_flak_cannon"            "1"
            "gyrocopter_homing_missile"            "1"
            "gyrocopter_rocket_barrage"            "1"
            "side_gunner_redux"                       "1"
            "huskar_berserkers_blood"            "1"
            "huskar_burning_spear"            "1"
            "huskar_inner_vitality"            "1"
            "huskar_life_break"            "1"
            "huskar_life_break_redux"     "1"
            "huskar_berserkers_blood_lod"   "1"
            "huskar_inner_fire"           "1"
            //"invoker_alacrity_lod"            "1"
            //"invoker_chaos_meteor_lod"            "1"
            //"invoker_cold_snap_lod"            "1"
            //"invoker_emp_lod"            "1"
            //"invoker_forge_spirit_lod"            "1"
            //"invoker_ghost_walk_lod"            "1"
            //"invoker_ice_wall_lod"            "1"
            //"invoker_sun_strike_lod"            "1"
            //"invoker_tornado_lod"            "1"
            //"invoker_deafening_blast_lod" "1"
            "invoker_alacrity_ad"            "1"
            "invoker_chaos_meteor_ad"            "1"
            "invoker_cold_snap_ad"            "1"
            "invoker_emp_ad"            "1"
            "invoker_forge_spirit_ad"            "1"
            "invoker_ghost_walk_ad"            "1"
            "invoker_ice_wall_ad"            "1"
            "invoker_sun_strike_ad"            "1"
            "invoker_tornado_ad"            "1"
            "invoker_deafening_blast_ad" "1"
            //"forged_spirit_melting_strike" "1" // Doesn't work, needs a remake
            "jakiro_dual_breath"            "1"
            "jakiro_ice_path"            "1"
            "jakiro_liquid_fire"            "1"
            "jakiro_macropyre"            "1"
            "juggernaut_blade_dance"            "1"
            "juggernaut_blade_fury"            "1"
            "juggernaut_healing_ward"            "1"
            "juggernaut_omni_slash"            "1"
            "keeper_of_the_light_blinding_light_lod"            "1"
            "keeper_of_the_light_chakra_magic"            "1"
            "keeper_of_the_light_chakra_magic_cooldown"     "1"
            "keeper_of_the_light_illuminate"            "1"
            "keeper_of_the_light_mana_leak"            "1"
            "keeper_of_the_light_recall_lod"            "1"
            "keeper_of_the_light_spirit_form"            "1"
            "keeper_of_the_light_will_o_wisp"   "1"
            "kunkka_ghostship"            "1"
            "kunkka_tidebringer"            "1"
            "kunkka_torrent"            "1"
            "kunkka_torrent_storm"            "1"
            "kunkka_x_marks_the_spot"            "1"
            "legion_commander_duel"            "1"
            "legion_commander_moment_of_courage"            "1"
            "legion_commander_overwhelming_odds"            "1"
            "legion_commander_press_the_attack"            "1"
            "leshrac_diabolic_edict"            "1"
            "leshrac_lightning_storm"            "1"
            "leshrac_pulse_nova"            "1"
            //"leshrac_pulse_nova_redux"       "1"
            "leshrac_split_earth"            "1"
            "lich_chain_frost"            "1"
            //"lich_dark_ritual"            "1"             //No longer in the game
            "lich_frost_armor"            "1"
            "lich_frost_nova"            "1"
            "lich_sinister_gaze"          "1"
            "lich_frost_shield"              "1"
            "life_stealer_feast"            "1"
            "life_stealer_feast_melee"      "1"
            "life_stealer_infest"            "1"
            //"life_stealer_control"              "1"
            "life_stealer_open_wounds"            "1"
            "life_stealer_rage"            "1"
            "lina_dragon_slave"            "1"
            "lina_fiery_soul"            "1"
            "lina_laguna_blade"            "1"
            "lina_light_strike_array"            "1"
            "lion_finger_of_death"            "1"
            "lion_impale"            "1"
            "lion_mana_drain"            "1"
            "lion_voodoo"            "1"
            "lone_druid_rabid"            "1"
            "lone_druid_spirit_bear"            "1"
            "lone_druid_true_form"            "1"
            "lone_druid_spirit_link" "1"
            "luna_eclipse"            "1"
            "luna_lucent_beam"            "1"
            "luna_lunar_blessing"            "1"
            "luna_moon_glaive"            "1"
            "lycan_feral_impulse"            "1"
            "lycan_howl"            "1"
            "lycan_shapeshift"            "1"
            "lycan_summon_wolves"            "1"
            "lycan_wolf_bite" "1"
            "mars_spear"            "1"
            "mars_gods_rebuke" "1"
            "mars_bulwark" "1"
            "mars_arena_of_blood" "1"
            "magnataur_empower"            "1"
            "magnataur_reverse_polarity"            "1"
            "magnataur_shockwave"            "1"
            "magnataur_skewer"            "1"
            "medusa_mana_shield"            "1"
            "medusa_mystic_snake"            "1"
            "medusa_split_shot"            "1"
            "medusa_stone_gaze"            "1"
            "meepo_earthbind"            "1"
            "meepo_geostrike"            "1"
            "meepo_ransack"   		"1"
            "meepo_poof"            "1"
            "mirana_arrow"            "1"
            "mirana_invis"            "1"
            "mirana_leap"            "1"
            "mirana_starfall"            "1"
            "mirana_starfall_lod"            "1"
            "monkey_king_boundless_strike"  "1"
            "monkey_king_tree_dance"  "1"
            "monkey_king_primal_spring"  "1"
            "monkey_king_jingu_mastery"  "1"
            "monkey_king_jingu_mastery_lod"  "1"
            "monkey_king_jingu_mastery_lod_melee"  "1"
            "monkey_king_wukongs_command"   "1"
            //"monkey_king_mischief"  "1"
            "morphling_adaptive_strike_agi"            "1"
            "morphling_adaptive_strike_str"           "1"
            "morphling_morph_agi"            "1"
            "morphling_morph_str"            "1"
            "morphling_replicate"            "1"
            "morphling_waveform"            "1"
            "naga_siren_ensnare"            "1"
            "naga_siren_mirror_image"            "1"
            "naga_siren_rip_tide"            "1"
            "naga_siren_song_of_the_siren"            "1"
            "necrolyte_death_pulse"            "1"
            "necrolyte_sadist_lod"      "1"
            "necrolyte_heartstopper_aura"            "1"
            "necrolyte_reapers_scythe"            "1"
            "necrolyte_sadist"            "1"
            "nevermore_dark_lord"            "1"
            "nevermore_necromastery"            "1"
            "nevermore_requiem"            "1"
            "nevermore_shadowraze1"            "1"
            "nevermore_shadowraze2"            "1"
            "nevermore_shadowraze3"            "1"
            "night_stalker_crippling_fear"            "1"
            "night_stalker_darkness"            "1"
            "night_stalker_hunter_in_the_night"            "1"
            "night_stalker_void"            "1"
            "night_stalker_darkness"      "1"            
            "nyx_assassin_impale"            "1"
            "nyx_assassin_mana_burn"            "1"
            "nyx_assassin_spiked_carapace"            "1"
            "nyx_assassin_vendetta"            "1"
            "nyx_assassin_burrow"            "1"
            "nyx_assassin_burrow_redux"            "1"
            "obsidian_destroyer_arcane_orb"            "1"
            "obsidian_destroyer_astral_imprisonment"            "1"
            "obsidian_destroyer_astral_imprisonment_redux" "1"
            "obsidian_destroyer_essence_aura_lod"            "1"
            "obsidian_destroyer_essence_aura_redux"            "1"
            "obsidian_destroyer_sanity_eclipse"            "1"
            "obsidian_destroyer_equilibrium"                "1"
            "ogre_magi_bloodlust"            "1"
            "ogre_magi_fireblast"            "1"
            "ogre_magi_ignite"            "1"
            "omniknight_degen_aura"            "1"
            "omniknight_guardian_angel"            "1"
            "omniknight_purification"            "1"
            "omniknight_repel"            "1"
            "omniknight_pacify"             "1"
            "oracle_false_promise"            "1"
            "oracle_fates_edict"            "1"
            "oracle_fortunes_end"            "1"
            "oracle_purifying_flames"            "1"
            "phantom_assassin_blur"            "1"
            "phantom_assassin_coup_de_grace"            "1"
            "phantom_assassin_coup_de_grace_melee"            "1"
            "phantom_assassin_phantom_strike"            "1"
            "phantom_assassin_stifling_dagger"            "1"
            "phantom_lancer_doppelwalk"            "1"
            "phantom_lancer_juxtapose"            "1"
            //"phantom_lancer_juxtapose_melee"            "1"
            "phantom_lancer_phantom_edge"            "1"
            "phantom_lancer_spirit_lance"            "1"
            "phoenix_fire_spirits"            "1"
            "phoenix_icarus_dive"            "1"
            "phoenix_sun_ray"            "1"
            "phoenix_supernova"            "1"
            "puck_dream_coil"            "1"
            //"puck_ethereal_jaunt"            "1"
            "puck_illusory_orb"            "1"
            "puck_phase_shift"            "1"
            "puck_waning_rift"            "1"
            "pudge_dismember"            "1"
            "pudge_meat_hook"            "1"
            "pudge_rot"            "1"
            "pugna_decrepify"            "1"
            "pugna_life_drain"            "1"
            "pugna_nether_blast"            "1"
            "pugna_nether_ward"            "1"
            "queenofpain_blink"            "1"
            "queenofpain_blink_redux"     "1" 
            "queenofpain_scream_of_pain"            "1"
            "queenofpain_shadow_strike"            "1"
            "queenofpain_sonic_wave"            "1"
            "rattletrap_battery_assault"            "1"
            "rattletrap_hookshot"            "1"
            "rattletrap_power_cogs"            "1"
            "rattletrap_rocket_flare"            "1"
            "rattletrap_overclocking"            "1"
            "razor_eye_of_the_storm"            "1"
            "razor_plasma_field"            "1"
            "razor_static_link"            "1"
            "razor_unstable_current"            "1"
            "riki_blink_strike"            "1"
            "riki_smoke_screen"            "1"
            //"riki_backstab_lod"            "1"
            "riki_backstab"            "1"
            "rubick_fade_bolt"            "1"
            "rubick_null_field"            "1"
            "rubick_telekinesis"            "1"
            "rubick_arcane_supremacy"    "1"
            "sandking_burrowstrike"            "1"
            "sandking_epicenter"            "1"
            "sandking_sand_storm"            "1"
            //"sandking_caustic_finale_redux"      "1"
            "sandking_caustic_finale"      "1"
            "shadow_demon_disruption"            "1"
            "shadow_demon_shadow_poison"            "1"
            //"shadow_demon_shadow_poison_release"            "1"
            "shadow_demon_soul_catcher"            "1"
            "shadow_shaman_ether_shock"            "1"
            "shadow_shaman_mass_serpent_ward"            "1"
            "shadow_shaman_shackles"            "1"
            "shadow_shaman_voodoo"            "1"
            "shredder_chakram"            "1"
            "shredder_reactive_armor"            "1"
            "shredder_timber_chain"            "1"
            "shredder_whirling_death"            "1"
            "silencer_curse_of_the_silent"            "1"
            "silencer_glaives_of_wisdom"            "1"
            "silencer_global_silence"            "1"
            "silencer_last_word"            "1"
            "silencer_glaives_of_wisdom_steal"  "1"
            "skeleton_king_hellfire_blast"            "1"
            "skeleton_king_mortal_strike"            "1"
            "skeleton_king_reincarnation"            "1"
            "skeleton_king_vampiric_aura"            "1"
            "skeleton_king_reincarnation_redux"      "1"
            "skywrath_mage_ancient_seal"            "1"
            "skywrath_mage_arcane_bolt"            "1"
            "skywrath_mage_concussive_shot"            "1"
            "skywrath_mage_mystic_flare"            "1"
            "slardar_amplify_damage"            "1"
            "slardar_bash"            "1"           //procs on every hit when not skilled, works normally when skilled
            //"slardar_bash_ranged"            "1"    //blank ability
            //"slardar_bash_redux" "1"                //does not proc, throws error
            "slardar_slithereen_crush"            "1"
            "slardar_sprint"            "1"
            "slark_dark_pact"            "1"
            "slark_pounce"            "1"
            "slark_essence_shift"            "1"
            "slark_shadow_dance"            "1"
            "sniper_assassinate"            "1"
            "sniper_headshot"            "1"
            "sniper_shrapnel"            "1"
            "sniper_take_aim"            "1"
            "spectre_desolate"            "1"
            "spectre_dispersion"            "1"
            "spectre_haunt"            "1"
            //"spectre_reality"            "1"
            "spectre_haunt_single"            "1"
            "spectre_spectral_dagger"            "1"
            "spirit_breaker_charge_of_darkness"            "1"
            "spirit_breaker_empowering_haste"            "1"
            "spirit_breaker_greater_bash"            "1"
            //"spirit_breaker_greater_bash_ranged"            "1" //blank ability
            "spirit_breaker_greater_bash_redux"            "1"
            "spirit_breaker_nether_strike"            "1"
            "spirit_breaker_bulldoze"                 "1"
            "storm_spirit_ball_lightning"            "1"
            "storm_spirit_electric_vortex"            "1"
            "storm_spirit_overload"            "1"
            "storm_spirit_static_remnant"            "1"
            "sven_gods_strength"            "1"
            "sven_great_cleave"            "1"
            "sven_storm_bolt"            "1"
            "sven_warcry"            "1"
            //"techies_focused_detonate"            "1"
            "techies_land_mines"            "1"
            "techies_remote_mines"            "1"
            "techies_stasis_trap"            "1"
            "techies_suicide"            "1"
            "templar_assassin_meld"            "1"
            "templar_assassin_psi_blades"            "1"
            "templar_assassin_psionic_trap"            "1"
            "templar_assassin_trap_teleport"            "1"
            "templar_assassin_refraction"            "1"
            //"templar_assassin_trap"            "1"
            "terrorblade_conjure_image"            "1"
            "terrorblade_metamorphosis"            "1"
            "terrorblade_reflection"            "1"
            "terrorblade_sunder"            "1"
            "tidehunter_anchor_smash"            "1"
            "tidehunter_gush"            "1"
            "tidehunter_kraken_shell"            "1"
            "tidehunter_ravage"            "1"
            "tinker_heat_seeking_missile"            "1"
            "tinker_laser"            "1"
            "tinker_march_of_the_machines"            "1"
            "tiny_avalanche"            "1"
            "tiny_craggy_exterior"            "1"
            "tiny_grow"            "1"
            "tiny_grow_lod"            "1"
            "tiny_grow_lod_redux"            "1"
            "tiny_toss"            "1"
            //"tiny_tree_channel"     "1"
            "tiny_tree_grab"     "1"
            //"treant_eyes_in_the_forest"            "1"
            "treant_leech_seed"            "1"
            "treant_natures_grasp"            "1"
            "treant_living_armor"            "1"
            "treant_natures_guise"            "1"
            "treant_overgrowth"            "1"
            "troll_warlord_battle_trance"            "1"
            "troll_warlord_berserkers_rage"            "1"
            "troll_warlord_fervor"            "1"
            "troll_warlord_whirling_axes_ranged"            "1"
            "tusk_frozen_sigil"            "1"
            "tusk_ice_shards"            "1"
            "tusk_snowball"            "1"
            "tusk_walrus_punch"            "1"
            "tusk_walrus_kick"            "1"
            "tusk_tag_team"               "1"
            "snapfire_scatterblast" "1"
            "snapfire_firesnap_cookie"    "1"
            "snapfire_lil_shredder" "1"
            "snapfire_mortimer_kisses"    "1"
            "void_spirit_aether_remnant"  "1"
            "void_spirit_dissimilate"     "1"
            "void_spirit_resonant_pulse"  "1"
            "void_spirit_astral_step"     "1"
            "undying_decay"            "1"
            "undying_decay_agi"            "1"
            "undying_decay_int"            "1"
            "undying_flesh_golem"            "1"
            "undying_soul_rip"            "1"
            "undying_tombstone"            "1"
            "ursa_earthshock"            "1"
            "ursa_enrage"            "1"
            "ursa_fury_swipes"              "1"
            "ursa_overpower"            "1"
            "ursa_overpower_melee"        "1"
            "vengefulspirit_command_aura"            "1"
            "vengefulspirit_magic_missile"            "1"
            "vengefulspirit_nether_swap"            "1"
            //"vengefulspirit_nether_swap_redux"            "1"   //blank ability
            "vengefulspirit_wave_of_terror"            "1"
            "venomancer_plague_ward"            "1"
            "venomancer_poison_nova"            "1"
            "venomancer_poison_sting"            "1"
            "venomancer_venomous_gale"            "1"
            "viper_corrosive_skin"            "1"
            "viper_nethertoxin"            "1"
            "viper_poison_attack"            "1"
            "viper_viper_strike"            "1"
            "visage_grave_chill"            "1"
            "visage_gravekeepers_cloak"            "1"
            "visage_summon_familiars"            "1"
            "warlock_fatal_bonds"            "1"
            "warlock_rain_of_chaos"            "1"
            "warlock_shadow_word"            "1"
            "warlock_upheaval"            "1"
            "weaver_geminate_attack"            "1"
            "weaver_shukuchi"            "1"
            "weaver_the_swarm"            "1"
            "weaver_time_lapse"            "1"
            "windrunner_focusfire"            "1"
            "windrunner_powershot"            "1"
            "windrunner_shackleshot"            "1"
            "windrunner_windrun"            "1"
            "wisp_overcharge"            "1"
            "wisp_relocate"            "1"
            //"wisp_spirits"            "1"	// crashes server when spirit timer expires
            "wisp_tether"            "1"
            "witch_doctor_death_ward"            "1"
            "witch_doctor_maledict"            "1"
            "witch_doctor_paralyzing_cask"            "1"
            "witch_doctor_voodoo_restoration"            "1"
            "zuus_arc_lightning"            "1"
            "zuus_lightning_bolt"            "1"
            "zuus_static_field"            "1"
            "zuus_thundergods_wrath"            "1"
            "zuus_cloud"                     "1"
            //"life_stealer_consume"            "1"
            "shadow_demon_demonic_purge"            "1"
            "shredder_chakram_2"            "1"
            "earth_spirit_petrify"            "1"
            "earth_spirit_stone_caller"            "1"
            "winter_wyvern_arctic_burn"            "1"
            "winter_wyvern_splinter_blast"            "1"
            "winter_wyvern_cold_embrace"            "1"
            "winter_wyvern_winters_curse"            "1"
            "life_stealer_assimilate"            "1"
            //"morphling_hybrid"            "0"               // doesnt work
            "arc_warden_flux"            "1"
            "arc_warden_magnetic_field"            "1"
            "arc_warden_spark_wraith"            "1"
            "arc_warden_tempest_double"            "1"
            "arc_warden_tempest_double_redux"            "1"
            "arc_warden_tempest_double_op"            "1"
            "death_prophet_spirit_siphon"            "1"
            "faceless_void_time_dilation"            "1"
            "lone_druid_savage_roar"            "1"
            "riki_tricks_of_the_trade"            "1"
            "lone_druid_true_form_battle_cry"            "1"
            // Brewmaster
            "brewmaster_earth_hurl_boulder"            "1"
            //"brewmaster_earth_pulverize"            "1"
            "brewmaster_earth_pulverize_redux"        "1"
            //"brewmaster_storm_wind_walk"            "1"
            "brewmaster_storm_wind_walk_redux"            "1"
            "brewmaster_storm_dispel_magic"            "1"
            "brewmaster_fire_permanent_immolation"            "1"
            "brewmaster_storm_cyclone"            "1"
            // Ogre magi ulty
            "ogre_magi_unrefined_fireblast"            "1"
            // Meepo Ulty
            //"meepo_divided_we_stand"            "1"
            // Rearm
            "tinker_rearm"            "1"
            // Riki
            //"riki_permanent_invisibility"            "1"
            // Multicast
            "ogre_magi_multicast"            "1"
            // Aftershock
            "earthshaker_aftershock"            "1"
            "pangolier_swashbuckle" "1"
            "pangolier_shield_crash"      "1"
            "pangolier_heartpiercer"      "1"
            "pangolier_gyroshell"   "1"
            "pangolier_lucky_shot"   "1"
            //"pangolier_lucky_shot_ranged"   "1"     //blank ability
            "dark_willow_bramble_maze"    "1"
            "dark_willow_bedlam"    "1"
            "dark_willow_terrorize" "1"
            "dark_willow_shadow_realm"    "1"
            "dark_willow_cursed_crown"    "1"
            "grimstroke_dark_artistry"    "1"
            "grimstroke_ink_creature" "1"
            "grimstroke_spirit_walk"    "1"
            "grimstroke_soul_chain"    "1"
            //"grimstroke_scepter"    "1"
            //"sled_penguin_redux"  "1"				// errors
            "hoodwink_acorn_shot"   "1"
            "hoodwink_bushwhack"    "1"
            "hoodwink_scurry"       "1"
            "hoodwink_sharpshooter" "1"
            "hoodwink_decoy"		"1"
            "hoodwink_hunters_boomerang"	"1"
            "dawnbreaker_fire_wreath" "1"
            "dawnbreaker_celestial_hammer" "1"
            //"dawnbreaker_converge" "1"
            //"dawnbreaker_luminosity" "1"      // crashes game: CGameParticleManager::SetParticleControlEnt: Unable to lookup attachment attach_weapon_core_fx
            "dawnbreaker_solar_guardian" "1"
            "life_stealer_ghoul_frenzy" "1"


            // Shard abilities added in 7.27
            "alchemist_berserk_potion"          "1"   // ok
            "antimage_mana_overload"            "1"   // ok
            "bristleback_hairball"              "1"   // needs quills and goo - added warning text
            "broodmother_silken_bola"           "1"   // needs spin web charge - added warning text
            "rattletrap_jetpack"                "1"   // ok  
            "dark_seer_normal_punch"            "1"   // ok
            "dragon_knight_fireball"            "1"   // ok
            //"faceless_void_time_walk_reverse"   "1"   // requires timewalk
            //"jakiro_liquid_ice"                 "1"   // misses? (with melee hero), hits but doesnt debuff (with ranged hero)
            "juggernaut_swift_slash"            "1"   // needs omnislash - added warning text
            "kunkka_tidal_wave"                 "1"   // ok
            "leshrac_greater_lightning_storm"   "1"   // ok
            "lich_ice_spire"                    "1"   // ok
            "magnataur_horn_toss"               "1"   // ok
            "medusa_cold_blooded"               "1"   // ok
            "meepo_petrify"                     "1"   // ok
            "necrolyte_death_seeker"            "1"   // needs death pulse - added warning text
            "ogre_magi_smash"                   "1" // fire shield ok 
            //"ogre_magi_frost_armor"             "1"   // cant find?
            "omniknight_hammer_of_purity"       "1"   // ok
            //"pangolier_gyroshell"               "1"   // cant find?
            "phantom_assassin_fan_of_knives"    "1"   // ok
            "riki_poison_dart"                  "1"   // ok
            "slark_fish_bait"                   "1"   // ok
            "sniper_concussive_grenade"         "1"   // ok
            //"spectre_haunt_single"              "1"
            "storm_spirit_electric_rave"        "1"   // needs overload - added warning text
            //"templar_assassin_trap_teleport"    "1"
            "terrorblade_terror_wave"           "1"   // ok
            "terrorblade_demon_zeal"            "1"   // ok
            "shredder_flamethrower"             "1"   // ok
            "tinker_defense_matrix"             "1"   // ok
            "visage_silent_as_the_grave"        "1"   // ok
            "witch_doctor_voodoo_switcheroo"    "1"   // needs death ward - added warning text

            // Abilities added in 7.3
            "broodmother_sticky_snare"          "1"
            "abyssal_underlord_dark_portal"     "1"
            "windrunner_gale_force"             "1"
            "slark_depth_shroud"				"1"   // needs shadow dance - added warning text
			//"snapfire_gobble_up"				"1"   // cant get spit creep to work
			//"snapfire_spit_creep"				"1"
			"keeper_of_the_light_radiant_bind"	"1"

			// Marci
			"marci_grapple"						"1"
			"marci_unleash"						"1"
			"marci_companion_run"				"1"
			"marci_guardian"					"1"

			// 7.31
			"dazzle_good_juju"					"1"
			"oracle_rain_of_destiny"			"1"
			"shadow_demon_demonic_cleanse"		"1"
			"tinker_warp_grenade"				"1"
            "tinker_shrink_ray"                 "1"
            "tinker_keen_teleport"			    "1"
            "techies_sticky_bomb"				"1"
			"techies_reactive_tazer"			"1"
            "zuus_heavenly_jump"                "1"

            "ice_shaman_incendiary_bomb"        "1"
            "ancient_rock_golem_weakening_aura" "1"
            "warpine_raider_seed_shot"          "1"
            "hill_troll_rally"                  "1"
            "kobold_disarm"                     "1"
            "kobold_tunneler_prospecting"       "1"
            "frostbitten_golem_time_warp_aura"  "1"
            "black_drake_magic_amplification_aura"  "1"
            "berserker_troll_break"             "1"
            "ogre_bruiser_ogre_smash"           "1"
            "giant_wolf_intimidate"             "1"
            "furbolg_enrage_attack_speed"       "1"
            "furbolg_enrage_damage"             "1"
            "forest_troll_high_priest_heal_amp_aura"    "1"
            "fel_beast_haunt"                   "1"
            "harpy_scout_take_off"              "1"
            "enraged_wildkin_hurricane"         "1"


			// Primal Beast
			"primal_beast_onslaught"			"1"
			"primal_beast_trample"				"1"
			"primal_beast_uproar"				"1"
			"primal_beast_rock_throw"			"1"
			"primal_beast_onslaught_release"	"0"	
			"primal_beast_pulverize"			"1"






        }
        // The neutrals skills
        "neutral" {
            "alpha_wolf_group" {
                "alpha_wolf_command_aura"                "1"
                "beastmaster_boar_poison"                "1"
                "alpha_wolf_critical_strike"                "1"
                "black_dragon_splash_attack"                "1"
                "black_dragon_fireball_lod"                "1"
            }
            "beastmaster_boar_group" {

                //"beastmaster_greater_boar_poison"                "1" //Duplicate
            }
            "big_thunder_lizard_group" {
                "big_thunder_lizard_frenzy"                "1"
                "big_thunder_lizard_slam"                "1"
                "big_thunder_lizard_wardrums_aura"                  "1"
            }
            "black_dragon_group" {

                //"black_dragon_fireball"                "1" //Duplicate

                "neutral_spell_immunity"                "1"
                "black_dragon_dragonhide_aura"                      "1"
            }
            "blue_dragonspawn_group" {
                "blue_dragonspawn_overseer_devotion_aura"                "1"
                "blue_dragonspawn_sorcerer_evasion"                "1"
                //"neutral_evasion"                "1"
            }
            "centaur_khan_group" {
                "centaur_khan_endurance_aura"                "1"
                "centaur_khan_war_stomp"                "1"
            }
            "dark_troll_warlord_group" {
                "dark_troll_warlord_ensnare"                "1"
                "dark_troll_warlord_raise_dead"                "1"
            }
            "enraged_wildkin_group" {
                "enraged_wildkin_tornado"                "1"
                "enraged_wildkin_toughness_aura"                "1"
            }
            "lone_druid_spirit_bear_group" {
                "lone_druid_spirit_bear_demolish"                "1"
                "lone_druid_spirit_bear_entangle"                "1"
                //"lone_druid_spirit_bear_return"                "1"
                "lone_druid_spirit_bear_return_lod"                "1"
                "visage_summon_familiars_stone_form"                "1"
            }
            "satyr_group" {
                "satyr_hellcaller_shockwave"                "1"
                "satyr_hellcaller_unholy_aura"                "1"
                "satyr_soulstealer_mana_burn"                "1"
                "satyr_trickster_purge"                "1"
            }
            "necronomicon_group" {
                "necronomicon_archer_aoe_lod"                "1"
                "necronomicon_archer_mana_burn_lod"                "1"
                "necronomicon_warrior_last_will_lod"                "1"
                "necronomicon_warrior_mana_burn_lod"                "1"
            }
            "roshan_group" {
                "roshan_slam"                "1"
                "roshan_spell_block"                "1"
                //"roshan_spell_block_lod"                "1"
                "roshan_bash"                "1"
            }
            "prowler_group" {
                "spawnlord_aura"                "1"
                "spawnlord_master_stomp"                "1"
                "spawnlord_master_freeze"                "1"
            }
            "warlock_group" {
                "warlock_golem_flaming_fists"                "1"
                "warlock_golem_permanent_immolation"                "1"
                "warlock_golem_permanent_immolation_lod"        "1"
            }
            "misc_neutral_1_group" {
                "forest_troll_high_priest_heal"                "1"
                "forest_troll_high_priest_mana_aura"  "1"
                "ghost_frost_attack"                "1"
                //"giant_wolf_critical_strike"                "1" //Duplicate
                "gnoll_assassin_envenomed_weapon"                "1"
            }
            "misc_neutral_2_group" {
                "granite_golem_hp_aura"                "1"
                "harpy_storm_chain_lightning"                "1"
                "kobold_taskmaster_speed_aura"                "1"
                "lycan_summon_wolves_critical_strike"                "1"
            }
            "misc_neutral_3_group" {
                "ogre_magi_frost_armor"                "1"
                "mud_golem_hurl_boulder"                "1"
                "mudgolem_cloak_aura"  "1"
                "polar_furbolg_ursa_warrior_thunder_clap"                "1"
                //"mud_golem_rock_destroy"  "1"      //doesnt work
            }
            //"misc_neutral_4_group" {
                // Removed because its buggy "backdoor_protection"                "1"

                // "broodmother_poison_sting"                "1"

                // "undying_tombstone_zombie_deathstrike"                "1" //Broken
            //}
            "forge_spirit" {
                  //"forged_spirit_melting_strike"      "1"       //cant level up skill
            }
        }
        // The custom skills in LoD
        "custom"
        {
            "flesh_heap"
            {
                  "pudge_flesh_heap_agility"            "1"       // errors on startup but does work ok 
                  "pudge_flesh_heap_int"            "1"
                  "pudge_flesh_heap_move_speed"     "1"           // works ok
                  "pudge_flesh_heap_spell_amp"       "1"          // works ok but doesnt show extra spell amp on character sheet
                  "pudge_flesh_heap_attack_range"   "1"           // works ok
                  //"pudge_flesh_heap_attack_speed"   "1"         // script errors
                  "pudge_flesh_heap_cast_range"   "1"             // works ok
                  "pudge_flesh_heap_bonus_vision" "1"             // works ok
                  "pudge_flesh_heap_cooldown_reduction" "1"       // errors on startup but does work ok 
                  "pudge_flesh_heap_magic_resistance" "1"         // works ok
                  "pudge_flesh_heap_evasion" "1"                  // errors on startup but does work ok 
                  //"pudge_flesh_heap_spell_lifesteal" "1"        // not working
                  //"pudge_flesh_heap_lifesteal" "1"              // not working
                  "pudge_flesh_heap_armor" "1"                    // works ok
                  "pudge_flesh_heap_health_regeneration" "1"      // works ok
                  "pudge_flesh_heap_mana_regeneration" "1"        // works ok
                  "pudge_flesh_heap_minion_damage" "1"            // works ok
                  "pudge_flesh_heap_tenacity" "1"                 // script errors when levelling up but does work ok
                  "pudge_flesh_heap_willpower" "1"                // script errors when levelling up but does work ok
            
                  // most of these have CalculateStatBonus script errors so may not work as intended

            }

            "survivor" 
            {
                  "spell_lab_survivor_health_regen" "1"
                  "spell_lab_survivor_move_speed" "1"
                  "spell_lab_survivor_vision" "1"
                  "spell_lab_survivor_magic_resistance" "1"
            }

            "spell_lab_souls" 
            {
                "spell_lab_souls_vision" "1"
                "spell_lab_souls_health_regen" "1"
                "spell_lab_souls_move_speed" "1"
                "spell_lab_souls_magic_resistance" "1"
            }

           "brawler"{
                 "brawler_int"                             "1"
                 "brawler_str"                             "1"
                 "brawler_agi"                             "1"
           }
           "imbaRoshan"{
                  //"imba_roshan_fury"      "1"
                  "imba_tower_healing_hero"     "1"
           }
            "spell_lab" {
                "spell_lab_one_with_nothing" "1"
                "spell_lab_symbiotic" "1"
                "arcane_mastery"   "1"
                "spell_lab_missile_storm" "1"
                "spell_lab_storm_minions" "1"
                "spell_lab_bfg" "1"
                "spell_lab_taxi" "1"
                //"spell_lab_ggs" "1"                 //spell effect gets stuck on field - doctors divine shower
                "spell_lab_void_step" "1"
            }
            "oneshotonekill" {
                  "jingtong"  "1"
                  "shiguanghuisu"      "1"
                  "benneng"   "1"
                  "sight"   "1"
                  "zhanhun"   "1"
            }
            "overflow" {
                  "blink_support"  "1"
                  "military"   "1"
                  "spell_reflect"   "1"
                  "berserker" "1"
                  "eldri_anti_magic" "1"
                  "channel_earthquake" "1"
                  "grow_beard" "1"
                  "eat_tree_eldri"  "1"
                  "chi_strike"  "1"
            }
            "angel_arena_blackstar" {
                  "aabs_nightshadow"     "1"
                  "aabs_thunder_musket"   "1"
            }
            "resurgence"{
                  "genos_survival_of_the_fittest"     "1"
            }
            "radiant_jungle"{
                  "spawn_small_camp"            "1"
                  "spawn_medium_camp"           "1"
                  "spawn_large_camp"            "1"
                  "spawn_ancient_camp"          "1"
            }        
            "overflow_ult" {
                  "night_wolf" "1"
                  "dark_blade"      "1"
                  "light_blade"   "1"
                  "metamorphosis"   "1"
                  "seer"   "1"                  //vision gets stuck on enemy heroes when used with multicast
                  "spectral_form"   "1"
                  "master_magic"   "1"
            }
            "mercy" {
                  "mercy_caduceus_healing"      "1"
                  //"mercy_caduceus_power"  "1"       //spell works but doesnt give damage or spell bonus
                  "mercy_guardian_angel"  "1"
                  "mercy_angelic_descent" "1"
                  "mercy_heroes_never_die"      "1"
            }

            "holdout" {
                "zuus_thundergods_vengeance"                "1"
                //"holdout_omnislash"                "1"	//disappears when you pick it and start game
                //"holdout_gods_strength"                "1"
                "holdout_gladiators_unite"                "1"
                "holdout_culling_blade"                "1"
                "holdout_arcane_aura"                "1"
                "holdout_gladiators_unite"                "1"
                //"holdout_scourge_ward"          "1"     //error in log: Cannot create an entity because entity class is NULL -1 
                //"holdout_multishot"             "1"       //disappears when you pick it and start game

            }
            "item_abilities" {
                "armoured_centipede"                              "1"
                "aether_range_lod"                "1"
                "octarine_vampirism_lod"                "1"
                "force_dash_lod"                "1"
                "shards_of_truesight_lod"                "1"
            }
           //  "random_abilities" {
           //     "true_random_lod_1"    "1"
           //     "true_random_lod_2"    "1"
           //     "true_random_lod_3"    "1"
           //     "true_random_lod_4"    "1"
           //     "true_random_lod_5"    "1"
           //     "true_random_lod_6"    "1"
           // }
            "cherub_abilities" {
                //"cherub_sleep_cloud"      "1"       //sleep cloud spell effect needs fixing
                "cherub_synthesis"      "1"
                "cherub_explosive_spore"      "1"
                "cherub_flower_garden"      "1"
            }

            "uther_abiliites"{
                  "uther_Hurl_Hammer"     "1"
                  "uther_Threatening_Bolt"      "1"
                  "uther_omniscience_wave"      "1"
                  "uther_Argent_Smite"      "1"
            }

            "proteus_abiliites"{
                  "proteus_razorwind"     "1"
                  //"proteus_polyp"      "1"          // crashed server
                  "proteus_jet"      "1"
                  "proteus_rarefaction"      "1"
            }

            "tenebris_abiliites"{
                  "tenebris_blood_ward"   "1"         // CRASHES
                  //"tenebris_effigy" "1"             // PARTICLES DOES NOT DISSAPEAR
                  "tenebris_fade_strike"  "1"
                  "tenebris_mortal_coil"  "1"
            }

            "suna_abiliites"{
                  "suna_blight_and_wither"      "1"
                  //"suna_dead_mans_chest"  "1" 
                  //"suna_kyonshi"    "1"             //sub ability of dead mans chest
                  //"suna_mind_control"     "1"       //SUB-ABILITY
                  "suna_puppeteer"  "1"
                  //"suna_vicissitude"      "1"       //not a very good spell
           }

           "veera"{
                  "veera_evasive_roll"    "1"
                  "veera_plains_runner"   "1"
                  "veera_pursuit"   "1"
                  "veera_thrill_of_the_hunt"    "1"
                  "veera_toxic_darts"     "1"
           }

           "zeros"{
                  "zeros_gerrymandering" "1"
                  "zeros_impose_tax" "1"
                  //"zeros_innate" "1"
                  "zeros_royal_statue" "1"
                  "zeros_blade_of_malice" "1"
                  "zeros_fanaticism" "1"
           }

           "achlys"{
                  "achlys_miserable_claws"      "1"
                  "achlys_nights_embrace" "1"
                  "achlys_sorrow_rising"  "1"
                  "achlys_death_mist"     "1"
           }

            "sirocco_abiliites"{
                  "sirocco_shifting_sands"      "1"
                  "sirocco_mirage"  "1"
                  "sirocco_dehydration_aura"    "1"
                  "sirocco_desert_curse"  "1"
            }

            "bellatrix_abiliites"{
                  "bellatrix_blood_cross" "1"
                  "bellatrix_blood_rake"  "1"
                  "bellatrix_live_transfusion"  "1"
                  "bellatrix_unholy_ecstasy"    "1"
            }

            "scaw_abilities"{
                  //"scawmar_spirits_away"  "1"       //works ok, complains about texture materials/models/heroes/statuseffects/colorwarp_desat.vtex
                  //"scawmar_fade_blink"    "1"       //simply slower and worse than normal blink or blink dagger etc
                  //"scawmar_illusion_line" "1"       //works but creates a copy of your hero?!
                  //"scawmar_mind_control"  "1"       //works, but as bot walked towards my character it crashed dota
                  //"scawmar_scryers_circle"      "1" //works ok, but creates a copy of your hero instead of illusions
            }

            "hylonome_abilities"{
                  "hylonome_eldritch_pull"      "1"
                  "hylonome_battle_rhythm"      "1"
                  "hylonome_anemic_aura"  "1"
                  "hylonome_libation"     "1"
            }

            "keen_abilities"{
                  "keen_commander_mortar_shot"  "1"
                  "keen_commander_recon_systems"      "1"
                  "keen_commander_siege_mode"   "1"
                  "keen_commander_slag_armor"   "1"
            }

            "alexander_abilities"{
                  "alexander_elandras_blessing" "1"
                  "alexander_godfall"     "1"
                  "alexander_radiant"     "1"
                  "alexander_soulseal"    "1"
            }

            "lightning_abilities"{
                  "lightning_lightning_dagger2" "1"
                  "lightning_overload"    "1"
                  "lightning_spark" "1"
                  "lightning_thunder_wave"     "1"
            }

            "ptomely_abilities"{
                  "ptomely_astralise"     "1"
                  "ptomely_enthrall"      "1"
                  "ptomely_expunge"       "1"
                  "ptomely_mirror_blade"  "1"
            }

            "mifune_abilities"{
                  "mifune_raigeki"  "1"
                  "mifune_genso"    "1"
                  "mifune_oiuchi"   "1"
                  "mifune_zanmato"  "1"
            }

            "erra_abilities"{
                  "erra_deathtouch" "1"
                  "erra_grave_guard"      "1"
                  "erra_morbid_blade"     "1"
                  "erra_to_dust"    "1"
            }

            "lich_abilities"{
                  "lich_absolute_zero" "1"
                  "lich_deep_freeze"  "1"
                  "lich_traveling_frost"  "1"
                  "lich_winters_requiem"  "1"
            }

            "hero_abilities"{
                  //"hero_justice_kick"     "1"       //coding and pushback issues 
                  "hero_one_punch"        "1"
                  "hero_freedom_strike"   "1"
                  "hero_heroic_soul"      "1"
            }

            "flower_abilities" {
                "garden_white_flower_base"      "1"
                "garden_red_flower_base"        "1"
                "garden_pink_blossom_base"      "1"
                "garden_blue_blossom_base"      "1"
                "garden_yellow_daisy_base"      "1"
                "garden_purple_lotus_base"      "1"
            }
            "zulf_abilities" {
                //"zulf_cyclone_trap"      "1"  //spell effect needs fixing
                "zulf_jet_stream"      "1"
                //"zulf_gale_force"      "1"    //spell effect needs fixing, does not get removed when spell ends
                "zulf_typhoon"      "1"
            }
            "angel_arena_reborn" {
                "angel_arena_lightning"   "1"
                "angel_arena_magic_fire"      "1"
                "angel_arena_razor_power"     "1"
                //"angel_arena_revenge"   "1"         //triggers on neutrals, not on heroes
                "angel_arena_shot"      "1"
                "angel_arena_storm"     "1"
                "angel_arena_summon_hawk"     "1"
                "angel_arena_berserk"   "1"
                "angel_arena_cripple"   "1"
            }
            "angel_arena_reborn_ult" {
                  "angel_arena_darkrage"  "1"
                  //"angel_arena_night_vampire"   "1"       // lifesteal does not work
                  "angel_arena_roots"     "1"
                  "angel_arena_song"      "1"
                  "angel_arena_hola_heal" "1"
                  "angel_arena_transmute" "1"
                  "angel_arena_demonic"   "1"
                  "angel_arena_grace"     "1"
            }
            "angel_arena_tome" {
                  "angel_arena_tome_lvlup"  "1"
                  "angel_arena_tome_gods"  "1"
                  "angel_arena_tome_int"  "1"
                  "angel_arena_tome_str"  "1"
                  "angel_arena_tome_agi"  "1"
                  "angel_arena_tome_med"  "1"
            }
          
            "life_in_arena" {
                  "ancient_priestess_surge_of_intelligence" "1"
                  "ancient_priestess_spirit_link"     "1"
                  "archmage_magic_barrier"      "1"
                  "berserker_fire_spear"  "1"
                  "dark_ranger_black_arrow"     "1"
                  "firelord_flame_strike" "1"
                  "firelord_fire_trap"    "1"
                  "frost_lord_cold" "1"
                  "frost_lord_frost_breath"     "1"
                  "ghoul_devour"    "1"
                  "akron_explosion" "1"
                  "paladin_blizzard"      "1"
                  "dark_knight_dark_forces"     "1"
                  "lord_of_lightning_lightning_shield"      "1"
                  "android_cluster_rockets"     "1"
                  "serpent_queen_ball_lightning"      "1"
            }
            "life_in_arena_passive" {
                  "butcher_zombie"  "1"
                  "frost_lord_freezing"   "1"
                  "lord_of_lightning_holy_wrath"      "1"
                  "kret_poisoning"  "1"
                  "kret_lust_for_life"    "1"
            }
            "life_in_arena_ferocity" {
                  "brewmaster_ferocity"   "1"               // str version does not increase your health
                  "brewmaster_ferocity_agi"     "1"         // does correctly update your armour
                  "brewmaster_ferocity_int"     "1"         // doesnt change mana pool
                  "brewmaster_ferocity_all"     "1"
            }
            "life_in_arena_ult" {
                  "ancient_priestess_ritual_protection" "1"
                  "berserker_madness"     "1"
                  "frost_lord_ice"  "1"
                  "lord_of_lightning_brain_storm"     "1"
                  "paladin_impregnability"      "1"
                  "angel_arena_archmage_anomaly"      "1"
            }
            "life_in_arena_illusion" {
                  "illusionist_mastery_of_deception"  "1"
                  "illusionist_whiff_of_deception"    "1"
                  "illusionist_agility_paws"    "1"
                  //"illusionist_mastery_of_illusions"  "1"	// creates permament copies of heroes that die and respawn
            }
            "retro_dota" {
                  //"invoker_retro_betrayal"      "1"       // useless ability
                  "invoker_retro_portal"      "1"
                  "invoker_retro_scout"      "1"
                  "invoker_retro_invisibility_aura"      "1"
                  "invoker_retro_confuse"      "1"
                  "invoker_retro_disarm"      "1"
                  "invoker_retro_deafening_blast"      "1"
            }

            "imba_towers_weak" {
                  //"imba_tower_aegis"   "1"            // aura works but doesnt give +3 armour per hero
                  "imba_tower_forest"   "1"
                  "imba_tower_self_repair"   "1"
                  "imba_tower_thorns"   "1"
            }
            "ebf" {
                  "ebf_rubick_arcane_echo" "1"
                  "ebf_mana_fiend_essence_amp"  "1"
                  "ebf_clinkz_trickshot"      "1"
                  "ebf_underlord_expulsion"      "1"
                  "ebf_troll_warlord_multistrike"      "1"
            }
            "dusk" {
                  "gemini_abyssal_vortex" "1"
                  "gemini_unstable_rift"  "1"
                  "gemini_voidal_flare" "1"
                  "gemini_extraplanar_pact" "1"
            }
            "duskMisc1" {
                  "self_explosion" "1"
                  //"ancient_defensive_wave"      "1"       //lua code needs fixing
                  //"ancient_last_resort"   "1"             //Its bugged with illusions, it brings them back to life
                  //"paragon_tranquility_seal"    "1"       //spell doesnt prevent damage and cant be cast on buildings
            }
            "duskMisc2" {
                  "crimson_blood_sorcery" "1"
                  "alchemist_alchemise"   "1"
                  "alchemist_motherloads" "1"
                  "aether_reality_shift"  "1"
            }

            "lysander" {
                  //"lysander_adventurous_gale"   "1"       //crashes dota when used
                  "lysander_captains_compass"   "1"
                  "lysander_grapeshot"    "1"
                  "lysander_phantom_fleet"      "1"
            }
            "basic_abilities"
            {
                  "basic_tenacity_bonus" "1"
                  //"basic_willpower_bonus" "1"
                  "basic_mana_bonus" "1"
                  "basic_health_bonus" "1"
                  "basic_gpm_bonus" "1"
                  "basic_movespeed_bonus" "1"
                  "basic_xpm_bonus" "1"
                  "basic_spell_amp_bonus" "1"
                  "basic_stat_gain_bonus" "1"
                  "basic_stat_bonus" "1"
                  "ability_mjolnir" "1"
                  "ability_blademail" "1"
                  "ability_wards"   "1"
                  "bash_reflect" "1"
                  "basic_bat" "1"
                  "basic_bat_reduction" "1"
            }


            "hawkeye" {
                  "hawkeye_detonator_dart" "1"
                  //"hawkeye_double_tap"  "1"     //single tap fires ok, second spell moves abilities around and doesnt work
                  "hawkeye_hit_n_run" "1"
                  "hawkeye_ricochet" "1"
            }
            "molten" {
                  "bulwark_strike"  "1"
                  "skipping_flames"       "1"
                  "unwavering_stance"     "1"
                  "molten_charge"    "1"
            }
      
            "DoD" {
                  "makemeleecreeps_lua"   "1"
                  "makerangedcreeps_lua"   "1"
                  "makecatapults_lua"   "1"
            }
            "memes_reborn"{
                  "lina_banana_redux"     "1"
                  "lina_coconut_redux"    "1"
                  "lina_grapefruit_redux" "1"
            }
            "patron_abilities" {
                  "crater" "1"
                  //"ranged_punch" "1"                      //crashes tools mode, no spell effect in normal game
                  "pushing_blast" "1"
                  //"sled_penguin_redux" "1"				// errors
            }
            
        }
        "imba"
        {
            // "hero_shredder"
            // {
            //     "imba_shredder_timber_chain"  "1"
            //     "imba_shredder_chakram"  "1"
            //     "imba_shredder_whirling_death"  "1"
            //     "imba_shredder_return_chakram"  "1"
            //     "imba_shredder_dendrophobia"  "1"
            //     "imba_shredder_reactive_armor"  "1"
            // }
            //"hero_naga_siren"
            //{
            //    "imba_naga_siren_rip_tide"  "1"
            //    "imba_naga_siren_mirror_image"  "1"
            //}
            //"hero_beastmaster"
            //{
            //    "imba_beastmaster_summon_boar"  "1"
            //    "imba_beastmaster_hawk_invis"  "1"
            //    "imba_beastmaster_summon_hawk"  "1"
            //    "imba_beastmaster_boar_poison"  "1"
            //}
            //"hero_shadow_shaman"
            //{
            //    "imba_shadow_shaman_mass_serpent_ward"  "1"
            //}
            //"hero_hell_empress"
            //{
            //   "imba_empress_hurl_through_hell"  "1"
            //    "imba_empress_ambient_effects"  "1"
            //    "imba_empress_royal_wrath"  "1"
            //    "imba_empress_hellbolt"  "1"
            //    "imba_empress_eleven_curses"  "1"
            //}
            //"hero_chaos_knight"
            //{
            //    "imba_chaos_knight_phantasm"  "1"
            //    "imba_chaos_knight_reality_rift"  "1"
            //}
            //"hero_sly_king"
            //{
            //    "imba_sly_king_winterbringer"  "1"
            //    "imba_sly_king_frozen_skin"  "1"
            //    "imba_sly_king_burrow_blast"  "1"
            //    "imba_sly_king_frost_gale"  "1"
            //}
            //"hero_tinker"
            //{
            //    "imba_tinker_march_of_the_machines"  "1"
            //    "imba_tinker_laser"  "1"
            //    "imba_tinker_rearm"  "1"
            //    "imba_tinker_heat_seeking_missile"  "1"
            //    "imba_tinker_technomancy"  "1"
            //}
            //"hero_doom_bringer"
            //{
            //    "imba_doom_bringer_doom"  "1"
            //}
            //"hero_phantom_lancer"
            //{
            //    "imba_phantom_lancer_spirit_lance"  "1"
            //}
            //"hero_techies"
            //{
            //    "imba_techies_remote_mine_pinpoint_detonation"  "1"
            //    "imba_techies_focused_detonate"  "1"
            //    "imba_techies_stasis_trap"  "1"
            //    "imba_techies_remote_mine"  "1"
            //    "imba_techies_stasis_trap_trigger"  "1"
            //    "imba_techies_minefield_sign"  "1"
            //    "imba_techies_proximity_mine_trigger"  "1"
            //    "imba_techies_blast_off"  "1"
            //}
            //"hero_rubick"
            //{
            //    "imba_rubick_spell_steal_controller"  "1"
            //    "imba_rubick_telekinesis"  "1"
            //}
            //"hero_spectre"
            //{
            //    "imba_spectre_reality"  "1"
            //    "imba_spectre_haunt"  "1"
            //}
            "hero_abaddon"
            {
                "imba_abaddon_aphotic_shield"  "1"
                "imba_abaddon_curse_of_avernus"  "1"
                "imba_abaddon_mist_coil"  "1"
                //"imba_abaddon_over_channel"  "1"          // HIDDEN ABILITY - DO NOT RE-ENABLE
                "imba_abaddon_borrowed_time"  "1"
            }
            "hero_alchemist"
            {
                //"imba_alchemist_mammonite"  "1"           // cant skill up
                "imba_alchemist_goblins_greed"  "1"
                "imba_alchemist_acid_spray"  "1"
                "imba_alchemist_chemical_rage"  "1"
                //"imba_alchemist_greevils_greed"  "1"
                "imba_alchemist_unstable_concoction"  "1"
            }
            "hero_antimage"
            {
                "imba_antimage_spell_shield"  "1"
                "imba_antimage_mana_void"  "1"
                "imba_antimage_mana_break"  "1"
                "imba_antimage_blink"  "1"
            }
            "hero_axe"
            {
                "imba_axe_berserkers_call"  "1"
                "imba_axe_culling_blade"  "1"
                "imba_axe_battle_hunger"  "1"
                "imba_axe_counter_helix"  "1"
            }
            "hero_bane"
            {
                "imba_bane_enfeeble"  "1"
                "imba_bane_brain_sap"  "1"
                "imba_bane_fiends_grip"  "1"
                //"imba_bane_nightmare_end"  "1"            // HIDDEN ABILITY
                "imba_bane_nightmare"  "1"
            }
            "hero_bloodseeker"
            {
                "imba_bloodseeker_blood_bath"  "1"
                "imba_bloodseeker_thirst"  "1"
                "imba_bloodseeker_bloodrage"  "1"
                "imba_bloodseeker_rupture"  "1"
            }
            "hero_bounty_hunter"
            {
                "imba_bounty_hunter_shadow_walk"  "1"
                "imba_bounty_hunter_jinada"  "1"
                "imba_bounty_hunter_shuriken_toss"  "1"
                "imba_bounty_hunter_headhunter"  "1"
                "imba_bounty_hunter_track"  "1"
            }
            "hero_bristleback"
            {
                "imba_bristleback_viscous_nasal_goo"  "1"
                "imba_bristleback_quill_spray"  "1"
                "imba_bristleback_bristleback"  "1"
                "imba_bristleback_warpath"  "1"
            }
            "hero_centaur"
            {
                "imba_centaur_hoof_stomp"  "1"
                "imba_centaur_double_edge"  "1"
                "imba_centaur_return"  "1"
                "imba_centaur_thick_hide"  "1"
                "imba_centaur_stampede"  "1"
            }
            "hero_chen"
            {
                "imba_chen_test_of_faith"  "1"
                "imba_chen_divine_favor"  "1"
                "imba_chen_holy_persuasion"  "1"
                "imba_chen_hand_of_god"  "1"
            }
            "hero_clinkz"
            {
                "imba_clinkz_searing_arrows"  "1"
                //"imba_clinkz_death_pact"  "1"             //doesnt show up in search
                "imba_clinkz_skeleton_walk"  "1"
                "imba_clinkz_strafe"  "1"
            }
            "hero_rattletrap"
            {
                "imba_rattletrap_battery_assault"  "1"
                "imba_rattletrap_power_cogs"  "1"
                "imba_rattletrap_rocket_flare"  "1"
                "imba_rattletrap_hookshot"  "1"
            }
            "hero_crystal_maiden"
            {
                "imba_crystal_maiden_crystal_nova"  "1"
                "imba_crystal_maiden_arcane_dynamo"  "1"
                "imba_crystal_maiden_freezing_field"  "1"
                "imba_crystal_maiden_brilliance_aura"  "1"
                "imba_crystal_maiden_frostbite"  "1"
            }
            "hero_dark_seer"
            {
                "imba_dark_seer_vacuum"  "1"
                "imba_dark_seer_ion_shell"  "1"
                "imba_dark_seer_surge"  "1"
                //"imba_dark_seer_wormhole"  "1"            //doesnt show up, related to vacuum ability, extra part of the spell
                "imba_dark_seer_wall_of_replica"  "1"
            }
            "hero_dazzle"
            {
                "imba_dazzle_ressurection"  "1"
                "imba_dazzle_shadow_wave"  "1"
                "imba_dazzle_poison_touch"  "1"
                "imba_dazzle_shallow_grave"  "1"
                "imba_dazzle_bad_juju"  "1"
            }
            "hero_magnataur"
            {
                "imba_magnataur_skewer"  "1"
                "imba_magnataur_shockwave"  "1"
                "imba_magnataur_empower"  "1"
                "imba_magnataur_reverse_polarity"  "1"
            }
            "hero_disruptor"
            {
                "imba_disruptor_static_storm"  "1"
                "imba_disruptor_glimpse"  "1"
                "imba_disruptor_kinetic_field"  "1"
                "imba_disruptor_stormbearer"  "1"
                "imba_disruptor_thunder_strike"  "1"
            }
            "hero_dragon_knight"
            {
                "imba_dragon_knight_dragon_blood"  "1"
                "imba_dragon_knight_elder_dragon_charge"  "1"
                "imba_dragon_knight_elder_dragon_form"  "1"
                "imba_dragon_knight_dragon_tail"  "1"
                "imba_dragon_knight_breathe_fire"  "1"
            }
            "hero_drow_ranger"
            {
                "imba_drow_ranger_deadeye"  "1"
                "imba_drow_ranger_marksmanship"  "1"
                "imba_drow_ranger_frost_arrows"  "1"
                "imba_drow_ranger_gust"  "1"
                "imba_drow_ranger_trueshot"  "1"
            }
            "hero_earth_spirit"
            {
                "imba_earth_spirit_boulder_smash"  "1"
                "imba_earth_spirit_rolling_boulder"  "1"
                "imba_earth_spirit_geomagnetic_grip"  "1"
                "imba_earth_spirit_stone_remnant"  "1"
                "imba_earth_spirit_petrify"  "1"
                "imba_earth_spirit_magnetize"  "1"
            }
            "hero_elder_titan"
            {
                "imba_elder_titan_echo_stomp"  "1"
                //"imba_elder_titan_echo_stomp_spirit"  "1"       // doesnt work
                "imba_elder_titan_ancestral_spirit"  "1"
                //"imba_elder_titan_return_spirit"  "1"
                "imba_elder_titan_natural_order"  "1"
                "imba_elder_titan_earth_splitter"  "1"
            }
            "hero_ember_spirit"
            {
                "imba_ember_spirit_searing_chains"  "1"
                "imba_ember_spirit_sleight_of_fist"  "1"
                "imba_ember_spirit_flame_guard"  "1"
                "imba_ember_spirit_activate_fire_remnant"  "1"
                "imba_ember_spirit_fire_remnant"  "1"
            }
            "hero_enchantress"
            {
                "imba_enchantress_untouchable"  "1"
                "imba_enchantress_enchant"  "1"
                "imba_enchantress_natures_attendants"  "1"
                "imba_enchantress_natura_shift"  "1"
                "imba_enchantress_impetus"  "1"
            }
            "hero_enigma"
            {
                "imba_enigma_malefice"  "1"
                "imba_enigma_demonic_conversion"  "1"
                "imba_enigma_midnight_pulse"  "1"
                "imba_enigma_black_hole"  "1"
            }
            "hero_faceless_void"
            {
                "imba_faceless_void_time_walk"  "1"
                "imba_faceless_void_time_dilation"  "1"
                "imba_faceless_void_time_lock"  "1"
                "imba_faceless_void_timelord"  "1"
                "imba_faceless_void_chronosphere"  "1"
            }
            "hero_huskar"
            {
                //"imba_huskar_inner_vitality"  "1"   // cant skill up
                "imba_huskar_inner_fire"  "1"
                "imba_huskar_burning_spear"  "1"
                "imba_huskar_berserkers_blood"  "1"
                "imba_huskar_life_break"  "1"
            }
            "hero_jakiro"
            {
                //"imba_jakiro_ice_breath"  "1"       // linked to fire breath
                "imba_jakiro_fire_breath"  "1"
                "imba_jakiro_liquid_fire"  "1"
                "imba_jakiro_ice_path"  "1"
                "imba_jakiro_macropyre"  "1"
            }
            "hero_juggernaut"
            {
                "imba_juggernaut_healing_ward"  "1"
                //"imba_juggernaut_healing_ward_passive"  "1"
                "imba_juggernaut_blade_dance"  "1"
                "imba_juggernaut_blade_fury"  "1"
                "imba_juggernaut_omni_slash"  "1"
            }
            "hero_keeper_of_the_light"
            {
                "imba_keeper_of_the_light_illuminate"  "1"
                "imba_keeper_of_the_light_blinding_light"  "1"
                "imba_keeper_of_the_light_chakra_magic"  "1"
                "imba_keeper_of_the_light_spotlights"  "1"
                "imba_keeper_of_the_light_will_o_wisp"  "1"
            }
            "hero_kunkka"
            {
                "imba_kunkka_torrent"  "1"
                "imba_kunkka_tidebringer"  "1"
                "imba_kunkka_x_marks_the_spot"  "1"
                "imba_kunkka_return"  "1"
                "imba_kunkka_ebb_and_flow"  "1"
                "imba_kunkka_ghostship"  "1"
            }
            "hero_lich"
            {
                "imba_lich_frost_nova"  "1"
                //"imba_lich_frost_armor"  "1"
                "imba_lich_frost_shield"  "1"
                "imba_lich_sinister_gaze"  "1"
                //"imba_lich_dark_ritual"  "1"
                "imba_lich_cold_front"  "1"
                "imba_lich_chain_frost"  "1"
            }
            "hero_lina"
            {
                "imba_lina_dragon_slave"  "1"
                "imba_lina_light_strike_array"  "1"
                "imba_lina_fiery_soul"  "1"
                "imba_lina_laguna_blade"  "1"
            }
            "hero_lion"
            {
                "imba_lion_mana_drain"  "1"
                "imba_lion_hex"  "1"
                "imba_lion_earth_spike"  "1"
                "imba_lion_finger_of_death"  "1"
            }
            "hero_luna"
            {
                "imba_luna_lucent_beam"  "1"
                "imba_luna_moon_glaive"  "1"
                "imba_luna_lunar_blessing"  "1"
                "imba_luna_eclipse"  "1"
            }
            "hero_lycan"
            {
                //"imba_lycan_summon_wolves"  "1"
                "imba_lycan_howl"  "1"
                "imba_lycan_feral_impulse"  "1"
                "imba_lycan_wolfsbane"  "1"
                "imba_lycan_shapeshift"  "1"
                
                //"imba_summoned_wolf_wicked_crunch"  "1"
                //"imba_summoned_wolf_hunter_instincts"  "1"
                //"imba_summoned_wolf_invisibility"  "1"
            }
            "hero_medusa"
            {
                "imba_medusa_split_shot"  "1"
                "imba_medusa_mystic_snake"  "1"
                "imba_medusa_mana_shield"  "1"
                "imba_medusa_stone_gaze"  "1"
            }
            "hero_mirana"
            {
                "imba_mirana_starfall"  "1"
                "imba_mirana_moonlight_shadow"  "1"
                "imba_mirana_arrow"  "1"
                "imba_mirana_leap"  "1"
            }
            "hero_necrolyte"
            {
                "imba_necrolyte_death_pulse"  "1"
                "imba_necrolyte_ghost_shroud"  "1"
                "imba_necrolyte_heartstopper_aura"  "1"
                "imba_necrolyte_sadist"  "1"
                "imba_necrolyte_reapers_scythe"  "1"
            }
            "hero_night_stalker"
            {
                "imba_night_stalker_void"  "1"
                "imba_night_stalker_crippling_fear_720"  "1"
                "imba_night_stalker_hunter_in_the_night"  "1"
                "imba_night_stalker_stalker_in_the_night"  "1"
                "imba_night_stalker_darkness"  "1"
            }
            "hero_nyx_assassin"
            {
                "imba_nyx_assassin_spiked_carapace"  "1"
                "imba_nyx_assassin_mana_burn"  "1"
                "imba_nyx_assassin_impale"  "1"
                "imba_nyx_assassin_vendetta"  "1"
            }
            "hero_obsidian_destroyer"
            {
                "imba_obsidian_destroyer_arcane_orb"  "1"
                "imba_obsidian_destroyer_astral_imprisonment"  "1"
                "imba_obsidian_destroyer_equilibrium"  "1"
                "imba_obsidian_destroyer_sanity_eclipse"  "1"
            }
            "hero_omniknight"
            {
                "imba_omniknight_purification"  "1"
                "imba_omniknight_repel"  "1"
                "imba_omniknight_hammer_of_virtue"  "1"
                "imba_omniknight_guardian_angel"  "1"
            }
            "hero_pangolier"
            {
                "imba_pangolier_swashbuckle"  "1"
                "imba_pangolier_shield_crash"  "1"
                "imba_pangolier_heartpiercer"  "1"
                "imba_pangolier_lucky_shot"  "1"
                "imba_pangolier_gyroshell"  "1"
            }
            "hero_phantom_assassin"
            {
                "imba_phantom_assassin_stifling_dagger"  "1"
                "imba_phantom_assassin_phantom_strike"  "1"
                "imba_phantom_assassin_blur"  "1"
                "imba_phantom_assassin_coup_de_grace"  "1"
            }
            "hero_phoenix"
            {
                "imba_phoenix_icarus_dive"  "1"
                // "imba_phoenix_icarus_dive_stop"  "1"
                "imba_phoenix_fire_spirits"  "1"
                //"imba_phoenix_launch_fire_spirit"  "1"
                "imba_phoenix_sun_ray"  "1"
                // "imba_phoenix_sun_ray_toggle_move"  "1"
                // "imba_phoenix_sun_ray_stop"  "1"
                //"imba_phoenix_burning_wings"  "1"
                "imba_phoenix_supernova"  "1"
            }
            "hero_pudge"
            {
                "imba_pudge_meat_hook"  "1"
                "imba_pudge_sharp_hook"  "1"
                "imba_pudge_light_hook"  "1"
                "imba_pudge_rot"  "1"
                "imba_pudge_flesh_heap"  "1"
                "imba_pudge_dismember"  "1"
            }
            "hero_pugna"
            {
                "imba_pugna_nether_blast"  "1"
                "imba_pugna_decrepify"  "1"
                //"imba_pugna_nether_ward"  "1"       //broken
                //"imba_pugna_nether_ward_aura"  "1"
                "imba_pugna_life_drain"  "1"
                //"imba_pugna_life_drain_end"  "1"
            }
            "hero_queenofpain"
            {
                "imba_queenofpain_shadow_strike"  "1"
                "imba_queenofpain_blink"  "1"
                "imba_queenofpain_scream_of_pain"  "1"
                "imba_queenofpain_sonic_wave"  "1"
                "imba_queenofpain_delightful_torment"  "1"
            }
            "hero_riki"
            {
                "imba_riki_smoke_screen"  "1"
                "imba_riki_blink_strike"  "1"
                "imba_riki_cloak_and_dagger"  "1"
                "imba_riki_tricks_of_the_trade"  "1"
            }
            "hero_sand_king"
            {
                "imba_sandking_epicenter"  "1"
                //"imba_sandking_sand_storm"  "1"     //Duplicate
                "imba_sandking_sand_storm_720"  "1"
                "imba_sandking_caustic_finale"  "1"
                "imba_sandking_burrowstrike"  "1"
            }
            "hero_nevermore"
            {
                "imba_nevermore_necromastery"  "1"
                "imba_nevermore_shadowraze_close"  "1"
                "imba_nevermore_dark_lord"  "1"
                "imba_nevermore_requiem"  "1"
                "imba_nevermore_shadowraze_far"  "1"
                "imba_nevermore_shadowraze_medium"  "1"
            }
            "hero_silencer"
            {
                "imba_silencer_arcane_curse"  "1"
                "imba_silencer_glaives_of_wisdom"  "1"
                "imba_silencer_last_word"  "1"
                "imba_silencer_arcane_supremacy"  "1"
                "imba_silencer_global_silence"  "1"
            }
            "hero_skywrath_mage"
            {
                "imba_skywrath_mage_arcane_bolt"  "1"
                "imba_skywrath_mage_concussive_shot"  "1"
                "imba_skywrath_mage_ancient_seal"  "1"
                "imba_skywrath_mage_mystic_flare"  "1"
            }
            "hero_slardar"
            {
                "imba_slardar_corrosive_haze"  "1"
                "imba_slardar_slithereen_crush"  "1"
                //"imba_slardar_bash_of_the_deep"  "1"      //error when not skilled, works when skilled - The chance was not found! Make sure to add it to the table or change the value.
                "imba_slardar_guardian_sprint"  "1"
                "imba_slardar_rain_cloud"  "1"
            }
            "hero_sniper"
            {
                "imba_sniper_shrapnel"  "1"
                "imba_sniper_headshot"  "1"
                "imba_sniper_take_aim"  "1"
                "imba_sniper_assassinate"  "1"
            }
            "hero_spirit_breaker"
            {
                "imba_spirit_breaker_charge_of_darkness"  "1"
                "imba_spirit_breaker_bulldoze"  "1"
                "imba_spirit_breaker_greater_bash"  "1"
                "imba_spirit_breaker_nether_strike"  "1"
            }
            "hero_storm_spirit"
            {
                "imba_storm_spirit_overload"  "1"
                "imba_storm_spirit_static_remnant"  "1"
                "imba_storm_spirit_electric_vortex"  "1"
                "imba_storm_spirit_ball_lightning"  "1"
            }
            "hero_sven"
            {
                "imba_sven_warcry"  "1"
                "imba_sven_colossal_slash"  "1"
                "imba_sven_great_cleave"  "1"
                "imba_sven_storm_bolt"  "1"
                "imba_sven_gods_strength"  "1"
            }
            "hero_tidehunter"
            {
                "imba_tidehunter_gush"  "1"
                "imba_tidehunter_kraken_shell"  "1"
                "imba_tidehunter_anchor_smash"  "1"
                "imba_tidehunter_ravage"  "1"
            }
            "hero_tiny"
            {
                "imba_tiny_rolling_stone"  "1"
                "imba_tiny_avalanche"  "1"
                "imba_tiny_toss"  "1"
                "imba_tiny_craggy_exterior"  "1"
                //"imba_tiny_tree_grab"  "1"
                //"imba_tiny_tree_throw"  "1"
                "imba_tiny_grow"  "1"
            }
            "hero_troll_warlord"
            {
                "imba_troll_warlord_berserkers_rage"  "1"
                "imba_troll_warlord_whirling_axes_ranged"  "1"
                "imba_troll_warlord_whirling_axes_melee"  "1"
                "imba_troll_warlord_fervor"  "1"
                "imba_troll_warlord_battle_trance"  "1"
            }
            "hero_ursa"
            {
                "imba_ursa_territorial_hunter"  "1"
                "imba_ursa_earthshock"  "1"
                "imba_ursa_enrage"  "1"
                "imba_ursa_fury_swipes"  "1"
                "imba_ursa_overpower"  "1"
            }
            "hero_vengefulspirit"
            {
                "imba_vengefulspirit_magic_missile"  "1"
                "imba_vengefulspirit_wave_of_terror"  "1"
                "imba_vengefulspirit_command_aura"  "1"
                "imba_vengefulspirit_rancor"  "1"
                "imba_vengefulspirit_nether_swap"  "1"
                //"imba_vengefulspirit_swap_back"  "1"
            }
            "hero_venomancer"
            {
                "imba_venomancer_venomous_gale"  "1"
                "imba_venomancer_plague_ward"  "1"
                "imba_venomancer_poison_sting"  "1"
                "imba_venomancer_poison_nova"  "1"
                "imba_venomancer_toxicity"  "1"
            }
            "hero_warlock"
            {
                "imba_warlock_fatal_bonds"  "1"
                "imba_warlock_shadow_word"  "1"
                "imba_warlock_upheaval"  "1"
                "imba_warlock_rain_of_chaos"  "1"
                "imba_warlock_flaming_fists"  "1"
                //"imba_warlock_golem_spell_immunity"  "1"
                //"imba_warlock_permanent_immolation"  "1"
            }
            "hero_winter_wyvern"
            {
                "imba_winter_wyvern_arctic_burn"  "1"
                "imba_winter_wyvern_splinter_blast"  "1"
                "imba_winter_wyvern_cold_embrace"  "1"
                "imba_winter_wyvern_winters_curse"  "1"
            }
            "hero_wisp"
            {
                "imba_wisp_tether"  "1"
                "imba_wisp_spirits"  "1"
                "imba_wisp_overcharge_721"  "1"
                "imba_wisp_swap_spirits"  "1"
                "imba_wisp_relocate"  "1"
            }
            "hero_witch_doctor"
            {
                "imba_witch_doctor_paralyzing_cask"  "1"
                "imba_witch_doctor_voodoo_restoration"  "1"
                "imba_witch_doctor_maledict"  "1"
                "imba_witch_doctor_death_ward"  "1"
            }
            "hero_wraith_king"
            {
                "imba_wraith_king_wraithfire_blast"  "1"
                "imba_wraith_king_vampiric_aura"  "1"
                "imba_wraith_king_mortal_strike"  "1"
                "imba_wraith_king_kingdom_come"  "1"
                //"imba_wraith_king_wraith_soul_strike"  "1"      //not a good spell
                "imba_wraith_king_reincarnation"  "1"
            }
            "hero_zuus"
            {
                "imba_zuus_arc_lightning"  "1"
                "imba_zuus_lightning_bolt"  "1"
                "imba_zuus_static_field"  "1"
                "imba_zuus_cloud"  "1"
                "imba_zuus_nimbus_zap"  "1"
                "imba_zuus_thundergods_wrath"  "1"
            }

        }
        // The IMBA skills in LoD
        "superop" {
            "radiant_jungle_op"
            {
                  "spawn_small_camp_op"            "1"
                  "spawn_medium_camp_op"           "1"
                  "spawn_large_camp_op"            "1"
                  "spawn_ancient_camp_op"          "1"
            }

            "angel_arena_tome_op" 
            {
                  "angel_arena_tome_lvlup_op"  "1"
                  "angel_arena_tome_gods_op"  "1"
                  "angel_arena_tome_int_op"  "1"
                  "angel_arena_tome_str_op"  "1"
                  "angel_arena_tome_agi_op"  "1"
                  "angel_arena_tome_med_op"  "1"
            }

            "imba_towers_700_and_survivor" 
            {
                  "imba_tower_healing_tower"    "1"
                  //"imba_roshan_fury_op"      "1"
                  "spell_lab_survivor_cooldown_op"    "1"
                  "spell_lab_survivor_spell_boost_op" "1"
            }

            "imba_towers_weak" 
            {
                "omniknight_degen_aura_tower"   "1"
                "omniknight_degen_aura_damage_tower"   "1"
                "vassal_shield"   "1"
                "titan_command_aura"    "1"
                "bahamut_reckoning_aura"  "1"
                "imba_tower_atrophy"   "1"
                "imba_tower_force"   "1"
                "imba_tower_mana_burn"   "1"
                "imba_tower_mana_flare"   "1"
                "imba_tower_mindblast"   "1"
                "imba_tower_permabash"   "1"
                "imba_tower_plague"   "1"
                "imba_tower_spacecow"   "1"
            }

            "imba_towers_medium" 
            {
                  "invoker_retro_invisibility_aura_tower"      "1"
                  "imba_tower_plasma_field"     "1"
                  "imba_tower_death_pulse"      "1"
                  "imba_tower_berserk"   "1"
                  "imba_tower_spell_shield"   "1"
                  "imba_tower_hex_aura"   "1"
                  "imba_tower_vicious"   "1"
                  "imba_tower_nature"   "1"
                  "imba_tower_chrono"   "1"
                  "summoner_tesla_coil"   "1"
                  "lich_cold_aura"    "1"
                  "imba_tower_laser"   "1"
                  "imba_tower_disease"   "1"
            }
            "imba_towers_strong" 
            {
                  "imba_tower_multihit"   "1"
                  "imba_tower_sniper"   "1"
                  "imba_tower_grievous_wounds"   "1"
                  "imba_tower_essence_drain"   "1"
                  "imba_tower_machinegun"   "1"
                  "imba_tower_salvo"   "1"
                  "imba_tower_fervor"   "1"
                  "imba_tower_split"   "1"
            }

            "memes_reborn_op"{
                  "lina_banana"     "1"
                  "lina_blazer"     "1"
                  "lina_coconut"    "1"
                  "lina_grapefruit" "1"
            }

            "survivor_op" 
            {
                  "spell_lab_survivor_agi_survival" "1"
                  "spell_lab_survivor_armor" "1"
                  "spell_lab_survivor_attack_range" "1"
                  "spell_lab_survivor_attack_speed" "1"
                  "spell_lab_survivor_bash" "1"
                  "spell_lab_survivor_cast_range" "1"
                  "spell_lab_survivor_cooldown" "1"
                  "spell_lab_survivor_critical" "1"
                  "spell_lab_survivor_damage_boost" "1"
                  "spell_lab_survivor_evasion" "1"
                  "spell_lab_survivor_int_survival" "1"
                  "spell_lab_survivor_life_steal" "1"
                  "spell_lab_survivor_mana_burn" "1"
                  "spell_lab_survivor_mana_regen" "1"
                  "spell_lab_survivor_spell_boost" "1"
                  "spell_lab_survivor_spell_vamp" "1"
                  "spell_lab_survivor_str_survival" "1"
                  "spell_lab_survivor_tenacity" "1"          
            }

            "spell_lab_souls_op" 
            {
                "spell_lab_souls_agi" "1"
                "spell_lab_souls_armor" "1"
                "spell_lab_souls_attack_range" "1"
                "spell_lab_souls_attack_speed" "1"
                "spell_lab_souls_cast_range" "1"
                "spell_lab_souls_cooldown" "1"
                "spell_lab_souls_damage" "1"
                "spell_lab_souls_evasion" "1"
                "spell_lab_souls_int" "1"            
                "spell_lab_souls_mana_regen" "1"
                "spell_lab_souls_spell_boost" "1"
                "spell_lab_souls_str" "1"
                "spell_lab_souls_tenacity" "1"
             }

            "basic_abilities"
            {
                  "basic_tenacity_bonus_op"   "1"
                  //"basic_willpower_bonus_op"   "1"
                  "basic_mana_bonus_op"   "1"
                  "basic_health_bonus_op" "1"
                  "basic_gpm_bonus_op" "1"
                  "basic_movespeed_bonus_op" "1"
                  "basic_xpm_bonus_op" "1"
                  "basic_spell_amp_bonus_op"   "1"
                  "basic_stat_gain_bonus_op"   "1"
                  "basic_stat_bonus_op"   "1"
                  "ability_mjolnir_op"    "1"
                  "ability_blademail_op" "1"
                  "ability_wards_op" "1"
                  "bash_reflect_op" "1"
                  //"redux_pocket_tower_ability"       "1" // Re-enable later
                  "basic_bat_op" "1"
                  "basic_bat_reduction_op" "1"
            }

            "singlePlayer_actives" {
                  "abyssal_underlord_dark_rift_op"    "1"
                  "axe_berserkers_call_op"            "1"
                  "batrider_flamebreak_op"            "1"
                  "bloodseeker_thirst_lod_op"         "1"
                  "dark_seer_vacuum_op"               "1" 
                  "global_stun"                       "1"   
                  "invoker_chaos_meteor_op"           "1"
                  "lich_chain_frost_op"               "1"                    
                  "tusk_walrus_kick_op"               "1"       
            }
            "singlePlayer_actives_2" {
                  "disruptor_kinetic_field_OP"              "1"
                  "disruptor_glimpse_OP"                    "1"
                  "ogre_magi_bloodlust_op"                  "1"
                  "ogre_magi_bloodlust_reverse"             "1"
                  "zuus_arc_lightning_op"                   "1"
                  "zuus_lightning_bolt_global"              "1"
                  "lone_druid_savage_roar_op"               "1"
                  "lone_druid_spirit_bear_return_lod_OP"    "1"
                  "tinker_heat_seeking_missile_redux"       "1"
                  "shadow_shaman_mass_serpent_ward_redux"   "1"
                  "legion_commander_duel_redux"             "1"
                  "mirana_invis_redux"                      "1"
                  "crystal_maiden_brilliance_aura_redux"    "1"
                  "faceless_void_chronosphere_redux"        "1"
            }
            "singlePlayer_actives_3" {
                  "android_cluster_rockets_OP"        "1"
                  "angel_arena_rifle_OP"              "1"
                  "serpent_queen_ball_lightning_op"   "1"
                  "shards_of_truesight_lod_OP"        "1"
                  "garden_red_flower_base_OP"         "1"
                  "hylonome_eldritch_pull_op"         "1"
                  "force_dash_lod_OP"                 "1"
                  "zulf_typhoon_OP"                   "1"
                  "android_pocket_factory"            "1"  
                  "aabs_nightshadow_op"               "1"
            }
            "singlePlayer_actives_4" {
                  "pangolier_swashbuckle_op"          "1"
                  "faceless_void_chronosphere_op"     "1"
                  "mars_arena_of_blood_op"            "1"
                  "grimstroke_soul_chain_friendly"    "1"
                  "grimstroke_soul_chain_op"          "1"
                  //"clinkz_burning_army_op"          "1"      // BUGGED Skeletons dont spawn
                  "summon_zombie"                     "1"
            }

            "singlePlayer_passive_4" {
                  "bounty_hunter_jinada_op"                 "1"
                  "bristleback_warpath_op"                  "1"
                  "templar_assassin_psi_blades_op"          "1"
                  "abyssal_underlord_atrophy_aura_op"     "1"       // needs updating to match new version
            }

            "singlePlayer_passive" {
                  "imba_tower_aegis_OP"                           "1"
                  //"erra_grave_guard_op"                         "1"  //Has been deleted since we brought in the LUA versions
                  "dragon_knight_dragon_blood_OP"                 "1"
                  "alchemist_goblins_greed_op"                    "1"
                  "shredder_reactive_armor_op"                    "1"
                  "nevermore_necromastery_op"                     "1"
                  //"imba_juggernaut_healing_ward_passive_redux"  "1"
                  "obsidian_destroyer_essence_aura_lod_health"    "1"
                  //"linkens_guard_lod"                           "1"                                          
            }
            "singlePlayer_passive_2" {
                  "angel_arena_razor_power_OP"        "1"
                  "angel_arena_nether_ritual"         "1"
                  "ebf_clinkz_trickshot_passive"      "1"
                  "lord_of_lightning_holy_wrath_OP"   "1"
                  "octarine_vampirism_lod_OP"         "1"
                  "aether_range_lod_OP"               "1"
                  "ebf_rubick_arcane_echo_OP"         "1"
                  "frost_lord_freezing_OP"            "1"
                  "pudge_flesh_heap_fiery_soul"     "1"
            }
            "singlePlayer_passive_3" {
                  "zhanhun_op"                        "1"
                  "jingtong_op"                       "1"
                  "spell_reflect_op"                  "1"
                  "master_magic_op"                   "1"
                  "channel_earthquake_op"             "1"
                  "chi_strike_sp"                     "1"
                  "metamorphosis_op"                  "1"
                  "death_prophet_witchcraft_op"       "1"
                  "invoker_sun_strike_lod_op"         "1"
            }

            "mega_ultimates" {
                  "mega_black_hole"       "1"
                  "armageddon"            "1"
                  "mega_chronosphere"     "1"
                  "mega_eclipse"          "1"
                  "floor_is_lava"         "1"
                  "mega_freezing_field"   "1"
                  "mega_suicide"          "1"
                  "mega_omni_slash"       "1"
                  "mega_call_down"        "1"
                  "mega_flare"            "1"
            }

      }
    }
    "heroToSkillMap" {
        "npc_dota_hero_antimage" {
            "Ability1"            "antimage_blink"
            "Ability2"            "antimage_blink_redux"
            "Ability3"            "antimage_mana_break"
            "Ability4"            "antimage_mana_void"
            "Ability5"            "antimage_spell_shield"
            "Ability6"            "antimage_counterspell"
        }

        "npc_dota_hero_queenofpain" {
            "Ability1"            "queenofpain_blink"
            "Ability2"            "queenofpain_blink_redux"
            "Ability3"            "queenofpain_scream_of_pain"
            "Ability4"            "queenofpain_shadow_strike"
            "Ability5"            "queenofpain_sonic_wave"
        }

        "npc_dota_hero_invoker" {
            "Ability1"            "invoker_alacrity_lod"
            "Ability2"            "invoker_chaos_meteor_lod"
            "Ability3"            "invoker_cold_snap_lod"
            "Ability4"            "invoker_emp_lod"
            "Ability5"            "invoker_forge_spirit_lod"
            "Ability6"            "invoker_ghost_walk_lod"
            "Ability7"            "invoker_ice_wall_lod"
            "Ability8"            "invoker_sun_strike_lod"
            "Ability9"            "invoker_tornado_lod"
            "Ability10"           "invoker_deafening_blast_lod"
        }

        "npc_dota_hero_beastmaster" {
            "Ability1"            "beastmaster_call_of_the_wild_boar"
            "Ability2"            "beastmaster_inner_beast"
            "Ability3"            "beastmaster_primal_roar"
            "Ability4"            "beastmaster_wild_axes"
            "Ability5"            "beastmaster_call_of_the_wild_hawk"
        }


        "npc_dota_hero_life_stealer" {
            "Ability1"            "life_stealer_rage"
            "Ability2"            "life_stealer_feast"
            "Ability3"            "life_stealer_feast_melee"
            "Ability4"            "life_stealer_open_wounds"
            "Ability5"            "life_stealer_infest"
            "Ability6"            "life_stealer_assimilate"
        }

        "npc_dota_hero_mirana" {
            "Ability1"            "mirana_starfall_lod"
            "Ability2"            "mirana_arrow"
            "Ability3"            "mirana_leap"
            "Ability4"            "mirana_invis"
        }
        "npc_dota_hero_tiny" {
            "Ability1"            "tiny_avalanche"
            "Ability2"            "tiny_toss"
            "Ability3"            "tiny_tree_grab"
            "Ability4"            "tiny_tree_channel"
            "Ability5"            "tiny_craggy_exterior"
            "Ability6"            "tiny_grow"
            "Ability7"            "tiny_toss_tree"
            "Ability8"            "tiny_grow_lod"
            "Ability9"            "tiny_grow_lod_redux" 
        }

        "npc_dota_hero_tusk" {
            "Ability1"        "tusk_ice_shards"
            "Ability2"        "tusk_snowball"
            "Ability3"        "tusk_tag_team"
            "Ability4"        "tusk_walrus_kick"
            "Ability6"        "tusk_walrus_punch"
            "Ability7"        "tusk_frozen_sigil"
        }
        "npc_dota_hero_snapfire" {
            "Ability1"        "snapfire_scatterblast"
            "Ability2"        "snapfire_firesnap_cookie"
            "Ability3"        "snapfire_lil_shredder"
            "Ability4"        "snapfire_mortimer_kisses"
        }
        "npc_dota_hero_void_spirit" {
            "Ability1"        "void_spirit_aether_remnant"
            "Ability2"        "void_spirit_dissimilate"
            "Ability3"        "void_spirit_resonant_pulse"
            "Ability4"        "void_spirit_astral_step"
        }

        "npc_dota_hero_skeleton_king" {
            "Ability1"            "skeleton_king_hellfire_blast"
            "Ability2"            "skeleton_king_mortal_strike"
            "Ability3"            "skeleton_king_reincarnation"
            "Ability4"            "skeleton_king_vampiric_aura"
            "Ability5"            "skeleton_king_reincarnation_redux"
        }
        "npc_dota_hero_bloodseeker" {
            "Ability1"            "bloodseeker_rupture"
            "Ability2"            "bloodseeker_blood_bath"
            "Ability3"            "bloodseeker_thirst_lod"
            "Ability4"            "bloodseeker_bloodrage"
            "Ability5"            "bloodseeker_blood_bath2"
        }
        "npc_dota_hero_ogre_magi" {
            "Ability1"            "ogre_magi_bloodlust"
            "Ability2"            "ogre_magi_fireblast"
            "Ability3"            "ogre_magi_ignite"
            "Ability4"            "ogre_magi_unrefined_fireblast"
            "Ability5"            "ogre_magi_multicast_lod"
            "Ability6"            "ogre_magi_multicast"
        }
        "npc_dota_hero_death_prophet" {
            "Ability1"            "death_prophet_carrion_swarm"
            "Ability2"            "death_prophet_silence"
            "Ability3"            "death_prophet_spirit_siphon"
            "Ability4"            "death_prophet_witchcraft"
            "Ability5"            "death_prophet_exorcism"
        }
        "npc_dota_hero_zuus" {
            "Ability1"            "zuus_arc_lightning"
            "Ability2"            "zuus_lightning_bolt"
            "Ability3"            "zuus_static_field"
            "Ability4"            "zuus_cloud"
            "Ability5"            "zuus_thundergods_wrath"
        }
        "npc_dota_hero_vengefulspirit" {
            "Ability1"            "vengefulspirit_magic_missile"
            "Ability2"            "vengefulspirit_wave_of_terror"
            "Ability3"            "vengefulspirit_command_aura"
            //"Ability4"            "vengefulspirit_nether_swap_redux"        // no npc text file for this ability
            "Ability5"            "vengefulspirit_nether_swap"
        }
        "npc_dota_hero_brewmaster" {
            "Ability1"            "brewmaster_thunder_clap"
            "Ability2"            "brewmaster_drunken_haze"
            "Ability3"            "brewmaster_drunken_brawler"
            "Ability4"            "brewmaster_primal_split"
            "Ability5"            "brewmaster_earth_hurl_boulder"
            "Ability6"            "brewmaster_earth_pulverize_redux"
            "Ability7"            "brewmaster_storm_wind_walk_redux"
            "Ability8"            "brewmaster_storm_dispel_magic"
            "Ability9"            "brewmaster_fire_permanent_immolation"
            "Ability10"           "brewmaster_storm_cyclone"
            "Ability11"           "brewmaster_cinder_brew"
        }
        "npc_dota_hero_crystal_maiden" {
            "Ability1"            "crystal_maiden_crystal_nova"
            "Ability2"            "crystal_maiden_frostbite"
            "Ability3"            "crystal_maiden_brilliance_aura"
            "Ability4"            "crystal_maiden_freezing_field"
        }
        "npc_dota_hero_chen" {
            "Ability1"        "chen_penitence"
            "Ability2"        "chen_divine_favor"
            "Ability3"        "chen_holy_persuasion"
            "Ability4"        "chen_test_of_faith"
            "Ability5"        "chen_hand_of_god"
        }
        "npc_dota_hero_clinkz" {
            "Ability1"        "clinkz_strafe"
            "Ability2"        "clinkz_searing_arrows"
            "Ability3"        "clinkz_wind_walk"
            "Ability4"        "clinkz_death_pact"
            "Ability5"        "clinkz_burning_army"
        }
        "npc_dota_hero_dazzle" {
            "Ability1"        "dazzle_poison_touch"
            "Ability2"        "dazzle_shallow_grave"
            "Ability3"        "dazzle_shadow_wave"
            "Ability4"        "dazzle_weave"
            "Ability5"        "dazzle_bad_juju"
            "Ability6"        "dazzle_bad_juju_redux"
        }
        "npc_dota_hero_rubick" {
            "Ability1"        "rubick_null_field"
            "Ability2"        "rubick_telekinesis"
            "Ability3"        "rubick_arcane_supremacy"
            "Ability4"        "rubick_fade_bolt"
        }
        "npc_dota_hero_axe" {
            "Ability1"            "axe_berserkers_call"
            "Ability2"            "axe_battle_hunger"
            "Ability3"            "axe_counter_helix"
            "Ability4"            "axe_culling_blade"
        }
        "npc_dota_hero_legion_commander" {
            "Ability1"            "legion_commander_overwhelming_odds"
            "Ability2"            "legion_commander_press_the_attack"
            "Ability3"            "legion_commander_moment_of_courage"
            "Ability4"            "legion_commander_duel"
        }
        "npc_dota_hero_sven" {
            "Ability1"            "sven_storm_bolt"
            "Ability2"            "sven_warcry"
            "Ability3"            "sven_great_cleave"
            "Ability4"            "sven_gods_strength"
        }
        "npc_dota_hero_spirit_breaker" {
            "Ability1"        "spirit_breaker_charge_of_darkness"
            "Ability2"        "spirit_breaker_empowering_haste"  
            "Ability3"        "spirit_breaker_greater_bash"      
            "Ability4"        "spirit_breaker_nether_strike"     
            "Ability5"        "spirit_breaker_bulldoze"
            "Ability6"        "spirit_breaker_greater_bash_ranged"             
        }
        "npc_dota_hero_juggernaut" {
            "Ability1"            "juggernaut_blade_fury"
            "Ability2"            "juggernaut_blade_dance"
            "Ability3"            "juggernaut_healing_ward"
            "Ability4"            "juggernaut_omni_slash"
            "Ability5"            "juggernaut_swift_slash"
            //"Ability6"          "juggernaut_healing_ward_mana"
        }
        "npc_dota_hero_obsidian_destroyer" {
            "Ability1"            "obsidian_destroyer_arcane_orb"
            "Ability2"            "obsidian_destroyer_astral_imprisonment"
            "Ability3"            "obsidian_destroyer_astral_imprisonment_redux"
            "Ability4"            "obsidian_destroyer_essence_aura_lod"
            "Ability5"            "obsidian_destroyer_essence_aura_redux"
            "Ability6"            "obsidian_destroyer_sanity_eclipse"
            "Ability7"            "obsidian_destroyer_equilibrium"
        }
        "npc_dota_hero_pangolier" {
            "Ability1"                          "pangolier_swashbuckle"
            "Ability2"                          "pangolier_shield_crash"
            "Ability3"                          "pangolier_lucky_shot"
            "Ability4"                          "pangolier_lucky_shot_ranged"
            "Ability5"                          "pangolier_heartpiercer"
            "Ability6"                          "pangolier_gyroshell"
      }
        "npc_dota_hero_earthshaker" {
            "Ability1"            "earthshaker_fissure"
            "Ability2"            "earthshaker_enchant_totem"
            "Ability3"            "earthshaker_aftershock"
            "Ability4"            "earthshaker_aftershock_lod"
            "Ability5"            "earthshaker_echo_slam"
        }
        "npc_dota_hero_slardar" {
            "Ability1"            "slardar_bash"
            "Ability2"            "slardar_sprint"
            "Ability3"            "slardar_slithereen_crush"
            "Ability4"            "slardar_amplify_damage"
            "Ability5"            "slardar_bash_ranged"
        }
        "npc_dota_hero_tinker" {
            "Ability1"            "tinker_laser"
            "Ability2"            "tinker_heat_seeking_missile"
            "Ability3"            "tinker_march_of_the_machines"
            "Ability4"            "tinker_rearm_lod"
            "Ability5"            "tinker_rearm"
        }
        "npc_dota_hero_slark" {
            "Ability1"            "slark_dark_pact"
            "Ability2"            "slark_pounce"
            "Ability3"            "slark_essence_shift"
            "Ability4"            "slark_essence_shift_intellect_lod"
            "Ability5"            "slark_essence_shift_strength_lod"
            "Ability6"            "slark_essence_shift_agility_lod"
            "Ability7"            "slark_shadow_dance"
            "Ability8"            "slark_shadow_dance_redux"

        }
        "npc_dota_hero_pudge" {
            "Ability1"            "pudge_meat_hook"
            "Ability2"            "pudge_rot"
            "Ability3"            "pudge_flesh_heap"
            "Ability4"            "pudge_dismember"
        }
        "npc_dota_hero_silencer" {
            "Ability1"            "silencer_curse_of_the_silent"
            "Ability2"            "silencer_glaives_of_wisdom"
            "Ability3"            "silencer_last_word"
            "Ability4"            "silencer_global_break"
            "Ability5"            "silencer_global_disarm"
            "Ability6"            "silencer_global_silence"
            "Ability7"            "silencer_glaives_of_wisdom_steal"
        }
        "npc_dota_hero_abyssal_underlord" {
            "Ability1"            "abyssal_underlord_atrophy_aura"
            "Ability2"            "abyssal_underlord_dark_rift"
            "Ability3"            "abyssal_underlord_firestorm"
            "Ability4"            "abyssal_underlord_pit_of_malice"
        }
        "npc_dota_hero_riki" {
            "Ability1"            "riki_smoke_screen"
            "Ability2"            "riki_blink_strike"
            "Ability3"            "riki_permanent_invisibility"
            "Ability4"            "riki_tricks_of_the_trade"
            "Ability5"            "riki_backstab"
        }
        "npc_dota_hero_ursa" {
            "Ability1"            "ursa_earthshock"
            "Ability2"            "ursa_overpower"
            "Ability3"            "ursa_overpower_melee"
            "Ability4"            "ursa_fury_swipes"
            "Ability5"            "ursa_fury_swipes_lod"
            "Ability6"            "ursa_enrage"
            "Ability7"            "ursa_enrage_old"
        }
        "npc_dota_hero_omniknight" {
            "Ability1"            "omniknight_degen_aura"
            "Ability3"            "omniknight_purification"
            "Ability5"            "omniknight_repel"
            "Ability6"            "omniknight_guardian_angel"
        }
        "npc_dota_hero_dazzle" {
            "Ability1"            "dazzle_poison_touch"
            "Ability2"            "dazzle_shadow_wave"
            "Ability3"            "dazzle_shallow_grave"
            "Ability4"            "dazzle_weave"
            "Ability5"            "dazzle_bad_juju"
            //"Ability6"            "dazzle_bad_juju_redux"
        }
        "npc_dota_hero_doom_bringer" {
            "Ability1"            "doom_bringer_devour_lod"
            "Ability2"            "doom_bringer_scorched_earth"
            "Ability3"            "doom_bringer_infernal_blade"
            "Ability4"            "doom_bringer_doom"
        }
      "npc_dota_hero_huskar" {
            "Ability1"            "huskar_berserkers_blood"
            "Ability2"            "huskar_burning_spear"
            "Ability3"            "huskar_inner_vitality"
            "Ability4"            "huskar_life_break"
            "Ability5"            "huskar_life_break_redux"
            "Ability6"            "huskar_berserkers_blood_lod"
            "Ability7"            "huskar_inner_fire"
        }
      "npc_dota_hero_lich" {
            "Ability1"        "lich_frost_nova"
            "Ability2"        "lich_frost_shield"
            "Ability3"        "lich_sinister_gaze"
            //"Ability4"        "lich_dark_ritual"
            "Ability4"        "lich_frost_armor"
            "Ability5"        "lich_chain_frost"
        }
      "npc_dota_hero_lone_druid" {

            "Ability1"        "lone_druid_rabid"
            "Ability2"        "lone_druid_spirit_bear"
            "Ability3"        "lone_druid_true_form"
            "Ability4"        "lone_druid_spirit_link"
            "Ability5"        "lone_druid_true_form_battle_cry"
            "Ability6"        "lone_druid_savage_roar"
        }
        "npc_dota_hero_meepo" {

            "Ability1"        "meepo_geostrike"
            "Ability2"        "meepo_earthbind"
            "Ability3"        "meepo_poof"
            "Ability4"        "meepo_divided_we_stand"
            "Ability5"        "meepo_ransack"
        }
      "npc_dota_hero_drow_ranger" {
            "Ability1"            "drow_ranger_frost_arrows"
            "Ability2"            "drow_ranger_wave_of_silence"
            "Ability3"            "drow_ranger_multishot"
            "Ability4"            "drow_ranger_marksmanship"
            "Ability5"            "marksmanship_int"
            "Ability6"            "marksmanship_str"
            "Ability7"            "drow_ranger_marksmanship_redux"
            "Ability8"            "drow_splitshot"
        }
       "npc_dota_hero_skywrath_mage"
        {
            "Ability1" "skywrath_mage_arcane_bolt"
            "Ability2"  "skywrath_mage_concussive_shot"
            "Ability3"  "skywrath_mage_ancient_seal"
            "Ability4"  "skywrath_mage_mystic_flare"
            "Ability5" "skywrath_mage_concussive_break"
        }
        "npc_dota_hero_undying"
        {
            "Ability1" "undying_decay"
            "Ability2"  "undying_soul_rip"
            "Ability3"  "undying_tombstone"
            "Ability4"  "undying_flesh_golem"
            "Ability5" "undying_decay_agi"
            "Ability6" "undying_decay_int"
        }
        "npc_dota_hero_monkey_king"
        {
            "Ability1" "monkey_king_boundless_strike"
            "Ability2"  "monkey_king_tree_dance"
            "Ability3"  "monkey_king_primal_spring"
            "Ability4"  "monkey_king_jingu_mastery_lod"
            "Ability5" "monkey_king_jingu_mastery_lod_ranged"
            //"Ability6" "monkey_king_mischief"
            "Ability6"  "monkey_king_wukongs_command"
        }
        "npc_dota_hero_mars"
        {
            "Ability1" "mars_spear"
            "Ability2"  "mars_gods_rebuke"
            "Ability3"  "mars_bulwark"
            "Ability4"  "mars_arena_of_blood"
        }

        "npc_dota_hero_necrolyte"
        {
            "Ability1" "necrolyte_death_pulse"
            "Ability2"  "necrolyte_sadist"
            "Ability3"  "necrolyte_sadist_lod"
            "Ability4"  "necrolyte_heartstopper_aura"
            "Ability5" "necrolyte_reapers_scythe"
        }
        "npc_dota_hero_sand_king"
        {
            "Ability1" "sandking_burrowstrike"
            "Ability2"  "sandking_epicenter"
            "Ability3"  "sandking_caustic_finale_redux"
            "Ability4"  "sandking_sand_storm"
        }
        "npc_dota_hero_phantom_lancer"
        {
            "Ability1" "phantom_lancer_doppelwalk"
            "Ability2"  "phantom_lancer_phantom_edge"
            "Ability3"  "phantom_lancer_juxtapose"
            //"Ability4"  "phantom_lancer_juxtapose_melee"
            "Ability4"  "phantom_lancer_spirit_lance"
        }
        "npc_dota_hero_alchemist"
        {
            "Ability1"  "alchemist_acid_spray"
            "Ability2"  "alchemist_goblins_greed"
            "Ability3"  "alchemist_unstable_concoction"
            "Ability4"  "alchemist_chemical_rage"
            "Ability5"  "alchemist_chemical_rage_redux"
            "Ability6"  "alchemist_transmuted_scepter"
            "Ability7"  "alchemist_aghnaim_magic_redux"
            "Ability8"  "alchemist_berserk_potion"
        }
        "npc_dota_hero_phantom_assassin"
        {
            "Ability1"  "phantom_assassin_stifling_dagger"
            "Ability2"  "phantom_assassin_phantom_strike"
            "Ability3"  "phantom_assassin_blur"
            "Ability4"  "phantom_assassin_coup_de_grace"
            "Ability5"  "phantom_assassin_coup_de_grace_melee"
        }
        "npc_dota_hero_abaddon"
        {
            "Ability1"  "abaddon_death_coil"
            "Ability2"  "abaddon_aphotic_shield"
            "Ability3"  "abaddon_frostmourne"
            "Ability4"  "abaddon_borrowed_time"
            "Ability5"  "abaddon_borrowed_time_redux"
        }
        "npc_dota_hero_arc_warden"
        {
            "Ability1"  "arc_warden_flux"
            "Ability2"  "arc_warden_magnetic_field"
            "Ability3"  "arc_warden_spark_wraith"
            "Ability4"  "arc_warden_tempest_double"
            "Ability5"  "arc_warden_tempest_double_redux"
            "Ability6"  "arc_warden_tempest_double_op"
        }
        "npc_dota_hero_faceless_void"
        {
            "Ability1"  "faceless_void_time_walk"
            "Ability2"  "faceless_void_time_dilation"
            "Ability3"  "faceless_void_time_lock"
            "Ability4"  "faceless_void_backtrack"
            "Ability5"  "faceless_void_chronosphere"
        }
        "npc_dota_hero_gyrocopter"
        {
            "Ability1"  "gyrocopter_call_down"
            "Ability2"  "gyrocopter_flak_cannon"
            "Ability4"  "gyrocopter_homing_missile"
            "Ability5"  "gyrocopter_rocket_barrage"
            "Ability6"  "side_gunner_redux"
        }
        "npc_dota_hero_night_stalker"
        {
            "Ability1"  "night_stalker_void"
            "Ability2"  "night_stalker_crippling_fear"
            "Ability3"  "night_stalker_hunter_in_the_night"
            "Ability4"  "night_stalker_darkness"
            "Ability5"  "night_stalker_innate_redux"
        }
        "npc_dota_hero_keeper_of_the_light"
        {
            "Ability1"  "keeper_of_the_light_blinding_light_lod"
            "Ability2"  "keeper_of_the_light_chakra_magic"
            "Ability3"  "keeper_of_the_light_chakra_magic_cooldown"
            "Ability4"  "keeper_of_the_light_illuminate"
            "Ability5"  "keeper_of_the_light_mana_leak"
            "Ability6"  "keeper_of_the_light_recall_lod"
            "Ability7"  "keeper_of_the_light_spirit_form"
            "Ability8"  "keeper_of_the_light_innate_redux"
            "Ability9"  "keeper_of_the_light_will_o_wisp"
        }
        "npc_dota_hero_nyx_assassin"
        {
            "Ability1"  "nyx_assassin_impale"
            "Ability2"  "nyx_assassin_mana_burn"
            "Ability3"  "nyx_assassin_spiked_carapace"
            "Ability4"  "nyx_assassin_vendetta"
            "Ability5"  "nyx_assassin_burrow"
            "Ability6"  "nyx_assassin_burrow_redux"
        }
        "npc_dota_hero_leshrac"
        {
            "Ability1"  "leshrac_split_earth"
            "Ability2"  "leshrac_lightning_storm"
            "Ability3"  "leshrac_diabolic_edict"
            "Ability4"  "leshrac_pulse_nova"
        }   
        "npc_dota_hero_morphling"
        {
            "Ability1"  "morphling_waveform"
            "Ability2"  "morphling_adaptive_strike_agi"
            "Ability3"  "morphling_adaptive_strike_str"
            "Ability4"  "morphling_morph_agi"
            "Ability5"  "morphling_morph_str"
            "Ability6"  "morphling_replicate"
            //"Ability7"  "morphling_hybrid"
            "Ability8"  "morph_int_str_redux"
            "Ability9"  "morph_str_int_redux"
            "Ability10"  "morph_agi_int_redux"
            "Ability11"  "morph_int_agi_redux"
        }
        "npc_dota_hero_dark_willow"
        {
            "Ability1"  "dark_willow_bramble_maze"
            "Ability2"  "dark_willow_shadow_realm"
            "Ability3"  "dark_willow_cursed_crown"
            "Ability4"  "dark_willow_bedlam"
            "Ability5"  "dark_willow_terrorize"
        }
        "npc_dota_hero_hoodwink"
        {
            "Ability1"  "hoodwink_acorn_shot"
            "Ability2"  "hoodwink_bushwhack"
            "Ability3"  "hoodwink_scurry"
            "Ability4"  "hoodwink_sharpshooter"
        }
 
         "npc_dota_hero_treant"   
        {
            "Ability1"  "treant_natures_grasp"
            "Ability2"  "treant_leech_seed"
            "Ability3"  "treant_living_armor"
            "Ability4"  "treant_eyes_in_the_forest"
            "Ability5"  "treant_natures_guise"
            "Ability6"  "treant_overgrowth"
        }

        "npc_dota_hero_dragon_knight" {
            "Ability1"  "dragon_knight_breathe_fire"
            "Ability2"  "dragon_knight_dragon_tail"
            "Ability3"  "dragon_knight_dragon_blood"
            "Ability4"  "dragon_knight_elder_dragon_form"
        }

        //"npc_dota_hero_dawnbreaker" {
        //    "Ability1"  "dawnbreaker_fire_wreath" "1"
        //    "Ability2"  "dawnbreaker_celestial_hammer" "1"
        //    "Ability3"  "dawnbreaker_converge" "1"
        //    "Ability4"  "dawnbreaker_luminosity" "1"
        //    "Ability5"  "dawnbreaker_solar_guardian" "1"
        //}

        "npc_dota_hero_marci" {
			"Ability1"		"marci_grapple"
			"Ability2"		"marci_companion_run"
			"Ability3"		"marci_guardian"
			"Ability4"		"marci_unleash"
        }


    }
}