"Abilities" {
    // These are the skill categories
    // The numbers are used for sending skills over the network, as well as encryptions
    "skills" {
        // The main skills, usually always avaiable
        "main" {
            "morph_int_str_redux"                     "1"
            "morph_str_int_redux"                     "1"
            "morph_agi_int_redux"                     "1"
             "morph_int_agi_redux"                      "1"
            "keeper_of_the_light_innate_redux"              "1"
            "night_stalker_innate_redux"                    "1"
            "skywrath_mage_concussive_break"               "1"
            "slark_essence_shift_strength_lod"            "1"
            "slark_essence_shift_intellect_lod"            "1"
            "slark_essence_shift_agility_lod"            "1"
            "slark_shadow_dance_redux"  "1"
            "ursa_fury_swipes_lod"              "1"
            "ursa_enrage_old"                  "1"
            "pudge_flesh_heap"            "1"
            "silencer_global_break"            "1"
            "silencer_global_disarm"            "1"
            //"juggernaut_healing_ward_mana"      "1"
            "ogre_magi_multicast_lod"            "1"
            "death_prophet_witchcraft"            "1"
            "earthshaker_aftershock_lod"            "1"
            "tinker_rearm_lod"            "1"
            "abaddon_aphotic_shield"            "1"
            "abaddon_borrowed_time"            "1"
            "abaddon_borrowed_time_redux"            "1"
            "abaddon_death_coil"            "1"
            "abaddon_frostmourne"            "1"
            "abyssal_underlord_atrophy_aura"            "1"
            "abyssal_underlord_dark_rift"            "1"
            "abyssal_underlord_firestorm"            "1"
            "abyssal_underlord_pit_of_malice"            "1"
            "alchemist_acid_spray"            "1"
            "alchemist_chemical_rage"            "1"
            "alchemist_chemical_rage_redux"     "1"
            "alchemist_goblins_greed"            "1"
            "alchemist_unstable_concoction"            "1"
            "alchemist_transmuted_scepter"      "1"
            "alchemist_aghnaim_magic_redux"     "1"
            "ancient_apparition_chilling_touch"            "1"
            "ancient_apparition_cold_feet"            "1"
            "ancient_apparition_ice_blast"            "1"
            "ancient_apparition_ice_vortex"            "1"
            "antimage_blink"            "1"     
            "antimage_blink_redux"  "1"
            "antimage_mana_break"            "1"
            "antimage_mana_void"            "1"
            "antimage_spell_shield"            "1"
            "antimage_counterspell"        "1"
            "axe_battle_hunger"            "1"
            "axe_berserkers_call"            "1"
            "axe_counter_helix"            "1"
            "axe_culling_blade"            "1"
            "bane_brain_sap"            "1"
            "bane_enfeeble"            "1"
            "bane_fiends_grip"            "1"
            "bane_nightmare"            "1"
            "batrider_firefly"            "1"
            "batrider_flamebreak"            "1"
            "batrider_flaming_lasso"            "1"
            "batrider_sticky_napalm"            "1"
            "beastmaster_call_of_the_wild"            "1"
            "beastmaster_inner_beast"            "1"
            "beastmaster_primal_roar"            "1"
            "beastmaster_wild_axes"            "1"
            "beastmaster_call_of_the_wild_hawk" "1"
            "bloodseeker_blood_bath"            "1"
            "bloodseeker_bloodrage"            "1"
            "bloodseeker_rupture"            "1"
            "bloodseeker_thirst_lod"            "1"
            "bloodseeker_blood_bath2"           "1"
            "bounty_hunter_jinada"            "1"
            "bounty_hunter_shuriken_toss"            "1"
            "bounty_hunter_track"            "1"
            "bounty_hunter_wind_walk"            "1"
            "brewmaster_drunken_brawler"            "1"
            "brewmaster_drunken_haze"            "1"
            "brewmaster_primal_split"            "1"
            "brewmaster_thunder_clap"            "1"
            "brewmaster_cinder_brew"            "1"
            "bristleback_bristleback"            "1"
            "bristleback_quill_spray"            "1"
            "bristleback_viscous_nasal_goo"            "1"
            "bristleback_warpath"            "1"
            "broodmother_incapacitating_bite"            "1"
            "broodmother_insatiable_hunger"            "1"
            "broodmother_spawn_spiderlings"            "1"
            "broodmother_spin_web"            "1"
            "centaur_double_edge"            "1"
            "centaur_hoof_stomp"            "1"
            "centaur_return"            "1"
            "centaur_stampede"            "1"
            "chaos_knight_chaos_bolt"            "1"
            "chaos_knight_chaos_strike"            "1"
            "chaos_knight_phantasm"            "1"
            "chaos_knight_reality_rift"            "1"
            "chen_hand_of_god"            "1"
            "chen_holy_persuasion"            "1"
            "chen_penitence"            "1"
            "chen_test_of_faith"            "1"
            "chen_divine_favor"                 "1"
            "clinkz_death_pact"            "1"
            "clinkz_searing_arrows"            "1"
            "clinkz_strafe"            "1"
            "clinkz_wind_walk"            "1"
            "clinkz_burning_army"         "1"
            "crystal_maiden_brilliance_aura"            "1"
            "crystal_maiden_crystal_nova"            "1"
            "crystal_maiden_freezing_field"            "1"
            "crystal_maiden_frostbite"            "1"
            "dark_seer_ion_shell"            "1"
            "dark_seer_surge"            "1"
            "dark_seer_vacuum"            "1"
            "dark_seer_wall_of_replica"            "1"
            "dazzle_poison_touch"            "1"
            "dazzle_shadow_wave"            "1"
            "dazzle_shallow_grave"            "1"
            "dazzle_weave"            "1"
            "dazzle_bad_juju" "1"
            "death_prophet_carrion_swarm"            "1"
            "death_prophet_exorcism"            "1"
            "death_prophet_silence"            "1"
            "disruptor_glimpse"            "1"
            "disruptor_kinetic_field"            "1"
            "disruptor_static_storm"            "1"
            "disruptor_thunder_strike"            "1"
            "doom_bringer_doom"            "1"
            "doom_bringer_devour_lod"     "1"
            "doom_bringer_scorched_earth"            "1"
            "dragon_knight_breathe_fire"            "1"
            "dragon_knight_dragon_blood"            "1"
            "dragon_knight_dragon_tail"            "1"
            "dragon_knight_elder_dragon_form"            "1"
            "drow_ranger_frost_arrows"            "1"
            "drow_ranger_marksmanship"            "1"
            "drow_ranger_marksmanship_redux"        "1"
            "drow_ranger_trueshot"            "1"
            "drow_ranger_wave_of_silence"            "1"
            "drow_splitshot"            "1"
            "marksmanship_int"                        "1"
            "marksmanship_str"                        "1"     
            "earth_spirit_boulder_smash"            "1"
            "earth_spirit_geomagnetic_grip"            "1"
            "earth_spirit_magnetize"            "1"
            "earth_spirit_rolling_boulder"            "1"
            "earthshaker_echo_slam"            "1"
            "earthshaker_enchant_totem"            "1"
            "earthshaker_fissure"            "1"
            "elder_titan_ancestral_spirit"            "1"
            "elder_titan_earth_splitter"            "1"
            "elder_titan_echo_stomp"            "1"
            "elder_titan_natural_order"            "1"
            //"ember_spirit_activate_fire_remnant"            "1"
            "ember_spirit_fire_remnant"            "1"
            "ember_spirit_flame_guard"            "1"
            "ember_spirit_searing_chains"            "1"
            "ember_spirit_sleight_of_fist"            "1"
            "enchantress_enchant"            "1"
            "enchantress_impetus"            "1"
            "enchantress_natures_attendants"            "1"
            "enchantress_untouchable"            "1"
            "enigma_black_hole"            "1"
            "enigma_demonic_conversion"            "1"
            "enigma_malefice"            "1"
            "enigma_midnight_pulse"            "1"
            "faceless_void_chronosphere"            "1"
            "faceless_void_time_lock"            "1"
            "faceless_void_time_walk"            "1"
            "faceless_void_backtrack"           "1"
            "furion_force_of_nature"            "1"
            "furion_sprout"            "1"
            "furion_teleportation"            "1"
            "furion_wrath_of_nature"            "1"
            "gyrocopter_call_down"            "1"
            "gyrocopter_flak_cannon"            "1"
            "gyrocopter_homing_missile"            "1"
            "gyrocopter_rocket_barrage"            "1"
            "side_gunner_redux"                       "1"
            "huskar_berserkers_blood"            "1"
            "huskar_burning_spear"            "1"
            "huskar_inner_vitality"            "1"
            "huskar_life_break"            "1"
            "huskar_life_break_redux"     "1"
            "huskar_berserkers_blood_lod"   "1"
            "huskar_inner_fire"           "1"
            "invoker_alacrity_lod"            "1"
            "invoker_chaos_meteor_lod"            "1"
            "invoker_cold_snap_lod"            "1"
            "invoker_emp_lod"            "1"
            "invoker_forge_spirit_lod"            "1"
            "invoker_ghost_walk_lod"            "1"
            "invoker_ice_wall_lod"            "1"
            "invoker_sun_strike_lod"            "1"
            "invoker_tornado_lod"            "1"
            "invoker_deafening_blast_lod" "1"
            //"forged_spirit_melting_strike" "1" // Doesn't work, needs a remake
            "jakiro_dual_breath"            "1"
            "jakiro_ice_path"            "1"
            "jakiro_liquid_fire"            "1"
            "jakiro_macropyre"            "1"
            "juggernaut_blade_dance"            "1"
            "juggernaut_blade_fury"            "1"
            "juggernaut_healing_ward"            "1"
            "juggernaut_omni_slash"            "1"
            "keeper_of_the_light_blinding_light_lod"            "1"
            "keeper_of_the_light_chakra_magic"            "1"
            "keeper_of_the_light_chakra_magic_cooldown"     "1"
            "keeper_of_the_light_illuminate"            "1"
            "keeper_of_the_light_mana_leak"            "1"
            "keeper_of_the_light_recall_lod"            "1"
            "keeper_of_the_light_spirit_form"            "1"
            "keeper_of_the_light_will_o_wisp"   "1"
            "kunkka_ghostship"            "1"
            "kunkka_tidebringer"            "1"
            "kunkka_torrent"            "1"
            "kunkka_x_marks_the_spot"            "1"
            "legion_commander_duel"            "1"
            "legion_commander_moment_of_courage"            "1"
            "legion_commander_overwhelming_odds"            "1"
            "legion_commander_press_the_attack"            "1"
            "leshrac_diabolic_edict"            "1"
            "leshrac_lightning_storm"            "1"
            //"leshrac_pulse_nova"            "1"
            "leshrac_pulse_nova_redux"       "1"
            "leshrac_split_earth"            "1"
            "lich_chain_frost"            "1"
            //"lich_dark_ritual"            "1" //No longer in the game
            "lich_frost_armor"            "1"
            "lich_frost_nova"            "1"
            "lich_sinister_gaze"          "1"
            "lich_frost_shield"              "1"
            "life_stealer_feast"            "1"
            "life_stealer_feast_melee"      "1"
            "life_stealer_infest"            "1"
          //"life_stealer_control"              "1"
            "life_stealer_open_wounds"            "1"
            "life_stealer_rage"            "1"
            "lina_dragon_slave"            "1"
            "lina_fiery_soul"            "1"
            "lina_laguna_blade"            "1"
            "lina_light_strike_array"            "1"
            "lion_finger_of_death"            "1"
            "lion_impale"            "1"
            "lion_mana_drain"            "1"
            "lion_voodoo"            "1"
            "lone_druid_rabid"            "1"
            "lone_druid_spirit_bear"            "1"
            "lone_druid_true_form"            "1"
            "lone_druid_spirit_link" "1"
            "luna_eclipse"            "1"
            "luna_lucent_beam"            "1"
            "luna_lunar_blessing"            "1"
            "luna_moon_glaive"            "1"
            "lycan_feral_impulse"            "1"
            "lycan_howl"            "1"
            "lycan_shapeshift"            "1"
            "lycan_summon_wolves"            "1"
            "magnataur_empower"            "1"
            "magnataur_reverse_polarity"            "1"
            "magnataur_shockwave"            "1"
            "magnataur_skewer"            "1"
            "medusa_mana_shield"            "1"
            "medusa_mystic_snake"            "1"
            "medusa_split_shot"            "1"
            "medusa_stone_gaze"            "1"
            "meepo_earthbind"            "1"
            "meepo_geostrike"            "1"
            "meepo_ransack"   "1"
            "meepo_poof"            "1"
            "mirana_arrow"            "1"
            "mirana_invis"            "1"
            "mirana_leap"            "1"
            "mirana_starfall_lod"            "1"
            "monkey_king_boundless_strike"  "1"
            "monkey_king_tree_dance"  "1"
            "monkey_king_primal_spring"  "1"
            "monkey_king_jingu_mastery_lod"  "1"
            "monkey_king_jingu_mastery_lod_melee"  "1"
            "monkey_king_wukongs_command"   "1"
            //"monkey_king_mischief"  "1"
            "morphling_adaptive_strike_agi"            "1"
            "morphling_adaptive_strike_str"           "1"
            "morphling_morph_agi"            "1"
            "morphling_morph_str"            "1"
            "morphling_replicate"            "1"
            "morphling_waveform"            "1"
            "naga_siren_ensnare"            "1"
            "naga_siren_mirror_image"            "1"
            "naga_siren_rip_tide"            "1"
            "naga_siren_song_of_the_siren"            "1"
            "necrolyte_death_pulse"            "1"
            "necrolyte_sadist_lod"      "1"
            "necrolyte_heartstopper_aura"            "1"
            "necrolyte_reapers_scythe"            "1"
            "necrolyte_sadist"            "1"
            "nevermore_dark_lord"            "1"
            "nevermore_necromastery"            "1"
            "nevermore_requiem"            "1"
            "nevermore_shadowraze1"            "1"
            "nevermore_shadowraze2"            "1"
            "nevermore_shadowraze3"            "1"
            "night_stalker_crippling_fear"            "1"
            "night_stalker_darkness"            "1"
            "night_stalker_hunter_in_the_night"            "1"
            "night_stalker_void"            "1"
            "nyx_assassin_impale"            "1"
            "nyx_assassin_mana_burn"            "1"
            "nyx_assassin_spiked_carapace"            "1"
            "nyx_assassin_vendetta"            "1"
            "nyx_assassin_burrow"            "1"
            "nyx_assassin_burrow_redux"            "1"
            "obsidian_destroyer_arcane_orb"            "1"
            //"obsidian_destroyer_astral_imprisonment"            "1" // Bugged ability because of charges not working
            "obsidian_destroyer_astral_imprisonment_redux" "1"
            "obsidian_destroyer_essence_aura_lod"            "1"
            "obsidian_destroyer_essence_aura_redux"            "1"
            "obsidian_destroyer_sanity_eclipse"            "1"
            "obsidian_destroyer_equilibrium"                "1"
            "ogre_magi_bloodlust"            "1"
            "ogre_magi_fireblast"            "1"
            "ogre_magi_ignite"            "1"
            "omniknight_degen_aura"            "1"
            "omniknight_guardian_angel"            "1"
            "omniknight_purification"            "1"
            "omniknight_repel"            "1"
            "oracle_false_promise"            "1"
            "oracle_fates_edict"            "1"
            "oracle_fortunes_end"            "1"
            "oracle_purifying_flames"            "1"
            "phantom_assassin_blur"            "1"
            "phantom_assassin_coup_de_grace"            "1"
            "phantom_assassin_coup_de_grace_melee"            "1"
            "phantom_assassin_phantom_strike"            "1"
            "phantom_assassin_stifling_dagger"            "1"
            "phantom_lancer_doppelwalk"            "1"
            "phantom_lancer_juxtapose"            "1"
            //"phantom_lancer_juxtapose_melee"            "1"
            "phantom_lancer_phantom_edge"            "1"
            "phantom_lancer_spirit_lance"            "1"
            "phoenix_fire_spirits"            "1"
            "phoenix_icarus_dive"            "1"
            "phoenix_sun_ray"            "1"
            "phoenix_supernova"            "1"
            "puck_dream_coil"            "1"
            //"puck_ethereal_jaunt"            "1"
            "puck_illusory_orb"            "1"
            "puck_phase_shift"            "1"
            "puck_waning_rift"            "1"
            "pudge_dismember"            "1"
            "pudge_meat_hook"            "1"
            "pudge_rot"            "1"
            "pugna_decrepify"            "1"
            "pugna_life_drain"            "1"
            "pugna_nether_blast"            "1"
            "pugna_nether_ward"            "1"
            "queenofpain_blink"            "1"
            "queenofpain_blink_redux"     "1" 
            "queenofpain_scream_of_pain"            "1"
            "queenofpain_shadow_strike"            "1"
            "queenofpain_sonic_wave"            "1"
            "rattletrap_battery_assault"            "1"
            "rattletrap_hookshot"            "1"
            "rattletrap_power_cogs"            "1"
            "rattletrap_rocket_flare"            "1"
            "razor_eye_of_the_storm"            "1"
            "razor_plasma_field"            "1"
            "razor_static_link"            "1"
            "razor_unstable_current"            "1"
            "riki_blink_strike"            "1"
            "riki_smoke_screen"            "1"
            "riki_backstab_lod"            "1"
            "rubick_fade_bolt"            "1"
            "rubick_null_field"            "1"
            "rubick_telekinesis"            "1"
            "rubick_arcane_supremacy"    "1"
            "sandking_burrowstrike"            "1"
            "sandking_epicenter"            "1"
            "sandking_sand_storm"            "1"
            "sandking_caustic_finale_redux"      "1"
            "shadow_demon_disruption"            "1"
            "shadow_demon_shadow_poison"            "1"
            //"shadow_demon_shadow_poison_release"            "1"
            "shadow_demon_soul_catcher"            "1"
            "shadow_shaman_ether_shock"            "1"
            "shadow_shaman_mass_serpent_ward"            "1"
            "shadow_shaman_shackles"            "1"
            "shadow_shaman_voodoo"            "1"
            "shredder_chakram"            "1"
            "shredder_reactive_armor"            "1"
            "shredder_timber_chain"            "1"
            "shredder_whirling_death"            "1"
            "silencer_curse_of_the_silent"            "1"
            "silencer_glaives_of_wisdom"            "1"
            "silencer_global_silence"            "1"
            "silencer_last_word"            "1"
            "silencer_glaives_of_wisdom_steal"  "1"
            "skeleton_king_hellfire_blast"            "1"
            "skeleton_king_mortal_strike"            "1"
            "skeleton_king_reincarnation"            "1"
            "skeleton_king_vampiric_aura"            "1"
            "skeleton_king_reincarnation_redux"      "1"
            "skywrath_mage_ancient_seal"            "1"
            "skywrath_mage_arcane_bolt"            "1"
            "skywrath_mage_concussive_shot"            "1"
            "skywrath_mage_mystic_flare"            "1"
            "slardar_amplify_damage"            "1"
            "slardar_bash"            "1"
            "slardar_slithereen_crush"            "1"
            "slardar_sprint"            "1"
            "slark_dark_pact"            "1"
            "slark_pounce"            "1"
            "slark_essence_shift"            "1"
            "slark_shadow_dance"            "1"
            "sniper_assassinate"            "1"
            "sniper_headshot"            "1"
            "sniper_shrapnel"            "1"
            "sniper_take_aim"            "1"
            "spectre_desolate"            "1"
            "spectre_dispersion"            "1"
            "spectre_haunt"            "1"
            //"spectre_reality"            "1"
            "spectre_spectral_dagger"            "1"
            "spirit_breaker_charge_of_darkness"            "1"
            "spirit_breaker_empowering_haste"            "1"
            "spirit_breaker_greater_bash"            "1"
            "spirit_breaker_nether_strike"            "1"
            "spirit_breaker_bulldoze"                 "1"
            "storm_spirit_ball_lightning"            "1"
            "storm_spirit_electric_vortex"            "1"
            "storm_spirit_overload"            "1"
            "storm_spirit_static_remnant"            "1"
            "sven_gods_strength"            "1"
            "sven_great_cleave"            "1"
            "sven_storm_bolt"            "1"
            "sven_warcry"            "1"
            //"techies_focused_detonate"            "1"
            "techies_land_mines"            "1"
            "techies_remote_mines"            "1"
            "techies_stasis_trap"            "1"
            "techies_suicide"            "1"
            "templar_assassin_meld"            "1"
            "templar_assassin_psi_blades"            "1"
            "templar_assassin_psionic_trap"            "1"
            "templar_assassin_refraction"            "1"
            //"templar_assassin_trap"            "1"
            "terrorblade_conjure_image"            "1"
            "terrorblade_metamorphosis"            "1"
            "terrorblade_reflection"            "1"
            "terrorblade_sunder"            "1"
            "tidehunter_anchor_smash"            "1"
            "tidehunter_gush"            "1"
            "tidehunter_kraken_shell"            "1"
            "tidehunter_ravage"            "1"
            "tinker_heat_seeking_missile"            "1"
            "tinker_laser"            "1"
            "tinker_march_of_the_machines"            "1"
            "tiny_avalanche"            "1"
            "tiny_craggy_exterior"            "1"
            "tiny_grow"            "1"
            "tiny_grow_lod"            "1"
            "tiny_grow_lod_redux"            "1"
            "tiny_toss"            "1"
            "treant_eyes_in_the_forest"            "1"
            "treant_leech_seed"            "1"
            "treant_living_armor"            "1"
            "treant_natures_guise"            "1"
            "treant_overgrowth"            "1"
            "troll_warlord_battle_trance"            "1"
            "troll_warlord_berserkers_rage"            "1"
            "troll_warlord_fervor"            "1"
            "troll_warlord_whirling_axes_ranged"            "1"
            "tusk_frozen_sigil"            "1"
            "tusk_ice_shards"            "1"
            "tusk_snowball"            "1"
            "tusk_walrus_punch"            "1"
            "tusk_walrus_kick"            "1"
            "tusk_tag_team"               "1"
            "undying_decay"            "1"
            "undying_decay_agi"            "1"
            "undying_decay_int"            "1"
            "undying_flesh_golem"            "1"
            "undying_soul_rip"            "1"
            "undying_tombstone"            "1"
            "ursa_earthshock"            "1"
            "ursa_enrage"            "1"
            "ursa_fury_swipes"              "1"
            "ursa_overpower"            "1"
            "ursa_overpower_melee"        "1"
            "vengefulspirit_command_aura"            "1"
            "vengefulspirit_magic_missile"            "1"
            "vengefulspirit_nether_swap"            "1"
            "vengefulspirit_wave_of_terror"            "1"
            "venomancer_plague_ward"            "1"
            "venomancer_poison_nova"            "1"
            "venomancer_poison_sting"            "1"
            "venomancer_venomous_gale"            "1"
            "viper_corrosive_skin"            "1"
            "viper_nethertoxin"            "1"
            "viper_poison_attack"            "1"
            "viper_viper_strike"            "1"
            "visage_grave_chill"            "1"
            "visage_gravekeepers_cloak"            "1"
            "visage_summon_familiars"            "1"
            "warlock_fatal_bonds"            "1"
            "warlock_rain_of_chaos"            "1"
            "warlock_shadow_word"            "1"
            "warlock_upheaval"            "1"
            "weaver_geminate_attack"            "1"
            "weaver_shukuchi"            "1"
            "weaver_the_swarm"            "1"
            "weaver_time_lapse"            "1"
            "windrunner_focusfire"            "1"
            "windrunner_powershot"            "1"
            "windrunner_shackleshot"            "1"
            "windrunner_windrun"            "1"
            "wisp_overcharge"            "1"
            "wisp_relocate"            "1"
            "wisp_spirits"            "1"
            "wisp_tether"            "1"
            "witch_doctor_death_ward"            "1"
            "witch_doctor_maledict"            "1"
            "witch_doctor_paralyzing_cask"            "1"
            "witch_doctor_voodoo_restoration"            "1"
            "zuus_arc_lightning"            "1"
            "zuus_lightning_bolt"            "1"
            "zuus_static_field"            "1"
            "zuus_thundergods_wrath"            "1"
            "zuus_cloud"                     "1"
            //"life_stealer_consume"            "1"
            "shadow_demon_demonic_purge"            "1"
            "shredder_chakram_2"            "1"
            "earth_spirit_petrify"            "1"
            "earth_spirit_stone_caller"            "1"
            "winter_wyvern_arctic_burn"            "1"
            "winter_wyvern_splinter_blast"            "1"
            "winter_wyvern_cold_embrace"            "1"
            "winter_wyvern_winters_curse"            "1"
            "life_stealer_assimilate"            "1"
            "morphling_hybrid"            "1"
            "arc_warden_flux"            "1"
            "arc_warden_magnetic_field"            "1"
            "arc_warden_spark_wraith"            "1"
            "arc_warden_tempest_double"            "1"
            "arc_warden_tempest_double_redux"            "1"
            "arc_warden_tempest_double_op"            "1"
            "death_prophet_spirit_siphon"            "1"
            //"doom_bringer_infernal_blade"            "1"
            "infernal_blade_lua"             "1"
            "faceless_void_time_dilation"            "1"
            "lone_druid_savage_roar"            "1"
            "riki_tricks_of_the_trade"            "1"
            "lone_druid_true_form_battle_cry"            "1"
            // Brewmaster
            "brewmaster_earth_hurl_boulder"            "1"
            //"brewmaster_earth_pulverize"            "1"
            "brewmaster_earth_pulverize_redux"        "1"
            //"brewmaster_storm_wind_walk"            "1"
            "brewmaster_storm_wind_walk_redux"            "1"
            "brewmaster_storm_dispel_magic"            "1"
            "brewmaster_fire_permanent_immolation"            "1"
            "brewmaster_storm_cyclone"            "1"
            // Ogre magi ulty
            "ogre_magi_unrefined_fireblast"            "1"
            // Meepo Ulty
            //"meepo_divided_we_stand"            "1"
            // Rearm
            "tinker_rearm"            "1"
            // Riki
            "riki_permanent_invisibility"            "1"
            // Multicast
            "ogre_magi_multicast"            "1"
            // Aftershock
            "earthshaker_aftershock"            "1"
            "pangolier_swashbuckle" "1"
            "pangolier_shield_crash"      "1"
            "pangolier_heartpiercer"      "1"
            "pangolier_gyroshell"   "1"
            "pangolier_lucky_shot"   "1"
            "dark_willow_bramble_maze"    "1"
            "dark_willow_bedlam"    "1"
            "dark_willow_terrorize" "1"
            "dark_willow_shadow_realm"    "1"
            "dark_willow_cursed_crown"    "1"
            "grimstroke_dark_artistry"    "1"
            "grimstroke_ink_creature" "1"
            "grimstroke_spirit_walk"    "1"
            "grimstroke_soul_chain"    "1"
        }
        // The neutrals skills
        "neutral" {
            "alpha_wolf_group" {
                "alpha_wolf_command_aura"                "1"
                "beastmaster_boar_poison"                "1"
                //"alpha_wolf_critical_strike"                "1"
                "black_dragon_splash_attack"                "1"
                "black_dragon_fireball_lod"                "1"
            }
            "beastmaster_boar_group" {

                //"beastmaster_greater_boar_poison"                "1" //Duplicate
            }
            "big_thunder_lizard_group" {
                "big_thunder_lizard_frenzy"                "1"
                "big_thunder_lizard_slam"                "1"
                "big_thunder_lizard_wardrums_aura"                  "1"
            }
            "black_dragon_group" {

                // "black_dragon_fireball"                "1"

                "neutral_spell_immunity"                "1"
                // "black_dragon_dragonhide_aura"                      "1"
            }
            "blue_dragonspawn_group" {
                "blue_dragonspawn_overseer_devotion_aura"                "1"
                "blue_dragonspawn_sorcerer_evasion"                "1"
                //"neutral_evasion"                "1"
            }
            "centaur_khan_group" {
                "centaur_khan_endurance_aura"                "1"
                "centaur_khan_war_stomp"                "1"
            }
            "dark_troll_warlord_group" {
                "dark_troll_warlord_ensnare"                "1"
                "dark_troll_warlord_raise_dead"                "1"
            }
            "enraged_wildkin_group" {
                "enraged_wildkin_tornado"                "1"
                "enraged_wildkin_toughness_aura"                "1"
            }
            "lone_druid_spirit_bear_group" {
                "lone_druid_spirit_bear_demolish"                "1"
                "lone_druid_spirit_bear_entangle"                "1"
                //"lone_druid_spirit_bear_return"                "1"
                "lone_druid_spirit_bear_return_lod"                "1"
                "visage_summon_familiars_stone_form"                "1"
            }
            "satyr_group" {
                "satyr_hellcaller_shockwave"                "1"
                "satyr_hellcaller_unholy_aura"                "1"
                "satyr_soulstealer_mana_burn"                "1"
                "satyr_trickster_purge"                "1"
            }
            "necronomicon_group" {
                "necronomicon_archer_aoe_lod"                "1"
                "necronomicon_archer_mana_burn_lod"                "1"
                "necronomicon_warrior_last_will_lod"                "1"
                "necronomicon_warrior_mana_burn_lod"                "1"
            }
            "roshan_group" {
                "roshan_slam"                "1"
                "roshan_spell_block"                "1"
                //"roshan_spell_block_lod"                "1"
                "roshan_bash"                "1"
            }
            "prowler_group" {
                "spawnlord_aura"                "1"
                "spawnlord_master_stomp"                "1"
                "spawnlord_master_freeze"                "1"
            }
            "warlock_group" {
                "warlock_golem_flaming_fists"                "1"
                "warlock_golem_permanent_immolation"                "1"
                "warlock_golem_permanent_immolation_lod"        "1"
            }
            "misc_neutral_1_group" {
                "forest_troll_high_priest_heal"                "1"
                "forest_troll_high_priest_mana_aura"  "1"
                "ghost_frost_attack"                "1"
                //"giant_wolf_critical_strike"                "1"
                "gnoll_assassin_envenomed_weapon"                "1"
            }
            "misc_neutral_2_group" {
                "granite_golem_hp_aura"                "1"
                "harpy_storm_chain_lightning"                "1"
                "kobold_taskmaster_speed_aura"                "1"
                "lycan_summon_wolves_critical_strike"                "1"
            }
            "misc_neutral_3_group" {
                "ogre_magi_frost_armor"                "1"
                "mud_golem_hurl_boulder"                "1"
                "mudgolem_cloak_aura"  "1"
                "polar_furbolg_ursa_warrior_thunder_clap"                "1"
                // doesnt work "mud_golem_rock_destroy"  "1"
            }
            //"misc_neutral_4_group" {
                // Removed because its buggy "backdoor_protection"                "1"

                // "broodmother_poison_sting"                "1"

                // "undying_tombstone_zombie_deathstrike"                "1" //Broken
            //}
            "forge_spirit" {
                  "forged_spirit_melting_strike"      "1"
            }
        }
        // The custom skills in LoD
        "custom"
        {
            "flesh_heap"
            {
                  "pudge_flesh_heap_agility"            "1"
                  "pudge_flesh_heap_int"            "1"
                  "pudge_flesh_heap_move_speed"     "1"
                  "pudge_flesh_heap_spell_amp"       "1"
                  "pudge_flesh_heap_attack_range"   "1"
                  "pudge_flesh_heap_cast_range"   "1"
                  "pudge_flesh_heap_bonus_vision" "1"
                  "pudge_flesh_heap_cooldown_reduction" "1"
                  "pudge_flesh_heap_magic_resistance" "1"
                  "pudge_flesh_heap_evasion" "1"
                  "pudge_flesh_heap_spell_lifesteal" "1"
                  "pudge_flesh_heap_lifesteal" "1"
                  "pudge_flesh_heap_armor" "1"
                  "pudge_flesh_heap_health_regeneration" "1"
                  "pudge_flesh_heap_mana_regeneration" "1"
                  "pudge_flesh_heap_minion_damage" "1"
                  "pudge_flesh_heap_tenacity" "1"
                  "pudge_flesh_heap_willpower" "1"
            }

            "survivor" 
            {
                  "spell_lab_survivor_health_regen" "1"
                  "spell_lab_survivor_move_speed" "1"
                  "spell_lab_survivor_vision" "1"
                  "spell_lab_survivor_magic_resistance" "1"
            }

            "spell_lab_souls" 
            {
                "spell_lab_souls_vision" "1"
                "spell_lab_souls_health_regen" "1"
                "spell_lab_souls_move_speed" "1"
                "spell_lab_souls_magic_resistance" "1"
            }

           "brawler"{
                 "brawler_int"                             "1"
                 "brawler_str"                             "1"
                 "brawler_agi"                             "1"
           }
           "imbaRoshan"{
                  //"imba_roshan_fury"      "1"
                  "imba_tower_healing_hero"     "1"
           }
            "spell_lab" {
                "spell_lab_one_with_nothing" "1"
                "spell_lab_symbiotic" "1"
                "arcane_mastery"   "1"
                "spell_lab_missile_storm" "1"
                "spell_lab_storm_minions" "1"
                "spell_lab_bfg" "1"
                "spell_lab_taxi" "1"
                //"spell_lab_ggs" "1"
            }
            "oneshotonekill" {
                  "jingtong"  "1"
                  "shiguanghuisu"      "1"
                  "benneng"   "1"
                  "sight"   "1"
                  "zhanhun"   "1"
            }
            "overflow" {
                  "blink_support"  "1"
                  "military"   "1"
                  "spell_reflect"   "1"
                  "berserker" "1"
                  "eldri_anti_magic" "1"
                  "channel_earthquake" "1"
                  "grow_beard" "1"
                  "eat_tree_eldri"  "1"
                  "chi_strike"  "1"
            }
            "angel_arena_blackstar" {
                  "aabs_nightshadow"     "1"
                  "aabs_thunder_musket"   "1"
            }
            //"resurgence"{
            //      "genos_survival_of_the_fittest"     "1"
            //}
            "radiant_jungle"{
                  "spawn_small_camp"            "1"
                  "spawn_medium_camp"           "1"
                  "spawn_large_camp"            "1"
                  "spawn_ancient_camp"          "1"
            }        
            "overflow_ult" {
                  "night_wolf" "1"
                  "dark_blade"      "1"
                  "light_blade"   "1"
                  "metamorphosis"   "1"
                  "seer"   "1"
                  "spectral_form"   "1"
                  "master_magic"   "1"
            }
            "mercy" {
                  "mercy_caduceus_healing"      "1"
                  //"mercy_caduceus_power"  "1"
                  "mercy_guardian_angel"  "1"
                  "mercy_angelic_descent" "1"
                  "mercy_heroes_never_die"      "1"
            }

            "holdout" {
                "zuus_thundergods_vengeance"                "1"
                "holdout_omnislash"                "1"
                "holdout_gods_strength"                "1"
                "holdout_gladiators_unite"                "1"
                "holdout_culling_blade"                "1"
                "holdout_arcane_aura"                "1"
                "holdout_gladiators_unite"                "1"
                //"holdout_scourge_ward"                              "1"      
                //"holdout_multishot"                                 "1"

            }
            "item_abilities" {
                "armoured_centipede"                              "1"
                "aether_range_lod"                "1"
                "octarine_vampirism_lod"                "1"
                "force_dash_lod"                "1"
                "shards_of_truesight_lod"                "1"
            }
           //  "random_abilities" {
           //     "true_random_lod_1"    "1"
           //     "true_random_lod_2"    "1"
           //     "true_random_lod_3"    "1"
           //     "true_random_lod_4"    "1"
           //     "true_random_lod_5"    "1"
           //     "true_random_lod_6"    "1"
           // }
            "cherub_abilities" {
                "cherub_sleep_cloud"      "1"
                "cherub_synthesis"      "1"
                "cherub_explosive_spore"      "1"
                "cherub_flower_garden"      "1"
            }

            "uther_abiliites"{
                  "uther_Hurl_Hammer"     "1"
                  "uther_Threatening_Bolt"      "1"
                  "uther_omniscience_wave"      "1"
                  "uther_Argent_Smite"      "1"
            }

            "proteus_abiliites"{
                  "proteus_razorwind"     "1"
                  "proteus_polyp"      "1"
                  "proteus_jet"      "1"
                  "proteus_rarefaction"      "1"
            }

            "tenebris_abiliites"{
                  "tenebris_blood_ward"   "1" //CRASHES
                  //"tenebris_effigy" "1" // PARTICLES DOES NOT DISSAPEAR
                  "tenebris_fade_strike"  "1"
                  "tenebris_mortal_coil"  "1"
            }

            "suna_abiliites"{
                  "suna_blight_and_wither"      "1"
            //    "suna_dead_mans_chest"  "1"
            //    "suna_kyonshi"    "1"
            //    "suna_mind_control"     "1" //SUB-ABILITY
                  "suna_puppeteer"  "1"
            //      "suna_vicissitude"      "1"
           }

           "veera"{
                  "veera_evasive_roll"    "1"
                  "veera_plains_runner"   "1"
                  "veera_pursuit"   "1"
                  "veera_thrill_of_the_hunt"    "1"
                  "veera_toxic_darts"     "1"
           }

           "zeros"{
                  "zeros_gerrymandering" "1"
                  "zeros_impose_tax" "1"
                  //"zeros_innate" "1"
                  "zeros_royal_statue" "1"
                  "zeros_blade_of_malice" "1"
                  "zeros_fanaticism" "1"
           }

           "achlys"{
                  "achlys_miserable_claws"      "1"
                  "achlys_nights_embrace" "1"
                  "achlys_sorrow_rising"  "1"
                  "achlys_death_mist"     "1"
           }

            "sirocco_abiliites"{
                  "sirocco_shifting_sands"      "1"
                  "sirocco_mirage"  "1"
                  "sirocco_dehydration_aura"    "1"
                  "sirocco_desert_curse"  "1"
            }

            "bellatrix_abiliites"{
                  "bellatrix_blood_cross" "1"
                  "bellatrix_blood_rake"  "1"
                  "bellatrix_live_transfusion"  "1"
                  "bellatrix_unholy_ecstasy"    "1"
            }

            //"scaw_abilities"{
            //      "scawmar_spirits_away"  "1"
            //      "scawmar_fade_blink"    "1"
            //      "scawmar_illusion_line" "1"
            //      "scawmar_mind_control"  "1"
            //      "scawmar_scryers_circle"      "1"
            //}

            "hylonome_abilities"{
                  "hylonome_eldritch_pull"      "1"
                  "hylonome_battle_rhythm"      "1"
                  "hylonome_anemic_aura"  "1"
                  "hylonome_libation"     "1"
            }

            "keen_abilities"{
                  "keen_commander_mortar_shot"  "1"
                  "keen_commander_recon_systems"      "1"
                  "keen_commander_siege_mode"   "1"
                  "keen_commander_slag_armor"   "1"
            }

            "alexander_abilities"{
                  "alexander_elandras_blessing" "1"
                  "alexander_godfall"     "1"
                  "alexander_radiant"     "1"
                  "alexander_soulseal"    "1"
            }

            "lightning_abilities"{
                  "lightning_lightning_dagger2" "1"
                  "lightning_overload"    "1"
                  "lightning_spark" "1"
                  "lightning_thunder_wave"     "1"
            }

            "ptomely_abilities"{
                  "ptomely_astralise"     "1"
                  "ptomely_enthrall"      "1"
                  "ptomely_expunge"       "1"
                  "ptomely_mirror_blade"  "1"
            }

            "mifune_abilities"{
                  "mifune_raigeki"  "1"
                  "mifune_genso"    "1"
                  "mifune_oiuchi"   "1"
                  "mifune_zanmato"  "1"
            }

            "erra_abilities"{
                  "erra_deathtouch" "1"
                  "erra_grave_guard"      "1"
                  "erra_morbid_blade"     "1"
                  "erra_to_dust"    "1"
            }

            "lich_abilities"{
                  "lich_absolute_zero" "1"
                  "lich_deep_freeze"  "1"
                  "lich_traveling_frost"  "1"
                  "lich_winters_requiem"  "1"
            }

            "hero_abilities"{
                  "hero_justice_kick"     "1"
                  "hero_one_punch"  "1"
                  "hero_freedom_strike"   "1"
                  "hero_heroic_soul"      "1"
            }

            "flower_abilities" {
                "garden_white_flower_base"      "1"
                "garden_red_flower_base"      "1"
                "garden_pink_blossom_base"      "1"
                "garden_blue_blossom_base"      "1"
                "garden_yellow_daisy_base"      "1"
                "garden_purple_lotus_base"      "1"
            }
            "zulf_abilities" {
                "zulf_cyclone_trap"      "1"
                "zulf_jet_stream"      "1"
                "zulf_gale_force"      "1"
                "zulf_typhoon"      "1"
            }
            "angel_arena_reborn" {
                "angel_arena_lightning"   "1"
                "angel_arena_magic_fire"      "1"
                "angel_arena_razor_power"     "1"
                "angel_arena_revenge"   "1"
                "angel_arena_shot"      "1"
                "angel_arena_storm"     "1"
                "angel_arena_summon_hawk"     "1"
                "angel_arena_berserk"   "1"
                "angel_arena_cripple"   "1"
            }
            "angel_arena_reborn_ult" {
                  "angel_arena_darkrage"  "1"
                  "angel_arena_night_vampire"   "1"
                  "angel_arena_roots"     "1"
                  "angel_arena_song"      "1"
                  "angel_arena_hola_heal" "1"
                  "angel_arena_transmute" "1"
                  "angel_arena_demonic"   "1"
                  "angel_arena_grace"     "1"
            }
            "angel_arena_tome" {
                  "angel_arena_tome_lvlup"  "1"
                  "angel_arena_tome_gods"  "1"
                  "angel_arena_tome_int"  "1"
                  "angel_arena_tome_str"  "1"
                  "angel_arena_tome_agi"  "1"
                  "angel_arena_tome_med"  "1"
            }
          
            "life_in_arena" {
                  "ancient_priestess_surge_of_intelligence" "1"
                  "ancient_priestess_spirit_link"     "1"
                  "archmage_magic_barrier"      "1"
                  "berserker_fire_spear"  "1"
                  "dark_ranger_black_arrow"     "1"
                  "firelord_flame_strike" "1"
                  "firelord_fire_trap"    "1"
                  "frost_lord_cold" "1"
                  "frost_lord_frost_breath"     "1"
                  "ghoul_devour"    "1"
                  "akron_explosion" "1"
                  "paladin_blizzard"      "1"
                  "dark_knight_dark_forces"     "1"
                  "lord_of_lightning_lightning_shield"      "1"
                  "android_cluster_rockets"     "1"
                  "serpent_queen_ball_lightning"      "1"
            }
            "life_in_arena_passive" {
                  "butcher_zombie"  "1"
                  "frost_lord_freezing"   "1"
                  "lord_of_lightning_holy_wrath"      "1"
                  "kret_poisoning"  "1"
                  "kret_lust_for_life"    "1"
            }
            "life_in_arena_ferocity" {
                  "brewmaster_ferocity"   "1"
                  "brewmaster_ferocity_agi"     "1"
                  "brewmaster_ferocity_int"     "1"
                  "brewmaster_ferocity_all"     "1"
            }
            "life_in_arena_ult" {
                  "ancient_priestess_ritual_protection" "1"
                  "berserker_madness"     "1"
                  "frost_lord_ice"  "1"
                  "lord_of_lightning_brain_storm"     "1"
                  "paladin_impregnability"      "1"
                  "angel_arena_archmage_anomaly"      "1"
            }
            "life_in_arena_illusion" {
                  "illusionist_mastery_of_deception"  "1"
                  "illusionist_whiff_of_deception"    "1"
                  "illusionist_agility_paws"    "1"
                  "illusionist_mastery_of_illusions"  "1"
            }
            "retro_dota" {
            //      "invoker_retro_betrayal"      "1"
                  "invoker_retro_portal"      "1"
                  "invoker_retro_scout"      "1"
                  "invoker_retro_invisibility_aura"      "1"
                  "invoker_retro_confuse"      "1"
                  "invoker_retro_disarm"      "1"
                  "invoker_retro_deafening_blast"      "1"
            }

            "imba_towers_weak" {
                "imba_tower_aegis"   "1"
                "imba_tower_forest"   "1"
                "imba_tower_self_repair"   "1"
                "imba_tower_thorns"   "1"
            }
            "ebf" {
                  "ebf_rubick_arcane_echo" "1"
                  "ebf_mana_fiend_essence_amp"  "1"
                  "ebf_clinkz_trickshot"      "1"
                  "ebf_underlord_expulsion"      "1"
                  "ebf_troll_warlord_multistrike"      "1"
            }
            "dusk" {
                  "gemini_abyssal_vortex" "1"
                  "gemini_unstable_rift"  "1"
                  "gemini_voidal_flare" "1"
                  "gemini_extraplanar_pact" "1"
            }
            "duskMisc1" {
                  "self_explosion" "1"
                  "ancient_defensive_wave"      "1"
                  //"ancient_last_resort"   "1" //Its bugged with illusions, it brings them back to life
                  "paragon_tranquility_seal"    "1"
            }
            "duskMisc2" {
                  "crimson_blood_sorcery" "1"
                  "alchemist_alchemise"   "1"
                  "alchemist_motherloads" "1"
                  "aether_reality_shift"  "1"
            }

            "lysander" {
                  //"lysander_adventurous_gale"   "1"
                  "lysander_captains_compass"   "1"
                  "lysander_grapeshot"    "1"
                  "lysander_phantom_fleet"      "1"
            }
            "basic_abilities"
            {
                  "basic_tenacity_bonus" "1"
                  //"basic_willpower_bonus" "1"
                  "basic_mana_bonus" "1"
                  "basic_health_bonus" "1"
                  "basic_gpm_bonus" "1"
                  "basic_movespeed_bonus" "1"
                  "basic_xpm_bonus" "1"
                  "basic_spell_amp_bonus" "1"
                  "basic_stat_gain_bonus" "1"
                  "basic_stat_bonus" "1"
                  "ability_mjolnir" "1"
                  "ability_blademail" "1"
                  "ability_wards"   "1"
                  "bash_reflect" "1"
            }


            "hawkeye" {
                  "hawkeye_detonator_dart" "1"
                  "hawkeye_double_tap"  "1"
                  "hawkeye_hit_n_run" "1"
                  "hawkeye_ricochet" "1"
            }
            "molten" {
                  "bulwark_strike"  "1"
                  "skipping_flames"       "1"
                  "unwavering_stance"     "1"
                  "molten_charge"    "1"
            }
      
            "DoD" {
                  "makemeleecreeps_lua"   "1"
                  "makerangedcreeps_lua"   "1"
                  "makecatapults_lua"   "1"
            }
            "memes_reborn"{
                  "lina_banana_redux"     "1"
                  "lina_coconut_redux"    "1"
                  "lina_grapefruit_redux" "1"
            }
            "patron_abilities" {
                  "crater" "1"
                  "ranged_punch" "1"
                  "pushing_blast" "1"
            }
            
        }
        "imba"
        {
            "hero_clinkz"
            {
                "imba_clinkz_searing_arrows"  "1"
                "imba_clinkz_death_pact"  "1"
                "imba_clinkz_skeleton_walk"  "1"
                //"imba_clinkz_strafe"  "1"
            }
            "hero_magnataur"
            {
                "imba_magnataur_skewer"  "1"
                "imba_magnataur_shockwave"  "1"
                "imba_magnataur_empower"  "1"
                "imba_magnataur_reverse_polarity"  "1"
            }
            "hero_silencer"
            {
                "imba_silencer_global_silence"  "1"
                "imba_silencer_arcane_curse"  "1"
                "imba_silencer_glaives_of_wisdom"  "1"
                "imba_silencer_arcane_supremacy"  "1"
                "imba_silencer_last_word"  "1"
            }
            "hero_ursa"
            {
                "imba_ursa_territorial_hunter"  "1"
                "imba_ursa_earthshock"  "1"
                "imba_ursa_enrage"  "1"
                "imba_ursa_fury_swipes"  "1"
                "imba_ursa_overpower"  "1"
            }
            "hero_sniper"
            {
                "imba_sniper_assassinate"  "1"
                "imba_sniper_take_aim"  "1"
                "imba_sniper_shrapnel"  "1"
                "imba_sniper_headshot"  "1"
            }
            "hero_necrolyte"
            {
                "imba_necrolyte_ghost_shroud"  "1"
                "imba_necrolyte_sadist"  "1"
                "imba_necrolyte_death_pulse"  "1"
                "imba_necrolyte_heartstopper_aura"  "1"
                "imba_necrolyte_reapers_scythe"  "1"
            }
            "hero_warlock"
            {
                "imba_warlock_upheaval"  "1"
                "imba_warlock_shadow_word"  "1"
                "imba_warlock_rain_of_chaos"  "1"
                "imba_warlock_flaming_fists"  "1"
                "imba_warlock_golem_spell_immunity"  "1"
                "imba_warlock_permanent_immolation"  "1"
                "imba_warlock_fatal_bonds"  "1"
            }
            "hero_drow_ranger"
            {
                //"imba_drow_ranger_deadeye"  "1"
                "imba_drow_ranger_marksmanship"  "1"
                "imba_drow_ranger_frost_arrows"  "1"
                "imba_drow_ranger_gust"  "1"
                "imba_drow_ranger_trueshot"  "1"
            }
            "hero_pudge"
            {
                "imba_pudge_dismember"  "1"
                "imba_pudge_rot"  "1"
                "imba_pudge_sharp_hook"  "1"
                "imba_pudge_meat_hook"  "1"
                "imba_pudge_light_hook"  "1"
            }
            "hero_disruptor"
            {
                "imba_disruptor_static_storm"  "1"
                "imba_disruptor_glimpse"  "1"
                "imba_disruptor_kinetic_field"  "1"
                "imba_disruptor_stormbearer"  "1"
                "imba_disruptor_thunder_strike"  "1"
            }
            // "hero_shredder"
            // {
            //     "imba_shredder_timber_chain"  "1"
            //     "imba_shredder_chakram"  "1"
            //     "imba_shredder_whirling_death"  "1"
            //     "imba_shredder_return_chakram"  "1"
            //     "imba_shredder_dendrophobia"  "1"
            //     "imba_shredder_reactive_armor"  "1"
            // }
            "hero_skeleton_king"
            {
                "imba_wraith_king_mortal_strike"  "1"
                "imba_wraith_king_reincarnation"  "1"
                "imba_wraith_king_wraith_soul_strike"  "1"
                "imba_wraith_king_kingdom_come"  "1"
                "imba_wraith_king_vampiric_aura"  "1"
                "imba_wraith_king_wraithfire_blast"  "1"
            }
            "hero_faceless_void"
            {
                "imba_faceless_void_time_lock"  "1"
                "imba_faceless_void_chronosphere"  "1"
                "imba_faceless_void_time_walk"  "1"
                "imba_faceless_void_timelord"  "1"
                "imba_faceless_void_time_dilation"  "1"
            }
            "hero_phoenix"
            {
                "imba_phoenix_supernova"  "1"
                //"imba_phoenix_launch_fire_spirit"  "1"
                "imba_phoenix_fire_spirits"  "1"
                "imba_phoenix_sun_ray"  "1"
                // "imba_phoenix_icarus_dive_stop"  "1"
                // "imba_phoenix_sun_ray_toggle_move"  "1"
                "imba_phoenix_icarus_dive"  "1"
                // "imba_phoenix_burning_wings"  "1"
                // "imba_phoenix_sun_ray_stop"  "1"
            }
            "hero_lion"
            {
                "imba_lion_mana_drain"  "1"
                "imba_lion_hex"  "1"
                "imba_lion_earth_spike"  "1"
                "imba_lion_finger_of_death"  "1"
            }
            "hero_tidehunter"
            {
                "imba_tidehunter_ravage"  "1"
            }
            "hero_naga_siren"
            {
                "imba_naga_siren_rip_tide"  "1"
                "imba_naga_siren_mirror_image"  "1"
            }
            "hero_crystal_maiden"
            {
                "imba_crystal_maiden_crystal_nova"  "1"
                "imba_crystal_maiden_arcane_dynamo"  "1"
                "imba_crystal_maiden_freezing_field"  "1"
                "imba_crystal_maiden_brilliance_aura"  "1"
                "imba_crystal_maiden_frostbite"  "1"
            }
            "hero_jakiro"
            {
                "imba_jakiro_ice_breath"  "1"
                "imba_jakiro_fire_breath"  "1"
                "imba_jakiro_liquid_fire"  "1"
                "imba_jakiro_ice_path"  "1"
                "imba_jakiro_macropyre"  "1"
            }
            "hero_enigma"
            {
                "imba_enigma_malefice"  "1"
                "imba_enigma_black_hole"  "1"
                "imba_enigma_midnight_pulse"  "1"
                "imba_enigma_demonic_conversion"  "1"
            }
            "hero_tiny"
            {
                "imba_tiny_craggy_exterior"  "1"
                "imba_tiny_toss"  "1"
                "imba_tiny_rolling_stone"  "1"
                "imba_tiny_avalanche"  "1"
                "imba_tiny_grow"  "1"
            }
            "hero_abaddon"
            {
                //"imba_abaddon_aphotic_shield"  "1"
                //"imba_abaddon_curse_of_avernus"  "1"
                //"imba_abaddon_mist_coil"  "1"
                //"imba_abaddon_over_channel"  "1" // HIDDEN ABILITY - DO NOT RE-ENABLE
                //"imba_abaddon_borrowed_time"  "1"
            }
            "hero_omniknight"
            {
                "imba_omniknight_repel"  "1"
                "imba_omniknight_guardian_angel"  "1"
                "imba_omniknight_purification"  "1"
                "imba_omniknight_hammer_of_virtue"  "1"
            }
            "hero_beastmaster"
            {
                "imba_beastmaster_summon_boar"  "1"
                "imba_beastmaster_hawk_invis"  "1"
                "imba_beastmaster_summon_hawk"  "1"
                "imba_beastmaster_boar_poison"  "1"
            }
            "hero_shadow_shaman"
            {
                "imba_shadow_shaman_mass_serpent_ward"  "1"
            }
            "hero_nevermore"
            {
                "imba_nevermore_necromastery"  "1"
                "imba_nevermore_shadowraze_close"  "1"
                "imba_nevermore_dark_lord"  "1"
                "imba_nevermore_requiem"  "1"
                "imba_nevermore_shadowraze_far"  "1"
                "imba_nevermore_shadowraze_medium"  "1"
            }
            "hero_hell_empress"
            {
                "imba_empress_hurl_through_hell"  "1"
                "imba_empress_ambient_effects"  "1"
                "imba_empress_royal_wrath"  "1"
                "imba_empress_hellbolt"  "1"
                "imba_empress_eleven_curses"  "1"
            }
            "hero_alchemist"
            {
                "imba_alchemist_mammonite"  "1"
                "imba_alchemist_goblins_greed"  "1"
                "imba_alchemist_acid_spray"  "1"
                "imba_alchemist_chemical_rage"  "1"
                //"imba_alchemist_greevils_greed"  "1"
                "imba_alchemist_unstable_concoction"  "1"
            }
            "hero_chaos_knight"
            {
                "imba_chaos_knight_phantasm"  "1"
                "imba_chaos_knight_reality_rift"  "1"
            }
            "hero_sand_king"
            {
                "imba_sandking_epicenter"  "1"
                "imba_sandking_caustic_finale"  "1"
                "imba_sandking_burrowstrike"  "1"
                "imba_sandking_sand_storm"  "1"
            }
            "hero_pugna"
            {
                "imba_pugna_nether_blast"  "1"
                "imba_pugna_life_drain"  "1"
                "imba_pugna_nether_ward"  "1"
                "imba_pugna_decrepify"  "1"
                "imba_pugna_nether_ward_aura"  "1"
                "imba_pugna_life_drain_end"  "1"
            }
            "hero_sly_king"
            {
                "imba_sly_king_winterbringer"  "1"
                "imba_sly_king_frozen_skin"  "1"
                "imba_sly_king_burrow_blast"  "1"
                "imba_sly_king_frost_gale"  "1"
            }
            "hero_tinker"
            {
                "imba_tinker_march_of_the_machines"  "1"
                "imba_tinker_laser"  "1"
                "imba_tinker_rearm"  "1"
                "imba_tinker_heat_seeking_missile"  "1"
                "imba_tinker_technomancy"  "1"
            }
            "hero_sven"
            {
                "imba_sven_warcry"  "1"
                "imba_sven_colossal_slash"  "1"
                "imba_sven_great_cleave"  "1"
                "imba_sven_storm_bolt"  "1"
                "imba_sven_gods_strength"  "1"
            }
            "hero_lycan"
            {
                "imba_lycan_wolfsbane"  "1"
                "imba_summoned_wolf_pack_leader"  "1"
                "imba_lycan_shapeshift"  "1"
                "imba_lycan_feral_impulse"  "1"
                "imba_lycan_howl"  "1"
                "imba_lycan_summon_wolves"  "1"
                "imba_summoned_wolf_wicked_crunch"  "1"
                "imba_summoned_wolf_hunter_instincts"  "1"
                "imba_summoned_wolf_invisibility"  "1"
            }
            "hero_scaldris"
            {
                "imba_scaldris_absolute_zero"  "1"
                "imba_scaldris_jet_blaze"  "1"
                "imba_scaldris_living_flame"  "1"
                "imba_scaldris_heatwave"  "1"
                "imba_scaldris_freeze"  "1"
                "imba_scaldris_scorch"  "1"
                "imba_scaldris_cold_front"  "1"
                "imba_scaldris_ice_floes"  "1"
                "imba_scaldris_antipode"  "1"
            }
            "hero_lich"
            {
                "imba_lich_chain_frost"  "1"
                "imba_lich_frost_nova"  "1"
                "imba_lich_cold_front"  "1"
                "imba_lich_frost_armor"  "1"
                "imba_lich_dark_ritual"  "1"
            }
            "hero_bane"
            {
                "imba_bane_enfeeble"  "1"
                "imba_bane_brain_sap"  "1"
                "imba_bane_fiends_grip"  "1"
                //"imba_bane_nightmare_end"  "1" // HIDDEN ABILITY
                "imba_bane_nightmare"  "1"
            }
            "hero_kunkka"
            {
                "imba_kunkka_torrent"  "1"
                "imba_kunkka_ebb_and_flow"  "1"
                "imba_kunkka_tidebringer"  "1"
                "imba_kunkka_return"  "1"
                "imba_kunkka_ghostship"  "1"
                "imba_kunkka_x_marks_the_spot"  "1"
            }
            "hero_axe"
            {
                //"imba_axe_berserkers_call"  "1"
                //"imba_axe_culling_blade"  "1"
                //"imba_axe_battle_hunger"  "1"
                //"imba_axe_counter_helix"  "1"
            }
            "hero_vengefulspirit"
            {
                "imba_vengefulspirit_swap_back"  "1"
                "imba_vengefulspirit_nether_swap"  "1"
                "imba_vengefulspirit_rancor"  "1"
                "imba_vengefulspirit_command_aura"  "1"
                "imba_vengefulspirit_wave_of_terror"  "1"
                "imba_vengefulspirit_magic_missile"  "1"
            }
            "hero_pangolier"
            {
                "imba_pangolier_swashbuckle"  "1"
                "imba_pangolier_gyroshell"  "1"
                "imba_pangolier_shield_crash"  "1"
                "imba_pangolier_heartpiercer"  "1"
            }
            "hero_doom_bringer"
            {
                "imba_doom_bringer_doom"  "1"
            }
            "hero_nyx_assassin"
            {
                "imba_nyx_assassin_spiked_carapace"  "1"
                "imba_nyx_assassin_mana_burn"  "1"
                "imba_nyx_assassin_impale"  "1"
                "imba_nyx_assassin_vendetta"  "1"
            }
            "hero_storm_spirit"
            {
                "imba_storm_spirit_overload"  "1"
                "imba_storm_spirit_static_remnant"  "1"
                "imba_storm_spirit_electric_vortex"  "1"
                "imba_storm_spirit_ball_lightning"  "1"
            }
            "hero_phantom_lancer"
            {
                "imba_phantom_lancer_spirit_lance"  "1"
            }
            "hero_slardar"
            {
                "imba_slardar_corrosive_haze"  "1"
                "imba_slardar_slithereen_crush"  "1"
                "imba_slardar_bash_of_the_deep"  "1"
                "imba_slardar_guardian_sprint"  "1"
                "imba_slardar_rain_cloud"  "1"
            }
            "hero_phantom_assassin"
            {
                "imba_phantom_assassin_coup_de_grace"  "1"
                "imba_phantom_assassin_stifling_dagger"  "1"
                "imba_phantom_assassin_phantom_strike"  "1"
                "imba_phantom_assassin_blur"  "1"
            }
            "hero_queenofpain"
            {
                //"imba_queenofpain_blink"  "1"
                //"imba_queenofpain_shadow_strike"  "1"
                //"imba_queenofpain_scream_of_pain"  "1"
                //"imba_queenofpain_sonic_wave"  "1"
                //"imba_queenofpain_delightful_torment"  "1"
            }
            "hero_riki"
            {
                "imba_riki_tricks_of_the_trade"  "1"
                "imba_riki_cloak_and_dagger"  "1"
                "imba_riki_blink_strike"  "1"
                "imba_riki_smoke_screen"  "1"
            }
            "hero_night_stalker"
            {
                "imba_night_stalker_crippling_fear"  "1"
                "imba_night_stalker_darkness"  "1"
                "imba_night_stalker_void"  "1"
                "imba_night_stalker_hunter_in_the_night"  "1"
                "imba_night_stalker_stalker_in_the_night"  "1"
            }
            "hero_mirana"
            {
                "imba_mirana_starfall"  "1"
                "imba_mirana_moonlight_shadow"  "1"
                "imba_mirana_arrow"  "1"
                "imba_mirana_leap"  "1"
            }
            "hero_juggernaut"
            {
                "imba_juggernaut_healing_ward"  "1"
                "imba_juggernaut_healing_ward_passive"  "1"
                "imba_juggernaut_blade_dance"  "1"
                "imba_juggernaut_blade_fury"  "1"
                "imba_juggernaut_omni_slash"  "1"
            }
            "hero_dragon_knight"
            {
                "imba_dragon_knight_dragon_blood"  "1"
                //"imba_dragon_knight_elder_dragon_charge"  "1"
                "imba_dragon_knight_elder_dragon_form"  "1"
                "imba_dragon_knight_dragon_tail"  "1"
                "imba_dragon_knight_breathe_fire"  "1"
            }
            "hero_witch_doctor"
            {
                "imba_witch_doctor_death_ward"  "1"
                "imba_witch_doctor_voodoo_restoration"  "1"
                "imba_witch_doctor_maledict"  "1"
                "imba_witch_doctor_paralyzing_cask"  "1"
            }
            "hero_skywrath_mage"
            {
                "imba_skywrath_mage_concussive_shot"  "1"
                "imba_skywrath_mage_mystic_flare"  "1"
                "imba_skywrath_mage_arcane_bolt"  "1"
            }
            "hero_obsidian_destroyer"
            {
                "imba_obsidian_destroyer_essence_aura"  "1"
                "imba_obsidian_destroyer_sanity_eclipse"  "1"
                "imba_obsidian_destroyer_astral_imprisonment"  "1"
                "imba_obsidian_destroyer_arcane_orb"  "1"
            }
            "hero_techies"
            {
                "imba_techies_remote_mine_pinpoint_detonation"  "1"
                "imba_techies_focused_detonate"  "1"
                "imba_techies_stasis_trap"  "1"
                "imba_techies_remote_mine"  "1"
                "imba_techies_stasis_trap_trigger"  "1"
                "imba_techies_minefield_sign"  "1"
                //"imba_techies_proximity_mine_trigger"  "1"
                "imba_techies_blast_off"  "1"
            }
            "hero_bounty_hunter"
            {
                "imba_bounty_hunter_shadow_walk"  "1"
                "imba_bounty_hunter_jinada"  "1"
                "imba_bounty_hunter_shuriken_toss"  "1"
                "imba_bounty_hunter_headhunter"  "1"
                "imba_bounty_hunter_track"  "1"
            }
            "hero_rubick"
            {
                //"imba_rubick_spell_steal_controller"  "1"
                "imba_rubick_telekinesis"  "1"
            }
            "hero_troll_warlord"
            {
                "imba_troll_warlord_berserkers_rage"  "1"
                "imba_troll_warlord_battle_trance"  "1"
                "imba_troll_warlord_fervor"  "1"
                "imba_troll_warlord_whirling_axes_melee"  "1"
                "imba_troll_warlord_whirling_axes_ranged"  "1"
            }
            "hero_spectre"
            {
                "imba_spectre_reality"  "1"
                "imba_spectre_haunt"  "1"
            }
            "hero_venomancer"
            {
                "imba_venomancer_venomous_gale"  "1"
                "imba_venomancer_plague_ward"  "1"
                "imba_venomancer_poison_sting"  "1"
                "imba_venomancer_poison_nova"  "1"
                "imba_venomancer_toxicity"  "1"
            }
            "hero_lina"
            {
                //"imba_lina_dragon_slave"  "1"
                //"imba_lina_light_strike_array"  "1"
                //"imba_lina_fiery_soul"  "1"
                //"imba_lina_laguna_blade"  "1"
            }
            "hero_antimage"
            {
                //"imba_antimage_spell_shield"  "1"
                //"imba_antimage_mana_void"  "1"
                //"imba_antimage_mana_break"  "1"
                //"imba_antimage_blink"  "1"
            }
            "hero_elder_titan"
            {
                "imba_elder_titan_natural_order"  "1"
                //"imba_elder_titan_echo_stomp"  "1" //Disabled because it crashes the game when used while astral spirit is out
                "imba_elder_titan_return_spirit"  "1"
                "imba_elder_titan_earth_splitter"  "1"
                "imba_elder_titan_ancestral_spirit"  "1"
                "imba_elder_titan_echo_stomp_spirit"  "1"
            }
            "hero_centaur"
            {
                "imba_centaur_hoof_stomp"  "1"
                "imba_centaur_double_edge"  "1"
                "imba_centaur_return"  "1"
                "imba_centaur_thick_hide"  "1"
                "imba_centaur_stampede"  "1"
            }
            "hero_bloodseeker"
            {
                "imba_bloodseeker_blood_bath"  "1"
                "imba_bloodseeker_thirst"  "1"
                "imba_bloodseeker_bloodrage"  "1"
                "imba_bloodseeker_rupture"  "1"
            }
            "hero_dazzle"
            {
                "imba_dazzle_ressurection"  "1"
                "imba_dazzle_shadow_wave"  "1"
                "imba_dazzle_poison_touch"  "1"
                "imba_dazzle_shallow_grave"  "1"
                "imba_dazzle_weave"  "1"
            }
        }
        // The IMBA skills in LoD
        "superop" {
            "radiant_jungle_op"
            {
                  "spawn_small_camp_op"            "1"
                  "spawn_medium_camp_op"           "1"
                  "spawn_large_camp_op"            "1"
                  "spawn_ancient_camp_op"          "1"
            }

            "angel_arena_tome_op" 
            {
                  "angel_arena_tome_lvlup_op"  "1"
                  "angel_arena_tome_gods_op"  "1"
                  "angel_arena_tome_int_op"  "1"
                  "angel_arena_tome_str_op"  "1"
                  "angel_arena_tome_agi_op"  "1"
                  "angel_arena_tome_med_op"  "1"
            }

            "imba_towers_700_and_survivor" 
            {
                  "imba_tower_healing_tower"    "1"
                  //"imba_roshan_fury_op"      "1"
                  "spell_lab_survivor_cooldown_op"    "1"
                  "spell_lab_survivor_spell_boost_op" "1"
            }

            "imba_towers_weak" 
            {
                "omniknight_degen_aura_tower"   "1"
                "omniknight_degen_aura_damage_tower"   "1"
                "vassal_shield"   "1"
                "titan_command_aura"    "1"
                "bahamut_reckoning_aura"  "1"
                "imba_tower_atrophy"   "1"
                "imba_tower_force"   "1"
                "imba_tower_mana_burn"   "1"
                "imba_tower_mana_flare"   "1"
                "imba_tower_mindblast"   "1"
                "imba_tower_permabash"   "1"
                "imba_tower_plague"   "1"
                "imba_tower_spacecow"   "1"
            }

            "imba_towers_medium" 
            {
                  "invoker_retro_invisibility_aura_tower"      "1"
                  //"imba_tower_plasma_field"     "1"
                  "imba_tower_death_pulse"      "1"
                  "imba_tower_berserk"   "1"
                  "imba_tower_spell_shield"   "1"
                  "imba_tower_hex_aura"   "1"
                  "imba_tower_vicious"   "1"
                  "imba_tower_nature"   "1"
                  "imba_tower_chrono"   "1"
                  "summoner_tesla_coil"   "1"
                  "lich_cold_aura"    "1"
                  "imba_tower_laser"   "1"
                  "imba_tower_disease"   "1"
            }
            "imba_towers_strong" 
            {
                  "imba_tower_multihit"   "1"
                  "imba_tower_sniper"   "1"
                  "imba_tower_grievous_wounds"   "1"
                  "imba_tower_essence_drain"   "1"
                  "imba_tower_machinegun"   "1"
                  "imba_tower_salvo"   "1"
                  "imba_tower_fervor"   "1"
                  "imba_tower_split"   "1"
            }

            "memes_reborn_op"{
                  "lina_banana"     "1"
                  "lina_blazer"     "1"
                  "lina_coconut"    "1"
                  "lina_grapefruit" "1"
            }

            "survivor_op" 
            {
                  "spell_lab_survivor_agi_survival" "1"
                  "spell_lab_survivor_armor" "1"
                  "spell_lab_survivor_attack_range" "1"
                  "spell_lab_survivor_attack_speed" "1"
                  "spell_lab_survivor_bash" "1"
                  "spell_lab_survivor_cast_range" "1"
                  "spell_lab_survivor_cooldown" "1"
                  "spell_lab_survivor_critical" "1"
                  "spell_lab_survivor_damage_boost" "1"
                  "spell_lab_survivor_evasion" "1"
                  "spell_lab_survivor_int_survival" "1"
                  "spell_lab_survivor_life_steal" "1"
                  "spell_lab_survivor_mana_burn" "1"
                  "spell_lab_survivor_mana_regen" "1"
                  "spell_lab_survivor_spell_boost" "1"
                  "spell_lab_survivor_spell_vamp" "1"
                  "spell_lab_survivor_str_survival" "1"
                  "spell_lab_survivor_tenacity" "1"          
            }

            "spell_lab_souls_op" 
            {
                "spell_lab_souls_agi" "1"
                "spell_lab_souls_armor" "1"
                "spell_lab_souls_attack_range" "1"
                "spell_lab_souls_attack_speed" "1"
                "spell_lab_souls_cast_range" "1"
                "spell_lab_souls_cooldown" "1"
                "spell_lab_souls_damage" "1"
                "spell_lab_souls_evasion" "1"
                "spell_lab_souls_int" "1"            
                "spell_lab_souls_mana_regen" "1"
                "spell_lab_souls_spell_boost" "1"
                "spell_lab_souls_str" "1"
                "spell_lab_souls_tenacity" "1"
             }

            "basic_abilities"
            {
                  "basic_tenacity_bonus_op"   "1"
                  "basic_willpower_bonus_op"   "1"
                  "basic_mana_bonus_op"   "1"
                  "basic_health_bonus_op" "1"
                  "basic_gpm_bonus_op" "1"
                  "basic_movespeed_bonus_op" "1"
                  "basic_xpm_bonus_op" "1"
                  "basic_spell_amp_bonus_op"   "1"
                  "basic_stat_gain_bonus_op"   "1"
                  "basic_stat_bonus_op"   "1"
                  "ability_mjolnir_op"    "1"
                  "ability_blademail_op" "1"
                  "ability_wards_op" "1"
                  "bash_reflect_op" "1"
                  //"redux_pocket_tower_ability"       "1" // Re-enable later
            }

            "singlePlayer_actives" {
                  "abyssal_underlord_dark_rift_op"   "1"
                  "axe_berserkers_call_op"      "1"
                  "batrider_flamebreak_op"      "1"
                  "bloodseeker_thirst_lod_op"            "1"
                  "dark_seer_vacuum_op"   "1" 
                  "global_stun"     "1"   
                  "invoker_chaos_meteor_op"   "1"
                  "lich_chain_frost_op"   "1"                    
                  "tusk_walrus_kick_op"   "1"       
            }
            "singlePlayer_actives_2" {
                  "disruptor_kinetic_field_OP"  "1"
                  "disruptor_glimpse_OP"  "1"
                  "ogre_magi_bloodlust_op"              "1"
                  "ogre_magi_bloodlust_reverse"           "1"
                  "zuus_arc_lightning_op" "1"
                  "zuus_lightning_bolt_global"            "1"
                  "lone_druid_savage_roar_op"   "1"
                  "lone_druid_spirit_bear_return_lod_OP"    "1"
                  "tinker_heat_seeking_missile_redux" "1"
                  "shadow_shaman_mass_serpent_ward_redux"   "1"
                  "legion_commander_duel_redux" "1"
                  "mirana_invis_redux"    "1"
                  "crystal_maiden_brilliance_aura_redux"    "1"
                  "faceless_void_chronosphere_redux"   "1"
            }
            "singlePlayer_actives_3" {
                  "android_cluster_rockets_OP" "1"
                  "angel_arena_rifle_OP" "1"
                  "serpent_queen_ball_lightning_op"   "1"
                  "shards_of_truesight_lod_OP"  "1"
                  "garden_red_flower_base_OP"   "1"
                  "hylonome_eldritch_pull_op"      "1"
                  "force_dash_lod_OP"     "1"
                  "zulf_typhoon_OP" "1"
                  "android_pocket_factory"      "1"  
                  "aabs_nightshadow_op"     "1"
            }
            "singlePlayer_passive" {
                  "imba_tower_aegis_OP"   "1"
                  //"erra_grave_guard_op"   "1" //Has been deleted since we brought in the LUA versions
                  "dragon_knight_dragon_blood_OP"     "1"
                  "alchemist_goblins_greed_op"  "1"
                  "shredder_reactive_armor_op"  "1"
                  "nevermore_necromastery_op"   "1"
                  //"imba_juggernaut_healing_ward_passive_redux"      "1"
                  "obsidian_destroyer_essence_aura_lod_health"    "1"
                  //"linkens_guard_lod"     "1"                                          
            }
            "singlePlayer_passive_2" {
                  "angel_arena_razor_power_OP"  "1"
                  "angel_arena_nether_ritual"   "1"
                  "ebf_clinkz_trickshot_passive"      "1"
                  "lord_of_lightning_holy_wrath_OP"   "1"
                  "octarine_vampirism_lod_OP"   "1"
                  "aether_range_lod_OP"   "1"
                  "ebf_rubick_arcane_echo_OP"   "1"
                  "frost_lord_freezing_OP"      "1"
            }
            "singlePlayer_passive_3" {
                  "zhanhun_op"   "1"
                  "jingtong_op"  "1"
                  "spell_reflect_op" "1"
                  "master_magic_op"   "1"
                  "channel_earthquake_op" "1"
                  "chi_strike_sp"  "1"
                  "metamorphosis_op"   "1"
                  "death_prophet_witchcraft_op"  "1"
                  "invoker_sun_strike_lod_op"   "1"
            }

            "mega_ultimates" {
                  "mega_black_hole"   "1"
                  "armageddon"        "1"
                  "mega_chronosphere"     "1"
                  "mega_eclipse"    "1"
                  "floor_is_lava"   "1"
                  "mega_freezing_field"   "1"
                  "mega_suicide"    "1"
                  "mega_omni_slash" "1"
                  "mega_call_down"  "1"
                  "mega_flare"      "1"
            }

      }
    }
    "heroToSkillMap" {
        "npc_dota_hero_antimage" {
            "Ability1"            "antimage_blink"
            "Ability2"            "antimage_blink_redux"
            "Ability3"            "antimage_mana_break"
            "Ability4"            "antimage_mana_void"
            "Ability5"            "antimage_spell_shield"
            "Ability6"            "antimage_counterspell"
        }

        "npc_dota_hero_queenofpain" {
            "Ability1"            "queenofpain_blink"
            "Ability2"            "queenofpain_blink_redux"
            "Ability3"            "queenofpain_scream_of_pain"
            "Ability4"            "queenofpain_shadow_strike"
            "Ability5"            "queenofpain_sonic_wave"
        }

        "npc_dota_hero_invoker" {
            "Ability1"            "invoker_alacrity_lod"
            "Ability2"            "invoker_chaos_meteor_lod"
            "Ability3"            "invoker_cold_snap_lod"
            "Ability4"            "invoker_emp_lod"
            "Ability5"            "invoker_forge_spirit_lod"
            "Ability6"            "invoker_ghost_walk_lod"
            "Ability7"            "invoker_ice_wall_lod"
            "Ability8"            "invoker_sun_strike_lod"
            "Ability9"            "invoker_tornado_lod"
            "Ability10"           "invoker_deafening_blast_lod"
        }

        "npc_dota_hero_beastmaster" {
            "Ability1"            "beastmaster_call_of_the_wild"
            "Ability2"            "beastmaster_inner_beast"
            "Ability3"            "beastmaster_primal_roar"
            "Ability4"            "beastmaster_wild_axes"
            "Ability5"            "beastmaster_call_of_the_wild_hawk"
        }


        "npc_dota_hero_life_stealer" {
            "Ability1"            "life_stealer_rage"
            "Ability2"            "life_stealer_feast"
            "Ability3"            "life_stealer_feast_melee"
            "Ability4"            "life_stealer_open_wounds"
            "Ability5"            "life_stealer_infest"
            "Ability6"            "life_stealer_assimilate"
        }

        "npc_dota_hero_mirana" {
            "Ability1"            "mirana_starfall_lod"
            "Ability2"            "mirana_arrow"
            "Ability3"            "mirana_leap"
            "Ability4"            "mirana_invis"
        }
        "npc_dota_hero_tiny" {
            "Ability1"            "tiny_avalanche"
            "Ability2"            "tiny_craggy_exterior"
            "Ability3"            "tiny_toss"
            "Ability4"            "tiny_grow"
            "Ability5"            "tiny_grow_lod"
            "Ability6"            "tiny_grow_lod_redux"
        }
        "npc_dota_hero_tusk" {
            "Ability1"        "tusk_ice_shards"
            "Ability2"        "tusk_snowball"
            "Ability3"        "tusk_tag_team"
            "Ability4"        "tusk_walrus_kick"
            "Ability6"        "tusk_walrus_punch"
            "Ability7"        "tusk_frozen_sigil"
        }

        "npc_dota_hero_skeleton_king" {
            "Ability1"            "skeleton_king_hellfire_blast"
            "Ability2"            "skeleton_king_mortal_strike"
            "Ability3"            "skeleton_king_reincarnation"
            "Ability4"            "skeleton_king_vampiric_aura"
            "Ability5"            "skeleton_king_reincarnation_redux"
        }
        "npc_dota_hero_bloodseeker" {
            "Ability1"            "bloodseeker_rupture"
            "Ability2"            "bloodseeker_blood_bath"
            "Ability3"            "bloodseeker_thirst_lod"
            "Ability4"            "bloodseeker_bloodrage"
            "Ability5"            "bloodseeker_blood_bath2"
        }
        "npc_dota_hero_ogre_magi" {
            "Ability1"            "ogre_magi_bloodlust"
            "Ability2"            "ogre_magi_fireblast"
            "Ability3"            "ogre_magi_ignite"
            "Ability4"            "ogre_magi_unrefined_fireblast"
            "Ability5"            "ogre_magi_multicast_lod"
            "Ability6"            "ogre_magi_multicast"
        }
        "npc_dota_hero_death_prophet" {
            "Ability1"            "death_prophet_carrion_swarm"
            "Ability2"            "death_prophet_silence"
            "Ability3"            "death_prophet_spirit_siphon"
            "Ability4"            "death_prophet_witchcraft"
            "Ability5"            "death_prophet_exorcism"
        }
        "npc_dota_hero_zuus" {
            "Ability1"            "zuus_arc_lightning"
            "Ability2"            "zuus_lightning_bolt"
            "Ability3"            "zuus_static_field"
            "Ability4"            "zuus_cloud"
            "Ability5"            "zuus_thundergods_wrath"
        }
        "npc_dota_hero_brewmaster" {
            "Ability1"            "brewmaster_thunder_clap"
            "Ability2"            "brewmaster_drunken_haze"
            "Ability3"            "brewmaster_drunken_brawler"
            "Ability4"            "brewmaster_primal_split"
            "Ability5"            "brewmaster_earth_hurl_boulder"
            "Ability6"            "brewmaster_earth_pulverize_redux"
            "Ability7"            "brewmaster_storm_wind_walk_redux"
            "Ability8"            "brewmaster_storm_dispel_magic"
            "Ability9"            "brewmaster_fire_permanent_immolation"
            "Ability10"           "brewmaster_storm_cyclone"
            "Ability11"           "brewmaster_cinder_brew"
        }
        "npc_dota_hero_crystal_maiden" {
            "Ability1"            "crystal_maiden_crystal_nova"
            "Ability2"            "crystal_maiden_frostbite"
            "Ability3"            "crystal_maiden_brilliance_aura"
            "Ability4"            "crystal_maiden_freezing_field"
        }
        "npc_dota_hero_chen" {
            "Ability1"        "chen_penitence"
            "Ability2"        "chen_divine_favor"
            "Ability3"        "chen_holy_persuasion"
            "Ability4"        "chen_test_of_faith"
            "Ability5"        "chen_hand_of_god"
        }
        "npc_dota_hero_clinkz" {
            "Ability1"        "clinkz_strafe"
            "Ability2"        "clinkz_searing_arrows"
            "Ability3"        "clinkz_wind_walk"
            "Ability4"        "clinkz_death_pact"
            "Ability5"        "clinkz_burning_army"
        }
        "npc_dota_hero_dazzle" {
            "Ability1"        "dazzle_poison_touch"
            "Ability2"        "dazzle_shallow_grave"
            "Ability3"        "dazzle_shadow_wave"
            "Ability4"        "dazzle_weave"
            "Ability5"        "dazzle_bad_juju"
        }
        "npc_dota_hero_rubick" {
            "Ability1"        "rubick_null_field"
            "Ability2"        "rubick_telekinesis"
            "Ability3"        "rubick_arcane_supremacy"
            "Ability4"        "rubick_fade_bolt"
        }
        "npc_dota_hero_axe" {
            "Ability1"            "axe_berserkers_call"
            "Ability2"            "axe_battle_hunger"
            "Ability3"            "axe_counter_helix"
            "Ability4"            "axe_culling_blade"
        }
        "npc_dota_hero_legion_commander" {
            "Ability1"            "legion_commander_overwhelming_odds"
            "Ability2"            "legion_commander_press_the_attack"
            "Ability3"            "legion_commander_moment_of_courage"
            "Ability4"            "legion_commander_duel"
        }
        "npc_dota_hero_sven" {
            "Ability1"            "sven_storm_bolt"
            "Ability2"            "sven_warcry"
            "Ability3"            "sven_great_cleave"
            "Ability4"            "sven_gods_strength"
        }
        "npc_dota_hero_spirit_breaker" {
            "Ability1"  "spirit_breaker_charge_of_darkness"
            "Ability2"  "spirit_breaker_empowering_haste"  
            "Ability3"  "spirit_breaker_greater_bash"      
            "Ability4"  "spirit_breaker_nether_strike"     
            "Ability5"  "spirit_breaker_bulldoze"          
        }
        "npc_dota_hero_juggernaut" {
            "Ability1"            "juggernaut_blade_fury"
            "Ability2"            "juggernaut_blade_dance"
            "Ability3"            "juggernaut_healing_ward"
            "Ability4"            "juggernaut_omni_slash"
            //"Ability5"            "juggernaut_healing_ward_mana"
        }
        "npc_dota_hero_obsidian_destroyer" {
            "Ability1"            "obsidian_destroyer_arcane_orb"
            "Ability2"            "obsidian_destroyer_astral_imprisonment"
            "Ability3"            "obsidian_destroyer_astral_imprisonment_redux"
            "Ability4"            "obsidian_destroyer_essence_aura_lod"
            "Ability5"            "obsidian_destroyer_essence_aura_redux"
            "Ability6"            "obsidian_destroyer_sanity_eclipse"
            "Ability7"            "obsidian_destroyer_equilibrium"
        }
        "npc_dota_hero_pangolier" {
            "Ability1"                          "pangolier_swashbuckle"
            "Ability2"                          "pangolier_shield_crash"
            "Ability3"                          "pangolier_lucky_shot"
            "Ability4"                          "pangolier_heartpiercer"
            "Ability5"                          "pangolier_gyroshell"
      }
        "npc_dota_hero_earthshaker" {
            "Ability1"            "earthshaker_fissure"
            "Ability2"            "earthshaker_enchant_totem"
            "Ability3"            "earthshaker_aftershock"
            "Ability4"            "earthshaker_aftershock_lod"
            "Ability5"            "earthshaker_echo_slam"
        }
        "npc_dota_hero_tinker" {
            "Ability1"            "tinker_laser"
            "Ability2"            "tinker_heat_seeking_missile"
            "Ability3"            "tinker_march_of_the_machines"
            "Ability4"            "tinker_rearm_lod"
            "Ability5"            "tinker_rearm"
        }
        "npc_dota_hero_slark" {
            "Ability1"            "slark_dark_pact"
            "Ability2"            "slark_pounce"
            "Ability3"            "slark_essence_shift"
            "Ability4"            "slark_essence_shift_intellect_lod"
            "Ability5"            "slark_essence_shift_strength_lod"
            "Ability6"            "slark_essence_shift_agility_lod"
            "Ability7"            "slark_shadow_dance"
            "Ability8"            "slark_shadow_dance_redux"

        }
        "npc_dota_hero_pudge" {
            "Ability1"            "pudge_meat_hook"
            "Ability2"            "pudge_rot"
            "Ability3"            "pudge_flesh_heap"
            "Ability4"            "pudge_dismember"
        }
        "npc_dota_hero_silencer" {
            "Ability1"            "silencer_curse_of_the_silent"
            "Ability2"            "silencer_glaives_of_wisdom"
            "Ability3"            "silencer_last_word"
            "Ability4"            "silencer_global_break"
            "Ability5"            "silencer_global_disarm"
            "Ability6"            "silencer_global_silence"
            "Ability7"            "silencer_glaives_of_wisdom_steal"
        }
        "npc_dota_hero_abyssal_underlord" {
            "Ability1"            "abyssal_underlord_atrophy_aura"
            "Ability2"            "abyssal_underlord_dark_rift"
            "Ability3"            "abyssal_underlord_firestorm"
            "Ability4"            "abyssal_underlord_pit_of_malice"
        }
        "npc_dota_hero_riki" {
            "Ability1"            "riki_smoke_screen"
            "Ability2"            "riki_blink_strike"
            "Ability3"            "riki_permanent_invisibility"
            "Ability4"            "riki_tricks_of_the_trade"
            "Ability5"            "riki_backstab_lod"
        }
        "npc_dota_hero_ursa" {
            "Ability1"            "ursa_earthshock"
            "Ability2"            "ursa_overpower"
            "Ability3"            "ursa_overpower_melee"
            "Ability4"            "ursa_fury_swipes"
            "Ability5"            "ursa_fury_swipes_lod"
            "Ability6"            "ursa_enrage"
            "Ability7"            "ursa_enrage_old"
        }
        "npc_dota_hero_omniknight" {
            "Ability1"            "omniknight_degen_aura"
            "Ability3"            "omniknight_purification"
            "Ability5"            "omniknight_repel"
            "Ability6"            "omniknight_guardian_angel"
        }
        "npc_dota_hero_dazzle" {
            "Ability1"            "dazzle_poison_touch"
            "Ability2"            "dazzle_shadow_wave"
            "Ability3"            "dazzle_shallow_grave"
            "Ability4"            "dazzle_weave"
            "Ability5"            "dazzle_bad_juju"
        }
        "npc_dota_hero_doom_bringer" {
            "Ability1"            "doom_bringer_devour_lod"
            "Ability2"            "doom_bringer_scorched_earth"
            "Ability3"            "infernal_blade_lua"
            "Ability4"            "doom_bringer_doom"
        }
      "npc_dota_hero_huskar" {
            "Ability1"            "huskar_berserkers_blood"
            "Ability2"            "huskar_burning_spear"
            "Ability3"            "huskar_inner_vitality"
            "Ability4"            "huskar_life_break"
            "Ability5"            "huskar_life_break_redux"
            "Ability6"            "huskar_berserkers_blood_lod"
            "Ability7"            "huskar_inner_fire"
        }
      "npc_dota_hero_lich" {
            "Ability1"        "lich_frost_nova"
            "Ability2"        "lich_frost_shield"
            "Ability3"        "lich_sinister_gaze"
            //"Ability4"        "lich_dark_ritual"
            "Ability4"        "lich_frost_armor"
            "Ability5"        "lich_chain_frost"
        }
      "npc_dota_hero_lone_druid" {

            "Ability1"        "lone_druid_rabid"
            "Ability2"        "lone_druid_spirit_bear"
            "Ability3"        "lone_druid_true_form"
            "Ability4"        "lone_druid_spirit_link"
            "Ability5"        "lone_druid_true_form_battle_cry"
            "Ability6"        "lone_druid_savage_roar"
        }
        "npc_dota_hero_meepo" {

            "Ability1"        "meepo_geostrike"
            "Ability2"        "meepo_earthbind"
            "Ability3"        "meepo_poof"
            "Ability4"        "meepo_divided_we_stand"
            "Ability5"        "meepo_ransack"
        }
      "npc_dota_hero_drow_ranger" {
            "Ability1"            "drow_ranger_frost_arrows"
            "Ability2"            "drow_ranger_wave_of_silence"
            "Ability3"            "drow_ranger_trueshot"
            "Ability4"            "drow_ranger_marksmanship"
            "Ability5"            "marksmanship_int"
            "Ability6"            "marksmanship_str"
            "Ability7"            "drow_ranger_marksmanship_redux"
            "Ability8"            "drow_splitshot"
        }
       "npc_dota_hero_skywrath_mage"
        {
            "Ability1" "skywrath_mage_arcane_bolt"
            "Ability2"  "skywrath_mage_concussive_shot"
            "Ability3"  "skywrath_mage_ancient_seal"
            "Ability4"  "skywrath_mage_mystic_flare"
            "Ability5" "skywrath_mage_concussive_break"
        }
        "npc_dota_hero_undying"
        {
            "Ability1" "undying_decay"
            "Ability2"  "undying_soul_rip"
            "Ability3"  "undying_tombstone"
            "Ability4"  "undying_flesh_golem"
            "Ability5" "undying_decay_agi"
            "Ability6" "undying_decay_int"
        }
        "npc_dota_hero_monkey_king"
        {
            "Ability1" "monkey_king_boundless_strike"
            "Ability2"  "monkey_king_tree_dance"
            "Ability3"  "monkey_king_primal_spring"
            "Ability4"  "monkey_king_jingu_mastery_lod"
            "Ability5" "monkey_king_jingu_mastery_lod_melee"
            //"Ability6" "monkey_king_mischief"
            "Ability6"  "monkey_king_wukongs_command"
        }
        "npc_dota_hero_necrolyte"
        {
            "Ability1" "necrolyte_death_pulse"
            "Ability2"  "necrolyte_sadist"
            "Ability3"  "necrolyte_sadist_lod"
            "Ability4"  "necrolyte_heartstopper_aura"
            "Ability5" "necrolyte_reapers_scythe"
        }
        "npc_dota_hero_sand_king"
        {
            "Ability1" "sandking_burrowstrike"
            "Ability2"  "sandking_epicenter"
            "Ability3"  "sandking_caustic_finale_redux"
            "Ability4"  "sandking_sand_storm"
        }
        "npc_dota_hero_phantom_lancer"
        {
            "Ability1" "phantom_lancer_doppelwalk"
            "Ability2"  "phantom_lancer_phantom_edge"
            "Ability3"  "phantom_lancer_juxtapose"
            //"Ability4"  "phantom_lancer_juxtapose_melee"
            "Ability4"  "phantom_lancer_spirit_lance"
        }
        "npc_dota_hero_alchemist"
        {
            "Ability1" "alchemist_acid_spray"
            "Ability2"  "alchemist_goblins_greed"
            "Ability3"  "alchemist_unstable_concoction"
            "Ability4"  "alchemist_chemical_rage"
            "Ability5"  "alchemist_chemical_rage_redux"
            "Ability6"  "alchemist_transmuted_scepter"
            "Ability7"  "alchemist_aghnaim_magic_redux"
        }
        "npc_dota_hero_phantom_assassin"
        {
            "Ability1"  "phantom_assassin_stifling_dagger"
            "Ability2"  "phantom_assassin_phantom_strike"
            "Ability3"  "phantom_assassin_blur"
            "Ability4"  "phantom_assassin_coup_de_grace"
            "Ability5"  "phantom_assassin_coup_de_grace_melee"
        }
        "npc_dota_hero_abaddon"
        {
            "Ability1" "abaddon_death_coil"
            "Ability2"  "abaddon_aphotic_shield"
            "Ability3"  "abaddon_frostmourne"
            "Ability4"  "abaddon_borrowed_time"
            "Ability5"  "abaddon_borrowed_time_redux"
        }
        "npc_dota_hero_arc_warden"
        {
            "Ability1"  "arc_warden_flux"
            "Ability2"  "arc_warden_magnetic_field"
            "Ability3"  "arc_warden_spark_wraith"
            "Ability4"  "arc_warden_tempest_double"
            "Ability5"  "arc_warden_tempest_double_redux"
            "Ability6"  "arc_warden_tempest_double_op"
        }
        "npc_dota_hero_faceless_void"
        {
            "Ability1"  "faceless_void_time_walk"
            "Ability2"  "faceless_void_time_dilation"
            "Ability3"  "faceless_void_time_lock"
            "Ability4"  "faceless_void_backtrack"
            "Ability5"  "faceless_void_chronosphere"
        }
        "npc_dota_hero_gyrocopter"
        {
            "Ability1"  "gyrocopter_call_down"
            "Ability2"  "gyrocopter_flak_cannon"
            "Ability4"  "gyrocopter_homing_missile"
            "Ability5"  "gyrocopter_rocket_barrage"
            "Ability6"  "side_gunner_redux"
        }
        "npc_dota_hero_night_stalker"
        {
            "Ability1"  "night_stalker_void"
            "Ability2"  "night_stalker_crippling_fear"
            "Ability3"  "night_stalker_hunter_in_the_night"
            "Ability4"  "night_stalker_darkness"
            "Ability5"  "night_stalker_innate_redux"
        }
        "npc_dota_hero_keeper_of_the_light"
        {
            "Ability1"  "keeper_of_the_light_blinding_light_lod"
            "Ability2"  "keeper_of_the_light_chakra_magic"
            "Ability3"  "keeper_of_the_light_chakra_magic_cooldown"
            "Ability4"  "keeper_of_the_light_illuminate"
            "Ability5"  "keeper_of_the_light_mana_leak"
            "Ability6"  "keeper_of_the_light_recall_lod"
            "Ability7"  "keeper_of_the_light_spirit_form"
            "Ability8"  "keeper_of_the_light_innate_redux"
            "Ability9"  "keeper_of_the_light_will_o_wisp"
        }
        "npc_dota_hero_nyx_assassin"
        {
            "Ability1"  "nyx_assassin_impale"
            "Ability2"  "nyx_assassin_mana_burn"
            "Ability3"  "nyx_assassin_spiked_carapace"
            "Ability4"  "nyx_assassin_vendetta"
            "Ability5"  "nyx_assassin_burrow"
            "Ability6"  "nyx_assassin_burrow_redux"
        }
        "npc_dota_hero_leshrac"
        {
            "Ability1"  "leshrac_split_earth"
            "Ability2"  "leshrac_lightning_storm"
            "Ability3"  "leshrac_diabolic_edict"
            "Ability4"  "leshrac_pulse_nova_redux"
        }   
        "npc_dota_hero_morphling"
        {
            "Ability1"  "morphling_waveform"
            "Ability2"  "morphling_adaptive_strike_agi"
            "Ability3"  "morphling_adaptive_strike_str"
            "Ability4"  "morphling_morph_agi"
            "Ability5"  "morphling_morph_str"
            "Ability6"  "morphling_replicate"
            "Ability7"  "morphling_hybrid"
            "Ability8"  "morph_int_str_redux"
            "Ability9"  "morph_str_int_redux"
            "Ability10"  "morph_agi_int_redux"
            "Ability11"  "morph_int_agi_redux"
        }
        "npc_dota_hero_dark_willow"
        {
            "Ability1"  "dark_willow_bramble_maze"
            "Ability2"  "dark_willow_shadow_realm"
            "Ability3"  "dark_willow_cursed_crown"
            "Ability4"  "dark_willow_bedlam"
            "Ability5"  "dark_willow_terrorize"
        }
    }
}
