"swappingAbilities" {
    "imba_bane_nightmare"           "imba_bane_nightmare_end"
    "imba_jakiro_fire_breath"       "imba_jakiro_ice_breath"
    "imba_kunkka_x_marks_the_spot"  "imba_kunkka_return"
    "snapfire_gobble_up" 			"snapfire_spit_creep"
	"primal_beast_onslaught"		"primal_beast_onslaught_release"
	"crystal_maiden_freezing_field"	"crystal_maiden_freezing_field_stop"
	"dawnbreaker_solar_guardian"	"dawnbreaker_land"
}
