"Abilities" {
    // These are the skill categories
    // The numbers are used for sending skills over the network, as well as encryptions
    "skills" {
        // The main skills, usually always avaiable
        "main" {
           "skywrath_mage_concussive_break"               "1"
            "slark_essence_shift_strength_lod"            "1"
            "slark_essence_shift_intellect_lod"            "1"
            "slark_essence_shift_agility_lod"            "1"
            "ursa_fury_swipes_lod"              "1"
            "ursa_enrage_old"                  "1"
            "pudge_flesh_heap"            "1"
            "pudge_flesh_heap_agility"            "1"
            "pudge_flesh_heap_int"            "1"
            "pudge_flesh_heap_move_speed"     "1"
            "pudge_flesh_heap_spell_amp"       "1"
            "pudge_flesh_heap_attack_range"   "1"
            "pudge_flesh_heap_bonus_vision" "1"
            "silencer_global_break"            "1"
            "silencer_global_disarm"            "1"
            "juggernaut_healing_ward_mana"      "1"
            "ogre_magi_multicast_lod"            "1"
            "death_prophet_witchcraft"            "1"
            "earthshaker_aftershock_lod"            "1"
            "tinker_rearm_lod"            "1"
            "abaddon_aphotic_shield"            "1"
            "abaddon_borrowed_time"            "1"
            "abaddon_death_coil"            "1"
            "abaddon_frostmourne"            "1"
            "abyssal_underlord_atrophy_aura"            "1"
            "abyssal_underlord_dark_rift"            "1"
            "abyssal_underlord_firestorm"            "1"
            "abyssal_underlord_pit_of_malice"            "1"
            "alchemist_acid_spray"            "1"
            "alchemist_chemical_rage"            "1"
            "alchemist_goblins_greed"            "1"
            "alchemist_unstable_concoction"            "1"
            "ancient_apparition_chilling_touch"            "1"
            "ancient_apparition_cold_feet"            "1"
            "ancient_apparition_ice_blast"            "1"
            "ancient_apparition_ice_vortex"            "1"
            "antimage_blink"            "1"
            "antimage_mana_break"            "1"
            "antimage_mana_void"            "1"
            "antimage_spell_shield"            "1"
            "axe_battle_hunger"            "1"
            "axe_berserkers_call"            "1"
            "axe_counter_helix"            "1"
            "axe_culling_blade"            "1"
            "bane_brain_sap"            "1"
            "bane_enfeeble"            "1"
            "bane_fiends_grip"            "1"
            "bane_nightmare"            "1"
            "batrider_firefly"            "1"
            "batrider_flamebreak"            "1"
            "batrider_flaming_lasso"            "1"
            "batrider_sticky_napalm"            "1"
            "beastmaster_call_of_the_wild_boar"            "1"
            "beastmaster_call_of_the_wild"            "1"
            "beastmaster_inner_beast"            "1"
            "beastmaster_primal_roar"            "1"
            "beastmaster_wild_axes"            "1"
            "bloodseeker_blood_bath"            "1"
            "bloodseeker_bloodrage"            "1"
            "bloodseeker_rupture"            "1"
            "bloodseeker_thirst_lod"            "1"
            "bloodseeker_blood_bath2"           "1"
            "bounty_hunter_jinada"            "1"
            "bounty_hunter_shuriken_toss"            "1"
            "bounty_hunter_track"            "1"
            "bounty_hunter_wind_walk"            "1"
            "brewmaster_drunken_brawler"            "1"
            "brewmaster_drunken_haze"            "1"
            "brewmaster_primal_split"            "1"
            "brewmaster_thunder_clap"            "1"
            "bristleback_bristleback"            "1"
            "bristleback_quill_spray"            "1"
            "bristleback_viscous_nasal_goo"            "1"
            "bristleback_warpath"            "1"
            "broodmother_incapacitating_bite"            "1"
            "broodmother_insatiable_hunger"            "1"
            "broodmother_spawn_spiderlings"            "1"
            "broodmother_spin_web"            "1"
            "centaur_double_edge"            "1"
            "centaur_hoof_stomp"            "1"
            "centaur_return"            "1"
            "centaur_stampede"            "1"
            "chaos_knight_chaos_bolt"            "1"
            "chaos_knight_chaos_strike"            "1"
            "chaos_knight_phantasm"            "1"
            "chaos_knight_reality_rift"            "1"
            "chen_hand_of_god"            "1"
            "chen_holy_persuasion"            "1"
            "chen_penitence"            "1"
            "chen_test_of_faith"            "1"
            "chen_test_of_faith_teleport"            "1"
            "clinkz_death_pact"            "1"
            "clinkz_searing_arrows"            "1"
            "clinkz_strafe"            "1"
            "clinkz_wind_walk"            "1"
            "crystal_maiden_brilliance_aura"            "1"
            "crystal_maiden_crystal_nova"            "1"
            "crystal_maiden_freezing_field"            "1"
            "crystal_maiden_frostbite"            "1"
            "dark_seer_ion_shell"            "1"
            "dark_seer_surge"            "1"
            "dark_seer_vacuum"            "1"
            "dark_seer_wall_of_replica"            "1"
            "dazzle_poison_touch"            "1"
            "dazzle_shadow_wave"            "1"
            "dazzle_shallow_grave"            "1"
            "dazzle_weave"            "1"
            "death_prophet_carrion_swarm"            "1"
            "death_prophet_exorcism"            "1"
            "death_prophet_silence"            "1"
            "disruptor_glimpse"            "1"
            "disruptor_kinetic_field"            "1"
            "disruptor_static_storm"            "1"
            "disruptor_thunder_strike"            "1"
            "doom_bringer_doom"            "1"
            "doom_bringer_devour_lod"     "1"
            "doom_bringer_scorched_earth"            "1"
            "dragon_knight_breathe_fire"            "1"
            "dragon_knight_dragon_blood"            "1"
            "dragon_knight_dragon_tail"            "1"
            "dragon_knight_elder_dragon_form"            "1"
            "drow_ranger_frost_arrows"            "1"
            "drow_ranger_marksmanship"            "1"
            "drow_ranger_trueshot"            "1"
            "drow_ranger_wave_of_silence"            "1"
                  "marksmanship_int"                        "1"
                  "marksmanship_str"                        "1"
            "earth_spirit_boulder_smash"            "1"
            "earth_spirit_geomagnetic_grip"            "1"
            "earth_spirit_magnetize"            "1"
            "earth_spirit_rolling_boulder"            "1"
            "earthshaker_echo_slam"            "1"
            "earthshaker_enchant_totem"            "1"
            "earthshaker_fissure"            "1"
            "elder_titan_ancestral_spirit"            "1"
            "elder_titan_earth_splitter"            "1"
            "elder_titan_echo_stomp"            "1"
            "elder_titan_natural_order"            "1"
            //"ember_spirit_activate_fire_remnant"            "1"
            "ember_spirit_fire_remnant"            "1"
            "ember_spirit_flame_guard"            "1"
            "ember_spirit_searing_chains"            "1"
            "ember_spirit_sleight_of_fist"            "1"
            "enchantress_enchant"            "1"
            "enchantress_impetus"            "1"
            "enchantress_natures_attendants"            "1"
            "enchantress_untouchable"            "1"
            "enigma_black_hole"            "1"
            "enigma_demonic_conversion"            "1"
            "enigma_malefice"            "1"
            "enigma_midnight_pulse"            "1"
            "faceless_void_chronosphere"            "1"
            "faceless_void_time_lock"            "1"
            "faceless_void_time_walk"            "1"
            "furion_force_of_nature"            "1"
            "furion_sprout"            "1"
            "furion_teleportation"            "1"
            "furion_wrath_of_nature"            "1"
            "gyrocopter_call_down"            "1"
            "gyrocopter_flak_cannon"            "1"
            "gyrocopter_homing_missile"            "1"
            "gyrocopter_rocket_barrage"            "1"
            "huskar_berserkers_blood"            "1"
            "huskar_burning_spear"            "1"
            "huskar_inner_vitality"            "1"
            "huskar_life_break"            "1"
            "huskar_berserkers_blood_lod"   "1"
            "invoker_alacrity_lod"            "1"
            "invoker_chaos_meteor_lod"            "1"
            "invoker_cold_snap_lod"            "1"
            "invoker_emp_lod"            "1"
            "invoker_forge_spirit_lod"            "1"
            "invoker_ghost_walk_lod"            "1"
            "invoker_ice_wall_lod"            "1"
            "invoker_sun_strike_lod"            "1"
            "invoker_tornado_lod"            "1"
            "jakiro_dual_breath"            "1"
            "jakiro_ice_path"            "1"
            "jakiro_liquid_fire"            "1"
            "jakiro_macropyre"            "1"
            "juggernaut_blade_dance"            "1"
            "juggernaut_blade_fury"            "1"
            "juggernaut_healing_ward"            "1"
            "juggernaut_omni_slash"            "1"
            "keeper_of_the_light_blinding_light_lod"            "1"
            "keeper_of_the_light_chakra_magic"            "1"
            "keeper_of_the_light_chakra_magic_cooldown"     "1"
            "keeper_of_the_light_illuminate"            "1"
            "keeper_of_the_light_mana_leak"            "1"
            "keeper_of_the_light_recall_lod"            "1"
            "keeper_of_the_light_spirit_form"            "1"
            "kunkka_ghostship"            "1"
            "kunkka_tidebringer"            "1"
            "kunkka_torrent"            "1"
            "kunkka_x_marks_the_spot"            "1"
            "legion_commander_duel"            "1"
            "legion_commander_moment_of_courage"            "1"
            "legion_commander_overwhelming_odds"            "1"
            "legion_commander_press_the_attack"            "1"
            "leshrac_diabolic_edict"            "1"
            "leshrac_lightning_storm"            "1"
            "leshrac_pulse_nova"            "1"
            "leshrac_split_earth"            "1"
            "lich_chain_frost"            "1"
            "lich_dark_ritual"            "1"
            "lich_frost_armor"            "1"
            "lich_frost_nova"            "1"
            "life_stealer_feast"            "1"
            "life_stealer_infest"            "1"
          //"life_stealer_control"              "1"
            "life_stealer_open_wounds"            "1"
            "life_stealer_rage"            "1"
            "lina_dragon_slave"            "1"
            "lina_fiery_soul"            "1"
            "lina_laguna_blade"            "1"
            "lina_light_strike_array"            "1"
            "lion_finger_of_death"            "1"
            "lion_impale"            "1"
            "lion_mana_drain"            "1"
            "lion_voodoo"            "1"
            "lone_druid_rabid"            "1"
            "lone_druid_spirit_bear"            "1"
            "lone_druid_true_form"            "1"
            "luna_eclipse"            "1"
            "luna_lucent_beam"            "1"
            "luna_lunar_blessing"            "1"
            "luna_moon_glaive"            "1"
            "lycan_feral_impulse"            "1"
            "lycan_howl"            "1"
            "lycan_shapeshift"            "1"
            "lycan_summon_wolves"            "1"
            "magnataur_empower"            "1"
            "magnataur_reverse_polarity"            "1"
            "magnataur_shockwave"            "1"
            "magnataur_skewer"            "1"
            "medusa_mana_shield"            "1"
            "medusa_mystic_snake"            "1"
            "medusa_split_shot"            "1"
            "medusa_stone_gaze"            "1"
            "meepo_earthbind"            "1"
            "meepo_geostrike"            "1"
            "meepo_poof"            "1"
            "mirana_arrow"            "1"
            "mirana_invis"            "1"
            "mirana_leap"            "1"
            "mirana_starfall_lod"            "1"
            "monkey_king_boundless_strike"  "1"
            "monkey_king_tree_dance"  "1"
            "monkey_king_primal_spring"  "1"
            "monkey_king_jingu_mastery_lod"  "1"
            "monkey_king_mischief"  "1"
            "morphling_adaptive_strike"            "1"
            "morphling_morph_agi"            "1"
            "morphling_morph_str"            "1"
            "morphling_replicate"            "1"
            "morphling_waveform"            "1"
            "naga_siren_ensnare"            "1"
            "naga_siren_mirror_image"            "1"
            "naga_siren_rip_tide"            "1"
            "naga_siren_song_of_the_siren"            "1"
            "necrolyte_death_pulse"            "1"
            "necrolyte_sadist_lod"      "1"
            "necrolyte_heartstopper_aura"            "1"
            "necrolyte_reapers_scythe"            "1"
            "necrolyte_sadist"            "1"
            "nevermore_dark_lord"            "1"
            "nevermore_necromastery"            "1"
            "nevermore_requiem"            "1"
            "nevermore_shadowraze1"            "1"
            "nevermore_shadowraze2"            "1"
            "nevermore_shadowraze3"            "1"
            "night_stalker_crippling_fear"            "1"
            "night_stalker_darkness"            "1"
            "night_stalker_hunter_in_the_night"            "1"
            "night_stalker_void"            "1"
            "nyx_assassin_impale"            "1"
            "nyx_assassin_mana_burn"            "1"
            "nyx_assassin_spiked_carapace"            "1"
            "nyx_assassin_vendetta"            "1"
            "obsidian_destroyer_arcane_orb"            "1"
            "obsidian_destroyer_astral_imprisonment"            "1"
            "obsidian_destroyer_essence_aura_lod"            "1"
            "obsidian_destroyer_essence_aura_redux"            "1"
            "obsidian_destroyer_sanity_eclipse"            "1"
            "ogre_magi_bloodlust"            "1"
            "ogre_magi_fireblast"            "1"
            "ogre_magi_ignite"            "1"
            "omniknight_degen_aura"            "1"
            "omniknight_guardian_angel"            "1"
            "omniknight_purification"            "1"
            "omniknight_repel"            "1"
            "oracle_false_promise"            "1"
            "oracle_fates_edict"            "1"
            "oracle_fortunes_end"            "1"
            "oracle_purifying_flames"            "1"
            "phantom_assassin_blur"            "1"
            "phantom_assassin_coup_de_grace"            "1"
            "phantom_assassin_phantom_strike"            "1"
            "phantom_assassin_stifling_dagger"            "1"
            "phantom_lancer_doppelwalk"            "1"
            "phantom_lancer_juxtapose"            "1"
            "phantom_lancer_juxtapose_melee"            "1"
            "phantom_lancer_phantom_edge"            "1"
            "phantom_lancer_spirit_lance"            "1"
            "phoenix_fire_spirits"            "1"
            "phoenix_icarus_dive"            "1"
            "phoenix_sun_ray"            "1"
            "phoenix_supernova"            "1"
            "puck_dream_coil"            "1"
            //"puck_ethereal_jaunt"            "1"
            "puck_illusory_orb"            "1"
            "puck_phase_shift"            "1"
            "puck_waning_rift"            "1"
            "pudge_dismember"            "1"
            "pudge_meat_hook"            "1"
            "pudge_rot"            "1"
            "pugna_decrepify"            "1"
            "pugna_life_drain"            "1"
            "pugna_nether_blast"            "1"
            "pugna_nether_ward"            "1"
            "queenofpain_blink"            "1"
            "queenofpain_scream_of_pain"            "1"
            "queenofpain_shadow_strike"            "1"
            "queenofpain_sonic_wave"            "1"
            "rattletrap_battery_assault"            "1"
            "rattletrap_hookshot"            "1"
            "rattletrap_power_cogs"            "1"
            "rattletrap_rocket_flare"            "1"
            "razor_eye_of_the_storm"            "1"
            "razor_plasma_field"            "1"
            "razor_static_link"            "1"
            "razor_unstable_current"            "1"
            "riki_blink_strike"            "1"
            "riki_smoke_screen"            "1"
            "riki_backstab_lod"            "1"
            "rubick_fade_bolt"            "1"
            "rubick_null_field"            "1"
            "rubick_telekinesis"            "1"
            "sandking_burrowstrike"            "1"
            "sandking_epicenter"            "1"
            "sandking_sand_storm"            "1"
            "sandking_caustic_finale_redux"      "1"
            "shadow_demon_disruption"            "1"
            "shadow_demon_shadow_poison"            "1"
            //"shadow_demon_shadow_poison_release"            "1"
            "shadow_demon_soul_catcher"            "1"
            "shadow_shaman_ether_shock"            "1"
            "shadow_shaman_mass_serpent_ward"            "1"
            "shadow_shaman_shackles"            "1"
            "shadow_shaman_voodoo"            "1"
            "shredder_chakram"            "1"
            "shredder_reactive_armor"            "1"
            "shredder_timber_chain"            "1"
            "shredder_whirling_death"            "1"
            "silencer_curse_of_the_silent"            "1"
            "silencer_glaives_of_wisdom"            "1"
            "silencer_global_silence"            "1"
            "silencer_last_word"            "1"
            "skeleton_king_hellfire_blast"            "1"
            "skeleton_king_mortal_strike"            "1"
            "skeleton_king_reincarnation"            "1"
            "skeleton_king_vampiric_aura"            "1"
            "skywrath_mage_ancient_seal"            "1"
            "skywrath_mage_arcane_bolt"            "1"
            "skywrath_mage_concussive_shot"            "1"
            "skywrath_mage_mystic_flare"            "1"
            "slardar_amplify_damage"            "1"
            "slardar_bash"            "1"
            "slardar_slithereen_crush"            "1"
            "slardar_sprint"            "1"
            "slark_dark_pact"            "1"
            "slark_pounce"            "1"
            "slark_essence_shift"            "1"
            "slark_shadow_dance"            "1"
            "sniper_assassinate"            "1"
            "sniper_headshot"            "1"
            "sniper_shrapnel"            "1"
            "sniper_take_aim"            "1"
            "spectre_desolate"            "1"
            "spectre_dispersion"            "1"
            "spectre_haunt"            "1"
            //"spectre_reality"            "1"
            "spectre_spectral_dagger"            "1"
            "spirit_breaker_charge_of_darkness"            "1"
            "spirit_breaker_empowering_haste"            "1"
            "spirit_breaker_greater_bash"            "1"
            "spirit_breaker_nether_strike"            "1"
            "storm_spirit_ball_lightning"            "1"
            "storm_spirit_electric_vortex"            "1"
            "storm_spirit_overload"            "1"
            "storm_spirit_static_remnant"            "1"
            "sven_gods_strength"            "1"
            "sven_great_cleave"            "1"
            "sven_storm_bolt"            "1"
            "sven_warcry"            "1"
            //"techies_focused_detonate"            "1"
            "techies_land_mines"            "1"
            "techies_remote_mines"            "1"
            "techies_stasis_trap"            "1"
            "techies_suicide"            "1"
            "templar_assassin_meld"            "1"
            "templar_assassin_psi_blades"            "1"
            "templar_assassin_psionic_trap"            "1"
            "templar_assassin_refraction"            "1"
            //"templar_assassin_trap"            "1"
            "terrorblade_conjure_image"            "1"
            "terrorblade_metamorphosis"            "1"
            "terrorblade_reflection"            "1"
            "terrorblade_sunder"            "1"
            "tidehunter_anchor_smash"            "1"
            "tidehunter_gush"            "1"
            "tidehunter_kraken_shell"            "1"
            "tidehunter_ravage"            "1"
            "tinker_heat_seeking_missile"            "1"
            "tinker_laser"            "1"
            "tinker_march_of_the_machines"            "1"
            "tiny_avalanche"            "1"
            "tiny_craggy_exterior"            "1"
            "tiny_grow_lod"            "1"
            "tiny_toss"            "1"
            "treant_eyes_in_the_forest"            "1"
            "treant_leech_seed"            "1"
            "treant_living_armor"            "1"
            "treant_natures_guise"            "1"
            "treant_overgrowth"            "1"
            "troll_warlord_battle_trance"            "1"
            "troll_warlord_berserkers_rage"            "1"
            "troll_warlord_fervor"            "1"
            "troll_warlord_whirling_axes_ranged"            "1"
            "tusk_frozen_sigil"            "1"
            "tusk_ice_shards"            "1"
            "tusk_snowball"            "1"
            "tusk_walrus_punch"            "1"
            "undying_decay"            "1"
            "undying_decay_agi"            "1"
            "undying_decay_int"            "1"
            "undying_flesh_golem"            "1"
            "undying_soul_rip"            "1"
            "undying_tombstone"            "1"
            "ursa_earthshock"            "1"
            "ursa_enrage"            "1"
            "ursa_fury_swipes"              "1"
            "ursa_overpower"            "1"
            "vengefulspirit_command_aura"            "1"
            "vengefulspirit_magic_missile"            "1"
            "vengefulspirit_nether_swap"            "1"
            "vengefulspirit_wave_of_terror"            "1"
            "venomancer_plague_ward"            "1"
            "venomancer_poison_nova"            "1"
            "venomancer_poison_sting"            "1"
            "venomancer_venomous_gale"            "1"
            "viper_corrosive_skin"            "1"
            "viper_nethertoxin"            "1"
            "viper_poison_attack"            "1"
            "viper_viper_strike"            "1"
            "visage_grave_chill"            "1"
            "visage_gravekeepers_cloak"            "1"
            "visage_summon_familiars"            "1"
            "warlock_fatal_bonds"            "1"
            "warlock_rain_of_chaos"            "1"
            "warlock_shadow_word"            "1"
            "warlock_upheaval"            "1"
            "weaver_geminate_attack"            "1"
            "weaver_shukuchi"            "1"
            "weaver_the_swarm"            "1"
            "weaver_time_lapse"            "1"
            "windrunner_focusfire"            "1"
            "windrunner_powershot"            "1"
            "windrunner_shackleshot"            "1"
            "windrunner_windrun"            "1"
            "wisp_overcharge"            "1"
            "wisp_relocate"            "1"
            "wisp_spirits"            "1"
            "wisp_tether"            "1"
            "witch_doctor_death_ward"            "1"
            "witch_doctor_maledict"            "1"
            "witch_doctor_paralyzing_cask"            "1"
            "witch_doctor_voodoo_restoration"            "1"
            "zuus_arc_lightning"            "1"
            "zuus_lightning_bolt"            "1"
            "zuus_static_field"            "1"
            "zuus_thundergods_wrath"            "1"
            "zuus_cloud"                     "1"
            //"life_stealer_consume"            "1"
            "shadow_demon_demonic_purge"            "1"
            "shredder_chakram_2"            "1"
            "earth_spirit_petrify"            "1"
            "earth_spirit_stone_caller"            "1"
            "winter_wyvern_arctic_burn"            "1"
            "winter_wyvern_splinter_blast"            "1"
            "winter_wyvern_cold_embrace"            "1"
            "winter_wyvern_winters_curse"            "1"
            "life_stealer_assimilate"            "1"
            "morphling_hybrid"            "1"
            "nyx_assassin_burrow"            "1"
            "tusk_walrus_kick"            "1"
            "arc_warden_flux"            "1"
            "arc_warden_magnetic_field"            "1"
            "arc_warden_spark_wraith"            "1"
            "arc_warden_tempest_double"            "1"
            "death_prophet_spirit_siphon"            "1"
            "doom_bringer_infernal_blade"            "1"
            "faceless_void_time_dilation"            "1"
            "lone_druid_savage_roar"            "1"
            "riki_tricks_of_the_trade"            "1"
            "lone_druid_true_form_battle_cry"            "1"
            // Brewmaster
            "brewmaster_earth_hurl_boulder"            "1"
            //"brewmaster_earth_pulverize"            "1"
            "brewmaster_earth_pulverize_redux"        "1"
            //"brewmaster_storm_wind_walk"            "1"
            "brewmaster_storm_wind_walk_redux"            "1"
            "brewmaster_storm_dispel_magic"            "1"
            "brewmaster_fire_permanent_immolation"            "1"
            "brewmaster_storm_cyclone"            "1"
            // Ogre magi ulty
            "ogre_magi_unrefined_fireblast"            "1"
            // Meepo Ulty
            "meepo_divided_we_stand"            "1"
            // Rearm
            "tinker_rearm"            "1"
            // Riki
            "riki_permanent_invisibility"            "1"
            // Multicast
            "ogre_magi_multicast"            "1"
            // Aftershock
            "earthshaker_aftershock"            "1"
        }
        // The neutrals skills
        "neutral" {
            "alpha_wolf_group" {
                "alpha_wolf_command_aura"                "1"
                "alpha_wolf_critical_strike"                "1"
            }
            "beastmaster_boar_group" {
                "beastmaster_boar_poison"                "1"
                "beastmaster_greater_boar_poison"                "1"
            }
            "big_thunder_lizard_group" {
                "big_thunder_lizard_frenzy"                "1"
                "big_thunder_lizard_slam"                "1"
                "big_thunder_lizard_wardrums_aura"                  "1"
            }
            "black_dragon_group" {
                "black_dragon_splash_attack"                "1"
                // "black_dragon_fireball"                "1"
            "black_dragon_fireball_lod"                "1"
                // "neutral_spell_immunity"                "1"
                //"black_dragon_dragonhide_aura"                      "1"
            }
            "blue_dragonspawn_group" {
                "blue_dragonspawn_overseer_devotion_aura"                "1"
                "blue_dragonspawn_overseer_evasion"                "1"
                "blue_dragonspawn_sorcerer_evasion"                "1"
            }
            "centaur_khan_group" {
                "centaur_khan_endurance_aura"                "1"
                "centaur_khan_war_stomp"                "1"
            }
            "dark_troll_warlord_group" {
                "dark_troll_warlord_ensnare"                "1"
                "dark_troll_warlord_raise_dead"                "1"
            }
            "enraged_wildkin_group" {
                "enraged_wildkin_tornado"                "1"
                "enraged_wildkin_toughness_aura"                "1"
            }
            "lone_druid_spirit_bear_group" {
                "lone_druid_spirit_bear_demolish"                "1"
                "lone_druid_spirit_bear_entangle"                "1"
                //"lone_druid_spirit_bear_return"                "1"
                "lone_druid_spirit_bear_return_lod"                "1"
            }
            "satyr_group" {
                "satyr_hellcaller_shockwave"                "1"
                "satyr_hellcaller_unholy_aura"                "1"
                "satyr_soulstealer_mana_burn"                "1"
                "satyr_trickster_purge"                "1"
            }
            "necronomicon_group" {
                "necronomicon_archer_aoe_lod"                "1"
                "necronomicon_archer_mana_burn_lod"                "1"
                "necronomicon_warrior_last_will_lod"                "1"
                "necronomicon_warrior_mana_burn_lod"                "1"
            }
            "roshan_group" {
                "roshan_slam"                "1"
                "roshan_spell_block"                "1"
                //"roshan_spell_block_lod"                "1"
                "roshan_bash"                "1"
            }
            "prowler_group" {
                "spawnlord_aura"                "1"
                "spawnlord_master_stomp"                "1"
                "spawnlord_master_freeze"                "1"
            }
            "warlock_group" {
                "warlock_golem_flaming_fists"                "1"
                "warlock_golem_permanent_immolation"                "1"
                "warlock_golem_permanent_immolation_lod"        "1"
            }
            "misc_neutral_1_group" {
                "forest_troll_high_priest_heal"                "1"
                "forest_troll_high_priest_mana_aura"  "1"
                "giant_wolf_critical_strike"                "1"
                "gnoll_assassin_envenomed_weapon"                "1"
            }
            "misc_neutral_2_group" {
                "granite_golem_hp_aura"                "1"
                "harpy_storm_chain_lightning"                "1"
                "kobold_taskmaster_speed_aura"                "1"
                "lycan_summon_wolves_critical_strike"                "1"
            }
            "misc_neutral_3_group" {
                "ogre_magi_frost_armor"                "1"
                "mud_golem_hurl_boulder"                "1"
                "mudgolem_cloak_aura"  "1"
                "polar_furbolg_ursa_warrior_thunder_clap"                "1"
                // doesnt work "mud_golem_rock_destroy"  "1"
            }
            "misc_neutral_4_group" {
                // Removed because its buggy "backdoor_protection"                "1"
                "ghost_frost_attack"                "1"
                "broodmother_poison_sting"                "1"
                "visage_summon_familiars_stone_form"                "1"
                "undying_tombstone_zombie_deathstrike"                "1"
            }
        }
        // The custom skills in LoD
        "custom" {
            "spell_lab" {
                  "spell_lab_symbiotic" "1"
            }
            "oneshotonekill" {
                  "jingtong"  "1"
                  "shiguanghuisu"      "1"
                  "benneng"   "1"
                  "sight"   "1"
                  "zhanhun"   "1"
            }
            "risen" {
                  "arcane_mastery"   "1"
            }
            "holdout" {
                "zuus_thundergods_vengeance"                "1"
                "holdout_omnislash"                "1"
                "holdout_gods_strength"                "1"
                "holdout_gladiators_unite"                "1"
                "holdout_culling_blade"                "1"
                "holdout_arcane_aura"                "1"
                "holdout_gladiators_unite"                "1"
                //"holdout_scourge_ward"                              "1"
                "armoured_centipede"                              "1"
                //"holdout_multishot"                                 "1"

            }
            "item_abilities" {
                "aether_range_lod"                "1"
                "octarine_vampirism_lod"                "1"
                "force_dash_lod"                "1"
                "shards_of_truesight_lod"                "1"
            }
           //  "random_abilities" {
           //     "true_random_lod_1"    "1"
           //     "true_random_lod_2"    "1"
           //     "true_random_lod_3"    "1"
           //     "true_random_lod_4"    "1"
           //     "true_random_lod_5"    "1"
           //     "true_random_lod_6"    "1"
           // }
            "cherub_abilities" {
                "cherub_sleep_cloud"      "1"
                "cherub_synthesis"      "1"
                "cherub_explosive_spore"      "1"
                "cherub_flower_garden"      "1"
            }
            "flower_abilities" {
                "garden_white_flower_base"      "1"
                "garden_red_flower_base"      "1"
                "garden_pink_blossom_base"      "1"
                "garden_blue_blossom_base"      "1"
                "garden_yellow_daisy_base"      "1"
                "garden_purple_lotus_base"      "1"
            }
            "zulf_abilities" {
                "zulf_cyclone_trap"      "1"
                "zulf_jet_stream"      "1"
                "zulf_gale_force"      "1"
                "zulf_typhoon"      "1"
            }
            "angel_arena_reborn" {
                "angel_arena_lightning"   "1"
                "angel_arena_magic_fire"      "1"
                "angel_arena_razor_power"     "1"
                "angel_arena_revenge"   "1"
                "angel_arena_shot"      "1"
                "angel_arena_storm"     "1"
                "angel_arena_summon_hawk"     "1"
                "angel_arena_berserk"   "1"
                "angel_arena_cripple"   "1"
            }
            "angel_arena_reborn_ult" {
                  "angel_arena_darkrage"  "1"
                  "angel_arena_night_vampire"   "1"
                  "angel_arena_roots"     "1"
                  "angel_arena_song"      "1"
                  "angel_arena_hola_heal" "1"
                  "angel_arena_transmute" "1"
                  "angel_arena_demonic"   "1"
                  "angel_arena_grace"     "1"
            }
            "life_in_arena" {
                  "ancient_priestess_surge_of_intelligence" "1"
                  "ancient_priestess_spirit_link"     "1"
                  "archmage_magic_barrier"      "1"
                  "berserker_fire_spear"  "1"
                  "dark_ranger_black_arrow"     "1"
                  "firelord_flame_strike" "1"
                  "firelord_fire_trap"    "1"
                  "frost_lord_cold" "1"
                  "frost_lord_frost_breath"     "1"
                  "ghoul_devour"    "1"
                  "akron_explosion" "1"
                  //"paladin_blizzard"      "1"
                  "dark_knight_dark_forces"     "1"
                  "lord_of_lightning_lightning_shield"      "1"
                  "android_cluster_rockets"     "1"
                  "serpent_queen_ball_lightning"      "1"
            }
            "life_in_arena_passive" {
                  "butcher_zombie"  "1"
                  "frost_lord_freezing"   "1"
                  "lord_of_lightning_holy_wrath"      "1"
                  "kret_poisoning"  "1"
                  "kret_lust_for_life"    "1"
            }
            "life_in_arena_ferocity" {
                  "brewmaster_ferocity"   "1"
                  "brewmaster_ferocity_agi"     "1"
                  "brewmaster_ferocity_int"     "1"
                  "brewmaster_ferocity_all"     "1"
            }
            "life_in_arena_ult" {
                  "android_pocket_factory"      "1"
                  "ancient_priestess_ritual_protection" "1"
                  "berserker_madness"     "1"
                  "frost_lord_ice"  "1"
                  "lord_of_lightning_brain_storm"     "1"
                  "paladin_impregnability"      "1"
                  "angel_arena_archmage_anomaly"      "1"
            }
            "life_in_arena_illusion" {
                  "illusionist_mastery_of_deception"  "1"
                  "illusionist_whiff_of_deception"    "1"
                  "illusionist_agility_paws"    "1"
                  "illusionist_mastery_of_illusions"  "1"
            }
            "retro_dota" {
            //      "invoker_retro_betrayal"      "1"
                  "invoker_retro_portal"      "1"
                  "invoker_retro_scout"      "1"
                  "invoker_retro_invisibility_aura"      "1"
                  "invoker_retro_confuse"      "1"
                  "invoker_retro_disarm"      "1"
                  "invoker_retro_deafening_blast"      "1"
            }
            "imba_towers_weak" {
                "vassal_shield"   "1"
                "titan_command_aura"    "1"
                "bahamut_reckoning_aura"  "1"
                "imba_tower_aegis"   "1"
                "imba_tower_atrophy"   "1"
                "imba_tower_force"   "1"
                "imba_tower_forest"   "1"
                "imba_tower_mana_burn"   "1"
                "imba_tower_mana_flare"   "1"
                "imba_tower_mindblast"   "1"
                "imba_tower_permabash"   "1"
                "imba_tower_plague"   "1"
                "imba_tower_self_repair"   "1"
                "imba_tower_spacecow"   "1"
                "imba_tower_thorns"   "1"
            }
            "imba_towers_medium" {
                  "imba_tower_berserk"   "1"
                  "imba_tower_spell_shield"   "1"
                  "imba_tower_hex_aura"   "1"
                  "imba_tower_vicious"   "1"
                  "imba_tower_nature"   "1"
                  "imba_tower_chrono"   "1"
                  "summoner_tesla_coil"   "1"
                  "lich_cold_aura"    "1"
                  "imba_tower_laser"   "1"
                  "imba_tower_disease"   "1"
            }
            "imba_towers_strong" {
                  "imba_tower_multihit"   "1"
                  "imba_tower_sniper"   "1"
                  "imba_tower_grievous_wounds"   "1"
                  "imba_tower_essence_drain"   "1"
                  "imba_tower_machinegun"   "1"
                  "imba_tower_salvo"   "1"
                  "imba_tower_fervor"   "1"
                  "imba_tower_split"   "1"
            }
            "imba" {
                  "imba_dazzle_shallow_grave_passive" "1"
                  "imba_omniknight_degen_aura"  "1"
                  "imba_omniknight_purification"      "1"
            }
            "ebf" {
                  "ebf_rubick_arcane_echo" "1"
                  "ebf_mana_fiend_essence_amp"  "1"
                  "ebf_clinkz_trickshot"      "1"
                  "ebf_underlord_expulsion"      "1"
                  "ebf_troll_warlord_multistrike"      "1"
            }
            "dusk" {
                  "gemini_abyssal_vortex" "1"
                  "gemini_unstable_rift"  "1"
                  "gemini_voidal_flare" "1"
            }
            "duskMisc1" {
                  "self_explosion" "1"
                  "ancient_defensive_wave"      "1"
                  "ancient_last_resort"   "1"
                  "paragon_tranquility_seal"    "1"
            }
            "duskMisc2" {
                  "crimson_blood_sorcery" "1"
                  "alchemist_alchemise"   "1"
                  "alchemist_motherloads" "1"
            }
            "hawkeye" {
                  "hawkeye_detonator_dart" "1"
                  "hawkeye_double_tap"  "1"
                  "hawkeye_hit_n_run" "1"
                  "hawkeye_ricochet" "1"
            }

          "singlePlayer" {
                  "disruptor_kinetic_field_OP"  "1"
                  "disruptor_glimpse_OP"  "1"
                  "garden_red_flower_base_OP"   "1"
                  "lone_druid_spirit_bear_return_lod_OP"    "1"
                  "global_stun"     "1"
                  "force_dash_lod_OP"     "1"
                  "zulf_typhoon_OP" "1"
                  "angel_arena_rifle_OP" "1"
                  "android_cluster_rockets_OP" "1"
                  "serpent_queen_ball_lightning_op"   "1"
                  "zuus_lightning_bolt_global"            "1"
            }
             "singlePlayer_passive" {
                  "imba_juggernaut_healing_ward_passive_redux"      "1"
                  "obsidian_destroyer_essence_aura_lod_health"    "1"
                  "shards_of_truesight_lod_OP"  "1"
                  "frost_lord_freezing_OP"      "1"
                  "ebf_rubick_arcane_echo_OP"   "1"
                  "octarine_vampirism_lod_OP"   "1"
                  "aether_range_lod_OP"   "1"
                  //"linkens_guard_lod"     "1"
                  "lord_of_lightning_holy_wrath_OP"   "1"
                  "angel_arena_razor_power_OP"  "1"
                  "angel_arena_nether_ritual"   "1"
                  "ebf_clinkz_trickshot_passive"      "1"
            }
            "DoD" {
                  "makemeleecreeps_lua"   "1"
                  "makerangedcreeps_lua"   "1"
                  "makecatapults_lua"   "1"
            }
        }
        // The IMBA skills in LoD
        "dotaimba" {
            "imba_necrolyte" {
                  "imba_necrolyte_death_pulse"    "1"
                  //"imba_necrolyte_death_pulse_aux"  "1"
                  "imba_necrolyte_heartstopper_aura"      "1"
                  "imba_necrolyte_sadist"      "1"
                  "imba_necrolyte_reapers_scythe"      "1"
            }
            "imba_PA" {
                  "imba_phantom_assassin_stifling_dagger"    "1"
                  "imba_phantom_assassin_phantom_strike"  "1"
                  "imba_phantom_assassin_blur"      "1"
                  "imba_phantom_assassin_coup_de_grace"      "1"
            }
            "imba_kunkka" {
                  "imba_kunkka_torrent"    "1"
                  "imba_kunkka_tidebringer"  "1"
                  "imba_kunkka_x_marks_the_spot"      "1"
                  "imba_kunkka_ghostship"      "1"
            }
            "imba_jugg" {
                  "imba_juggernaut_blade_fury"    "1"
                  "imba_juggernaut_healing_ward"  "1"
                  //"imba_juggernaut_healing_ward_upgrade"      "1"
                  //"imba_juggernaut_healing_totem_passive"      "1"
                  "imba_juggernaut_blade_dance"      "1"
                  "imba_juggernaut_omni_slash"      "1"
            }
            "imba_lion" {
                  "imba_lion_earth_spike"    "1"
                  "imba_lion_hex"  "1"
                  "imba_lion_mana_drain"      "1"
                  "imba_lion_finger_of_death"      "1"
            }
            "imba_warlock" {
                  "imba_warlock_shadow_word"    "1"
                  "imba_warlock_upheaval"  "1"
                  "imba_warlock_rain_of_chaos"      "1"
                  "imba_warlock_flaming_fists"      "1"
                  "imba_warlock_permanent_immolation"      "1"
            }
            "imba_lich" {
                  "imba_lich_frost_nova"    "1"
                  "imba_lich_frost_armor"  "1"
                  "imba_lich_dark_ritual"      "1"
                  "imba_lich_chain_frost"      "1"
            }
            "imba_sven" {
                  "imba_sven_storm_bolt"    "1"
                  "imba_sven_great_cleave"  "1"
                  "imba_sven_warcry"      "1"
                  "imba_sven_gods_strength"      "1"
            }
            "imba_alchemist" {
                  "alchemist_acid_spray_imba"      "1"
                  // "alchemist_unstable_concoction_imba"      "1"
                  "alchemist_goblins_greed_imba"      "1"
                  "alchemist_chemical_rage_imba"      "1"
            }
            "imba_AA" {
                  "ancient_apparition_cold_feet_imba"      "1"
                  "ancient_apparition_ice_vortex_imba"      "1"
                  "ancient_apparition_chilling_touch_imba"      "1"
            }
            "imba_arc_warden" {
                  "arc_warden_flux_imba"      "1"
                  "arc_warden_magnetic_field_imba"      "1"
                  "arc_warden_spark_wraith_imba"      "1"
                  "arc_warden_tempest_double_imba"      "1"
            }
            "imba_batrider" {
                  //BUGGED// "batrider_sticky_napalm_imba"      "1"
                  "batrider_flamebreak_imba"      "1"
                  "batrider_firefly_imba"      "1"
                  "batrider_flaming_lasso_imba"      "1"
            }
            //"imba_lina" {
            //      "imba_lina_dragon_slave"    "1"
            //      "imba_lina_dragon_slave_aux"  "1"
            //      "imba_lina_dragon_slave_aux_fiery"      "1"
            //      "imba_lina_light_strike_array"      "1"
            //      "imba_lina_light_strike_array_fiery"      "1"
            //      "imba_lina_fiery_soul"      "1"
            //      "imba_lina_blazing_soul"      "1"
            //      "imba_lina_laguna_blade"      "1"
            //      "imba_lina_laguna_blade_fiery"      "1"
            //   }
            //"imba_magnus" {
            //      "imba_magnus_shockwave"    "1"
            //      "imba_magnus_empower"  "1"
            //      "imba_magnus_magnetize"      "1"
            //      "imba_magnus_reverse_polarity"      "1"
            //   }
            //"imba_mirana" {
            //      "imba_mirana_starfall"    "1"
            //      "imba_mirana_arrow"  "1"
            //      "imba_mirana_leap"      "1"
            //      "imba_mirana_cosmic_dust"      "1"
            //   }
            //"imba_nevermore" {
            //      "imba_nevermore_shadowraze1"    "1"
            //      "imba_nevermore_shadowraze2"  "1"
            //      "imba_nevermore_shadowraze3"      "1"
            //      "imba_nevermore_necromastery"      "1"
            //      "imba_nevermore_dark_lord"      "1"
            //      "imba_nevermore_requiem"      "1"
            //      "imba_nevermore_requiem_aux"      "1"
            //   }
            //"imba_nyx" {
            //      "imba_night_stalker_void"    "1"
            //      "imba_night_stalker_crippling_fear"  "1"
            //      "imba_night_stalker_hunter_in_the_night"      "1"
            //      "imba_night_stalker_darkness"      "1"
            //   }
            //"imba_omniknight" {
            //      "imba_omniknight_purification"    "1"
            //      "imba_omniknight_repel"  "1"
            //      "imba_omniknight_degen_aura"      "1"
            //      "imba_omniknight_guardian_angel"      "1"
            //   }
            //"imba_obsidian_destroyer" {
            //      "imba_obsidian_destroyer_arcane_orb"    "1"
            //      "imba_obsidian_destroyer_astral_imprisonment"  "1"
            //      "imba_obsidian_destroyer_essence_aura"      "1"
            //      "imba_obsidian_destroyer_sanity_eclipse"      "1"
            //   }
            //"imba_nightstalker" {
            //      "imba_nyx_assassin_impale"    "1"
            //      "imba_nyx_assassin_spiked_carapace"  "1"
            //      "imba_nyx_assassin_vendetta"      "1"
            //      "imba_night_stalker_darkness"      "1"
            //   }
            //
            "imba_pudge" {
                  "imba_pudge_meat_hook"    "1"
                  "imba_pudge_rot"  "1"
                  "imba_pudge_flesh_heap"      "1"
                  "imba_pudge_sharp_hook"      "1"
                  "imba_pudge_light_hook"      "1"
                  "imba_pudge_dismember"      "1"
               }
            "imba_pugna" {
                  "imba_pugna_nether_blast"    "1"
                  "imba_pugna_decrepify"  "1"
                  //"imba_pugna_nether_ward"      "1" // Needs to be added to the units file
                  "imba_pugna_nether_ward_aura"      "1" // Would be really strong, but why not?
                  //"imba_pugna_life_drain_end"      "1" // Shouldnt be there
                  //"imba_pugna_life_drain"      "1" //Because drain end exists we shouldnt add this

               }
            //"imba_silencer" { // Tooltips broken, easy fix?
            //      "imba_silencer_arcane_curse"    "1"
            //      "imba_silencer_glaives_of_wisdom"  "1"
            //      "imba_silencer_last_word"      "1"
            //      "imba_silencer_global_silence"      "1"
            //   }
            //"imba_sniper" {  // Adding nothing might look better than 1 skill
            //      "imba_sniper_headshot"    "1"
            //      "imba_sniper_take_aim_near"  "1" //The 3 take aims wont work
            //      "imba_sniper_take_aim_normal"      "1"
           //       "imba_sniper_take_aim_far"      "1"
            //      "imba_sniper_assassinate"      "1" // No shrapnel?
            //   }
            //"imba_techies" { //Too mucch weirdness
            //      "imba_techies_land_mines"    "1"
            //      "imba_techies_land_mine_passive"  "1"
            //      "imba_techies_stasis_trap"      "1"
            //      "imba_techies_stasis_trap_passive"      "1"
            //      "imba_techies_remote_auto_creep"      "1"
            //      "imba_techies_remote_auto_hero"      "1"
            //      "imba_techies_minefield_sign"      "1"
            //      "imba_techies_minefield_teleport"      "1"
            //   }
            "imba_sandking" {
                  "imba_sandking_burrowstrike"    "1"
                  "imba_sandking_sand_storm"  "1"
                  "imba_sandking_caustic_finale"      "1"
                  //"imba_sandking_treacherous_sands"      "1"
                  "imba_sandking_epicenter"      "1"
               }
            "imba_skywrath" {
                  "imba_skywrath_mage_arcane_bolt"    "1"
                  "imba_skywrath_mage_concussive_shot"  "1"
                  //"imba_skywrath_mage_concussive_shot_ghastly"      "1"
                  "imba_skywrath_mage_ancient_seal"      "1"
                  "imba_skywrath_mage_mystic_flare"      "1"
               }
             "imba_troll_warlord" {
                  "imba_troll_warlord_whirling_axes_melee"    "1"
                  "imba_troll_warlord_whirling_axes_ranged"  "1"
                  "imba_troll_warlord_fervor"      "1"
                  //"imba_troll_warlord_berserkers_rage"      "1" Doesnt work
                  "imba_troll_warlord_battle_trance"      "1"
               }
            "imba_wraith_king" {
                  "imba_wraith_king_wraithfire_blast"    "1"
                  "imba_wraith_king_vampiric_aura"  "1"
                  "imba_wraith_king_mortal_strike"      "1"
                  //"imba_wraith_king_reincarnation"      "1" Does not work
               }
            "imba_tinker" {
                  "imba_tinker_laser"    "1"
                  "imba_tinker_heat_seeking_missile"  "1"
                  "imba_tinker_march_of_the_machines"      "1"
                  "imba_tinker_rearm"      "1"
               }
            //"imba_vengeful" {
            //      "imba_vengeful_magic_missile"    "1"
            //      "imba_vengeful_wave_of_terror"  "1"
            //      "imba_vengeful_command_aura"      "1"
            //      "imba_vengeful_rancor"      "1"
            //      "imba_vengeful_nether_swap"      "1"
            //      "imba_vengeful_swap_back"      "1"
            //       }
            "imba_venomancer" {
                  "imba_venomancer_venomous_gale"    "1"
                  "imba_venomancer_poison_sting"  "1"
                  "imba_venomancer_plague_ward"      "1"
                  //"imba_venomancer_poison_sting_ward"      "1" Passive ward skills
                  //"imba_venomancer_scourge_ward_multiattack"      "1"
                  //"imba_venomancer_toxicity"      "1" Is an innate, dont think we should use this
                  "imba_venomancer_poison_nova"      "1"
               }
            "imba_rubick" {
                  "imba_rubick_telekinesis"    "1"
                  "imba_rubick_telekinesis_land"  "1"
               }
            "imba_qop" {
                  "imba_queenofpain_shadow_strike"    "1"
                  "imba_queenofpain_blink"  "1"
                  "imba_queenofpain_scream_of_pain"      "1"
                  "imba_queenofpain_delightful_torment"      "1"
                  "imba_queenofpain_sonic_wave"      "1"
              }
            "imba_jakiro" {
                  //"imba_jakiro_fire_breath"    "1"Swapping is them is bugged
                  //"imba_jakiro_ice_breath"  "1" Swapping is them is bugged
                  "imba_jakiro_liquid_fire"      "1"
                  "imba_jakiro_macropyre"      "1"
               }
            "imba_faceless" {
                  "imba_faceless_void_time_walk"    "1"
                  "imba_faceless_void_time_dilation"  "1"
                  "imba_faceless_void_time_lock"      "1"
                  "imba_faceless_void_timelord"      "1"
                  "imba_faceless_void_chronosphere"      "1"
            }
            "imba_enigma" {
                  "imba_enigma_malefice"    "1"
                  //"imba_enigma_demonic_conversion"  "1" eidolon doesnt have a projectile
                  "imba_enigma_midnight_pulse"      "1"
                  "imba_enigma_gravity"      "1"
                  "imba_enigma_black_hole"      "1"
            }
            "imba_drow" {
                  "imba_drow_ranger_frost_arrows"    "1"
                  "imba_drow_ranger_gust"  "1"
                  "imba_drow_ranger_trueshot"      "1"
                  "imba_drow_ranger_marksmanship"      "1"
            }
            "imba_dazzle" {
                  "imba_dazzle_poison_touch"    "1"
                  "imba_dazzle_shallow_grave"  "1"
                  "imba_dazzle_shadow_wave"      "1"
                  "imba_dazzle_weave"      "1"
            }
            "imba_CM" {
                  "imba_crystal_maiden_crystal_nova"    "1"
                  "imba_crystal_maiden_frostbite"  "1"
                  "imba_crystal_maiden_brilliance_aura"      "1"
                  "imba_crystal_maiden_freezing_field"   "1"
            }
            "imba_clinkz" {
                  "imba_clinkz_strafe"    "1"
                  "imba_clinkz_searing_arrows"  "1"
                  "imba_clinkz_skeleton_walk"      "1"
                  //"imba_clinkz_death_pact"   "1" Doesn't steal stats now, should be fixable
            }
            "imba_centaur" {
                  "imba_centaur_hoof_stomp"    "1"
                  "imba_centaur_double_edge"  "1"
                  "imba_centaur_return"      "1"
                  "imba_centaur_stampede"   "1"
            }
            "imba_bounty" {
                  "imba_bounty_hunter_shuriken_toss"    "1"
                  "imba_bounty_hunter_wind_walk"  "1"
                  "imba_bounty_hunter_track"      "1"
                  "imba_bounty_hunter_shadow_jaunt"   "1"
            }
            "imba_bane" {
                  "imba_bane_enfeeble"    "1"
                  //"imba_bane_nightmare"  "1"  // Doesn't replace nicely
                  //"imba_bane_nightmare_end"   "1"
                  "imba_bane_brain_sap"   "1"
                  "imba_bane_fiends_grip"   "1"
            }
            "imba_abaddon" {
                  "imba_abaddon_death_coil"    "1"
                  "imba_abaddon_frostmourne"  "1"
                  "imba_abaddon_borrowed_time"      "1"
                  "imba_abaddon_aphotic_shield"   "1"
            }
            "imba_antimage" {
                  "imba_antimage_mana_break"    "1"
                  "imba_antimage_spell_shield"  "1"
                  "imba_antimage_magehunter"      "1"
                  "imba_antimage_mana_void"   "1"
            }
            "imba_axe" {
                  "imba_axe_berserkers_call"    "1"
                  "imba_axe_battle_hunger"  "1"
                  "imba_axe_counter_helix"      "1"
                  "imba_axe_culling_blade"   "1"
            }
            "imba_beastmaster" {
                  "beastmaster_wild_axes_imba"    "1"
                  "beastmaster_call_of_the_wild_imba"  "1"
                  "beastmaster_call_of_the_wild_boar_imba"      "1"
                  "beastmaster_inner_beast_imba"   "1"
                  "beastmaster_primal_roar_imba"   "1"
            }
            "imba_bloodseeker" {
                  "bloodseeker_bloodrage_imba"    "1"
                  "bloodseeker_blood_bath_imba"  "1"
                  "bloodseeker_thirst_imba"      "1"
                  "bloodseeker_rupture_imba"   "1"
            }
            "imba_bristleback" {
                  "bristleback_viscous_nasal_goo_imba"    "1"
                  "bristleback_quill_spray_imba"  "1"
                  "bristleback_bristleback_imba"      "1"
                  "bristleback_warpath_imba"   "1"
            }
            "imba_broodmother" {
                  "broodmother_spawn_spiderlings_imba"    "1"
                  "broodmother_spin_web_imba"  "1"
                  "broodmother_incapacitating_bite_imba"      "1"
                  "broodmother_insatiable_hunger_imba"   "1"
            }
            "imba_chaos_knight" {
                  "chaos_knight_chaos_bolt_imba"    "1"
                  "chaos_knight_reality_rift_imba"  "1"
                  "chaos_knight_chaos_strike_imba"      "1"
                  "chaos_knight_phantasm_imba"   "1"
            }
            "imba_chen" {
                  "chen_penitence_imba"    "1"
                  "chen_test_of_faith_imba"  "1"
                  "chen_test_of_faith_teleport_imba"      "1"
                  "chen_holy_persuasion_imba"   "1"
                  "chen_hand_of_god_imba"   "1"
            }
            "imba_clockwerk" {
                  "rattletrap_battery_assault_imba"    "1"
                  "rattletrap_power_cogs_imba"  "1"
                  "rattletrap_rocket_flare_imba"      "1"
                  "rattletrap_hookshot_imba"   "1"
            }
            "imba_dark_seer" {
                  "dark_seer_vacuum_imba"    "1"
                  "dark_seer_ion_shell_imba"  "1"
                  "dark_seer_surge_imba"      "1"
                  "dark_seer_wall_of_replica_imba"   "1"
            }
            "imba_death_prophet" {
                  "death_prophet_carrion_swarm_imba"    "1"
                  "death_prophet_silence_imba"  "1"
                  "death_prophet_spirit_siphon_imba"      "1"
                  "death_prophet_exorcism_imba"   "1"
            }
            "imba_disruptor" {
                  "disruptor_thunder_strike_imba"    "1"
                  "disruptor_glimpse_imba"  "1"
                  "disruptor_kinetic_field_imba"      "1"
                  "disruptor_static_storm_imba"   "1"
            }
            "imba_doom" {
                  "doom_bringer_devour_imba"    "1"
                  "doom_bringer_scorched_earth_imba"  "1"
                  "doom_bringer_infernal_blade_imba"      "1"
                  "doom_bringer_doom_imba"   "1"
            }
            "imba_dragon_knight" {
                  "dragon_knight_breathe_fire_imba"    "1"
                  "dragon_knight_dragon_tail_imba"  "1"
                  "dragon_knight_dragon_blood_imba"      "1"
                  "dragon_knight_elder_dragon_form_imba"   "1"
            }
            "imba_earthshaker" {
                  "earthshaker_fissure_imba"    "1"
                  "earthshaker_enchant_totem_imba"  "1"
                  "earthshaker_aftershock_imba"      "1"
                  "earthshaker_echo_slam_imba"   "1"
            }
            "imba_earthspirit" {
                  "earth_spirit_boulder_smash_imba"    "1"
                  "earth_spirit_rolling_boulder_imba"  "1"
                  "earth_spirit_geomagnetic_grip_imba"      "1"
                  "earth_spirit_stone_caller_imba"   "1"
                  "earth_spirit_petrify_imba"      "1"
                  "earth_spirit_magnetize_imba"   "1"
            }
            "imba_eldertitan" {
                  // Two buggy abilities dont work, probably dont have right sub abilities
                  //"elder_titan_echo_stomp_imba"    "1"
                  //"elder_titan_ancestral_spirit_imba"  "1"
                  "elder_titan_natural_order_imba"      "1"
                  "elder_titan_earth_splitter_imba"   "1"
            }
            "imba_emberspirit" {
                  "ember_spirit_searing_chains_imba"  "1"
                  "ember_spirit_sleight_of_fist_imba"      "1"
                  "ember_spirit_flame_guard_imba"   "1"
            }
            "imba_enchantress" {
                  "enchantress_untouchable_imba"    "1"
                  "enchantress_enchant_imba"  "1"
                  "enchantress_natures_attendants_imba"      "1"
                  "enchantress_impetus_imba"   "1"
            }
            "imba_huskar" {
                  "huskar_inner_vitality_imba"    "1"
                  "huskar_burning_spear_imba"  "1"
                  "huskar_berserkers_blood_imba"      "1"
                  "huskar_life_break_imba"   "1"
            }
            "imba_kotl" {
                  "keeper_of_the_light_illuminate_imba"    "1"
                  "keeper_of_the_light_mana_leak_imba"  "1"
                  "keeper_of_the_light_chakra_magic_imba"      "1"
                  "keeper_of_the_light_recall_imba"   "1"
                  "keeper_of_the_light_blinding_light_imba"   "1"
            }
            "imba_legion" {
                  "legion_commander_overwhelming_odds_imba"    "1"
                  "legion_commander_press_the_attack_imba"  "1"
                  // Moment of courage doesnt proc
                  //"legion_commander_moment_of_courage_imba"      "1"
                  "legion_commander_duel_imba"   "1"
            }
            "imba_leshrac" {
                  "leshrac_split_earth_imba"    "1"
                  "leshrac_diabolic_edict_imba"  "1"
                  "leshrac_lightning_storm_imba"      "1"
                  "leshrac_pulse_nova_imba"   "1"
            }
            "imba_lifestealer" {
                  "life_stealer_rage_imba"    "1"
                  "life_stealer_feast_imba"  "1"
                  "life_stealer_open_wounds_imba"      "1"
            }
            "imba_luna" {
                  "luna_lucent_beam_imba"    "1"
                  "luna_moon_glaive_imba"  "1"
                  "luna_lunar_blessing_imba"      "1"
            }
            "imba_medusa" {
                  "medusa_split_shot_imba"    "1"
                  "medusa_mystic_snake_imba"  "1"
                  "medusa_mana_shield_imba"      "1"
                  "medusa_stone_gaze_imba"   "1"
            }
            "imba_naga" {
                  "naga_siren_mirror_image_imba"    "1"
                  "naga_siren_ensnare_imba"  "1"
                  "naga_siren_rip_tide_imba"      "1"
                  "naga_siren_song_of_the_siren_imba"   "1"
            }
            "imba_furion" {
                  "furion_sprout_imba"    "1"
                  "furion_teleportation_imba"  "1"
                  "furion_force_of_nature_imba"      "1"
                  "furion_wrath_of_nature_imba"   "1"
            }
            "imba_oracle" {
                  "oracle_fortunes_end_imba"    "1"
                  "oracle_fates_edict_imba"  "1"
                  "oracle_purifying_flames_imba"      "1"
                  "oracle_false_promise_imba"   "1"
            }
            "imba_phantom_lancer" {
                  "phantom_lancer_spirit_lance_imba"    "1"
                  "phantom_lancer_doppelwalk_imba"  "1"
                  "phantom_lancer_juxtapose_imba"      "1"
                  "phantom_lancer_phantom_edge_imba"   "1"
            }
      }
    }
    "heroToSkillMap" {
        "npc_dota_hero_invoker" {
            "Ability1"            "invoker_alacrity_lod"
            "Ability2"            "invoker_chaos_meteor_lod"
            "Ability3"            "invoker_cold_snap_lod"
            "Ability4"            "invoker_emp_lod"
            "Ability5"            "invoker_forge_spirit_lod"
            "Ability6"            "invoker_ghost_walk_lod"
            "Ability7"            "invoker_ice_wall_lod"
            "Ability8"            "invoker_sun_strike_lod"
            "Ability9"            "invoker_tornado_lod"
        }
        "npc_dota_hero_mirana" {
            "Ability1"            "mirana_starfall_lod"
            "Ability2"            "mirana_arrow"
            "Ability3"            "mirana_leap"
            "Ability4"            "mirana_invis"
        }
        "npc_dota_hero_tiny" {
            "Ability1"            "tiny_avalanche"
            "Ability2"            "tiny_craggy_exterior"
            "Ability3"            "tiny_toss"
            "Ability4"            "tiny_grow_lod"
        }
        "npc_dota_hero_bloodseeker" {
            "Ability1"            "bloodseeker_rupture"
            "Ability2"            "bloodseeker_blood_bath"
            "Ability3"            "bloodseeker_thirst_lod"
            "Ability4"            "bloodseeker_bloodrage"
            "Ability5"            "bloodseeker_blood_bath2"
        }
        "npc_dota_hero_ogre_magi" {
            "Ability1"            "ogre_magi_bloodlust"
            "Ability2"            "ogre_magi_fireblast"
            "Ability3"            "ogre_magi_ignite"
            "Ability4"            "ogre_magi_unrefined_fireblast"
            "Ability5"            "ogre_magi_multicast_lod"
            "Ability6"            "ogre_magi_multicast"
        }
        "npc_dota_hero_keeper_of_the_light" {
            "Ability1"            "keeper_of_the_light_illuminate"
            "Ability2"            "keeper_of_the_light_mana_leak"
            "Ability3"            "keeper_of_the_light_chakra_magic"
            "Ability4"            "keeper_of_the_light_chakra_magic_cooldown"
            "Ability5"            "keeper_of_the_light_recall_lod"
            "Ability6"            "keeper_of_the_light_blinding_light_lod"
            "Ability7"            "keeper_of_the_light_spirit_form"
        }
        "npc_dota_hero_death_prophet" {
            "Ability1"            "death_prophet_carrion_swarm"
            "Ability2"            "death_prophet_silence"
            "Ability3"            "death_prophet_spirit_siphon"
            "Ability4"            "death_prophet_witchcraft"
            "Ability5"            "death_prophet_exorcism"
        }
        "npc_dota_hero_zuus" {
            "Ability1"            "zuus_arc_lightning"
            "Ability2"            "zuus_lightning_bolt"
            "Ability3"            "zuus_static_field"
            "Ability4"            "zuus_cloud"
            "Ability5"            "zuus_thundergods_wrath"
        }
        "npc_dota_hero_brewmaster" {
            "Ability1"            "brewmaster_thunder_clap"
            "Ability2"            "brewmaster_drunken_haze"
            "Ability3"            "brewmaster_drunken_brawler"
            "Ability4"            "brewmaster_primal_split"
            "Ability5"            "brewmaster_earth_hurl_boulder"
            "Ability6"            "brewmaster_earth_pulverize_redux"
            "Ability7"            "brewmaster_storm_wind_walk_redux"
            "Ability8"            "brewmaster_storm_dispel_magic"
            "Ability9"            "brewmaster_fire_permanent_immolation"
            "Ability10"           "brewmaster_storm_cyclone"
        }
        "npc_dota_hero_crystal_maiden" {
            "Ability1"            "crystal_maiden_crystal_nova"
            "Ability2"            "crystal_maiden_frostbite"
            "Ability3"            "crystal_maiden_brilliance_aura"
            "Ability4"            "crystal_maiden_freezing_field"
        }
        "npc_dota_hero_axe" {
            "Ability1"            "axe_berserkers_call"
            "Ability2"            "axe_battle_hunger"
            "Ability3"            "axe_counter_helix"
            "Ability4"            "axe_culling_blade"
        }
        "npc_dota_hero_legion_commander" {
            "Ability1"            "legion_commander_overwhelming_odds"
            "Ability2"            "legion_commander_press_the_attack"
            "Ability3"            "legion_commander_moment_of_courage"
            "Ability4"            "legion_commander_duel"
        }
        "npc_dota_hero_sven" {
            "Ability1"            "sven_storm_bolt"
            "Ability2"            "sven_warcry"
            "Ability3"            "sven_great_cleave"
            "Ability4"            "sven_gods_strength"
        }
        "npc_dota_hero_juggernaut" {
            "Ability1"            "juggernaut_blade_fury"
            "Ability2"            "juggernaut_blade_dance"
            "Ability3"            "juggernaut_healing_ward"
            "Ability4"            "juggernaut_omni_slash"
            "Ability5"            "juggernaut_healing_ward_mana"
        }
        "npc_dota_hero_obsidian_destroyer" {
            "Ability1"            "obsidian_destroyer_arcane_orb"
            "Ability2"            "obsidian_destroyer_astral_imprisonment"
            "Ability3"            "obsidian_destroyer_essence_aura_lod"
            "Ability4"            "obsidian_destroyer_essence_aura_redux"
            "Ability5"            "obsidian_destroyer_sanity_eclipse"
        }
        "npc_dota_hero_earthshaker" {
            "Ability1"            "earthshaker_fissure"
            "Ability2"            "earthshaker_enchant_totem"
            "Ability3"            "earthshaker_aftershock"
            "Ability4"            "earthshaker_aftershock_lod"
            "Ability5"            "earthshaker_echo_slam"
        }
        "npc_dota_hero_tinker" {
            "Ability1"            "tinker_laser"
            "Ability2"            "tinker_heat_seeking_missile"
            "Ability3"            "tinker_march_of_the_machines"
            "Ability4"            "tinker_rearm_lod"
            "Ability5"            "tinker_rearm"
        }
        "npc_dota_hero_slark" {
            "Ability1"            "slark_dark_pact"
            "Ability2"            "slark_pounce"
            "Ability3"            "slark_essence_shift"
            "Ability4"            "slark_essence_shift_intellect_lod"
            "Ability5"            "slark_essence_shift_strength_lod"
            "Ability6"            "slark_essence_shift_agility_lod"
            "Ability7"            "slark_shadow_dance"

        }
        "npc_dota_hero_pudge" {
            "Ability1"            "pudge_meat_hook"
            "Ability2"            "pudge_rot"
            "Ability3"            "pudge_flesh_heap"
            "Ability4"            "pudge_flesh_heap_int"
            "Ability5"            "pudge_flesh_heap_agility"
            "Ability6"            "pudge_dismember"
            "Ability7"            "pudge_flesh_heap_move_speed"
            "Ability8"            "pudge_flesh_heap_spell_amp"
            "Ability9"            "pudge_flesh_heap_attack_range"
          "Ability10"            "pudge_flesh_heap_bonus_vision"
        }
        "npc_dota_hero_silencer" {
            "Ability1"            "silencer_curse_of_the_silent"
            "Ability2"            "silencer_glaives_of_wisdom"
            "Ability3"            "silencer_last_word"
            "Ability4"            "silencer_global_break"
            "Ability5"            "silencer_global_disarm"
            "Ability6"            "silencer_global_silence"
        }
        "npc_dota_hero_abyssal_underlord" {
            "Ability1"            "abyssal_underlord_atrophy_aura"
            "Ability2"            "abyssal_underlord_dark_rift"
            "Ability3"            "abyssal_underlord_firestorm"
            "Ability4"            "abyssal_underlord_pit_of_malice"
        }
        "npc_dota_hero_riki" {
            "Ability1"            "riki_smoke_screen"
            "Ability2"            "riki_blink_strike"
            "Ability3"            "riki_permanent_invisibility"
            "Ability4"            "riki_tricks_of_the_trade"
            "Ability5"            "riki_backstab_lod"
        }
        "npc_dota_hero_ursa" {
            "Ability1"            "ursa_earthshock"
            "Ability2"            "ursa_overpower"
            "Ability3"            "ursa_fury_swipes"
            "Ability4"            "ursa_fury_swipes_lod"
            "Ability5"            "ursa_enrage"
            "Ability6"            "ursa_enrage_old"
        }
        "npc_dota_hero_omniknight" {
            "Ability1"            "omniknight_degen_aura"
            "Ability3"            "omniknight_purification"
            "Ability5"            "omniknight_repel"
            "Ability6"            "omniknight_guardian_angel"
        }
        "npc_dota_hero_dazzle" {
            "Ability1"            "dazzle_poison_touch"
            "Ability2"            "dazzle_shadow_wave"
            "Ability3"            "dazzle_shallow_grave"
            "Ability4"            "dazzle_weave"
        }
        "npc_dota_hero_doom_bringer" {
            "Ability1"            "doom_bringer_devour_lod"
            "Ability2"            "doom_bringer_scorched_earth"
            "Ability3"            "doom_bringer_infernal_blade"
            "Ability4"            "doom_bringer_doom"
        }
            "npc_dota_hero_huskar" {
            "Ability1"            "huskar_berserkers_blood"
            "Ability2"            "huskar_burning_spear"
            "Ability3"            "huskar_inner_vitality"
            "Ability4"            "huskar_life_break"
                  "Ability5"            "huskar_berserkers_blood_lod"
        }
            "npc_dota_hero_drow_ranger" {
            "Ability1"            "drow_ranger_frost_arrows"
            "Ability2"            "drow_ranger_wave_of_silence"
            "Ability3"            "drow_ranger_trueshot"
            "Ability4"            "drow_ranger_marksmanship"
                  "Ability5"            "marksmanship_int"
                  "Ability6"            "marksmanship_str"
        }
       "npc_dota_hero_skywrath_mage"
        {
            "Ability1" "skywrath_mage_arcane_bolt"
            "Ability2"  "skywrath_mage_concussive_shot"
            "Ability3"  "skywrath_mage_ancient_seal"
            "Ability4"  "skywrath_mage_mystic_flare"
            "Ability5" "skywrath_mage_concussive_break"
        }
        "npc_dota_hero_undying"
        {
            "Ability1" "undying_decay"
            "Ability2"  "undying_soul_rip"
            "Ability3"  "undying_tombstone"
            "Ability4"  "undying_flesh_golem"
            //"Ability5" "undying_decay_agi"
            //"Ability6" "undying_decay_int"
        }
        "npc_dota_hero_monkey_king"
        {
            "Ability1" "monkey_king_boundless_strike"
            "Ability2"  "monkey_king_tree_dance"
            "Ability3"  "monkey_king_primal_spring"
            "Ability4"  "monkey_king_jingu_mastery_lod"
            "Ability5" "monkey_king_mischief"
        }
        "npc_dota_hero_necrolyte"
        {
            "Ability1" "necrolyte_death_pulse"
            "Ability2"  "necrolyte_sadist"
            "Ability3"  "necrolyte_sadist_lod"
            "Ability4"  "necrolyte_heartstopper_aura"
            "Ability5" "necrolyte_reapers_scythe"
        }
        "npc_dota_hero_sand_king"
        {
            "Ability1" "sandking_burrowstrike"
            "Ability2"  "sandking_epicenter"
            "Ability3"  "sandking_caustic_finale_redux"
            "Ability4"  "sandking_sand_storm"
        }
        "npc_dota_hero_phantom_lancer"
        {
            "Ability1" "phantom_lancer_doppelwalk"
            "Ability2"  "phantom_lancer_phantom_edge"
            "Ability3"  "phantom_lancer_juxtapose"
            "Ability4"  "phantom_lancer_juxtapose_melee" 
            "Ability5"  "phantom_lancer_spirit_lance"
        }
    }
}
