"Bans" {
    // The first key is a spell, the 2nd is all the spells that cant be used with it
    "BannedCombinations" {
        // Sticky Napalm, crazy damage
        "batrider_sticky_napalm" {
            "axe_battle_hunger"                     "1"
            //"batrider_flamebreak"                   "1"
            "brewmaster_fire_permanent_immolation"  "1"
            "dark_seer_ion_shell"                   "1"
            "doom_bringer_scorched_earth"           "1"
            "ember_spirit_flame_guard"              "1"
            "gyrocopter_rocket_barrage"             "1"
            "huskar_burning_spear"                  "1"
            "juggernaut_blade_fury"                 "1"
            "kunkka_torrent"                        "1" //Kunkka Torrent does 10 ticks of damage in short succession
            "leshrac_diabolic_edict"                "1" //40 Explosions
            "leshrac_pulse_nova"                    "1" //Especially overpowered in x5 multiplier and up
            "pudge_rot"                             "1"
            "shadow_shaman_shackles"                "1"
            "skywrath_mage_mystic_flare"            "1"
            "slark_dark_pact"                       "1"
            "venomancer_poison_sting"               "1"
            "viper_poison_attack"                   "1"
            "warlock_golem_permanent_immolation"    "1"
            "bloodseeker_rupture"                   "1"
            "death_prophet_spirit_siphon"           "1"
            "pugna_life_drain"                      "1"
        }

        // Multishot abuse
        "holdout_multishot" {
            "ember_spirit_sleight_of_fist"  "1"
            "holdout_omnislash"             "1"
            "medusa_split_shot"             "1"
            "life_stealer_feast"            "1" // Cray Cray HP steal!
        }

        // Split shot abuse
        //"medusa_split_shot" {
        //    "phantom_lancer_juxtapose"      "1" // Infinite illusions
        //}

        // Mega punches, can get of more than 1 walrus punch
        "tusk_walrus_punch" {
            "ursa_overpower"      "1"
        }
        
        // Crashy Combo
        "lone_druid_true_form" {
            "troll_warlord_berserkers_rage" "1"
        }

        // Dont need both essence auras
        "obsidian_destroyer_essence_aura_lod" {
            "obsidian_destroyer_essence_aura_redux" "1"
        }
		
		// Roshan Bash works on illusions for some reason, it shouldn't
        "roshan_bash" {
			"naga_siren_mirror_image"       "1"
			"shadow_demon_disruption"       "1"
			"morphling_hybrid"              "1"
			"phantom_lancer_doppelwalk"     "1"
			"phantom_lancer_spirit_lance"   "1"
			"terrorblade_reflection"        "1"
			"terrorblade_conjure_image"     "1"
			"illusionist_whiff_of_deception"	"1"
			"illusionist_agility_paws"	"1"
        }
		
		// Too easy fountain kill
        "invoker_retro_betrayal" {
            "chen_test_of_faith_teleport" "1"
        }
		
		// 100% damage reduction
        "abyssal_underlord_atrophy_aura" {
            "imba_tower_atrophy" "1"
        }

        // Infernal blade abuse
        "doom_bringer_infernal_blade" {
            "hawkeye_ricochet" "1"
        }
		
		//Suicide wont kill on Nohtl protection
		"imba_dazzle_shallow_grave_passive" {
            "techies_suicide" "1"
        }
        
        // Global Walrus Kick 
		"tusk_walrus_kick" {
			"lone_druid_true_form"          "1"
            "troll_warlord_berserkers_rage" "1"
        }

        // Teleport Abuse
        "furion_teleportation" {
            "abaddon_borrowed_time"             "1"
            "spectre_dispersion"                "1"
        }

        // Rearm Abuse
        "tinker_rearm" {
            "abaddon_borrowed_time"             "1"
            "ancient_apparition_ice_blast"      "1"
            "arc_warden_tempest_double"         "1"
            "dark_seer_wall_of_replica"         "1"
            "faceless_void_chronosphere"        "1"
            "furion_wrath_of_nature"            "1"
            "gyrocopter_call_down"              "1"
            "invoker_sun_strike_lod"            "1"
            "magnataur_reverse_polarity"        "1"
            "necrolyte_reapers_scythe"          "1"
            "omniknight_guardian_angel"         "1" //Can spam global Omni ulti (with aghs), from fountain
            "phoenix_supernova"                 "1"
            "razor_eye_of_the_storm"            "1"
            "silencer_global_silence"           "1"
            "shadow_shaman_mass_serpent_ward"   "1"
            "skeleton_king_reincarnation"       "1"
            "slark_shadow_dance"                "1" //Become untouchable throughout the game with obsidian_destroyer_essence_aura
            "spectre_haunt"                     "1"
            "tidehunter_ravage"                 "1"
            "treant_overgrowth"                 "1"
            "warlock_rain_of_chaos"             "1"
            "zuus_thundergods_vengeance"        "1"
            "zuus_thundergods_wrath"            "1"
        }

        // Arc warden's ult is basically like rearm
        "arc_warden_tempest_double" {
            "abaddon_borrowed_time"             "1"
            "ancient_apparition_ice_blast"      "1"
            "dark_seer_wall_of_replica"         "1"
            "faceless_void_chronosphere"        "1"
            "furion_wrath_of_nature"            "1"
            "gyrocopter_call_down"              "1"
            "invoker_sun_strike_lod"            "1"
            "magnataur_reverse_polarity"        "1"
            "necrolyte_reapers_scythe"          "1"
            "omniknight_guardian_angel"         "1" //Can spam global Omni ulti (with aghs), from fountain
            "phoenix_supernova"                 "1"
            "razor_eye_of_the_storm"            "1"
            "silencer_global_silence"           "1"
            "shadow_shaman_mass_serpent_ward"   "1"
            "skeleton_king_reincarnation"       "1"
            "slark_shadow_dance"                "1" //Become untouchable throughout the game with obsidian_destroyer_essence_aura
            "spectre_haunt"                     "1"
            "tidehunter_ravage"                 "1"
            "tinker_rearm"                      "1"
            "treant_overgrowth"                 "1"
            "warlock_rain_of_chaos"             "1"
            "zuus_thundergods_vengeance"        "1"
            "zuus_thundergods_wrath"            "1"

            "techies_land_mines"                "1"
            "techies_focused_detonate"          "1"
            "techies_remote_mines"              "1"
            "techies_stasis_trap"               "1"
            "meepo_divided_we_stand"            "1"
            "visage_summon_familiars"           "1"
            "techies_suicide"                   "1"
        }

        // Meepo abuse
        "meepo_divided_we_stand" {
            "abaddon_borrowed_time"         "1" // Glitchy
            "alchemist_chemical_rage"       "1"
            "alchemist_chemical_rage_lod"   "1"
            "ancient_apparition_ice_blast"  "1"
            "faceless_void_chronosphere"    "1" // Total of 25 seconds Chrono
            "furion_wrath_of_nature"        "1"
            "gyrocopter_call_down"          "1"
            "invoker_sun_strike_lod"        "1"
            "lone_druid_spirit_bear"        "1" // This one is kind of crashy
            "meepo_divided_we_stand"        "1" // This stops divided we stand being picked twice
            "ogre_magi_multicast_lod"       "1"
            "zuus_thundergods_vengeance"    "1"
            "zuus_thundergods_wrath"        "1"
        }

        // Unlimited rearm
        "phoenix_supernova" {
            "phoenix_supernova" "1"
            "abaddon_borrowed_time" "1"
        }

        // This spell now works on all abilities!
        "death_prophet_witchcraft" {
            "bristleback_warpath"               "1"
            "bristleback_quill_spray"           "1" // It's time this juggernaut was banned
            "earthshaker_aftershock"            "1"
            "lina_fiery_soul"                   "1"
            "storm_spirit_overload"             "1"
            "zuus_static_field"                 "1"
            "obsidian_destroyer_essence_aura"   "1"
            "puck_phase_shift"                  "1"
            "ember_spirit_sleight_of_fist"      "1"
            "brewmaster_earth_hurl_boulder"     "1"
        }

        // Individual bans for old spamable spells
        "zuus_arc_lightning" {
            "earthshaker_aftershock"            "1"
        }
        "storm_spirit_ball_lightning" {
            "bristleback_warpath"               "1"
            "earthshaker_aftershock"            "1"
            "lina_fiery_soul"                   "1"
            "zuus_static_field"                 "1"
        }
        "storm_spirit_static_remnant" {
            "earthshaker_aftershock"            "1"
            "zuus_static_field"                 "1"
        }
        "earthshaker_enchant_totem" {
            "zuus_static_field"                 "1"
            "ursa_overpower"                    "1" // Can get off 3 or so enchant hits
        }
         "ursa_overpower" {
            "bounty_hunter_jinada"              "1" // Can get off plenty of 100% crits successively with ranged hero
            "brewmaster_drunken_brawler"        "1" // Also OP on ranged hero, many 100% crits after another
        }
        "obsidian_destroyer_arcane_orb" {
            "bristleback_warpath"               "1"
            "lina_fiery_soul"                   "1"
            "storm_spirit_overload"             "1"
            "earthshaker_aftershock"            "1"
        }

        "nyx_assassin_burrow" {
            // Crazy damage reduction
            "bristleback_bristleback"           "1"
            "spectre_dispersion"                "1"

            // Movement while burrowed
            "furion_teleportation"              "1"
            "queenofpain_blink"                 "1"
            "riki_blink_strike"                 "1"
            "antimage_blink"                    "1"
            "storm_spirit_ball_lightning"       "1"
        }
    }

    // List of spells that use banned Categories
    "CategoryBans" {
        "bristleback_warpath"               "ToggleSpells"
        "earthshaker_aftershock"            "SpammableSpells"
        "lina_fiery_soul"                   "ToggleSpells"
        "storm_spirit_overload"             "ToggleSpells"
        "zuus_static_field"                 "SpammableSpells"
        "obsidian_destroyer_essence_aura"   "ToggleSpells"
    }

    // List of categories to use with the categories bans
    "Categories" {
        // List of spells that can be spammed easily
        // 1 to reference a spell
        // 2 to reference another list (note: Do NOT create recursion, there is no recursion checking!)
        "SpammableSpells" {
            // Ban ToggleSpells
            "ToggleSpells"                      "2"

            // Ban skillz
            "abaddon_aphotic_shield"            "1"
            "abaddon_death_coil"                "1"
            "alchemist_unstable_concoction"     "1"
            "ancient_apparition_ice_vortex"     "1"
            "antimage_blink"                    "1"
            "arc_warden_spark_wraith"           "1"
            "axe_battle_hunger"                 "1"
            "bane_nightmare"                    "1"
            "batrider_sticky_napalm"            "1"
            "bloodseeker_blood_rage"            "1"
            "bounty_hunter_track"               "1"
            "bristleback_quill_spray"           "1"
            "bristleback_viscous_nasal_goo"     "1"
            "chaos_knight_reality_rift"         "1"
            "courier_burst"                     "1"
            "dazzle_shadow_wave"                "1"
            "doom_bringer_devour"               "1"
            "earthshaker_enchant_totem"         "1"
            "elder_titan_ancestral_spirit"      "1"
            "gyrocopter_rocket_barrage"         "1"
            "leshrac_lightning_storm"           "1"
            "lich_ice_armor"                    "1"
            "lion_mana_drain"                   "1"
            "luna_lucent_beam"                  "1"
            "necrolyte_death_pulse"             "1"
            "phantom_assassin_phantom_strike"   "1"
            "puck_phase_shift"                  "1"
            "pugna_nether_blast"                "1"
            "queen_of_pain_blink"               "1"
            "rubick_telekinesis"                "1"
            "shadow_demon_shadow_poison"        "1"
            "shredder_timber_chain"             "1"
            "skywrath_mage_arcane_bolt"         "1"
            "slark_dark_pact"                   "1"
            "templar_assassin_meld"             "1"
            "tidehunter_anchor_smash"           "1"
            "tinker_rearm"                      "1"
            "treant_natures_guise"              "1"
            "undying_decay"                     "1"
            "venomancer_plague_ward"            "1"
            "weaver_shukuchi"                   "1"

            "oracle_purifying_flames"			"1"

            // Items
            "lod_item_ring_of_basilius"         "1"
            "lod_item_necronomicon"             "1"
            "lod_item_necronomicon_2"           "1"
            "lod_item_necronomicon_3"           "1"
            "lod_item_mjollnir"                 "1"
            "lod_item_diffusal_blade"           "1"
            "lod_item_diffusal_blade_2"         "1"
        }

        // Toggle spells
        "ToggleSpells" {
            "courier_go_to_secretshop"          "1"
            "courier_return_stash_items"        "1"
            "courier_return_to_base"            "1"
            "courier_take_stash_items"          "1"
            "courier_transfer_items"            "1"
            "forest_troll_high_priest_heal"     "1"
            "furion_teleportation"              "1"
            "harpy_storm_chain_lightning"       "1"
            "holdout_multishot"                 "1"
            "lod_item_power_treads"             "1" // Amazing when toggling aftershock!
            "leshrac_pulse_nova"                "1"
            "medusa_mana_shield"                "1"
            "medusa_split_shot"                 "1"
            "meepo_poof"                        "1"
            "morphling_morph_agi"               "1"
            "morphling_morph_str"               "1"
            "pudge_rot"                         "1"
            "riki_blink_strike"                 "1"
            "shredder_chakram"                  "1"
            "techies_focused_detonate"          "1"
            "troll_warlord_berserkers_rage"     "1"
            "wisp_overcharge"                   "1"
            "witch_doctor_voodoo_restoration"   "1"
            "life_stealer_consume"              "1"
            "life_stealer_assimilate"           "1"
            "life_stealer_infest"               "1" // You get consume, which can be spammmmed
            "nyx_assassin_burrow"               "1" // Why you do this, valve?
            "spectre_reality"                   "1" // Can be used over and over
            "skeleton_king_vampiric_aura"       "1" // New update allows it to be toggled
            "life_stealer_assimilate"           "1"
            "elder_titan_return_spirit"         "1"
            "cherub_synthesis"			"1"
        }
    }

    // These are groups of spells where none of these can be used together
    "BannedGroups" {
        // The one hit combo group
        "1" {
            "bounty_hunter_jinada"              "1"
            "brewmaster_drunken_brawler"        "1"
            "earthshaker_enchant_totem"         "1"
            "kunkka_tidebringer"                "1"
            "tiny_grow"                         "1"
            "tusk_walrus_punch"                 "1"
            "weaver_geminate_attack"            "1"
            "terrorblade_metamorphosis"         "1"
            "clinkz_death_pact"                 "1"
            "tiny_grow_lod"                     "1"
        }

        // The mega range group
        "2" {
            "dragon_knight_elder_dragon_form"   "1"
            "sniper_take_aim"                   "1"
            "templar_assassin_psi_blades"       "1"
            "terrorblade_metamorphosis"         "1"
            "winter_wyvern_arctic_burn"         "1"
        }
        
		// Chemical Rages
        "3" {
            "alchemist_chemical_rage"  			 "1"
            "custom_bot_chemical_rage" 			 "1"
        }
		
		// Shadow Dances
        "4" {
            "slark_shadow_dance" 	  			 "1"
            "custom_bot_shadow_dance"  		     "1"
        }
		
		"5" {
			"roshan_bash"                           "1"
			"slardar_bash"                          "1"
			"spirit_breaker_greater_bash"           "1"
			"faceless_void_time_lock"               "1"
			"troll_warlord_berserkers_rage"         "1"
			"imba_tower_permabash"   "1"
        }
    }

    // Stop multicast on these spells
    "noMulticast" {
        "enraged_wildkin_tornado"           "1"
        "invoker_cold_snap_lod"             "1"
        "item_ancient_janggo"               "1"
        "item_black_king_bar"               "1"
        "item_courier"                      "1"
        "item_diffusal_blade"               "1"
        "item_diffusal_blade_2"             "1"
        "item_power_treads"                 "1"
        "item_slippers_of_halcyon"          "1"
        "item_tpscroll"                     "1"
        "item_travel_boots"                 "1"
        "item_travel_boots_2"               "1"
        "item_urn_of_shadows"               "1"
        "lich_dark_ritual"                  "1"
        "phoenix_sun_ray"                   "1"
        "shredder_chakram"                  "1"
        "shredder_timber_chain"             "1"
        //"witch_doctor_death_ward"         "1"
        "item_ward_observer"                "1"
        "item_ward_sentry"                  "1"
        "item_bottle"                       "1"
        "item_moon_shard"                   "1"
        "phantom_assassin_phantom_strike"   "1"
        "life_stealer_infest"               "1"
        "pudge_meat_hook"                   "1"
        "item_tango"                        "1"
        "item_clarity"                      "1"
        "item_enchanted_mango"              "1"
        "item_flask"                        "1"
        "item_dust"                         "1"
        "item_ward_dispenser"               "1"
        "item_tango_single"                 "1"
        "tusk_snowball"			    "1"

    }

    // Abiltiies that won't have their cooldowns lowered by our patch
    "noWitchcraft" {
        "death_prophet_carrion_swarm"   "1"
        "death_prophet_silence"         "1"
    }

    // Skills that are never allowed on a tower
    "noTowerAlways" {
        "pudge_flesh_heap"              "1"
        "troll_warlord_berserkers_rage" "1"
        "vengefulspirit_command_aura"   "1"
        "riki_permanent_invisibility"   "1" //Towers become unclickable
    }

    // Stop tower from getting these abilities
    "noTower" {
        "pudge_flesh_heap"              "#noTowerCrash"
        "troll_warlord_berserkers_rage" "#noTowerCrash"
        "life_stealer_feast"            "#noTowerOP"
        "medusa_split_shot"             "#noTowerActivate"
        "dragon_knight_dragon_blood"    "#noTowerLongGame"
        "shredder_reactive_armor"       "#noTowerLongGame"
        "vengefulspirit_command_aura"   "#noTowerCrash"
        "ursa_fury_swipes"              "#noTowerOP"
        "riki_permanent_invisibility"   "#noTowerNoAttack"
        "lod_item_helm_of_the_dominator""#noTowerLongGame"
        "lod_item_mask_of_madness"      "#noTowerLongGame"
        "lod_item_lifesteal"            "#noTowerLongGame"
        "lod_item_satanic"              "#noTowerLongGame"
        "lod_item_heart"                "#noTowerLongGame"
        "slark_shadow_dance"            "#noTowerLongGame"
        "necrolyte_sadist"              "#noTowerOP"
        "brewmaster_drunken_brawler"    "#noTowerOP"
        "faceless_void_backtrack"       "#noTowerOP"
        "phantom_assassin_blur"         "#noTowerOP"
    }

    // Skills that can't be used on a player unless troll combos are allowed
    "noHero" {
        "lone_druid_spirit_bear_return" "1"
    }

    // Skills that can not be used on bears
    "noBear" {
        "pudge_flesh_heap"              "1"
        "troll_warlord_berserkers_rage" "1"
        "vengefulspirit_command_aura"   "1"
    }

    // Skills that cant be used with WTF mode
    "wtfAutoBan" {
        "zuus_thundergods_vengeance"        "1"
        "zuus_thundergods_wrath"            "1"
        "zuus_static_field"                 "1"
        "spectre_haunt"                     "1"
        "invoker_sun_strike_lod"            "1"
        "silencer_global_silence"           "1"
        "ancient_apparition_ice_blast"      "1"
        "gyrocopter_call_down"              "1"
        "earthshaker_aftershock"            "1"
        "shadow_shaman_mass_serpent_ward"   "1"
        "warlock_rain_of_chaos"             "1"
        "terrorblade_conjure_image"         "1"
        "dazzle_shallow_grave"              "1"
        "shredder_whirling_death"           "1"
        "skeleton_king_reincarnation"       "1"
        "abaddon_borrowed_time"             "1"
        "enigma_demonic_conversion"         "1"
        "furion_force_of_nature"            "1"
        "omniknight_guardian_angel"         "1"
        "furion_wrath_of_nature"            "1"
        "rattletrap_rocket_flare"           "1"
    }

    // Prevents the following skills from being randomed
    "doNotRandom" { 
        "paladin_blizzard"      "1"
        "spawnlord_master_freeze_creep" "1"
        "chaos_knight_chaos_strike_gyro"    "1"
        "brewmaster_storm_wind_walk"            "1"
        "brewmaster_earth_pulverize"    "1"
        "paladin_blizzard"  "1"
        "ogre_magi_multicast"   "1"
        "imba_juggernaut_healing_ward_passive"  "1"
        "treant_eyes_in_the_forest_notification"    "1"
        "meepo_divided_we_stand"            "1"
        "phase_datadriven"  "1"
        "makemeleecreeps_lua"   "1"
        "makerangedcreeps_lua"   "1"
        "makecatapults_lua"   "1"
        "hawkeye_double_tap_second_shot"            "1"
        "invoker_forge_spirit"                      "1"
        "luna_eclipse"                              "1"
        "elder_titan_return_spirit"                 "1"
        "morphling_morph_str"                       "1"
        "morphling_morph_agi"                       "1"
        "puck_ethereal_jaunt"                       "1"
        "puck_illusory_orb"                         "1"
        "templar_assassin_psionic_trap"             "1"
        "templar_assassin_trap"                     "1"
        "chen_test_of_faith"                        "1"
        "chen_test_of_faith_teleport"               "1"
        "shredder_chakram"                          "1"
        "shredder_chakram_2"                        "1"
        "earth_spirit_boulder_smash"                "1"
        "earth_spirit_stone_caller"                 "1"
        "earth_spirit_stone_caller_imba"   "1"
        "earth_spirit_magnetize"                    "1"
        "earth_spirit_petrify"                      "1"
        "lone_druid_true_form_battle_cry"           "1"
        "lone_druid_savage_roar"                    "1"
        "ember_spirit_fire_remnant"                 "1"
        "ember_spirit_activate_fire_remnant"        "1"
        "keeper_of_the_light_spirit_form"           "1"
        "keeper_of_the_light_recall_lod"            "1"
        "keeper_of_the_light_blinding_light_lod"    "1"
        "techies_remote_mines"                      "1"
        "techies_focused_detonate"                  "1"
        "life_stealer_consume"                      "1"
        "life_stealer_assimilate"                   "1"
        "nevermore_shadowraze1"                     "1"
        "nevermore_shadowraze2"                     "1"
        "nevermore_shadowraze3"                     "1"
        "spectre_haunt"                             "1"
        "spectre_reality"                           "1"
        "shadow_demon_shadow_poison"                "1"
        "shadow_demon_shadow_poison_release"        "1"
        "nevermore_requiem"                         "1"
        "earthshaker_aftershock_lod"                "1"
        "rubick_spell_steal"                        "1"
		//Terrible abilities
		"broodmother_poison_sting"           	    "1"
		"gnoll_assassin_envenomed_weapon"           "1"		
		"satyr_soulstealer_mana_burn"               "1"
        "lone_druid_spirit_bear_return_lod"                "1"
        // Bad one level abilities
        "blue_dragonspawn_overseer_evasion"                "1"
        "blue_dragonspawn_sorcerer_evasion"                "1"  
        "monkey_king_mischief"                      "1"
        "satyr_trickster_purge"                     "1"
        "giant_wolf_critical_strike"                "1"
        "alpha_wolf_critical_strike"                "1"
        "gemini_unstable_rift_one"      "1"
        "imba_dazzle_shallow_grave_passive_one"      "1"
        "imba_tower_forest_one"      "1"
        "ebf_rubick_arcane_echo_one"      "1"
        "aether_range_lod_global"       "1"
        "monkey_king_wukongs_command"   "1"
	"imba_crystal_maiden_freezing_field_scepter"    "1"
        "imba_jakiro_ice_breath"    "1"
        "imba_juggernaut_healing_ward_upgrade" "1"
        "imba_necrolyte_death_pulse_aux"        "1"
        "imba_necrolyte_death_pulse"    "1"
        "imba_necrolyte_heartstopper_aura"      "1"
        "necrolyte_sadist_lod"      "1"
        "imba_necrolyte_reapers_scythe"      "1" 
        "imba_phantom_assassin_stifling_dagger"    "1"
        "imba_phantom_assassin_phantom_strike"  "1"
        "imba_phantom_assassin_blur"      "1"
        "imba_phantom_assassin_coup_de_grace"      "1"
        "imba_kunkka_torrent"    "1"
        "imba_kunkka_tidebringer"  "1"
        "imba_kunkka_x_marks_the_spot"      "1"
        "imba_kunkka_ghostship"      "1"
        "imba_juggernaut_blade_fury"    "1"
        "imba_juggernaut_healing_ward"  "1"    
        "imba_juggernaut_blade_dance"      "1"
        "imba_juggernaut_omni_slash"      "1"
        "imba_lion_earth_spike"    "1"
        "imba_lion_hex"  "1"
        "imba_lion_mana_drain"      "1"
        "imba_lion_finger_of_death"      "1"
        "imba_warlock_shadow_word"    "1"
        "imba_warlock_upheaval"  "1"
        "imba_warlock_rain_of_chaos"      "1"
        "imba_warlock_flaming_fists"      "1"
        "imba_warlock_permanent_immolation"      "1"
        "imba_lich_frost_nova"    "1"
        "imba_lich_frost_armor"  "1"
        "imba_lich_dark_ritual"      "1"
        "imba_lich_chain_frost"      "1"
        "imba_sven_storm_bolt"    "1"
        "imba_sven_great_cleave"  "1"
        "imba_sven_warcry"      "1"
        "imba_sven_gods_strength"      "1"
        "alchemist_acid_spray_imba"      "1"
        "alchemist_unstable_concoction_imba"      "1"
        "alchemist_goblins_greed_imba"      "1"
        "alchemist_chemical_rage_imba"      "1"
        "imba_lina_dragon_slave"    "1"
        "imba_lina_dragon_slave_aux"  "1"
        "imba_lina_dragon_slave_aux_fiery"      "1"
        "imba_lina_light_strike_array"      "1"
        "imba_lina_light_strike_array_fiery"      "1"
        "imba_lina_fiery_soul"      "1"
        "imba_lina_blazing_soul"      "1"
        "imba_lina_laguna_blade"      "1"
        "imba_lina_laguna_blade_fiery"      "1"
        "imba_magnus_shockwave"    "1"
        "imba_magnus_empower"  "1"
        "imba_magnus_magnetize"      "1"
        "imba_magnus_reverse_polarity"      "1"
        "imba_mirana_starfall"    "1"
        "imba_mirana_arrow"  "1"
        "imba_mirana_leap"      "1"
        "imba_mirana_cosmic_dust"      "1"
        "imba_nevermore_shadowraze1"    "1"
        "imba_nevermore_shadowraze2"  "1"
        "imba_nevermore_shadowraze3"      "1"
        "imba_nevermore_necromastery"      "1"
        "imba_nevermore_dark_lord"      "1"
        "imba_nevermore_requiem"      "1"
        "imba_nevermore_requiem_aux"      "1"
        "imba_night_stalker_void"    "1"
        "imba_night_stalker_crippling_fear"  "1"
        "imba_night_stalker_hunter_in_the_night"      "1"
        "imba_night_stalker_darkness"      "1"
        "imba_omniknight_purification"    "1"
        "imba_omniknight_repel"  "1"
        "imba_omniknight_degen_aura"      "1"
        "imba_omniknight_guardian_angel"      "1"
        "imba_obsidian_destroyer_arcane_orb"    "1"
        "imba_obsidian_destroyer_astral_imprisonment"  "1"
        "imba_obsidian_destroyer_essence_aura"      "1"
        "imba_obsidian_destroyer_sanity_eclipse"      "1"
        "imba_nyx_assassin_impale"    "1"
        "imba_nyx_assassin_spiked_carapace"  "1"
        "imba_nyx_assassin_vendetta"      "1"
        "imba_night_stalker_darkness"      "1"
        "imba_pudge_meat_hook"    "1"
        "imba_pudge_rot"  "1"
        "imba_pudge_flesh_heap"      "1"
        "imba_pudge_sharp_hook"      "1"
        "imba_pudge_light_hook"      "1"
        "imba_pudge_dismember"      "1"
        "imba_pugna_nether_blast"    "1"
        "imba_pugna_decrepify"  "1"
        "imba_pugna_nether_ward"      "1"
        "imba_pugna_nether_ward_aura"      "1"
        "imba_queenofpain_sonic_wave"      "1"
        "imba_silencer_arcane_curse"    "1"
        "imba_silencer_glaives_of_wisdom"  "1"
        "imba_silencer_last_word"      "1"
        "imba_silencer_global_silence"      "1"
        "imba_sniper_headshot"    "1"
        "imba_sniper_take_aim_near"  "1"
        "imba_sniper_take_aim_normal"      "1"
        "imba_sniper_take_aim_far"      "1"
        "imba_sniper_assassinate"      "1"    
        "imba_techies_land_mines"    "1"
        "imba_techies_land_mine_passive"  "1"
        "imba_techies_stasis_trap"      "1"
        "imba_techies_stasis_trap_passive"      "1"
        "imba_techies_remote_auto_creep"      "1"
        "imba_techies_remote_auto_hero"      "1"
        "imba_techies_minefield_sign"      "1"
        "imba_techies_minefield_teleport"      "1"
        "imba_sandking_burrowstrike"    "1"
        "imba_sandking_sand_storm"  "1"
        "imba_sandking_caustic_finale"      "1"
        "imba_sandking_treacherous_sands"      "1"
        "imba_sandking_epicenter"      "1"
        "imba_skywrath_mage_arcane_bolt"    "1"
        "imba_skywrath_mage_concussive_shot"  "1"
        "imba_skywrath_mage_concussive_shot_ghastly"      "1"
        "imba_skywrath_mage_ancient_seal"      "1"
        "imba_skywrath_mage_mystic_flare"      "1"
        "imba_troll_warlord_whirling_axes_melee"    "1"
        "imba_troll_warlord_whirling_axes_ranged"  "1"
        "imba_troll_warlord_fervor"      "1"
        "imba_troll_warlord_berserkers_rage"      "1"
        "imba_troll_warlord_battle_trance"      "1"
        "imba_wraith_king_wraithfire_blast"    "1"
        "imba_wraith_king_vampiric_aura"  "1"
        "imba_wraith_king_mortal_strike"      "1"
        "imba_wraith_king_reincarnation"      "1"
        "imba_tinker_laser"    "1"
        "imba_tinker_heat_seeking_missile"  "1"
        "imba_tinker_march_of_the_machines"      "1"
        "imba_tinker_rearm"      "1"
        "imba_vengeful_magic_missile"    "1"
        "imba_vengeful_wave_of_terror"  "1"
        "imba_vengeful_command_aura"      "1"
        "imba_vengeful_rancor"      "1"
        "imba_vengeful_nether_swap"      "1"
        "imba_vengeful_swap_back"      "1"
        "imba_venomancer_venomous_gale"    "1"
        "imba_venomancer_poison_sting"  "1"
        "imba_venomancer_plague_ward"      "1"
        "imba_venomancer_poison_sting_ward"      "1"
        "imba_venomancer_scourge_ward_multiattack"      "1"
        "imba_venomancer_toxicity"      "1"
        "imba_venomancer_poison_nova"      "1"
        "imba_rubick_telekinesis"    "1"
        "imba_rubick_telekinesis_land"  "1"
        "imba_pugna_nether_ward"      "1"
        "imba_pugna_nether_ward_aura"      "1"
        "imba_queenofpain_sonic_wave"      "1"
        "imba_queenofpain_shadow_strike"    "1"
        "imba_queenofpain_blink"  "1"
        "imba_queenofpain_scream_of_pain"      "1"
        "imba_queenofpain_delightful_torment"      "1"
        "imba_pugna_life_drain_end"      "1"
        "imba_pugna_life_drain"      "1"
        "imba_jakiro_fire_breath"    "1"
        "imba_jakiro_liquid_fire"      "1"
        "imba_jakiro_macropyre"      "1"
        "imba_faceless_void_time_walk"    "1"
        "imba_faceless_void_time_dilation"  "1"
        "imba_faceless_void_time_lock"      "1"
        "imba_faceless_void_timelord"      "1"
        "imba_faceless_void_chronosphere"      "1"
        "imba_enigma_malefice"    "1"
        "imba_enigma_demonic_conversion"  "1"
        "imba_enigma_midnight_pulse"      "1"
        "imba_enigma_gravity"      "1"
        "imba_enigma_black_hole"      "1"
        "imba_drow_ranger_frost_arrows"    "1"
        "imba_drow_ranger_gust"  "1"
        "imba_drow_ranger_trueshot"      "1"
        "imba_drow_ranger_marksmanship"      "1"
        "imba_dazzle_poison_touch"    "1"
        "imba_dazzle_shallow_grave"  "1"
        "imba_dazzle_shadow_wave"      "1"
        "imba_dazzle_weave"      "1"
        "imba_crystal_maiden_crystal_nova"    "1"
        "imba_crystal_maiden_frostbite"  "1"
        "imba_crystal_maiden_brilliance_aura"      "1"
        "imba_crystal_maiden_freezing_field"   "1"
        "imba_clinkz_strafe"    "1"
        "imba_clinkz_searing_arrows"  "1"
        "imba_clinkz_skeleton_walk"      "1"
        "imba_clinkz_death_pact"   "1"
        "imba_centaur_hoof_stomp"    "1"
        "imba_centaur_double_edge"  "1"
        "imba_centaur_return"      "1"
        "imba_centaur_stampede"   "1"
        "imba_bounty_hunter_shuriken_toss"    "1"
        "imba_bounty_hunter_wind_walk"  "1"
        "imba_bounty_hunter_track"      "1"
        "imba_bounty_hunter_shadow_jaunt"   "1"
        "imba_bane_enfeeble"    "1"
        "imba_bane_nightmare"  "1"
        "imba_bane_nightmare_end"      "1"
        "imba_bane_brain_sap"   "1"
        "imba_bane_fiends_grip"   "1"
        "imba_abaddon_death_coil"    "1"
        "imba_abaddon_frostmourne"  "1"
        "imba_abaddon_borrowed_time"      "1"
        "imba_abaddon_aphotic_shield"   "1"
        "imba_antimage_mana_break"    "1"
        "imba_antimage_spell_shield"  "1"
        "imba_antimage_magehunter"      "1"
        "imba_antimage_mana_void"   "1"
        "imba_axe_berserkers_call"    "1"
        "imba_axe_battle_hunger"  "1"
        "imba_axe_counter_helix"      "1"
        "imba_axe_culling_blade"   "1"
        "elder_titan_echo_stomp_imba"      "1"
        "elder_titan_ancestral_spirit_imba"   "1"
    }

    // Abilities that are considered to be OP
    "OPSkillsList" {
		//Thirst needs to be looked at
		"bloodseeker_thirst_lod"            "1"

        "obsidian_destroyer_essence_aura_lod"   "1"
		
		// Buggy True Randoms
		"true_random_lod_1"    "1"
		"true_random_lod_2"    "1"
		"true_random_lod_3"    "1"
		"true_random_lod_4"    "1"
		"true_random_lod_5"    "1"
		"true_random_lod_6"    "1"
		
        // Roshan
        "roshan_spell_block"    "4001"
        "roshan_bash"     "4012"

        // Warlock Golem
        "warlock_golem_flaming_fists" "4002"
        "warlock_golem_permanent_immolation"      "4003"

        // Brewmaster
        "brewmaster_earth_hurl_boulder"     "4004"
        "brewmaster_earth_pulverize"  "4005"
        "brewmaster_storm_wind_walk"  "4006"
        "brewmaster_storm_dispel_magic"     "4007"
        "brewmaster_fire_permanent_immolation"    "4008"
        "brewmaster_storm_cyclone"    "4009"

        // Neutral spell immunity
        "neutral_spell_immunity"      "4010"

        // Tower Abilities
        "backdoor_protection"   "4011"

        // Ogre magi ulty
        //"ogre_magi_unrefined_fireblast"  "466"

        // Meepo Ulty
        "meepo_divided_we_stand"      "467"

        // Rearm
        "tinker_rearm"  "488"

        // Riki
        "riki_permanent_invisibility"   "311"

        // Multicast
        // "ogre_magi_multicast_lod"   "260"

        // Witch Craft
        "death_prophet_witchcraft"  "89"

        // Bear TP
        "lone_druid_spirit_bear_return" "1"
		
		//Old Bersekers blood
		"huskar_berserkers_blood_lod"	"1"				
		
		//Angel Arena Reborn
		"angel_arena_nether_ritual"	"1"
		"ursa_fury_swipes"              "1"
        "slark_essence_shift"           "1"
        "earthshaker_aftershock"        "1"
        "zuus_static_field"             "1"
        "batrider_sticky_napalm"        "1"
        "abaddon_borrowed_time"         "1"
        "skeleton_king_reincarnation"   "1"
        "weaver_shukuchi"               "1"
        "lina_fiery_soul"               "1"
        "bristleback_warpath"           "1"
        "arc_warden_tempest_double"     "1"
        "death_prophet_spirit_siphon"   "1"
        "tiny_grow_lod"                 "1"
        "silencer_glaives_of_wisdom"	"1"
        "bloodseeker_blood_bath2"       "1"
    }

    // Abilities that will be banned by default in LoD
    // This list is up for debate
    "SuperOP" {	
	"imba_juggernaut_healing_ward_passive_redux"  "1"        
	"vassal_shield"   "1"
        "titan_command_aura"    "1"
        "summoner_tesla_coil"   "1"
		"disruptor_kinetic_field_OP"	"1"
		"disruptor_glimpse_OP"	"1"
		"garden_red_flower_base_OP"	"1"
		"obsidian_destroyer_essence_aura_lod_health" "1"
		"shards_of_truesight_lod_OP"	"1"
		"frost_lord_freezing_OP"	"1"
		"lone_druid_spirit_bear_return_lod_OP"	"1"
		"ebf_rubick_arcane_echo_OP"	"1"
		"global_stun"	"1"
		"octarine_vampirism_lod_OP"	"1"
		"force_dash_lod_OP"	"1"
		"aether_range_lod_OP"	"1"
		//"linkens_guard_lod"	"1"
		"lord_of_lightning_holy_wrath_OP"	"1"
		"imba_tower_atrophy"   "1"
		"imba_tower_berserk"   "1"
		"imba_tower_chrono"   "1"
		"imba_tower_disease"   "1"
		"imba_tower_essence_drain"   "1"
		"imba_tower_fervor"   "1"
		"imba_tower_force"   "1"
        "lich_cold_aura"    "1"
        "bahamut_reckoning_aura"  "1"
		"imba_tower_grievous_wounds"   "1"
		"imba_tower_hex_aura"   "1"
		"imba_tower_laser"   "1"
		"imba_tower_machinegun"   "1"
		"imba_tower_mana_burn"   "1"
		"imba_tower_mana_flare"   "1"
		"imba_tower_mindblast"   "1"
		"imba_tower_multihit"   "1"
		"imba_tower_nature"   "1"
		"imba_tower_permabash"   "1"
		"imba_tower_plague"   "1"
		"imba_tower_salvo"   "1"
		"imba_tower_sniper"   "1"
		"imba_tower_spacecow"   "1"
		"imba_tower_spell_shield"   "1"
		"imba_tower_split"   "1"
		"imba_tower_vicious"   "1"		
		"angel_arena_rifle_OP" "1"
		"zulf_typhoon_OP" "1"
		"angel_arena_razor_power_OP"	"1"
		"android_cluster_rockets_OP" "1"
		"angel_arena_nether_ritual"	"1"
		"ebf_clinkz_trickshot_passive"      "1"
		"serpent_queen_ball_lightning_op"	"1"	    
        "zuus_lightning_bolt_global"   "1"    
    }
}