"Bans" {
    // The first key is a spell, the 2nd is all the spells that cant be used with it
    "BannedCombinations" {
        // Sticky Napalm, crazy damage
        "batrider_sticky_napalm" {
            "axe_battle_hunger"                     "1"
            //"batrider_flamebreak"                   "1"
            "brewmaster_fire_permanent_immolation"  "1"
            "dark_seer_ion_shell"                   "1"
            "doom_bringer_scorched_earth"           "1"
            "ember_spirit_flame_guard"              "1"
            "gyrocopter_rocket_barrage"             "1"
            "huskar_burning_spear"                  "1"
            "juggernaut_blade_fury"                 "1"
            "kunkka_torrent"                        "1" //Kunkka Torrent does 10 ticks of damage in short succession
            "leshrac_diabolic_edict"                "1" //40 Explosions
            "leshrac_pulse_nova"                    "1" //Especially overpowered in x5 multiplier and up
            "pudge_rot"                             "1"
            "shadow_shaman_shackles"                "1"
            "skywrath_mage_mystic_flare"            "1"
            "slark_dark_pact"                       "1"
            "venomancer_poison_sting"               "1"
            "viper_poison_attack"                   "1"
            "warlock_golem_permanent_immolation"    "1"
            "bloodseeker_rupture"                   "1"
            "death_prophet_spirit_siphon"           "1"
            "pugna_life_drain"                      "1"
        }

        // Multishot abuse
        "holdout_multishot" {
            "ember_spirit_sleight_of_fist"  "1"
            "holdout_omnislash"             "1"
            "medusa_split_shot"             "1"
            "life_stealer_feast"            "1" // Cray Cray HP steal!
        }

        // Split shot abuse
        //"medusa_split_shot" {
        //    "phantom_lancer_juxtapose"      "1" // Infinite illusions
        //}

        // Crashy Combo
        "lone_druid_true_form" {
            "troll_warlord_berserkers_rage" "1"
        }
        
        // Global Walrus Kick 
		"tusk_walrus_kick" {
			"lone_druid_true_form"          "1"
            "troll_warlord_berserkers_rage" "1"
        }

        // Teleport Abuse
        "furion_teleportation" {
            "abaddon_borrowed_time"             "1"
            "spectre_dispersion"                "1"
        }

        // Rearm Abuse
        "tinker_rearm" {
            "abaddon_borrowed_time"             "1"
            "ancient_apparition_ice_blast"      "1"
            "arc_warden_tempest_double"         "1"
            "dark_seer_wall_of_replica"         "1"
            "faceless_void_chronosphere"        "1"
            "furion_wrath_of_nature"            "1"
            "gyrocopter_call_down"              "1"
            "invoker_sun_strike_lod"            "1"
            "magnataur_reverse_polarity"        "1"
            "necrolyte_reapers_scythe"          "1"
            "omniknight_guardian_angel"         "1" //Can spam global Omni ulti (with aghs), from fountain
            "phoenix_supernova"                 "1"
            "razor_eye_of_the_storm"            "1"
            "silencer_global_silence"           "1"
            "shadow_shaman_mass_serpent_ward"   "1"
            "skeleton_king_reincarnation"       "1"
            "slark_shadow_dance"                "1" //Become untouchable throughout the game with obsidian_destroyer_essence_aura
            "spectre_haunt"                     "1"
            "tidehunter_ravage"                 "1"
            "treant_overgrowth"                 "1"
            "warlock_rain_of_chaos"             "1"
            "zuus_thundergods_vengeance"        "1"
            "zuus_thundergods_wrath"            "1"
        }

        // Arc warden's ult is basically like rearm
        "arc_warden_tempest_double" {
            "abaddon_borrowed_time"             "1"
            "ancient_apparition_ice_blast"      "1"
            "dark_seer_wall_of_replica"         "1"
            "faceless_void_chronosphere"        "1"
            "furion_wrath_of_nature"            "1"
            "gyrocopter_call_down"              "1"
            "invoker_sun_strike_lod"            "1"
            "magnataur_reverse_polarity"        "1"
            "necrolyte_reapers_scythe"          "1"
            "omniknight_guardian_angel"         "1" //Can spam global Omni ulti (with aghs), from fountain
            "phoenix_supernova"                 "1"
            "razor_eye_of_the_storm"            "1"
            "silencer_global_silence"           "1"
            "shadow_shaman_mass_serpent_ward"   "1"
            "skeleton_king_reincarnation"       "1"
            "slark_shadow_dance"                "1" //Become untouchable throughout the game with obsidian_destroyer_essence_aura
            "spectre_haunt"                     "1"
            "tidehunter_ravage"                 "1"
            "tinker_rearm"                      "1"
            "treant_overgrowth"                 "1"
            "warlock_rain_of_chaos"             "1"
            "zuus_thundergods_vengeance"        "1"
            "zuus_thundergods_wrath"            "1"

            "techies_land_mines"                "1"
            "techies_focused_detonate"          "1"
            "techies_remote_mines"              "1"
            "techies_stasis_trap"               "1"
            "meepo_divided_we_stand"            "1"
            "visage_summon_familiars"           "1"
            "techies_suicide"                   "1"
        }

        // Meepo abuse
        "meepo_divided_we_stand" {
            "abaddon_borrowed_time"         "1" // Glitchy
            "alchemist_chemical_rage"       "1"
            "alchemist_chemical_rage_lod"   "1"
            "ancient_apparition_ice_blast"  "1"
            "faceless_void_chronosphere"    "1" // Total of 25 seconds Chrono
            "furion_wrath_of_nature"        "1"
            "gyrocopter_call_down"          "1"
            "invoker_sun_strike_lod"        "1"
            "lone_druid_spirit_bear"        "1" // This one is kind of crashy
            "meepo_divided_we_stand"        "1" // This stops divided we stand being picked twice
            "ogre_magi_multicast_lod"       "1"
            "zuus_thundergods_vengeance"    "1"
            "zuus_thundergods_wrath"        "1"
        }

        // Unlimited rearm
        "phoenix_supernova" {
            "phoenix_supernova" "1"
            "abaddon_borrowed_time" "1"
        }

        // This spell now works on all abilities!
        "death_prophet_witchcraft" {
            "bristleback_warpath"               "1"
            "bristleback_quill_spray"           "1" // It's time this juggernaut was banned
            "earthshaker_aftershock"            "1"
            "lina_fiery_soul"                   "1"
            "storm_spirit_overload"             "1"
            "zuus_static_field"                 "1"
            "obsidian_destroyer_essence_aura"   "1"
            "puck_phase_shift"                  "1"
            "ember_spirit_sleight_of_fist"      "1"
        }

        // Individual bans for old spamable spells
        "zuus_arc_lightning" {
            "earthshaker_aftershock"            "1"
        }
        "storm_spirit_ball_lightning" {
            "bristleback_warpath"               "1"
            "earthshaker_aftershock"            "1"
            "lina_fiery_soul"                   "1"
            "zuus_static_field"                 "1"
        }
        "storm_spirit_static_remnant" {
            "earthshaker_aftershock"            "1"
            "zuus_static_field"                 "1"
        }
        "earthshaker_enchant_totem" {
            "zuus_static_field"                 "1"
            "ursa_overpower"                    "1" // Can get off 3 or so enchant hits
        }
         "ursa_overpower" {
            "bounty_hunter_jinada"              "1" // Can get off plenty of 100% crits successively with ranged hero
            "brewmaster_drunken_brawler"        "1" // Also OP on ranged hero, many 100% crits after another
        }
        "obsidian_destroyer_arcane_orb" {
            "bristleback_warpath"               "1"
            "lina_fiery_soul"                   "1"
            "storm_spirit_overload"             "1"
            "earthshaker_aftershock"            "1"
        }

        "nyx_assassin_burrow" {
            // Crazy damage reduction
            "bristleback_bristleback"           "1"
            "spectre_dispersion"                "1"

            // Movement while burrowed
            "furion_teleportation"              "1"
            "queenofpain_blink"                 "1"
            "riki_blink_strike"                 "1"
            "antimage_blink"                    "1"
            "storm_spirit_ball_lightning"       "1"
        }
    }

    // List of spells that use banned Categories
    "CategoryBans" {
        "bristleback_warpath"               "ToggleSpells"
        "earthshaker_aftershock"            "SpammableSpells"
        "lina_fiery_soul"                   "ToggleSpells"
        "storm_spirit_overload"             "ToggleSpells"
        "zuus_static_field"                 "SpammableSpells"
        "obsidian_destroyer_essence_aura"   "ToggleSpells"
    }

    // List of categories to use with the categories bans
    "Categories" {
        // List of spells that can be spammed easily
        // 1 to reference a spell
        // 2 to reference another list (note: Do NOT create recursion, there is no recursion checking!)
        "SpammableSpells" {
            // Ban ToggleSpells
            "ToggleSpells"                      "2"

            // Ban skillz
            "abaddon_aphotic_shield"            "1"
            "abaddon_death_coil"                "1"
            "alchemist_unstable_concoction"     "1"
            "ancient_apparition_ice_vortex"     "1"
            "antimage_blink"                    "1"
            "arc_warden_spark_wraith"           "1"
            "axe_battle_hunger"                 "1"
            "bane_nightmare"                    "1"
            "batrider_sticky_napalm"            "1"
            "bloodseeker_blood_rage"            "1"
            "bounty_hunter_track"               "1"
            "bristleback_quill_spray"           "1"
            "bristleback_viscous_nasal_goo"     "1"
            "chaos_knight_reality_rift"         "1"
            "courier_burst"                     "1"
            "dazzle_shadow_wave"                "1"
            "doom_bringer_devour"               "1"
            "earthshaker_enchant_totem"         "1"
            "elder_titan_ancestral_spirit"      "1"
            "gyrocopter_rocket_barrage"         "1"
            "leshrac_lightning_storm"           "1"
            "lich_ice_armor"                    "1"
            "lion_mana_drain"                   "1"
            "luna_lucent_beam"                  "1"
            "necrolyte_death_pulse"             "1"
            "phantom_assassin_phantom_strike"   "1"
            "puck_phase_shift"                  "1"
            "pugna_nether_blast"                "1"
            "queen_of_pain_blink"               "1"
            "rubick_telekinesis"                "1"
            "shadow_demon_shadow_poison"        "1"
            "shredder_timber_chain"             "1"
            "skywrath_mage_arcane_bolt"         "1"
            "slark_dark_pact"                   "1"
            "templar_assassin_meld"             "1"
            "tidehunter_anchor_smash"           "1"
            "tinker_rearm"                      "1"
            "treant_natures_guise"              "1"
            "undying_decay"                     "1"
            "venomancer_plague_ward"            "1"
            "weaver_shukuchi"                   "1"

            "oracle_purifying_flames"			"1"

            // Items
            "lod_item_ring_of_basilius"         "1"
            "lod_item_necronomicon"             "1"
            "lod_item_necronomicon_2"           "1"
            "lod_item_necronomicon_3"           "1"
            "lod_item_mjollnir"                 "1"
            "lod_item_diffusal_blade"           "1"
            "lod_item_diffusal_blade_2"         "1"
        }

        // Toggle spells
        "ToggleSpells" {
            "courier_go_to_secretshop"          "1"
            "courier_return_stash_items"        "1"
            "courier_return_to_base"            "1"
            "courier_take_stash_items"          "1"
            "courier_transfer_items"            "1"
            "forest_troll_high_priest_heal"     "1"
            "furion_teleportation"              "1"
            "harpy_storm_chain_lightning"       "1"
            "holdout_multishot"                 "1"
            "lod_item_power_treads"             "1" // Amazing when toggling aftershock!
            "leshrac_pulse_nova"                "1"
            "medusa_mana_shield"                "1"
            "medusa_split_shot"                 "1"
            "meepo_poof"                        "1"
            "morphling_morph_agi"               "1"
            "morphling_morph_str"               "1"
            "pudge_rot"                         "1"
            "riki_blink_strike"                 "1"
            "shredder_chakram"                  "1"
            "techies_focused_detonate"          "1"
            "troll_warlord_berserkers_rage"     "1"
            "wisp_overcharge"                   "1"
            "witch_doctor_voodoo_restoration"   "1"
            "life_stealer_consume"              "1"
            "life_stealer_assimilate"           "1"
            "life_stealer_infest"               "1" // You get consume, which can be spammmmed
            "nyx_assassin_burrow"               "1" // Why you do this, valve?
            "spectre_reality"                   "1" // Can be used over and over
            "skeleton_king_vampiric_aura"       "1" // New update allows it to be toggled
            "life_stealer_assimilate"           "1"
            "elder_titan_return_spirit"         "1"
        }
    }

    // These are groups of spells where none of these can be used together
    "BannedGroups" {
        // The one hit combo group
        "1" {
            "bounty_hunter_jinada"              "1"
            "brewmaster_drunken_brawler"        "1"
            "earthshaker_enchant_totem"         "1"
            "kunkka_tidebringer"                "1"
            "tiny_grow"                         "1"
            "tusk_walrus_punch"                 "1"
            "weaver_geminate_attack"            "1"
            "terrorblade_metamorphosis"         "1"
            "clinkz_death_pact"                 "1"
            "tiny_grow_lod"                     "1"
        }

        // The mega range group
        "2" {
            "dragon_knight_elder_dragon_form"   "1"
            "sniper_take_aim"                   "1"
            "templar_assassin_psi_blades"       "1"
            "terrorblade_metamorphosis"         "1"
            "winter_wyvern_arctic_burn"         "1"
        }
    }

    // Stop multicast on these spells
    "noMulticast" {
        "enraged_wildkin_tornado"           "1"
        "invoker_cold_snap_lod"             "1"
        "item_ancient_janggo"               "1"
        "item_black_king_bar"               "1"
        "item_courier"                      "1"
        "item_diffusal_blade"               "1"
        "item_diffusal_blade_2"             "1"
        "item_power_treads"                 "1"
        "item_slippers_of_halcyon"          "1"
        "item_tpscroll"                     "1"
        "item_travel_boots"                 "1"
        "item_travel_boots_2"               "1"
        "item_urn_of_shadows"               "1"
        "lich_dark_ritual"                  "1"
        "phoenix_sun_ray"                   "1"
        "shredder_chakram"                  "1"
        "shredder_timber_chain"             "1"
        //"witch_doctor_death_ward"         "1"
        "item_ward_observer"                "1"
        "item_ward_sentry"                  "1"
        "item_bottle"                       "1"
        "item_moon_shard"                   "1"
        "phantom_assassin_phantom_strike"   "1"
        "life_stealer_infest"               "1"
        "pudge_meat_hook"                   "1"
        "item_tango"                        "1"
        "item_clarity"                      "1"
        "item_enchanted_mango"              "1"
        "item_flask"                        "1"
        "item_dust"                         "1"
        "item_ward_dispenser"               "1"
        "item_tango_single"                 "1"

    }

    // Abiltiies that won't have their cooldowns lowered by our patch
    "noWitchcraft" {
        "death_prophet_carrion_swarm"   "1"
        "death_prophet_silence"         "1"
    }

    // Skills that are never allowed on a tower
    "noTowerAlways" {
        "pudge_flesh_heap"              "1"
        "troll_warlord_berserkers_rage" "1"
        "vengefulspirit_command_aura"   "1"
        "riki_permanent_invisibility"   "1" //Towers become unclickable
    }

    // Stop tower from getting these abilities
    "noTower" {
        "pudge_flesh_heap"              "#noTowerCrash"
        "troll_warlord_berserkers_rage" "#noTowerCrash"
        "life_stealer_feast"            "#noTowerOP"
        "medusa_split_shot"             "#noTowerActivate"
        "dragon_knight_dragon_blood"    "#noTowerLongGame"
        "shredder_reactive_armor"       "#noTowerLongGame"
        "vengefulspirit_command_aura"   "#noTowerCrash"
        "ursa_fury_swipes"              "#noTowerOP"
        "riki_permanent_invisibility"   "#noTowerNoAttack"
        "lod_item_helm_of_the_dominator""#noTowerLongGame"
        "lod_item_mask_of_madness"      "#noTowerLongGame"
        "lod_item_lifesteal"            "#noTowerLongGame"
        "lod_item_satanic"              "#noTowerLongGame"
        "lod_item_heart"                "#noTowerLongGame"
        "slark_shadow_dance"            "#noTowerLongGame"
        "necrolyte_sadist"              "#noTowerOP"
        "brewmaster_drunken_brawler"    "#noTowerOP"
        "faceless_void_backtrack"       "#noTowerOP"
        "phantom_assassin_blur"         "#noTowerOP"
    }

    // Skills that can't be used on a player unless troll combos are allowed
    "noHero" {
        "lone_druid_spirit_bear_return" "1"
    }

    // Skills that can not be used on bears
    "noBear" {
        "pudge_flesh_heap"              "1"
        "troll_warlord_berserkers_rage" "1"
        "vengefulspirit_command_aura"   "1"
    }

    // Skills that cant be used with WTF mode
    "wtfAutoBan" {
        "zuus_thundergods_vengeance"        "1"
        "zuus_thundergods_wrath"            "1"
        "zuus_static_field"                 "1"
        "spectre_haunt"                     "1"
        "invoker_sun_strike_lod"            "1"
        "silencer_global_silence"           "1"
        "ancient_apparition_ice_blast"      "1"
        "gyrocopter_call_down"              "1"
        "earthshaker_aftershock"            "1"
        "shadow_shaman_mass_serpent_ward"   "1"
        "warlock_rain_of_chaos"             "1"
        "terrorblade_conjure_image"         "1"
        "dazzle_shallow_grave"              "1"
        "shredder_whirling_death"           "1"
        "skeleton_king_reincarnation"       "1"
        "abaddon_borrowed_time"             "1"
        "enigma_demonic_conversion"         "1"
        "furion_force_of_nature"            "1"
        "omniknight_guardian_angel"         "1"
        "furion_wrath_of_nature"            "1"
        "rattletrap_rocket_flare"           "1"
    }

    // Prevents the following skills from being randomed
    "doNotRandom" {
        "luna_eclipse"                              "1"
        "elder_titan_return_spirit"                 "1"
        "morphling_morph_str"                       "1"
        "morphling_morph_agi"                       "1"
        "puck_ethereal_jaunt"                       "1"
        "puck_illusory_orb"                         "1"
        "templar_assassin_psionic_trap"             "1"
        "templar_assassin_trap"                     "1"
        "chen_test_of_faith"                        "1"
        "chen_test_of_faith_teleport"               "1"
        "shredder_chakram"                          "1"
        "shredder_chakram_2"                        "1"
        "tusk_walrus_kick"                          "1"
        "earth_spirit_boulder_smash"                "1"
        "earth_spirit_stone_caller"                 "1"
        "earth_spirit_magnetize"                    "1"
        "earth_spirit_petrify"                      "1"
        "lone_druid_true_form_battle_cry"           "1"
        "lone_druid_savage_roar"                    "1"
        "ember_spirit_fire_remnant"                 "1"
        "ember_spirit_activate_fire_remnant"        "1"
        "keeper_of_the_light_spirit_form"           "1"
        "keeper_of_the_light_recall_lod"            "1"
        "keeper_of_the_light_blinding_light_lod"    "1"
        "techies_remote_mines"                      "1"
        "techies_focused_detonate"                  "1"
        "life_stealer_consume"                      "1"
        "life_stealer_assimilate"                   "1"
        "nevermore_shadowraze1"                     "1"
        "nevermore_shadowraze2"                     "1"
        "nevermore_shadowraze3"                     "1"
        "spectre_haunt"                             "1"
        "spectre_reality"                           "1"
        "nyx_assassin_burrow"                       "1"
        "shadow_demon_shadow_poison"                "1"
        "shadow_demon_shadow_poison_release"        "1"
        "abaddon_borrowed_time"                     "1"
        "skeleton_king_reincarnation"               "1"
        "ursa_fury_swipes"                          "1"
        "nevermore_requiem"                         "1"
        "earthshaker_aftershock"                    "1"
        "earthshaker_aftershock_lod"                "1"
        "zuus_static_field"                         "1"
        "lina_fiery_soul"                           "1"
        "bristleback_warpath"                       "1"
        "rubick_spell_steal"                        "1"
    }

    // Abilities that are considered to be OP
    "OPSkillsList" {
        // Roshan
        "roshan_spell_block"    "4001"
        "roshan_bash"     "4012"

        // Warlock Golem
        "warlock_golem_flaming_fists" "4002"
        "warlock_golem_permanent_immolation"      "4003"

        // Brewmaster
        "brewmaster_earth_hurl_boulder"     "4004"
        "brewmaster_earth_pulverize"  "4005"
        "brewmaster_storm_wind_walk"  "4006"
        "brewmaster_storm_dispel_magic"     "4007"
        "brewmaster_fire_permanent_immolation"    "4008"
        "brewmaster_storm_cyclone"    "4009"

        // Neutral spell immunity
        "neutral_spell_immunity"      "4010"

        // Tower Abilities
        "backdoor_protection"   "4011"

        // Ogre magi ulty
        "ogre_magi_unrefined_fireblast"  "466"

        // Meepo Ulty
        "meepo_divided_we_stand"      "467"

        // Rearm
        "tinker_rearm"  "488"

        // Riki
        "riki_permanent_invisibility"   "311"

        // Multicast
        // "ogre_magi_multicast_lod"   "260"

        // Witch Craft
        "death_prophet_witchcraft"  "89"

        // Bear TP
        "lone_druid_spirit_bear_return" "1"
    }

    // Abilities that will be banned by default in LoD
    // This list is up for debate
    "lodBanList" {
        "ursa_fury_swipes"              "1"
        "earthshaker_aftershock"        "1"
        "zuus_static_field"             "1"
        "batrider_sticky_napalm"        "1"
        "abaddon_borrowed_time"         "1"
        "skeleton_king_reincarnation"   "1"
        "weaver_shukuchi"               "1"
        "lina_fiery_soul"               "1"
        "bristleback_warpath"           "1"
        "arc_warden_tempest_double"     "1"
        "death_prophet_spirit_siphon"   "1"
        "tiny_grow_lod"                 "1"
        "silencer_glaives_of_wisdom"	"1"
    }
}
