// Tracking contributors
"contributors" {
    // Ash47, Core coder and designer
    "28090256" {
        "steamID64" "76561197988355984"
        "premium"   "10"
    }

    // darklordabc, Redux project lead
    "93913347" {
        "steamID64" "76561198054179075"
        "premium"   "10"
    }

    // TideSofDarK, UI/Spells contributor
    "41110316" {
        "steamID64" "76561198001376044"
        "premium"   "10"
    }
}
