"PatreonFeatures"
{
    "Options"
    {   
        //"lodOptionFastRunes"    "1"
        "lodOptionPeriodicSpellCast"    "1"
        "lodOptionRandomOnDeath" "1"
        "lodOptionConvertableTowers" "1"
        "lodOptionPocketTowers" "1"
        //"lodOptionKillStreakPower"  "1"
        "lodOptionCooldownReduction"    "1"
        //"lodOptionGoldDropOnDeath"  "1"
        "lodOptionResurrectAllies"  "1"
        "lodOptionRandomLaneCreeps"  "1"
    }
}