// Sounds id from here https://github.com/SteamDatabase/GameTracking/blob/master/dota/game/dota/pak01_dir/soundevents/voscripts
"sounds" {
    "precache_sounds" {
        "soundevents/voscripts/game_sounds_vo_life_stealer.vsndevts" "1"
        "soundevents/voscripts/game_sounds_vo_legion_commander.vsndevts" "1"
        "soundevents/voscripts/game_sounds_vo_bloodseeker.vsndevts" "1"
        "soundevents/voscripts/game_sounds_vo_enigma.vsndevts" "1"
        "soundevents/voscripts/game_sounds_vo_sniper.vsndevts" "1"
        "soundevents/voscripts/game_sounds_vo_wisp.vsndevts" "1"
        "soundevents/voscripts/game_sounds_vo_night_stalker.vsndevts" "1"
        "soundevents/voscripts/game_sounds_vo_centaur.vsndevts" "1"
        "soundevents/voscripts/game_sounds_vo_furion.vsndevts" "1"
        "soundevents/voscripts/game_sounds_vo_chen.vsndevts" "1"
        "soundevents/voscripts/game_sounds_vo_enchantress.vsndevts" "1"
		"soundevents/voscripts/game_sounds_vo_phantom_assassin.vsndevts" "1"
		"soundevents/voscripts/game_sounds_vo_abaddon.vsndevts" "1"
		"soundevents/voscripts/game_sounds_vo_ursa.vsndevts" "1"
		"soundevents/voscripts/game_sounds_vo_mirana.vsndevts" "1"
		"soundevents/voscripts/game_sounds_vo_techies.vsndevts" "1"
		"soundevents/voscripts/game_sounds_vo_tiny.vsndevts" "1"
		"soundevents/voscripts/game_sounds_vo_terrorblade.vsndevts" "1"
        "soundevents/game_sounds_heroes/game_sounds_legion_commander.vsndevts" "1"
        "soundevents/lod_game_sounds.vsndevts" "1"
    }

    "game_option_host" {
        "announcer_ann_custom_mode_05" "1"
    }

    "game_option_player" {
        "announcer_announcer_intl2012_usher_03" "1"
    }

    "game_picking_phase" {
        "announcer_announcer_type_ability_draft_01" "1"
        "announcer_ann_custom_draft_01" "1"
    }

    "game_30_sec_remaining" {
        "announcer_ann_custom_timer_sec_30" "1"
    }

    "game_15_sec_remaining" {
        "announcer_ann_custom_timer_sec_15" "1"
    }

    "game_10_sec_remaining" {
        "announcer_ann_custom_timer_sec_10" "1"
    }

    "game_6_sec_remaining" {
        "announcer_announcer_choose_hero" "1"
    }

    "game_error_alert" {
        "announcer_ann_custom_sports_02" "1"
        "announcer_ann_custom_sports_03" "1"
        "announcer_ann_custom_sports_04" "1"
        "announcer_ann_custom_bad_01" "1"
    }

    "game_out_of_points" {
        "announcer_ann_custom_generic_alert_05" "1"
        "announcer_ann_custom_generic_alert_06" "1"
    }

    "game_ban_started" {
        "announcer_announcer_ban_yr" "1"
    }

    "game_review_phase" {
        "announcer_announcer_battle_prepare_01" "1"
        "announcer_announcer_welcome_08" "1"
    }

    "build_infest_support" {
        "life_stealer_lifest_ability_infest_cast_02" "1"
        "life_stealer_lifest_ability_infest_cast_03" "1"
        "life_stealer_lifest_ability_infest_hero_01" "1"
        "life_stealer_lifest_ability_infest_hero_03" "1"
    }
    "build_hawkeye" {
        "sniper_snip_kill_03" "1"
        "sniper_snip_level_02" "1"
        "sniper_snip_level_06" "1"
        "sniper_snip_tf2_04" "1"
    }
    "build_rapture" {
        "bloodseeker_blod_ability_rupture_01" "1"
        "bloodseeker_blod_ability_rupture_02" "1"
        "bloodseeker_blod_ability_rupture_03" "1"
        "bloodseeker_blod_attack_09" "1"
    }
    "build_team_fight" {
        "enigma_enig_ability_black_01" "1"
        "enigma_enig_respawn_10" "1"
        "enigma_enig_regen_02" "1"
    }
    "build_duelist" {
        "legion_commander_legcom_duel_01" "1"
        "legion_commander_legcom_duel_02" "1"
        "legion_commander_legcom_duel_09" "1"
        "legion_commander_legcom_duel_06" "1"
        "legion_commander_legcom_duel_05" "1"
        "legion_commander_legcom_duel_08" "1"
        "legion_commander_legcom_duelhero_06" "1"
    }
    "build_cannon" {
        "sniper_snip_spawn_04" "1"
        "sniper_snip_ability_shrapnel_01" "1"
        "sniper_snip_tf2_01" "1"
        "sniper_snip_kill_arrow_07" "1"
    }
    "build_medic" {
        "wisp_spawn_respawn" "1"
        "wisp_battlebegins" "1"
    }
    "build_hunter_in_the_night" {
        "night_stalker_nstalk_spawn_02" "1"
        "night_stalker_nstalk_move_07" "1"
        "night_stalker_nstalk_ability_dark_02" "1"
    }
    "build_generic_tank" {
        "centaur_cent_doub_edge_01" "1"
        "centaur_cent_underattack_01" "1"
        "centaur_cent_laugh_04" "1"
    }
    "build_no_ulty" {
        "furion_furi_lasthit_01" "1"
        "furion_furi_lasthit_06" "1"
        "furion_furi_lasthit_07" "1"
    "furion_furi_level_06" "1"
    }
    "build_creep_builder" {
        "chen_chen_ability_holyp_06" "1"
        "chen_chen_ability_holyp_02" "1"
        "chen_chen_ability_holyp_05" "1"
    "chen_chen_ability_holyp_04" "1"
    }
    "build_cherub" {
        "enchantress_ench_ability_nature_02" "1"
        "enchantress_ench_spawn_04" "1"
        "enchantress_ench_respawn_11" "1"
        "enchantress_ench_regen_02" "1"
    }
	"build_dagger_harrasment" {
        "phantom_assassin_phass_ability_stiflingdagger_01" "1"
        "phantom_assassin_phass_ability_stiflingdagger_02" "1"
        "phantom_assassin_phass_ability_stiflingdagger_03" "1"
        "phantom_assassin_phass_ability_stiflingdagger_04" "1"
		"phantom_assassin_phass_ability_blur_02" "1"
    }
	"build_abaddon_pro" {
        "abaddon_abad_deathcoil_06" "1"
        "abaddon_abad_aphoticshield_03" "1"
        "abaddon_abad_aphoticshield_01" "1"
        "abaddon_abad_purch_01" "1"
    }
	"build_roshan_beware" {
        "ursa_ursa_items_10" "1"
        "ursa_ursa_items_11" "1"
    }
	"build_skillshot" {
        "mirana_mir_kill_04" "1"
		"mirana_mir_ability_arrow_01" "1"
		"mirana_mir_ability_arrow_02" "1"
    }
	"build_techies" {
        "techies_tech_setmine_08" "1"
		"techies_tech_minekill_02" "1"
		"techies_tech_settrap_01" "1"
		"techies_tech_focuseddetonate_08" "1"
    }	
	"build_building_buster" {
        "tiny_tiny_attack_08" "1"
		"tiny_tiny_cast_02" "1"
		"tiny_tiny_ability_toss_07" "1"
		"tiny_tiny_level_07" "1"
    }
	"build_super_rat" {
        "terrorblade_terr_sunder_06" "1"
		"terrorblade_terr_deny_17" "1"
		"terrorblade_terr_lasthit_10" "1"
    }
	
	
    // "build_dagger_harrasment"
    // "build_global_caster"
    // "build_magic_be_dashed"
    // "build_attributes"
    // "build_stunner"
    // "build_anti_tank"
}