"Votings" {
	"balance" {
		"switch_team" {

		}
		"add_dire_bots" {
			
		}
		"add_radiant_bots" {
			
		}
	}
	"goldandexp" {
		"give_gold" {

		}
		"give_exp" {

		}
		"change_gold_tickrate" {

		}
		"change_gold_modifier" {

		}
		"change_exp_modifier" {

		}
	}
	"respawn" {
		"change_respawn_time" {

		}
		"change_additional_respawn_time" {

		}
		"change_buyback_cooldown" {

		}
	}
	"other" {
		"switch_universal_shop" {

		}
		"switch_all_vision" {

		}
	}
}