"use strict";
var backList = [
    { img: "venomancer.jpg", title: "\"Venomancer\"", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
    { img: "crystal_maiden.png", author: "eric geusz", url: "http://entroz.deviantart.com" },
    { img: "doom.jpg", author: "eric geusz", url: " http://entroz.deviantart.com" },
    { img: "bristle.jpg", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
    { img: "ck.jpg", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
    { img: "clink.jpg", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
    { img: "clockwerk.jpg", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
    { img: "crystal_maiden.jpg", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
    { img: "dirge.jpg", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
    { img: "doom2.jpg", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
    { img: "ember.jpg", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
    { img: "es.jpg", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
    { img: "jugg.jpg", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
    { img: "jugg2.jpg", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
    { img: "kotl.jpg", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
    { img: "medusa.jpg", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
    { img: "np.jpg", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
    { img: "nyx.jpg", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
    { img: "od.jpg", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
    { img: "pl.jpg", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
    { img: "puck.jpg", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
    { img: "razor.jpg", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
    { img: "sd.jpg", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
    { img: "sf.jpg", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
    { img: "silencer.jpg", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
    { img: "sky.jpg", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
    { img: "slardar.jpg", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
    { img: "sven.jpg", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
    { img: "venomancer.jpg", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
    { img: "venomancer2.jpg", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
    { img: "vs.jpg", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
    { img: "warlock.jpg", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
    { img: "bladeandbow.jpg", author: "Valve", url: "" },
    { img: "direancient.jpg", author: "Valve", url: "" },
    { img: "io.jpg", author: "Valve", url: "" },
    { img: "midlane.jpg", author: "Valve", url: "" },
    { img: "np2.jpg", author: "Valve", url: "" },
    { img: "pureskill.jpg", author: "Valve", url: "" },
    { img: "radiantancient.jpg", author: "Valve", url: "" },
    { img: "roshan.jpg", author: "Valve", url: "" },
    { img: "rubick.jpg", author: "Valve", url: "" },
    {  img: "tidehunter.jpg", author: "Valve", url: "" },
    //title for below: The Calm Before the Horn
    {  img: "calmbeforehorn.jpg", author: "Eran Fowler", url: "http://eranfolio.deviantart.com/" },
    {  img: "huskarfire.jpg", author: "Valve", url: "" },
    {  img: "pa.jpg", author: "Valve", url: "" },
    {  img: "abaddon.jpg", author: "Valve", url: "" },
    {  img: "drow.jpg", author: "Valve", url: "" },
    {  img: "ursa.jpg", author: "Valve", url: "" },
    {  img: "dragonknight.jpg", author: "Valve", url: "" },
    {  img: "luna.jpg", author: "Valve", url: "" },
    {  img: "ta.jpg", author: "Valve", url: "" },
];