"use strict";
var backList = [
    { img: "abaddon.jpg", author: "Valve", url: "" },
	{ img: "calmbeforehorn.jpg", author: "Eran Fowler", url: "http://eranfolio.deviantart.com/" },
	{ img: "dragonknight.jpg", author: "Valve", url: "" },
	{ img: "drow.jpg", author: "Valve", url: "" },
	{ img: "huskarfire.jpg", author: "Valve", url: "" },
	{ img: "luna.jpg", author: "Valve", url: "" },
	{ img: "pa.jpg", author: "Valve", url: "" },
	{ img: "ta.jpg", author: "Valve", url: "" },
	{ img: "tidehunter.jpg", author: "Valve", url: "" },
	{ img: "ursa.jpg", author: "Valve", url: "" },
	{ img: "bladeandbow.jpg", author: "Valve", url: "" },
	{ img: "bristle.jpg", title: "\"Bristleback\"", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
	{ img: "ck.jpg", author: "Chaos Knight", url: "http://biggreenpepper.deviantart.com" },
	{ img: "clink.jpg", title: "\"Clinkz Bone\"", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
	{ img: "clockwerk.jpg", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
	{ img: "crystal_maiden.jpg", title: "\"Carry Maiden\"", author: "eric geusz", url: "http://entroz.deviantart.com" },
	{ img: "direancient.jpg", author: "Valve", url: "" },
	{ img: "dirge.jpg", title: "\"Dirge\"", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
	{ img: "doom.jpg", title: "\"Doom\"", author: "eric geusz", url: "http://steamcommunity.com/id/sfmruls1337" },
	{ img: "doom2.jpg", title: "\"Doom\"", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
	{ img: "ember.jpg", title: "\"Ember Spirit\"", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
	{ img: "es.jpg", title: "\"Earth Spirit\"", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
	{ img: "io.jpg", author: "Valve", url: "" },
	{ img: "jugg.jpg", title: "\"Jugg Sakura\"", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
	{ img: "jugg2.jpg", title: "\"Jugg Loading\"", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
	{ img: "kotl.jpg", title: "\"Keeper Of The Light\"", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
	{ img: "medusa.jpg", title: "\"Medusa\"", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
	{ img: "midlane.jpg", author: "Valve", url: "" },
	{ img: "np.jpg", title: "\"Nature's Prophet\"", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
	{ img: "np2.jpg", author: "Valve", url: "" },
	{ img: "nyx.jpg", title: "\"Nyx Assassin\"", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
	{ img: "od.jpg", title: "\"Obsidian Destroyer\"", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
	{ img: "pl.jpg", title: "\"Phantom Lancer\"", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
	{ img: "puck.jpg", title: "\"Puck\"", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
	{ img: "pureskill.jpg", author: "Valve", url: "" },
	{ img: "radiantancient.jpg", author: "Valve", url: "" },
	{ img: "razor.jpg", title: "\"Razor\"", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
	{ img: "roshan.jpg", author: "Valve", url: "" },
	{ img: "rubick.jpg", author: "Valve", url: "" },
	{ img: "sd.jpg", title: "\"Shadow Demon\"", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
	{ img: "sf.jpg", title: "\"Shadow Fiend\"", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
	{ img: "silencer.jpg", title: "\"Silencer\"", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
	{ img: "sky.jpg", title: "\"Skywrath Mage\"", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
	{ img: "slardar.jpg", title: "\"Slardar\"", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
	{ img: "sven.jpg", title: "\"The Fearless\"", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
	{ img: "venomancer.jpg", title: "\"Lesale Deathbringer\"", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
	{ img: "venomancer2.jpg", title: "\"Veno\"", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
	{ img: "vs.jpg", title: "\"Vengeful Spirit\"", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
	{ img: "bane_elemental.jpg", title: "\"Bane Elemental\"", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
	{ img: "Broodmother.jpg", title: "\"Broodmother\"", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
	{ img: "dark_seer.jpg", title: "\"Dark Seer\"", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
	{ img: "leshrac.jpg", title: "\"Leshrac\"", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
	{ img: "Lich.jpg", title: "\"Lich\"", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
	{ img: "night_stalker.jpg", title: "\"Night Stalker\"", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
	{ img: "Remembering_Skeleton_King.jpg", title: "\"Remebering Skeleton King\"", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
	{ img: "rikimaru.jpg", title: "\"Rikimaru\"", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
	{ img: "tiny.jpg", title: "\"Tiny\"", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
	{ img: "visage.jpg", title: "\"Visage\"", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
];