-- Generated by TypescriptToLua v0.2.0
-- https://github.com/Perryvw/TypescriptToLua
require("typescript_lualib")
LinkLuaModifier("modifier_flying_with_slow","abilities/mutators/modifier_flying_with_slow.lua",LUA_MODIFIER_MOTION_NONE)
fly_redux = {}
fly_redux.__index = fly_redux
function fly_redux.new(construct, ...)
    local instance = setmetatable({}, fly_redux)
    if construct and fly_redux.constructor then fly_redux.constructor(instance, ...) end
    return instance
end
function fly_redux.constructor(self)
end
function fly_redux.GetIntrinsicModifierName(self)
    return "modifier_flying_with_slow"
end
fly_redux_op = {}
fly_redux_op.__index = fly_redux_op
function fly_redux_op.new(construct, ...)
    local instance = setmetatable({}, fly_redux_op)
    if construct and fly_redux_op.constructor then fly_redux_op.constructor(instance, ...) end
    return instance
end
function fly_redux_op.constructor(self)
end
function fly_redux_op.GetIntrinsicModifierName(self)
    return "modifier_flying_with_slow"
end
