-- Generated by TypescriptToLua v0.2.0
-- https://github.com/Perryvw/TypescriptToLua
require("typescript_lualib")
LinkLuaModifier("modifier_pushing_blast_slow","abilities/pushing_blast.lua",LUA_MODIFIER_MOTION_NONE)
pushing_blast = {}
pushing_blast.__index = pushing_blast
function pushing_blast.new(construct, ...)
    local instance = setmetatable({}, pushing_blast)
    if construct and pushing_blast.constructor then pushing_blast.constructor(instance, ...) end
    return instance
end
function pushing_blast.constructor(self)
end
function pushing_blast.OnSpellStart(self)
    local caster = self:GetCaster()

    local point = caster:GetAbsOrigin()

    local p = ParticleManager:CreateParticle("particles/units/heroes/hero_keeper_of_the_light/keeper_of_the_light_blinding_light_aoe.vpcf",PATTACH_CUSTOMORIGIN,caster)

    ParticleManager:SetParticleControl(p,0,point)
    ParticleManager:SetParticleControl(p,1,point)
    ParticleManager:SetParticleControl(p,2,Vector(self:GetSpecialValueFor("radius"),0,0))
    local units = FindUnitsInRadius(caster:GetTeamNumber(),point,nil,self:GetSpecialValueFor("radius"),DOTA_UNIT_TARGET_TEAM_ENEMY,DOTA_UNIT_TARGET_BASIC+DOTA_UNIT_TARGET_HERO,DOTA_UNIT_TARGET_FLAG_NONE,FIND_ANY_ORDER,false)

    TS_forEach(units, function(unit)
        unit:AddNewModifier(caster,self,"modifier_pushing_blast_slow",{duration = self:GetSpecialValueFor("duration")})
        local dist = (point-unit:GetAbsOrigin()):Length2D()

        print(point[1],point[2],point[3])
        local knockback = {should_stun = true,knockback_duration = 0.33,duration = 0.33,knockback_distance = self:GetSpecialValueFor("radius")-dist,knockback_height = 0,center_x = caster:GetAbsOrigin()[1],center_y = caster:GetAbsOrigin()[2],center_z = GetGroundHeight(caster:GetAbsOrigin(),nil)}

        unit:AddNewModifier(caster,self,"modifier_knockback",knockback)
        local dTable = {victim = unit,ability = self,attacker = caster,damage = self:GetSpecialValueFor("damage"),damage_type = DAMAGE_TYPE_MAGICAL}

        ApplyDamage(dTable)
    end
)
end
modifier_pushing_blast_slow = {}
modifier_pushing_blast_slow.__index = modifier_pushing_blast_slow
function modifier_pushing_blast_slow.new(construct, ...)
    local instance = setmetatable({}, modifier_pushing_blast_slow)
    if construct and modifier_pushing_blast_slow.constructor then modifier_pushing_blast_slow.constructor(instance, ...) end
    return instance
end
function modifier_pushing_blast_slow.constructor(self)
end
function modifier_pushing_blast_slow.DeclareFunctions(self)
    return {MODIFIER_PROPERTY_MOVESPEED_BONUS_PERCENTAGE}
end
function modifier_pushing_blast_slow.GetModifierMoveSpeedBonus_Percentage(self)
    return -self:GetAbility():GetSpecialValueFor("ms_slow")
end
