"Abilities" {
    abs {
        ////////////////////
        // Main Skills Tab
        ////////////////////

        // Earth Shaker
        "0"     "earthshaker_fissure"
        "1"     "earthshaker_enchant_totem"
        "2"     "earthshaker_aftershock"
        "3"     "earthshaker_echo_slam"

        // Sven
        "4"     "sven_storm_bolt"
        "5"     "sven_great_cleave"
        "6"     "sven_warcry"
        "7"     "sven_gods_strength"

        //Tiny
        "8"     "tiny_avalanche"
        "9"     "tiny_toss"
        "10"    "tiny_craggy_exterior"
        "11"    "tiny_grow"

        // Kunkka
        "12"    "kunkka_torrent"
        "13"    "kunkka_tidebringer"
        "14"    "kunkka_x_marks_the_spot"
        "15"    "kunkka_ghostship"

        // Beast Master
        "16"    "beastmaster_wild_axes"
        "17"    "beastmaster_call_of_the_wild_boar"
        "18"    "beastmaster_inner_beast"
        "19"    "beastmaster_primal_roar"

        // Dragon Knight
        "20"    "dragon_knight_breathe_fire"
        "21"    "dragon_knight_dragon_tail"
        "22"    "dragon_knight_dragon_blood"
        "23"    "dragon_knight_elder_dragon_form"

        // Clockwerk
        "24"    "rattletrap_battery_assault"
        "25"    "rattletrap_power_cogs"
        "26"    "rattletrap_rocket_flare"
        "27"    "rattletrap_hookshot"

        // Antimage
        "28"    "antimage_mana_break"
        "29"    "antimage_blink"
        "30"    "antimage_spell_shield"
        "31"    "antimage_mana_void"

        // Drow Ranger
        "32"    "drow_ranger_frost_arrows"
        "33"    "drow_ranger_wave_of_silence"
        "34"    "drow_ranger_trueshot"
        "35"    "drow_ranger_marksmanship"

        // Juggernaut
        "36"    "juggernaut_blade_fury"
        "37"    "juggernaut_healing_ward"
        "38"    "juggernaut_blade_dance"
        "39"    "juggernaut_omni_slash"

        // Mirana
        "40"    "mirana_starfall"
        "41"    "mirana_arrow"
        "42"    "mirana_leap"
        "43"    "mirana_invis"

        // Morphling
        "44"    "morphling_waveform"
        "45"    "morphling_adaptive_strike"
        "46"    "morphling_morph_str||morphling_morph_agi"
        "47"    "morphling_replicate"

        // Phantom Lancer
        "48"    "phantom_lancer_spirit_lance"
        "49"    "phantom_lancer_doppelwalk"
        "50"    "phantom_lancer_juxtapose"
        "51"    "phantom_lancer_phantom_edge"

        // Vengeful Spirit
        "52"    "vengefulspirit_magic_missile"
        "53"    "vengefulspirit_wave_of_terror"
        "54"    "vengefulspirit_command_aura"
        "55"    "vengefulspirit_nether_swap"

        // Crystal Maiden
        "56"    "crystal_maiden_crystal_nova"
        "57"    "crystal_maiden_frostbite"
        "58"    "crystal_maiden_brilliance_aura"
        "59"    "crystal_maiden_freezing_field"

        // Puck
        "60"    "puck_illusory_orb||puck_ethereal_jaunt"
        "61"    "puck_waning_rift"
        "62"    "puck_phase_shift"
        "63"    "puck_dream_coil"

        // Storm Spirit
        "64"    "storm_spirit_static_remnant"
        "65"    "storm_spirit_electric_vortex"
        "66"    "storm_spirit_overload"
        "67"    "storm_spirit_ball_lightning"

        // Windrunner
        "68"    "windrunner_shackleshot"
        "69"    "windrunner_powershot"
        "70"    "windrunner_windrun"
        "71"    "windrunner_focusfire"

        // Zeus
        "72"    "zuus_arc_lightning"
        "73"    "zuus_lightning_bolt"
        "74"    "zuus_static_field"
        "75"    "zuus_thundergods_wrath"

        // Lina
        "76"    "lina_dragon_slave"
        "77"    "lina_light_strike_array"
        "78"    "lina_fiery_soul"
        "79"    "lina_laguna_blade"

        // Shadow Shaman
        "80"    "shadow_shaman_ether_shock"
        "81"    "shadow_shaman_voodoo"
        "82"    "shadow_shaman_shackles"
        "83"    "shadow_shaman_mass_serpent_ward"

        // Omniknight
        "84"    "omniknight_purification"
        "85"    "omniknight_repel"
        "86"    "omniknight_degen_aura"
        "87"    "omniknight_guardian_angel"

        // Huskar
        "88"    "huskar_inner_vitality"
        "89"    "huskar_burning_spear"
        "90"    "huskar_berserkers_blood"
        "91"    "huskar_life_break"

        // Alchemist
        "92"    "alchemist_acid_spray"
        "93"    "alchemist_unstable_concoction"
        "94"    "alchemist_goblins_greed"
        //"95"    "alchemist_chemical_rage"

        // Brewmaster
        "96"    "brewmaster_thunder_clap"
        "97"    "brewmaster_drunken_haze"
        "98"    "brewmaster_drunken_brawler"
        "99"    "brewmaster_primal_split"

        // Treant Protector
        "100"   "treant_natures_guise"
        "101"   "treant_leech_seed"
        "102"   "treant_living_armor"
        "103"   "treant_overgrowth"

        // Wisp
        "104"   "wisp_tether"
        "105"   "wisp_spirits"
        "106"   "wisp_overcharge"
        "107"   "wisp_relocate"

        // Centaur Warchief
        "108"   "centaur_hoof_stomp"
        "109"   "centaur_double_edge"
        "110"   "centaur_return"
        "111"   "centaur_stampede"

        // Riki
        "112"   "riki_smoke_screen"
        "113"   "riki_blink_strike"
        "114"   "riki_backstab"
        //"115"   "riki_permanent_invisibility"

        // Sniper
        "116"   "sniper_shrapnel"
        "117"   "sniper_headshot"
        "118"   "sniper_take_aim"
        "119"   "sniper_assassinate"

        // Templar Assassin
        "120"   "templar_assassin_refraction"
        "121"   "templar_assassin_meld"
        "122"   "templar_assassin_psi_blades"
        "123"   "templar_assassin_psionic_trap||templar_assassin_trap"

        // Luna
        "124"   "luna_lucent_beam"
        "125"   "luna_moon_glaive"
        "126"   "luna_lunar_blessing"
        "127"   "luna_eclipse"

        // Bounty Hunter
        "128"   "bounty_hunter_shuriken_toss"
        "129"   "bounty_hunter_jinada"
        "130"   "bounty_hunter_wind_walk"
        "131"   "bounty_hunter_track"

        // Ursa
        "132"   "ursa_earthshock"
        "133"   "ursa_overpower"
        "134"   "ursa_fury_swipes"
        "135"   "ursa_enrage"

        // Gyrocopter
        "136"   "gyrocopter_rocket_barrage"
        "137"   "gyrocopter_homing_missile"
        "138"   "gyrocopter_flak_cannon"
        "139"   "gyrocopter_call_down"

        // Tinker
        "140"   "tinker_laser"
        "141"   "tinker_heat_seeking_missile"
        "142"   "tinker_march_of_the_machines"
        "143"   "tinker_rearm"

        // Furion
        "144"   "furion_sprout"
        "145"   "furion_teleportation"
        "146"   "furion_force_of_nature"
        "147"   "furion_wrath_of_nature"

        // Enchantress
        "148"   "enchantress_untouchable"
        "149"   "enchantress_enchant"
        "150"   "enchantress_natures_attendants"
        "151"   "enchantress_impetus"

        // Jakiro
        "152"   "jakiro_dual_breath"
        "153"   "jakiro_ice_path"
        "154"   "jakiro_liquid_fire"
        "155"   "jakiro_macropyre"

        // Chen
        "156"   "chen_penitence"
        "157"   "chen_test_of_faith||chen_test_of_faith_teleport"
        "158"   "chen_holy_persuasion"
        "159"   "chen_hand_of_god"

        // Silencer
        "160"   "silencer_curse_of_the_silent"
        "161"   "silencer_glaives_of_wisdom"
        "162"   "silencer_last_word"
        "163"   "silencer_global_silence"

        // Ogre Magi
        "164"   "ogre_magi_fireblast"
        "165"   "ogre_magi_ignite"
        "166"   "ogre_magi_bloodlust"
        "167"   "ogre_magi_multicast_lod"

        // Shredder Timbersaw
        "168"   "shredder_whirling_death"
        "169"   "shredder_timber_chain"
        "170"   "shredder_reactive_armor"
        "171"   "shredder_chakram"

        // Bristleback
        "172"   "bristleback_viscous_nasal_goo"
        "173"   "bristleback_quill_spray"
        "174"   "bristleback_bristleback"
        "175"   "bristleback_warpath"

        // Tusk
        "176"   "tusk_ice_shards"
        "177"   "tusk_snowball"
        "178"   "tusk_frozen_sigil"
        "179"   "tusk_walrus_punch"

        // Elder Titan
        "180"   "elder_titan_echo_stomp"
        "181"   "elder_titan_ancestral_spirit||elder_titan_return_spirit"
        "182"   "elder_titan_natural_order"
        "183"   "elder_titan_earth_splitter"

        // Legion Commander
        "184"   "legion_commander_overwhelming_odds"
        "185"   "legion_commander_press_the_attack"
        "186"   "legion_commander_moment_of_courage"
        "187"   "legion_commander_duel"

        // Earth Spirit
        "188"   "earth_spirit_boulder_smash"
        "189"   "earth_spirit_rolling_boulder"
        "190"   "earth_spirit_geomagnetic_grip"
        "191"   "earth_spirit_magnetize"

        // Phoenix
        "192"   "phoenix_icarus_dive"
        "193"   "phoenix_fire_spirits"
        "194"   "phoenix_sun_ray"
        "195"   "phoenix_supernova"

        // Lone Druid
        "196"   "lone_druid_spirit_bear"
        "197"   "lone_druid_rabid"
        "198"   "lone_druid_synergy"
        //"199"   "lone_druid_true_form"

        // Naga Siren
        "200"   "naga_siren_mirror_image"
        "201"   "naga_siren_ensnare"
        "202"   "naga_siren_rip_tide"
        "203"   "naga_siren_song_of_the_siren"

        // Troll Warlord
        "204"   "troll_warlord_berserkers_rage"
        "205"   "troll_warlord_whirling_axes_ranged"
        "206"   "troll_warlord_fervor"
        "207"   "troll_warlord_battle_trance"

        // Ember Spirit
        "208"   "ember_spirit_searing_chains"
        "209"   "ember_spirit_sleight_of_fist"
        "210"   "ember_spirit_flame_guard"
        //"211"   "ember_spirit_fire_remnant||ember_spirit_activate_fire_remnant"

        // None

        // None

        // None

        // Rubick
        "224"   "rubick_telekinesis"
        "225"   "rubick_fade_bolt"
        "226"   "rubick_null_field"
        "227"   "rubick_spell_steal"

        // Disruptor
        "228"   "disruptor_thunder_strike"
        "229"   "disruptor_glimpse"
        "230"   "disruptor_kinetic_field"
        "231"   "disruptor_static_storm"

        // Keeper of the Light
        "232"   "keeper_of_the_light_illuminate"
        "233"   "keeper_of_the_light_mana_leak"
        "234"   "keeper_of_the_light_chakra_magic"
        "235"   "keeper_of_the_light_spirit_form||keeper_of_the_light_recall_lod||keeper_of_the_light_blinding_light_lod"

        // Skywrath Mage
        "236"   "skywrath_mage_arcane_bolt"
        "237"   "skywrath_mage_concussive_shot"
        "238"   "skywrath_mage_ancient_seal"
        "239"   "skywrath_mage_mystic_flare"

        // Oracle
        "240"   "oracle_fortunes_end"
        "241"   "oracle_fates_edict"
        "242"   "oracle_purifying_flames"
        "243"   "oracle_false_promise"

        // Axe
        "252"   "axe_berserkers_call"
        "253"   "axe_battle_hunger"
        "254"   "axe_counter_helix"
        "255"   "axe_culling_blade"

        // Pudge
        "256"   "pudge_meat_hook"
        "257"   "pudge_rot"
        "258"   "pudge_flesh_heap"
        "259"   "pudge_dismember"

        // Sand King
        "260"   "sandking_burrowstrike"
        "261"   "sandking_sand_storm"
        "262"   "sandking_caustic_finale"
        "263"   "sandking_epicenter"

        // Slardar
        "264"   "slardar_sprint"
        "265"   "slardar_slithereen_crush"
        "266"   "slardar_bash"
        "267"   "slardar_amplify_damage"

        // Tidehunter
        "268"   "tidehunter_gush"
        "269"   "tidehunter_kraken_shell"
        "270"   "tidehunter_anchor_smash"
        "271"   "tidehunter_ravage"

        // Skeleton King or Wraith King
        "272"   "skeleton_king_hellfire_blast"
        "273"   "skeleton_king_vampiric_aura"
        "274"   "skeleton_king_mortal_strike"
        "275"   "skeleton_king_reincarnation"

        // Lifestealer
        "276"   "life_stealer_rage"
        "277"   "life_stealer_feast"
        "278"   "life_stealer_open_wounds"
        "279"   "life_stealer_infest"

        // Bloodseeker
        "280"   "bloodseeker_bloodrage"
        "281"   "bloodseeker_blood_bath"
        "282"   "bloodseeker_thirst"
        "283"   "bloodseeker_rupture"

        // Nevermore
        "285"   "nevermore_necromastery"
        "286"   "nevermore_dark_lord"
        "287"   "nevermore_requiem"

        // Razor
        "288"   "razor_plasma_field"
        "289"   "razor_static_link"
        "290"   "razor_unstable_current"
        "291"   "razor_eye_of_the_storm"

        // Venomancer
        "292"   "venomancer_venomous_gale"
        "293"   "venomancer_poison_sting"
        "294"   "venomancer_plague_ward"
        "295"   "venomancer_poison_nova"

        // Faceless Void
        "296"   "faceless_void_time_walk"
        "297"   "faceless_void_backtrack"
        "298"   "faceless_void_time_lock"
        "299"   "faceless_void_chronosphere"

        // Phantom Assassin
        "300"   "phantom_assassin_stifling_dagger"
        "301"   "phantom_assassin_phantom_strike"
        "302"   "phantom_assassin_blur"
        "303"   "phantom_assassin_coup_de_grace"

        // Viper
        "304"   "viper_poison_attack"
        "305"   "viper_nethertoxin"
        "306"   "viper_corrosive_skin"
        "307"   "viper_viper_strike"

        // Bane
        "308"   "bane_enfeeble"
        "309"   "bane_brain_sap"
        "310"   "bane_nightmare"
        "311"   "bane_fiends_grip"

        // Lich
        "312"   "lich_frost_nova"
        "313"   "lich_frost_armor"
        "314"   "lich_dark_ritual"
        "315"   "lich_chain_frost"

        // Lion
        "316"   "lion_impale"
        "317"   "lion_voodoo"
        "318"   "lion_mana_drain"
        "319"   "lion_finger_of_death"

        // Witch Doctor
        "320"   "witch_doctor_paralyzing_cask"
        "321"   "witch_doctor_voodoo_restoration"
        "322"   "witch_doctor_maledict"
        "323"   "witch_doctor_death_ward"

        // Enigma
        "324"   "enigma_malefice"
        "325"   "enigma_demonic_conversion"
        "326"   "enigma_midnight_pulse"
        "327"   "enigma_black_hole"

        // Necrolyte
        "328"   "necrolyte_death_pulse"
        "329"   "necrolyte_heartstopper_aura"
        "330"   "necrolyte_sadist"
        "331"   "necrolyte_reapers_scythe"

        // Warlock
        "332"   "warlock_fatal_bonds"
        "333"   "warlock_shadow_word"
        "334"   "warlock_upheaval"
        "335"   "warlock_rain_of_chaos"

        // Night Stalker
        "336"   "night_stalker_void"
        "337"   "night_stalker_crippling_fear"
        "338"   "night_stalker_hunter_in_the_night"
        "339"   "night_stalker_darkness"

        // Doom Bringer
        //"340"   "doom_bringer_devour"
        "341"   "doom_bringer_scorched_earth"
        "342"   "doom_bringer_lvl_death"
        "343"   "doom_bringer_doom"

        // Spirit Breaker
        "344"   "spirit_breaker_charge_of_darkness"
        "345"   "spirit_breaker_empowering_haste"
        "346"   "spirit_breaker_greater_bash"
        "347"   "spirit_breaker_nether_strike"

        // Lycan
        "348"   "lycan_summon_wolves"
        "349"   "lycan_howl"
        "350"   "lycan_feral_impulse"
        "351"   "lycan_shapeshift"

        // Chaos Knight
        "352"   "chaos_knight_chaos_bolt"
        "353"   "chaos_knight_reality_rift"
        "354"   "chaos_knight_chaos_strike"
        "355"   "chaos_knight_phantasm"

        // Undying
        "356"   "undying_decay"
        "357"   "undying_soul_rip"
        "358"   "undying_tombstone"
        "359"   "undying_flesh_golem"

        // Magnus
        "360"   "magnataur_shockwave"
        "361"   "magnataur_empower"
        "362"   "magnataur_skewer"
        "363"   "magnataur_reverse_polarity"

        // Clinkz
        "364"   "clinkz_strafe"
        "365"   "clinkz_searing_arrows"
        "366"   "clinkz_wind_walk"
        "367"   "clinkz_death_pact"

        // Broodmother
        "368"   "broodmother_spawn_spiderlings"
        "369"   "broodmother_spin_web"
        "370"   "broodmother_incapacitating_bite"
        "371"   "broodmother_insatiable_hunger"

        // Weaver
        "372"   "weaver_the_swarm"
        "373"   "weaver_shukuchi"
        "374"   "weaver_geminate_attack"
        "375"   "weaver_time_lapse"

        // Spectre
        "376"   "spectre_spectral_dagger"
        "377"   "spectre_desolate"
        "378"   "spectre_dispersion"

        // Meepo
        "380"   "meepo_earthbind"
        "381"   "meepo_poof"
        "382"   "meepo_geostrike"
        "383"   "meepo_divided_we_stand"

        // Nyx Assassin
        "384"   "nyx_assassin_impale"
        "385"   "nyx_assassin_mana_burn"
        "386"   "nyx_assassin_spiked_carapace"
        "387"   "nyx_assassin_vendetta"

        // Slark
        "388"   "slark_dark_pact"
        "389"   "slark_pounce"
        //"390"   "slark_essence_shift"
        "391"   "slark_shadow_dance"

        // Queen of Pain
        "392"   "queenofpain_shadow_strike"
        "393"   "queenofpain_blink"
        "394"   "queenofpain_scream_of_pain"
        "395"   "queenofpain_sonic_wave"

        // Death Prophet
        "396"   "death_prophet_carrion_swarm"
        "397"   "death_prophet_silence"
        "398"   "death_prophet_witchcraft"
        "399"   "death_prophet_exorcism"

        // Pugna
        "400"   "pugna_nether_blast"
        "401"   "pugna_decrepify"
        "402"   "pugna_nether_ward"
        "403"   "pugna_life_drain"

        // Dazzle
        "404"   "dazzle_poison_touch"
        "405"   "dazzle_shallow_grave"
        "406"   "dazzle_shadow_wave"
        "407"   "dazzle_weave"

        // Leshrac
        "408"   "leshrac_split_earth"
        "409"   "leshrac_diabolic_edict"
        "410"   "leshrac_lightning_storm"
        "411"   "leshrac_pulse_nova"

        // Dark Seer
        "412"   "dark_seer_vacuum"
        "413"   "dark_seer_ion_shell"
        "414"   "dark_seer_surge"
        "415"   "dark_seer_wall_of_replica"

        // Batrider
        "416"   "batrider_sticky_napalm"
        "417"   "batrider_flamebreak"
        "418"   "batrider_firefly"
        "419"   "batrider_flaming_lasso"

        // Abaddon
        "420"   "abaddon_death_coil"
        "421"   "abaddon_aphotic_shield"
        "422"   "abaddon_frostmourne"
        "423"   "abaddon_borrowed_time"

        // Abysal Underlord
        "424"   "abyssal_underlord_firestorm"
        "425"   "abyssal_underlord_pit_of_malice"
        "426"   "abyssal_underlord_atrophy_aura"
        "427"   "abyssal_underlord_dark_rift"

        // None x 5

        // Medusa
        "448"   "medusa_split_shot"
        "449"   "medusa_mystic_snake"
        "450"   "medusa_mana_shield"
        "451"   "medusa_stone_gaze"

        // Terrorblade
        "452"   "terrorblade_reflection"
        "453"   "terrorblade_conjure_image"
        "454"   "terrorblade_metamorphosis"
        "455"   "terrorblade_sunder"

        // None x 5

        // Ancient Apparition
        "476"   "ancient_apparition_cold_feet"
        "477"   "ancient_apparition_ice_vortex"
        "478"   "ancient_apparition_chilling_touch"
        "479"   "ancient_apparition_ice_blast"

        // Invoker
        "480"   "invoker_forge_spirit_lod||invoker_sun_strike_lod"
        "481"   "invoker_deafening_blast_lod||invoker_emp_lod"
        "482"   "invoker_chaos_meteor_lod||invoker_alacrity_lod||invoker_ice_wall_lod"
        "483"   "invoker_ghost_walk_lod||invoker_cold_snap_lod||invoker_tornado_lod"

        // Obsidian Destroyer
        "484"   "obsidian_destroyer_arcane_orb"
        "485"   "obsidian_destroyer_astral_imprisonment"
        "486"   "obsidian_destroyer_essence_aura"
        "487"   "obsidian_destroyer_sanity_eclipse"

        // Shadow Demon
        "488"   "shadow_demon_disruption"
        "489"   "shadow_demon_soul_catcher"
        "490"   "shadow_demon_shadow_poison||shadow_demon_shadow_poison_release"
        //"491"   "shadow_demon_demonic_purge"

        // Visage
        "492"   "visage_grave_chill"
        //"493"   "visage_soul_assumption"
        "494"   "visage_gravekeepers_cloak"
        "495"   "visage_summon_familiars"

        // Techies
        "496"   "techies_land_mines"
        "497"   "techies_stasis_trap"
        "498"   "techies_suicide"
        "499"   "techies_remote_mines||techies_focused_detonate"

        ////////////////////
        // Wrath Night Skills Tab
        ////////////////////

        // Sven
        "1007"  "holdout_gods_strength"

        // Drow
        "1033"  "holdout_multishot"

        // Jugernaut
        "1039"  "holdout_omnislash"

        // Zeus
        "1075"  "zuus_thundergods_vengeance"

        // Omni Knight
        //"1087"  "holdout_guardian_angel"

        // Legion Commander
        "1187"   "holdout_gladiators_unite"

        // Axe
        "1255"  "holdout_culling_blade"

        ////////////////////
        // Neutral Skills Tab
        ////////////////////

        // Cast abiltiies
        "2028"  "centaur_khan_war_stomp"
        "2029"  "polar_furbolg_ursa_warrior_thunder_clap"
        "2032"  "dark_troll_warlord_ensnare"
        "2033"  "dark_troll_warlord_raise_dead"
        "2036"  "enraged_wildkin_tornado"
        "2037"  "big_thunder_lizard_slam"
        "2040"  "satyr_trickster_purge"
        "2041"  "satyr_soulstealer_mana_burn"
        "2044"  "big_thunder_lizard_frenzy"
        "2045"  "ogre_magi_frost_armor"
        "2048"  "satyr_hellcaller_shockwave"
        "2049"  "forest_troll_high_priest_heal"
        "2052"  "harpy_storm_chain_lightning"

        // Attack modifiers
        "2196"  "black_dragon_splash_attack"
        "2198"  "ghost_frost_attack"
        "2199"  "lone_druid_spirit_bear_demolish"
        "2202"  "lone_druid_spirit_bear_entangle"

        // Critical strikes
        "2203"  "lycan_summon_wolves_critical_strike"
        "2206"  "giant_wolf_critical_strike"
        "2207"  "alpha_wolf_critical_strike"

        // Evasion
        "2210"  "blue_dragonspawn_sorcerer_evasion"
        "2211"  "blue_dragonspawn_overseer_evasion"

        // Auras
        "2214"  "alpha_wolf_command_aura"
        "2215"  "centaur_khan_endurance_aura"
        "2218"  "enraged_wildkin_toughness_aura"
        "2219"  "satyr_hellcaller_unholy_aura"
        "2221"  "undying_tombstone_zombie_deathstrike"
        "2222"  "blue_dragonspawn_overseer_devotion_aura"
        "2223"  "kobold_taskmaster_speed_aura"

        // Poison
        "2280"  "beastmaster_boar_poison"
        "2281"  "beastmaster_greater_boar_poison"
        "2282"  "gnoll_assassin_envenomed_weapon"

        // Necro Stuff
        //"2301"  "necronomicon_warrior_sight_lod"
        "2304"  "necronomicon_warrior_mana_burn_lod"
        "2305"  "necronomicon_archer_mana_burn_lod"
        "2306"  "necronomicon_archer_aoe_lod"
        "2307"  "necronomicon_warrior_last_will_lod"

        // Courier stuff
        "2292"  "courier_return_to_base"
        "2293"  "courier_go_to_secretshop"
        "2294"  "courier_transfer_items"
        "2295"  "courier_return_stash_items"
        "2376"  "courier_take_stash_items"
        "2377"  "courier_burst"
    }
}