"Bans" {
    // The first key is a spell, the 2nd is all the spells that cant be used with it
    "BannedCombinations" {
        // Sticky Napalm, crazy damage
        "batrider_sticky_napalm" {
            "axe_battle_hunger"                     "1"
            "batrider_flamebreak"                   "1"
            "brewmaster_fire_permanent_immolation"  "1"
            "dark_seer_ion_shell"                   "1"
            "doom_bringer_scorched_earth"           "1"
            "ember_spirit_flame_guard"              "1"
            "gyrocopter_rocket_barrage"             "1"
            "huskar_burning_spear"                  "1"
            "juggernaut_blade_fury"                 "1"
            "pudge_rot"                             "1"
            "shadow_shaman_shackles"                "1"
            "skywrath_mage_mystic_flare"            "1"
            "slark_dark_pact"                       "1"
            "venomancer_poison_sting"               "1"
            "viper_poison_attack"                   "1"
            "warlock_golem_permanent_immolation"    "1"
        }

        // Multishot abuse
        "holdout_multishot" {
            "ember_spirit_sleight_of_fist"  "1"
            "holdout_omnislash"             "1"
            "medusa_split_shot"             "1"
            "life_stealer_feast"            "1" // Cray Cray HP steal!
        }

        // Crashy Combo
        "lone_druid_true_form" {
            "troll_warlord_berserkers_rage" "1"
        }

        // Rearm Abuse
        "tinker_rearm" {
            "ancient_apparition_ice_blast"      "1"
            "dark_seer_wall_of_replica"         "1"
            "faceless_void_chronosphere"        "1"
            "furion_wrath_of_nature"            "1"
            "invoker_sun_strike_lod"            "1"
            "magnataur_reverse_polarity"        "1"
            "necrolyte_reapers_scythe"          "1"
            "phoenix_supernova"                 "1"
            "razor_eye_of_the_storm"            "1"
            "silencer_global_silence"           "1"
            "shadow_shaman_mass_serpent_ward"   "1"
            "skeleton_king_reincarnation"       "1"
            "spectre_haunt"                     "1"
            "tidehunter_ravage"                 "1"
            "treant_overgrowth"                 "1"
            "warlock_rain_of_chaos"             "1"
            "zuus_thundergods_vengeance"        "1"
            "zuus_thundergods_wrath"            "1"
        }

        // Meepo abuse
        "meepo_divided_we_stand" {
            "abaddon_borrowed_time"         "1" // Glitchy
            "alchemist_chemical_rage"       "1"
            "alchemist_chemical_rage_lod"   "1"
            "ancient_apparition_ice_blast"  "1"
            "furion_wrath_of_nature"        "1"
            "gyrocopter_call_down"          "1"
            "invoker_sun_strike_lod"        "1"
            "lone_druid_spirit_bear"        "1" // This one is kind of crashy
            "meepo_divided_we_stand"        "1" // This stops divided we stand being picked twice
            "zuus_thundergods_vengeance"    "1"
            "zuus_thundergods_wrath"        "1"
        }

        // Unlimited rearm
        "phoenix_supernova" {
            "phoenix_supernova" "1"
        }

        // Essence Aura abuse
        "obsidian_destroyer_essence_aura" {
            "courier_go_to_secretshop"          "1"
            "courier_return_stash_items"        "1"
            "courier_return_to_base"            "1"
            "courier_take_stash_items"          "1"
            "courier_transfer_items"            "1"
            "forest_troll_high_priest_heal"     "1"
            "furion_teleportation"              "1"
            "harpy_storm_chain_lightning"       "1"
            "holdout_multishot"                 "1"
            "leshrac_pulse_nova"                "1"
            "medusa_mana_shield"                "1"
            "medusa_split_shot"                 "1"
            "meepo_poof"                        "1"
            "morphling_morph_agi"               "1"
            "morphling_morph_str"               "1"
            "pudge_rot"                         "1"
            "riki_blink_strike"                 "1"
            "shredder_chakram"                  "1"
            "storm_spirit_ball_lightning"       "1"
            "techies_focused_detonate"          "1"
            "troll_warlord_berserkers_rage"     "1"
            "wisp_overcharge"                   "1"
            "witch_doctor_voodoo_restoration"   "1"
            "life_stealer_consume"              "1"
        }
    }

    // List of spells that use banned Categories
    "CategoryBans" {
        "bristleback_warpath"               "ToggleSpells"
        "earthshaker_aftershock"            "SpammableSpells"
        "lina_fiery_soul"                   "ToggleSpells"
        "storm_spirit_overload"             "ToggleSpells"
        "zuus_static_field"                 "SpammableSpells"
    }

    // List of categories to use with the categories bans
    "Categories" {
        // List of spells that can be spammed easily
        "SpammableSpells" {
            "abaddon_aphotic_shield"            "1"
            "abaddon_death_coil"                "1"
            "alchemist_unstable_concoction"     "1"
            "ancient_apparition_ice_vortex"     "1"
            "antimage_blink"                    "1"
            "axe_battle_hunger"                 "1"
            "bane_nightmare"                    "1"
            "batrider_sticky_napalm"            "1"
            "bloodseeker_blood_rage"            "1"
            "bounty_hunter_track"               "1"
            "bristleback_quill_spray"           "1"
            "bristleback_viscous_nasal_goo"     "1"
            "chaos_knight_reality_rift"         "1"
            "courier_burst"                     "1"
            "courier_go_to_secretshop"          "1"
            "courier_return_stash_items"        "1"
            "courier_return_to_base"            "1"
            "courier_take_stash_items"          "1"
            "courier_transfer_items"            "1"
            "dazzle_shadow_wave"                "1"
            "doom_bringer_devour"               "1"
            "earthshaker_enchant_totem"         "1"
            "elder_titan_ancestral_spirit"      "1"
            "forest_troll_high_priest_heal"     "1"
            "furion_teleportation"              "1"
            "gyrocopter_rocket_barrage"         "1"
            "harpy_storm_chain_lightning"       "1"
            "holdout_multishot"                 "1"
            "leshrac_lightning_storm"           "1"
            "leshrac_pulse_nova"                "1"
            "lich_ice_armor"                    "1"
            "lion_mana_drain"                   "1"
            "luna_lucent_beam"                  "1"
            "medusa_mana_shield"                "1"
            "medusa_split_shot"                 "1"
            "meepo_poof"                        "1"
            "morphling_morph_agi"               "1"
            "morphling_morph_str"               "1"
            "necrolyte_death_pulse"             "1"
            "obsidian_destroyer_arcane_orb"     "1"
            "phantom_assassin_phantom_strike"   "1"
            "puck_phase_shift"                  "1"
            "pudge_rot"                         "1"
            "pugna_nether_blast"                "1"
            "queen_of_pain_blink"               "1"
            "riki_blink_strike"                 "1"
            "rubick_telekinesis"                "1"
            "shadow_demon_shadow_poison"        "1"
            "shredder_chakram"                  "1"
            "shredder_timber_chain"             "1"
            "skywrath_mage_arcane_bolt"         "1"
            "slark_dark_pact"                   "1"
            "storm_spirit_ball_lightning"       "1"
            "storm_spirit_static_remnant"       "1"
            "techies_focused_detonate"          "1"
            "templar_assassin_meld"             "1"
            "tidehunter_anchor_smash"           "1"
            "tinker_rearm"                      "1"
            "treant_natures_guise"              "1"
            "troll_warlord_berserkers_rage"     "1"
            "undying_decay"                     "1"
            "venomancer_plague_ward"            "1"
            "weaver_shukuchi"                   "1"
            "wisp_overcharge"                   "1"
            "witch_doctor_voodoo_restoration"   "1"
            "zuus_arc_lightning"                "1"
            "zuus_lightning_bolt"               "1"
            "life_stealer_consume"              "1"
        }

        // Toggle spells
        "ToggleSpells" {
            "courier_go_to_secretshop"          "1"
            "courier_return_stash_items"        "1"
            "courier_return_to_base"            "1"
            "courier_take_stash_items"          "1"
            "courier_transfer_items"            "1"
            "forest_troll_high_priest_heal"     "1"
            "furion_teleportation"              "1"
            "harpy_storm_chain_lightning"       "1"
            "holdout_multishot"                 "1"
            "leshrac_pulse_nova"                "1"
            "medusa_mana_shield"                "1"
            "medusa_split_shot"                 "1"
            "meepo_poof"                        "1"
            "morphling_morph_agi"               "1"
            "morphling_morph_str"               "1"
            "obsidian_destroyer_arcane_orb"     "1"
            "pudge_rot"                         "1"
            "riki_blink_strike"                 "1"
            "shredder_chakram"                  "1"
            "storm_spirit_ball_lightning"       "1"
            "techies_focused_detonate"          "1"
            "troll_warlord_berserkers_rage"     "1"
            "wisp_overcharge"                   "1"
            "witch_doctor_voodoo_restoration"   "1"
            "life_stealer_consume"              "1"
        }
    }

    // These are groups of spells where none of these can be used together
    "BannedGroups" {
        // The one hit combo group
        "1" {
            "bounty_hunter_jinada"              "1"
            "brewmaster_drunken_brawler"        "1"
            "earthshaker_enchant_totem"         "1"
            "kunkka_tidebringer"                "1"
            "tiny_grow"                         "1"
            "tusk_walrus_punch"                 "1"
            "weaver_geminate_attack"            "1"
            "terrorblade_metamorphosis"         "1"
            "clinkz_death_pact"                 "1"
            "tiny_grow_lod"                     "1"
        }

        // The mega range group
        "2" {
            "dragon_knight_elder_dragon_form"   "1"
            "sniper_take_aim"                   "1"
            "templar_assassin_psi_blades"       "1"
            "terrorblade_metamorphosis"         "1"
        }
    }

    // Stop multicast on these spells
    "noMulticast" {
        "enraged_wildkin_tornado"       "1"
        "invoker_cold_snap_lod"         "1"
        "item_ancient_janggo"           "1"
        "item_black_king_bar"           "1"
        "item_courier"                  "1"
        "item_diffusal_blade"           "1"
        "item_diffusal_blade_2"         "1"
        "item_power_treads"             "1"
        "item_slippers_of_halcyon"      "1"
        "item_tpscroll"                 "1"
        "item_travel_boots"             "1"
        "item_urn_of_shadows"           "1"
        "lich_dark_ritual"              "1"
        "phoenix_sun_ray"               "1"
        "shredder_chakram"              "1"
        "shredder_timber_chain"         "1"
        "witch_doctor_death_ward"       "1"
    }

    // Stop tower from getting these abilities
    "noTower" {
        "pudge_flesh_heap"              "1"
    }
}