"Bans" {
    "BannedCombinations" {
        // Enchant Totem, Jinada, Walrus, Tidebringer, Geminate Attack
        "1" {
            "1" "earthshaker_enchant_totem"
            "2" "bounty_hunter_jinada"
        }

        "2" {
            "1" "earthshaker_enchant_totem"
            "2" "kunkka_tidebringer"
        }

        "3" {
            "1" "bounty_hunter_jinada"
            "2" "kunkka_tidebringer"
        }

        "4" {
            "1" "earthshaker_enchant_totem"
            "2" "tusk_walrus_punch"
        }

        "5" {
            "1" "kunkka_tidebringer"
            "2" "tusk_walrus_punch"
        }

        "6" {
            "1" "earthshaker_enchant_totem"
            "2" "weaver_geminate_attack"
        }

        "7" {
            "1" "chaos_knight_reality_rift"
            "2" "weaver_geminate_attack"
        }

        "8" {
            "1" "tiny_grow"
            "2" "weaver_geminate_attack"
        }

        "9" {
            "1" "tiny_grow"
            "2" "earthshaker_enchant_totem"
        }

        "10" {
            "1" "tiny_grow"
            "2" "bounty_hunter_jinada"
        }

        // Sticky Napalm, Ion Shell, Rot, Blade Fury
        "11" {
            "1" "batrider_sticky_napalm"
            "2" "dark_seer_ion_shell"
        }

        "12" {
            "1" "batrider_sticky_napalm"
            "2" "pudge_rot"
        }

        "13" {
            "1" "batrider_sticky_napalm"
            "2" "juggernaut_blade_fury"
        }

        "14" {
            "1" "batrider_sticky_napalm"
            "2" "huskar_burning_spear"
        }

        "15" {
            "1" "batrider_sticky_napalm"
            "2" "venomancer_poison_sting"
        }

        "16" {
            "1" "batrider_sticky_napalm"
            "2" "axe_battle_hunger"
        }

        "17" {
            "1" "batrider_sticky_napalm"
            "2" "viper_poison_attack"
        }

        "18" {
            "1" "batrider_sticky_napalm"
            "2" "gyrocopter_rocket_barrage"
        }

        "19" {
            "1" "batrider_sticky_napalm"
            "2" "slark_dark_pact"
        }

        "20" {
            "1" "batrider_sticky_napalm"
            "2" "shadow_shaman_shackles"
        }

        "21" {
            "1" "batrider_sticky_napalm"
            "2" "skywrath_mage_mystic_flare"
        }

        "22" {
            "1" "batrider_sticky_napalm"
            "2" "batrider_flamebreak"
        }

        "23" {
            "1" "batrider_sticky_napalm"
            "2" "warlock_golem_permanent_immolation"
        }

        "24" {
            "1" "batrider_sticky_napalm"
            "2" "brewmaster_fire_permanent_immolation"
        }

        "25" {
            "1" "batrider_sticky_napalm"
            "2" "doom_bringer_scorched_earth"
        }

        // Passive-Active Combos
        "26" {
            "1" "lina_fiery_soul"
            "2" "abaddon_death_coil"
        }

        "27" {
            "1" "lina_fiery_soul"
            "2" "alchemist_unstable_concoction"
        }

        "28" {
            "1" "lina_fiery_soul"
            "2" "abaddon_aphotic_shield"
        }

        "29" {
            "1" "lina_fiery_soul"
            "2" "ancient_apparition_ice_vortex"
        }

        "30" {
            "1" "lina_fiery_soul"
            "2" "antimage_blink"
        }

        "31" {
            "1" "lina_fiery_soul"
            "2" "axe_battle_hunger"
        }

        "32" {
            "1" "lina_fiery_soul"
            "2" "bane_nightmare"
        }

        "33" {
            "1" "lina_fiery_soul"
            "2" "batrider_sticky_napalm"
        }

        "34" {
            "1" "lina_fiery_soul"
            "2" "bloodseeker_blood_rage"
        }

        "35" {
            "1" "lina_fiery_soul"
            "2" "bounty_hunter_track"
        }

        "36" {
            "1" "lina_fiery_soul"
            "2" "bristleback_quill_spray"
        }

        "37" {
            "1" "lina_fiery_soul"
            "2" "bristleback_viscous_nasal_goo"
        }

        "38" {
            "1" "lina_fiery_soul"
            "2" "chaos_knight_reality_rift"
        }

        "39" {
            "1" "lina_fiery_soul"
            "2" "dazzle_shadow_wave"
        }

        "40" {
            "1" "lina_fiery_soul"
            "2" "doom_bringer_devour"
        }

        "41" {
            "1" "lina_fiery_soul"
            "2" "earthshaker_enchant_totem"
        }

        "42" {
            "1" "lina_fiery_soul"
            "2" "elder_titan_ancestral_spirit"
        }

        "43" {
            "1" "lina_fiery_soul"
            "2" "gyrocopter_rocket_barrage"
        }

        "44" {
            "1" "lina_fiery_soul"
            "2" "leshrac_pulse_nova"
        }

        "45" {
            "1" "lina_fiery_soul"
            "2" "leshrac_lightning_storm"
        }

        "46" {
            "1" "lina_fiery_soul"
            "2" "lich_ice_armor"
        }

        "47" {
            "1" "lina_fiery_soul"
            "2" "lion_mana_drain"
        }

        "48" {
            "1" "lina_fiery_soul"
            "2" "luna_lucent_beam"
        }

        "49" {
            "1" "lina_fiery_soul"
            "2" "medusa_mana_shield"
        }

        "50" {
            "1" "lina_fiery_soul"
            "2" "medusa_split_shot"
        }

        "51" {
            "1" "lina_fiery_soul"
            "2" "meepo_poof"
        }

        "52" {
            "1" "lina_fiery_soul"
            "2" "morphling_morph_agi"
        }

        "53" {
            "1" "lina_fiery_soul"
            "2" "morphling_morph_str"
        }

        "54" {
            "1" "lina_fiery_soul"
            "2" "necrolyte_death_pulse"
        }

        "55" {
            "1" "lina_fiery_soul"
            "2" "obsidian_destroyer_arcane_orb"
        }

        "56" {
            "1" "lina_fiery_soul"
            "2" "phantom_assassin_phantom_strike"
        }

        "57" {
            "1" "lina_fiery_soul"
            "2" "puck_phase_shift"
        }

        "58" {
            "1" "lina_fiery_soul"
            "2" "queen_of_pain_blink"
        }

        "59" {
            "1" "lina_fiery_soul"
            "2" "pudge_rot"
        }

        "60" {
            "1" "lina_fiery_soul"
            "2" "pugna_nether_blast"
        }

        "61" {
            "1" "lina_fiery_soul"
            "2" "riki_blink_strike"
        }

        "62" {
            "1" "lina_fiery_soul"
            "2" "rubick_telekinesis"
        }

        "63" {
            "1" "lina_fiery_soul"
            "2" "shadow_demon_shadow_poison"
        }

        "64" {
            "1" "lina_fiery_soul"
            "2" "shredder_chakram"
        }

        "65" {
            "1" "lina_fiery_soul"
            "2" "shredder_timber_chain"
        }

        "66" {
            "1" "lina_fiery_soul"
            "2" "skywrath_mage_arcane_bolt"
        }

        "67" {
            "1" "lina_fiery_soul"
            "2" "slark_dark_pact"
        }

        "68" {
            "1" "lina_fiery_soul"
            "2" "storm_spirit_ball_lightning"
        }

        "69" {
            "1" "lina_fiery_soul"
            "2" "storm_spirit_static_remnant"
        }

        "70" {
            "1" "lina_fiery_soul"
            "2" "templar_assassin_meld"
        }

        "71" {
            "1" "lina_fiery_soul"
            "2" "tidehunter_anchor_smash"
        }

        "72" {
            "1" "lina_fiery_soul"
            "2" "treant_natures_guise"
        }

        "73" {
            "1" "lina_fiery_soul"
            "2" "tinker_rearm"
        }

        "74" {
            "1" "lina_fiery_soul"
            "2" "troll_warlord_berserkers_rage"
        }

        "75" {
            "1" "lina_fiery_soul"
            "2" "undying_decay"
        }

        "76" {
            "1" "lina_fiery_soul"
            "2" "venomancer_plague_ward"
        }

        "77" {
            "1" "lina_fiery_soul"
            "2" "weaver_shukuchi"
        }

        "78" {
            "1" "lina_fiery_soul"
            "2" "wisp_overcharge"
        }

        "79" {
            "1" "lina_fiery_soul"
            "2" "witch_doctor_voodoo_restoration"
        }

        "80" {
            "1" "lina_fiery_soul"
            "2" "zuus_arc_lightning"
        }

        "81" {
            "1" "lina_fiery_soul"
            "2" "zuus_lightning_bolt"
        }

        "82" {
            "1" "lina_fiery_soul"
            "2" "forest_troll_high_priest_heal"
        }

        "83" {
            "1" "lina_fiery_soul"
            "2" "courier_return_to_base"
        }

        "84" {
            "1" "lina_fiery_soul"
            "2" "courier_go_to_secretshop"
        }

        "85" {
            "1" "lina_fiery_soul"
            "2" "courier_transfer_items"
        }

        "86" {
            "1" "lina_fiery_soul"
            "2" "courier_return_stash_items"
        }

        "87" {
            "1" "lina_fiery_soul"
            "2" "courier_take_stash_items"
        }

        "88" {
            "1" "lina_fiery_soul"
            "2" "courier_burst"
        }

        "89" {
            "1" "lina_fiery_soul"
            "2" "furion_teleportation"
        }

        "90" {
            "1" "lina_fiery_soul"
            "2" "shredder_chakram"
        }

        "91" {
            "1" "earthshaker_aftershock"
            "2" "alchemist_unstable_concoction"
        }

        "92" {
            "1" "earthshaker_aftershock"
            "2" "bane_nightmare"
        }

        "93" {
            "1" "earthshaker_aftershock"
            "2" "batrider_sticky_napalm"
        }

        "94" {
            "1" "earthshaker_aftershock"
            "2" "bristleback_quill_spray"
        }

        "95" {
            "1" "earthshaker_aftershock"
            "2" "bristleback_viscous_nasal_goo"
        }

        "96" {
            "1" "earthshaker_aftershock"
            "2" "doom_bringer_devour"
        }

        "97" {
            "1" "earthshaker_aftershock"
            "2" "elder_titan_ancestral_spirit"
        }

        "98" {
            "1" "earthshaker_aftershock"
            "2" "leshrac_pulse_nova"
        }

        "99" {
            "1" "earthshaker_aftershock"
            "2" "lone_druid_true_form"
        }

        "100" {
            "1" "earthshaker_aftershock"
            "2" "medusa_mana_shield"
        }

        "101" {
            "1" "earthshaker_aftershock"
            "2" "medusa_split_shot"
        }

        "102" {
            "1" "earthshaker_aftershock"
            "2" "morphling_morph_agi"
        }

        "103" {
            "1" "earthshaker_aftershock"
            "2" "morphling_morph_str"
        }

        "104" {
            "1" "earthshaker_aftershock"
            "2" "obsidian_destroyer_arcane_orb"
        }

        "105" {
            "1" "earthshaker_aftershock"
            "2" "pudge_rot"
        }

        "106" {
            "1" "earthshaker_aftershock"
            "2" "pugna_life_drain"
        }

        "107" {
            "1" "earthshaker_aftershock"
            "2" "rubick_telekinesis"
        }

        "108" {
            "1" "earthshaker_aftershock"
            "2" "shadow_demon_shadow_poison"
        }

        "109" {
            "1" "earthshaker_aftershock"
            "2" "shredder_chakram"
        }

        "110" {
            "1" "earthshaker_aftershock"
            "2" "shredder_timber_chain"
        }

        "111" {
            "1" "earthshaker_aftershock"
            "2" "skywrath_mage_arcane_bolt"
        }

        "112" {
            "1" "earthshaker_aftershock"
            "2" "storm_spirit_ball_lightning"
        }

        "113" {
            "1" "earthshaker_aftershock"
            "2" "storm_spirit_static_remnant"
        }

        "114" {
            "1" "earthshaker_aftershock"
            "2" "tidehunter_anchor_smash"
        }

        115 {
            "1" "earthshaker_aftershock"
            "2" "treant_natures_guise"
        }

        "116" {
            "1" "earthshaker_aftershock"
            "2" "tinker_rearm"
        }

        "117" {
            "1" "earthshaker_aftershock"
            "2" "troll_warlord_berserkers_rage"
        }

        "118" {
            "1" "earthshaker_aftershock"
            "2" "undying_decay"
        }

        "119" {
            "1" "earthshaker_aftershock"
            "2" "wisp_overcharge"
        }

        "120" {
            "1" "earthshaker_aftershock"
            "2" "witch_doctor_voodoo_restoration"
        }

        "121" {
            "1" "earthshaker_aftershock"
            "2" "zuus_arc_lightning"
        }

        "122" {
            "1" "earthshaker_aftershock"
            "2" "forest_troll_high_priest_heal"
        }

        "91" {
            "1" "earthshaker_aftershock"
            "2" "courier_return_to_base"
        }

        "123" {
            "1" "earthshaker_aftershock"
            "2" "courier_go_to_secretshop"
        }

        "124" {
            "1" "earthshaker_aftershock"
            "2" "courier_transfer_items"
        }

        "125" {
            "1" "earthshaker_aftershock"
            "2" "courier_return_stash_items"
        }

        "126" {
            "1" "earthshaker_aftershock"
            "2" "courier_take_stash_items"
        }

        "127" {
            "1" "earthshaker_aftershock"
            "2" "courier_burst"
        }

        "128" {
            "1" "earthshaker_aftershock"
            "2" "furion_teleportation"
        }

        "129" {
            "1" "earthshaker_aftershock"
            "2" "shredder_chakram"
        }

        // Toggles
        "130" {
            "1" "obsidian_destroyer_essence_aura"
            "2" "alchemist_unstable_concoction"
        }

        "131" {
            "1" "obsidian_destroyer_essence_aura"
            "2" "bane_nightmare"
        }

        "132" {
            "1" "obsidian_destroyer_essence_aura"
            "2" "doom_bringer_devour"
        }

        "133" {
            "1" "obsidian_destroyer_essence_aura"
            "2" "elder_titan_ancestral_spirit"
        }

        "134" {
            "1" "obsidian_destroyer_essence_aura"
            "2" "leshrac_pulse_nova"
        }

        "135" {
            "1" "obsidian_destroyer_essence_aura"
            "2" "medusa_mana_shield"
        }

        "136" {
            "1" "obsidian_destroyer_essence_aura"
            "2" "medusa_split_shot"
        }

        "137" {
            "1" "obsidian_destroyer_essence_aura"
            "2" "morphling_morph_agi"
        }

        "138" {
            "1" "obsidian_destroyer_essence_aura"
            "2" "morphling_morph_str"
        }

        "139" {
            "1" "obsidian_destroyer_essence_aura"
            "2" "pudge_rot"
        }

        "140" {
            "1" "obsidian_destroyer_essence_aura"
            "2" "rubick_telekinesis"
        }

        "141" {
            "1" "obsidian_destroyer_essence_aura"
            "2" "storm_spirit_ball_lightning"
        }

        "142" {
            "1" "obsidian_destroyer_essence_aura"
            "2" "troll_warlord_berserkers_rage"
        }

        "143" {
            "1" "obsidian_destroyer_essence_aura"
            "2" "wisp_overcharge"
        }

        "144" {
            "1" "obsidian_destroyer_essence_aura"
            "2" "witch_doctor_voodoo_restoration"
        }

        "145" {
            "1" "obsidian_destroyer_essence_aura"
            "2" "forest_troll_high_priest_heal"
        }

        "146" {
            "1" "obsidian_destroyer_essence_aura"
            "2" "courier_return_to_base"
        }

        "147" {
            "1" "obsidian_destroyer_essence_aura"
            "2" "courier_go_to_secretshop"
        }

        "148" {
            "1" "obsidian_destroyer_essence_aura"
            "2" "courier_transfer_items"
        }

        "149" {
            "1" "obsidian_destroyer_essence_aura"
            "2" "courier_return_stash_items"
        }

        "150" {
            "1" "obsidian_destroyer_essence_aura"
            "2" "courier_take_stash_items"
        }

        "151" {
            "1" "obsidian_destroyer_essence_aura"
            "2" "courier_burst"
        }

        "152" {
            "1" "obsidian_destroyer_essence_aura"
            "2" "furion_teleportation"
        }

        "153" {
            "1" "obsidian_destroyer_essence_aura"
            "2" "shredder_chakram"
        }

        "154" {
            "1" "obsidian_destroyer_essence_aura"
            "2" "tinker_rearm"
        }

        "155" {
            "1" "storm_spirit_overload"
            "2" "alchemist_unstable_concoction"
        }

        "156" {
            "1" "storm_spirit_overload"
            "2" "bane_nightmare"
        }

        "157" {
            "1" "storm_spirit_overload"
            "2" "doom_bringer_devour"
        }

        "158" {
            "1" "storm_spirit_overload"
            "2" "elder_titan_ancestral_spirit"
        }

        "159" {
            "1" "storm_spirit_overload"
            "2" "medusa_split_shot"
        }

        "160" {
            "1" "storm_spirit_overload"
            "2" "medusa_mana_shield"
        }

        "161" {
            "1" "storm_spirit_overload"
            "2" "morphling_morph_agi"
        }

        "162" {
            "1" "storm_spirit_overload"
            "2" "morphling_morph_str"
        }

        "163" {
            "1" "storm_spirit_overload"
            "2" "obsidian_destroyer_arcane_orb"
        }

        "164" {
            "1" "storm_spirit_overload"
            "2" "pudge_rot"
        }

        "165" {
            "1" "storm_spirit_overload"
            "2" "rubick_telekinesis"
        }

        "166" {
            "1" "storm_spirit_overload"
            "2" "troll_warlord_berserkers_rage"
        }

        "167" {
            "1" "storm_spirit_overload"
            "2" "wisp_overcharge"
        }

        "168" {
            "1" "storm_spirit_overload"
            "2" "witch_doctor_voodoo_restoration"
        }

        "169" {
            "1" "storm_spirit_overload"
            "2" "forest_troll_high_priest_heal"
        }

        "170" {
            "1" "storm_spirit_overload"
            "2" "courier_return_to_base"
        }

        "171" {
            "1" "storm_spirit_overload"
            "2" "courier_go_to_secretshop"
        }

        "172" {
            "1" "storm_spirit_overload"
            "2" "courier_transfer_items"
        }

        "173" {
            "1" "storm_spirit_overload"
            "2" "courier_return_stash_items"
        }

        "174" {
            "1" "storm_spirit_overload"
            "2" "courier_take_stash_items"
        }

        "175" {
            "1" "storm_spirit_overload"
            "2" "courier_burst"
        }

        "176" {
            "1" "storm_spirit_overload"
            "2" "furion_teleportation"
        }

        "177" {
            "1" "storm_spirit_overload"
            "2" "shredder_chakram"
        }

        "178" {
            "1" "storm_spirit_overload"
            "2" "tinker_rearm"
        }

        "179" {
            "1" "zuus_static_field"
            "2" "alchemist_unstable_concoction"
        }

        "180" {
            "1" "zuus_static_field"
            "2" "bane_nightmare"
        }

        "181" {
            "1" "zuus_static_field"
            "2" "doom_bringer_devour"
        }

        "182" {
            "1" "zuus_static_field"
            "2" "elder_titan_ancestral_spirit"
        }

        "183" {
            "1" "zuus_static_field"
            "2" "medusa_mana_shield"
        }

        "184" {
            "1" "zuus_static_field"
            "2" "medusa_split_shot"
        }

        "185" {
            "1" "zuus_static_field"
            "2" "morphling_morph_agi"
        }

        "186" {
            "1" "zuus_static_field"
            "2" "morphling_morph_str"
        }

        "187" {
            "1" "zuus_static_field"
            "2" "obsidian_destroyer_arcane_orb"
        }

        "188" {
            "1" "zuus_static_field"
            "2" "pudge_rot"
        }

        "189" {
            "1" "zuus_static_field"
            "2" "rubick_telekinesis"
        }

        "190" {
            "1" "zuus_static_field"
            "2" "troll_warlord_berserkers_rage"
        }

        "191" {
            "1" "zuus_static_field"
            "2" "wisp_overcharge"
        }

        "192" {
            "1" "zuus_static_field"
            "2" "witch_doctor_voodoo_restoration"
        }

        "193" {
            "1" "zuus_static_field"
            "2" "forest_troll_high_priest_heal"
        }

        "194" {
            "1" "zuus_static_field"
            "2" "courier_return_to_base"
        }

        "195" {
            "1" "zuus_static_field"
            "2" "courier_go_to_secretshop"
        }

        "196" {
            "1" "zuus_static_field"
            "2" "courier_transfer_items"
        }

        "197" {
            "1" "zuus_static_field"
            "2" "courier_return_stash_items"
        }

        "198" {
            "1" "zuus_static_field"
            "2" "courier_take_stash_items"
        }

        "199" {
            "1" "zuus_static_field"
            "2" "courier_burst"
        }

        "200" {
            "1" "zuus_static_field"
            "2" "furion_teleportation"
        }

        "201" {
            "1" "zuus_static_field"
            "2" "shredder_chakram"
        }

        "202" {
            "1" "zuus_static_field"
            "2" "tinker_rearm"
        }

        "203" {
            "1" "bristleback_warpath"
            "2" "elder_titan_ancestral_spirit"
        }

        "204" {
            "1" "bristleback_warpath"
            "2" "leshrac_pulse_nova"
        }

        "205" {
            "1" "bristleback_warpath"
            "2" "medusa_mana_shield"
        }

        "206" {
            "1" "bristleback_warpath"
            "2" "medusa_split_shot"
        }

        "207" {
            "1" "bristleback_warpath"
            "2" "morphling_morph_agi"
        }

        "208" {
            "1" "bristleback_warpath"
            "2" "morphling_morph_str"
        }

        "209" {
            "1" "bristleback_warpath"
            "2" "pudge_rot"
        }

        "210" {
            "1" "bristleback_warpath"
            "2" "troll_warlord_berserkers_rage"
        }

        "211" {
            "1" "bristleback_warpath"
            "2" "courier_return_to_base"
        }

        "212" {
            "1" "bristleback_warpath"
            "2" "courier_go_to_secretshop"
        }

        "213" {
            "1" "bristleback_warpath"
            "2" "courier_transfer_items"
        }

        "214" {
            "1" "bristleback_warpath"
            "2" "courier_return_stash_items"
        }

        "215" {
            "1" "bristleback_warpath"
            "2" "courier_take_stash_items"
        }

        "216" {
            "1" "bristleback_warpath"
            "2" "furion_teleportation"
        }

        "217" {
            "1" "bristleback_warpath"
            "2" "shredder_chakram"
        }

        "218" {
            "1" "bristleback_warpath"
            "2" "tinker_rearm"
        }

        // Misc
        "219" {
            "1" "lone_druid_true_form"
            "2" "troll_warlord_berserkers_rage"
        }

        // Rearm Abuse
        "220" {
            "1" "tinker_rearm"
            "2" "zuus_thundergods_wrath"
        }

        "221" {
            "1" "tinker_rearm"
            "2" "furion_wrath_of_nature"
        }

        "222" {
            "1" "tinker_rearm"
            "2" "skeleton_king_reincarnation"
        }

        "223" {
            "1" "tinker_rearm"
            "2" "silencer_global_silence"
        }

        "224" {
            "1" "tinker_rearm"
            "2" "treant_overgrowth"
        }

        "225" {
            "1" "tinker_rearm"
            "2" "dark_seer_wall_of_replica"
        }

        "226" {
            "1" "tinker_rearm"
            "2" "necrolyte_reapers_scythe"
        }

        "227" {
            "1" "tinker_rearm"
            "2" "razor_eye_of_the_storm"
        }

        "228" {
            "1" "tinker_rearm"
            "2" "tidehunter_ravage"
        }

        "229" {
            "1" "tinker_rearm"
            "2" "warlock_rain_of_chaos"
        }

        "230" {
            "1" "tinker_rearm"
            "2" "magnataur_reverse_polarity"
        }

        "231" {
            "1" "tinker_rearm"
            "2" "ancient_apparition_ice_blast"
        }

        "232" {
            "1" "tinker_rearm"
            "2" "faceless_void_chronosphere"
        }

        "233" {
            "1" "tinker_rearm"
            "2" "invoker_sun_strike_lod"
        }

        // More Napalm abuse
        "234" {
            "1" "ember_spirit_flame_guard"
            "2" "batrider_sticky_napalm"
        }

        // Draw Multishot abuse
        "235" {
            "1" "lina_fiery_soul"
            "2" "holdout_multishot"
        }

        "236" {
            "1" "holdout_multishot"
            "2" "obsidian_destroyer_essence_aura"
        }

        "237" {
            "1" "holdout_multishot"
            "2" "bristleback_warpath"
        }

        "238" {
            "1" "holdout_multishot"
            "2" "earthshaker_aftershock"
        }

        "239" {
            "1" "holdout_multishot"
            "2" "storm_spirit_overload"
        }

        "240" {
            "1" "holdout_multishot"
            "2" "zuus_static_field"
        }

        // More rearm abuse
        "241" {
            "1" "phoenix_supernova"
            "2" "tinker_rearm"
        }

        // WTF Particle effect
        "242" {
            "1" "techies_focused_detonate"
            "2" "earthshaker_aftershock"
        }

        // Crazy drow combo
        "243" {
            "1" "holdout_multishot"
            "2" "ember_spirit_sleight_of_fist"
        }

        "244" {
            "1" "holdout_multishot"
            "2" "holdout_omnislash"
        }

        // Meepo abuse
        "245" {
            "1" "meepo_divided_we_stand"
            "2" "zuus_thundergods_vengeance"
        }

        "246" {
            "1" "meepo_divided_we_stand"
            "2" "zuus_thundergods_wrath"
        }

        "247" {
            "1" "meepo_divided_we_stand"
            "2" "furion_wrath_of_nature"
        }

        "248" {
            "1" "meepo_divided_we_stand"
            "2" "invoker_sun_strike_lod"
        }

        "249" {
            "1" "meepo_divided_we_stand"
            "2" "ancient_apparition_ice_blast"
        }

        "250" {
            "1" "techies_focused_detonate"
            "2" "lina_fiery_soul"
        }

        "251" {
            "1" "meepo_divided_we_stand"
            "2" "meepo_divided_we_stand"
        }

        "252" {
            "1" "techies_focused_detonate"
            "2" "bristleback_warpath"
        }

        // This one is kind of crashy
        "253" {
            "1" "lone_druid_spirit_bear"
            "2" "meepo_divided_we_stand"
        }

        "254" {
            "1" "harpy_storm_chain_lightning"
            "2" "earthshaker_aftershock"
        }

        "255" {
            "1" "harpy_storm_chain_lightning"
            "2" "lina_fiery_soul"
        }

        "256" {
            "1" "harpy_storm_chain_lightning"
            "2" "obsidian_destroyer_essence_aura"
        }

        // Stop chemical rage BS
        "257" {
            "1" "alchemist_chemical_rage_lod"
            "2" "tinker_rearm"
        }

        "258" {
            "1" "alchemist_chemical_rage_lod"
            "2" "phoenix_supernova"
        }

        // Leaving stuff on the map
        "259" {
            "1" "techies_focused_detonate"
            "2" "obsidian_destroyer_essence_aura"
        }

        "260" {
            "1" "techies_focused_detonate"
            "2" "zuus_static_field"
        }

        // Unlimited rearm
        "261" {
            "1" "phoenix_supernova"
            "2" "phoenix_supernova"
        }

        // Glitchy
        "262" {
            "1" "meepo_divided_we_stand"
            "2" "abaddon_borrowed_time"
        }
    }

    // Stop multicast on these spells
    "noMulticast" {
        "item_tpscroll"                 "1"
        "item_travel_boots"             "1"
        "item_power_treads"             "1"
        "item_courier"                  "1"
        "item_ancient_janggo"           "1"
        "item_black_king_bar"           "1"
        "item_urn_of_shadows"           "1"
        "item_diffusal_blade"           "1"
        "item_diffusal_blade_2"         "1"
        "shredder_timber_chain"         "1"
        "invoker_cold_snap_lod"         "1"
        "phoenix_sun_ray"               "1"
        "enraged_wildkin_tornado"       "1"
        "witch_doctor_death_ward"       "1"
        "shredder_chakram"              "1"
        "item_slippers_of_halcyon"      "1"
    }
}
