"use strict";
var backList = [
    { img: "abaddon.jpg" },
	{ img: "calmbeforehorn.jpg", author: "Eran Fowler", url: "http://eranfolio.deviantart.com/" },
	{ img: "dragonknight.jpg" },
	{ img: "drow.jpg" },
	{ img: "huskarfire.jpg" },
	{ img: "luna.jpg" },
	{ img: "pa.jpg" },
	{ img: "ta.jpg" },
	{ img: "tidehunter.jpg" },
	{ img: "ursa.jpg" },
	{ img: "bladeandbow.jpg" },
	{ img: "bristle.jpg", title: "\"Bristleback\"", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
	{ img: "ck.jpg", author: "Chaos Knight", url: "http://biggreenpepper.deviantart.com" },
	{ img: "clink.jpg", title: "\"Clinkz Bone\"", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
	{ img: "clockwerk.jpg", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
	{ img: "crystal_maiden.jpg", title: "\"Carry Maiden\"", author: "eric geusz", url: "http://entroz.deviantart.com" },
	{ img: "direancient.jpg" },
	{ img: "dirge.jpg", title: "\"Dirge\"", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
	{ img: "doom.jpg", title: "\"Doom\"", author: "eric geusz", url: "http://steamcommunity.com/id/sfmruls1337" },
	{ img: "doom2.jpg", title: "\"Doom\"", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
	{ img: "ember.jpg", title: "\"Ember Spirit\"", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
	{ img: "es.jpg", title: "\"Earth Spirit\"", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
	{ img: "io.jpg" },
	{ img: "jugg.jpg", title: "\"Jugg Sakura\"", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
	{ img: "jugg2.jpg", title: "\"Jugg Loading\"", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
	{ img: "kotl.jpg", title: "\"Keeper Of The Light\"", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
	{ img: "medusa.jpg", title: "\"Medusa\"", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
	{ img: "midlane.jpg" },
	{ img: "np.jpg", title: "\"Nature's Prophet\"", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
	{ img: "np2.jpg" },
	{ img: "nyx.jpg", title: "\"Nyx Assassin\"", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
	{ img: "od.jpg", title: "\"Obsidian Destroyer\"", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
	{ img: "pl.jpg", title: "\"Phantom Lancer\"", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
	{ img: "puck.jpg", title: "\"Puck\"", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
	{ img: "pureskill.jpg" },
	{ img: "radiantancient.jpg" },
	{ img: "razor.jpg", title: "\"Razor\"", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
	{ img: "roshan.jpg" },
	{ img: "rubick.jpg" },
	{ img: "sd.jpg", title: "\"Shadow Demon\"", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
	{ img: "sf.jpg", title: "\"Shadow Fiend\"", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
	{ img: "silencer.jpg", title: "\"Silencer\"", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
	{ img: "sky.jpg", title: "\"Skywrath Mage\"", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
	{ img: "slardar.jpg", title: "\"Slardar\"", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
	{ img: "sven.jpg", title: "\"The Fearless\"", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
	{ img: "venomancer.jpg", title: "\"Lesale Deathbringer\"", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
	{ img: "venomancer2.jpg", title: "\"Veno\"", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
	{ img: "vs.jpg", title: "\"Vengeful Spirit\"", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
	{ img: "bane_elemental.jpg", title: "\"Bane Elemental\"", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
	{ img: "Broodmother.jpg", title: "\"Broodmother\"", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
	{ img: "dark_seer.jpg", title: "\"Dark Seer\"", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
	{ img: "leshrac.jpg", title: "\"Leshrac\"", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
	{ img: "Lich.jpg", title: "\"Lich\"", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
	{ img: "night_stalker.jpg", title: "\"Night Stalker\"", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
	{ img: "Remembering_Skeleton_King.jpg", title: "\"Remebering Skeleton King\"", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
	{ img: "rikimaru.jpg", title: "\"Rikimaru\"", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
	{ img: "tiny.jpg", title: "\"Tiny\"", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
	{ img: "visage.jpg", title: "\"Visage\"", author: "BigGreenPepper", url: "http://biggreenpepper.deviantart.com" },
	{ img: "01vNZZh.jpg" },
	{ img: "0w5fIvW.jpg" },
	{ img: "10EpFKt.jpg" },
	{ img: "18wahBc.jpg" },
	{ img: "1iDvdyl.jpg" },
	{ img: "1uuO1Ne.jpg" },
	{ img: "2dADonb.jpg" },
	{ img: "2kq4mRt.jpg" },
	{ img: "2qHTqxv.jpg" },
	{ img: "37HkAJ7.jpg" },
	{ img: "3F2cNfH.jpg" },
	{ img: "3T3eBT1.jpg" },
	{ img: "3U4qJBL.jpg" },
	{ img: "48KDDrm.jpg" },
	{ img: "4aDEK0S.jpg" },
	{ img: "4gbsXmL.jpg" },
	{ img: "66BzmL4.jpg" },
	{ img: "69VHpcR.jpg" },
	{ img: "6gLmLwA.jpg" },
	{ img: "6ifDsFY.jpg" },
	{ img: "6IwGhpk.jpg" },
	{ img: "7b8DsDX.jpg" },
	{ img: "8gnJQEO.jpg" },
	{ img: "a3hPCA5.jpg" },
	{ img: "Ab12Qjq.jpg" },
	{ img: "aClD7hl.jpg" },
	{ img: "AtOJ2eb.jpg" },
	{ img: "bCw4j0I.jpg" },
	{ img: "BDifwi8.jpg" },
	{ img: "bnyI5LA.jpg" },
	{ img: "bsoGxxW.jpg" },
	{ img: "caecNCK.jpg" },
	{ img: "CiI0XKj.jpg" },
	{ img: "cTSfTjY.jpg" },
	{ img: "CuVjJEY.jpg" },
	{ img: "D4VD8iC.jpg" },
	{ img: "d65DpOz.jpg" },
	{ img: "dkwEzik.jpg" },
	{ img: "dv8I5qK.jpg" },
	{ img: "ECHLfTL.jpg" },
	{ img: "EiR7Qmk.jpg" },
	{ img: "fiC1NK4.jpg" },
	{ img: "fKb5Xp6.jpg" },
	{ img: "fL1VUqa.jpg" },
	{ img: "g4FLSnB.jpg" },
	{ img: "G6pqQhz.jpg" },
	{ img: "hgunBT9.jpg" },
	{ img: "hRjoUPK.jpg" },
	{ img: "HvxnzqD.jpg" },
	{ img: "HYxfOqq.jpg" },
	{ img: "ifjccyj.jpg" },
	{ img: "ik300X0.jpg" },
	{ img: "iReOLOQ.jpg" },
	{ img: "iusIdmx.jpg" },
	{ img: "jCYlSyZ.jpg" },
	{ img: "KDE96QY.jpg" },
	{ img: "kFvNmfz.jpg" },
	{ img: "kN4405O.jpg" },
	{ img: "KwAlKip.jpg" },
	{ img: "l1kqsKO.jpg" },
	{ img: "l8ScUAs.jpg" },
	{ img: "lzVZ52z.jpg" },
	{ img: "MChCjtr.jpg" },
	{ img: "MDoojh5.jpg" },
	{ img: "mKj682e.jpg" },
	{ img: "o39GFMj.jpg" },
	{ img: "oAGtTH7.jpg" },
	{ img: "oamIgBc.jpg" },
	{ img: "OhYnpwS.jpg" },
	{ img: "ozMgrbt.jpg" },
	{ img: "qdWoJki.jpg" },
	{ img: "qTlCw4p.jpg" },
	{ img: "r9z3Hax.jpg" },
	{ img: "RHPN6AF.jpg" },
	{ img: "RIMXelb.jpg" },
	{ img: "roLjhNM.jpg" },
	{ img: "RpBXJeG.jpg" },
	{ img: "ruuUQfE.jpg" },
	{ img: "RVqbv5M.jpg" },
	{ img: "s7iAIeB.jpg" },
	{ img: "S9H8WfR.jpg" },
	{ img: "SIkVU6w.jpg" },
	{ img: "SyFqypt.jpg" },
	{ img: "TBuwrFJ.jpg" },
	{ img: "THvsvOd.jpg" },
	{ img: "TnvrLOp.jpg" },
	{ img: "TrXWgsb.jpg" },
	{ img: "uLoTf74.jpg" },
	{ img: "Uv6XNJa.jpg" },
	{ img: "v7aroXO.jpg" },
	{ img: "Vec1ZOF.jpg" },
	{ img: "vgZ5hSn.jpg" },
	{ img: "VKPozqg.jpg" },
	{ img: "W0S1DKS.jpg" },
	{ img: "waeDOb0.jpg" },
	{ img: "wAzIPzQ.jpg" },
	{ img: "WkZiBaV.jpg" },
	{ img: "woCc0EE.jpg" },
	{ img: "WXqsXbU.jpg" },
	{ img: "x9CE3ex.jpg" },
	{ img: "XIfjupN.jpg" },
	{ img: "xKkoNpQ.jpg" },
	{ img: "xOaUZPY.jpg" },
	{ img: "XV0wYZW.jpg" },
	{ img: "xylKoQG.jpg" },
	{ img: "ZHrAZAZ.jpg" },
	{ img: "Znjx4Ls.jpg" },
	{ img: "ZRzGl3b.jpg" },
	{ img: "ZyegbCE.jpg" },	
];
