--------------------------------------------------------------------------------------------------------
--
--    Hero: Chen
--    Perk: 
--
--------------------------------------------------------------------------------------------------------
LinkLuaModifier( "modifier_npc_dota_hero_chen_perk", "abilities/hero_perks/npc_dota_hero_chen_perk.lua" ,LUA_MODIFIER_MOTION_NONE )
--------------------------------------------------------------------------------------------------------
if npc_dota_hero_chen_perk == nil then npc_dota_hero_chen_perk = class({}) end
--------------------------------------------------------------------------------------------------------
--    Modifier: modifier_npc_dota_hero_chen_perk        
--------------------------------------------------------------------------------------------------------
if modifier_npc_dota_hero_chen_perk == nil then modifier_npc_dota_hero_chen_perk = class({}) end
--------------------------------------------------------------------------------------------------------
function modifier_npc_dota_hero_chen_perk:IsPassive()
  return true
end
--------------------------------------------------------------------------------------------------------
function modifier_npc_dota_hero_chen_perk:IsHidden()
  return false
end
--------------------------------------------------------------------------------------------------------
function modifier_npc_dota_hero_chen_perk:RemoveOnDeath()
	return false
end
--------------------------------------------------------------------------------------------------------
-- Add additional functions
--------------------------------------------------------------------------------------------------------
function modifier_npc_dota_hero_chen_perk:DeclareFunctions()
  local funcs = {
    MODIFIER_EVENT_ON_ABILITY_START,
  }
  return funcs
end

function modifier_npc_dota_hero_chen_perk:OnAbilityStart(keys)
  
function modifier_npc_dota_hero_chen_perk:OnAbilityStart(keys)
  if IsServer() then
    local hero = self:GetCaster()
    local target = keys.target
    local ability = keys.ability
    if not chen_abilities then
      chen_abilities = {
      "slark_essence_shift_strength_lod",
      "slark_essence_shift_intellect_lod",
      "slark_essence_shift_agility_lod",
      "ursa_fury_swipes_lod"  ,
      "pudge_flesh_heap_agi",
      "pudge_flesh_heap_int",
      "silencer_global_break",
      "juggernaut_healing_ward_mana",
      "ogre_magi_multicast_lod",
      "death_prophet_witchcraft",
      "earthshaker_aftershock_lod",
      "tinker_rearm_lod",
      "abaddon_aphotic_shield",
      "abaddon_borrowed_time",
      "abaddon_death_coil",
      "abaddon_frostmourne",
      "abyssal_underlord_atrophy_aura",
      "abyssal_underlord_dark_rift",
      "abyssal_underlord_firestorm",
      "abyssal_underlord_pit_of_malice",
      "alchemist_acid_spray",
      "alchemist_chemical_rage",
      "alchemist_goblins_greed",
      "alchemist_unstable_concoction",
      "ancient_apparition_chilling_touch",
      "ancient_apparition_cold_feet",
      "ancient_apparition_ice_blast",
      "ancient_apparition_ice_vortex",
      "antimage_blink",
      "antimage_mana_break",
      "antimage_mana_void",
      "antimage_spell_shield",
      "axe_battle_hunger",
      "axe_berserkers_call",
      "axe_counter_helix",
      "axe_culling_blade",
      "bane_brain_sap",
      "bane_enfeeble",
      "bane_fiends_grip",
      "bane_nightmare",
      "batrider_firefly",
      "batrider_flamebreak",
      "batrider_flaming_lasso",
      "batrider_sticky_napalm",
      "beastmaster_call_of_the_wild_boar",
      "beastmaster_call_of_the_wild"     ,
      "beastmaster_inner_beast",
      "beastmaster_primal_roar",
      "beastmaster_wild_axes",
      "bloodseeker_blood_bath",
      "bloodseeker_bloodrage",
      "bloodseeker_rupture",
      "bloodseeker_thirst_lod",
      "bounty_hunter_jinada",
      "bounty_hunter_shuriken_toss",
      "bounty_hunter_track",
      "bounty_hunter_wind_walk",
      "brewmaster_drunken_brawler",
      "brewmaster_drunken_haze",
      "brewmaster_primal_split",
      "brewmaster_thunder_clap",
      "bristleback_bristleback",
      "bristleback_quill_spray",
      "bristleback_viscous_nasal_goo",
      "bristleback_warpath",
      "broodmother_incapacitating_bite",
      "broodmother_insatiable_hunger",
      "broodmother_spawn_spiderlings",
      "broodmother_spin_web",
      "centaur_double_edge",
      "centaur_hoof_stomp",
      "centaur_return",
      "centaur_stampede",
      "chaos_knight_chaos_bolt",
      "chaos_knight_chaos_strike",
      "chaos_knight_phantasm",
      "chaos_knight_reality_rift",
      "chen_hand_of_god",
      "chen_holy_persuasion",
      "chen_penitence",
      "chen_test_of_faith",
      "chen_test_of_faith_teleport",
      "clinkz_death_pact",
      "clinkz_searing_arrows",
      "clinkz_strafe",
      "clinkz_wind_walk",
      "crystal_maiden_brilliance_aura",
      "crystal_maiden_crystal_nova",
      "crystal_maiden_freezing_field",
      "crystal_maiden_frostbite",
      "dark_seer_ion_shell",
      "dark_seer_surge",
      "dark_seer_vacuum",
      "dark_seer_wall_of_replica",
      "dazzle_poison_touch",
      "dazzle_shadow_wave",
      "dazzle_shallow_grave",
      "dazzle_weave",
      "death_prophet_carrion_swarm",
      "death_prophet_exorcism",
      "death_prophet_silence",
      "disruptor_glimpse",
      "disruptor_kinetic_field",
      "disruptor_static_storm",
      "disruptor_thunder_strike",
      "doom_bringer_doom",
      "doom_bringer_devour_lod"  ,
      "doom_bringer_scorched_earth",
      "dragon_knight_breathe_fire",
      "dragon_knight_dragon_blood",
      "dragon_knight_dragon_tail",
      "dragon_knight_elder_dragon_form",
      "drow_ranger_frost_arrows",
      "drow_ranger_marksmanship",
      "drow_ranger_trueshot",
      "drow_ranger_wave_of_silence",
      "earth_spirit_boulder_smash",
      "earth_spirit_geomagnetic_grip",
      "earth_spirit_magnetize",
      "earth_spirit_rolling_boulder",
      "earthshaker_echo_slam",
      "earthshaker_enchant_totem",
      "earthshaker_fissure",
      "elder_titan_ancestral_spirit",
      "elder_titan_earth_splitter",
      "elder_titan_echo_stomp",
      "elder_titan_natural_order",
      "ember_spirit_activate_fire_remnant",
      "ember_spirit_fire_remnant",
      "ember_spirit_flame_guard",
      "ember_spirit_searing_chains",
      "ember_spirit_sleight_of_fist",
      "enchantress_enchant",
      "enchantress_impetus",
      "enchantress_natures_attendants",
      "enchantress_untouchable",
      "enigma_black_hole",
      "enigma_demonic_conversion",
      "enigma_malefice",
      "enigma_midnight_pulse",
      "faceless_void_chronosphere",
      "faceless_void_time_lock",
      "faceless_void_time_walk",
      "furion_force_of_nature",
      "furion_sprout",
      "furion_teleportation",
      "furion_wrath_of_nature",
      "gyrocopter_call_down",
      "gyrocopter_flak_cannon",
      "gyrocopter_homing_missile",
      "gyrocopter_rocket_barrage",
      "huskar_berserkers_blood",
      "huskar_burning_spear",
      "huskar_inner_vitality",
      "huskar_life_break",
      "invoker_alacrity_lod",
      "invoker_chaos_meteor_lod",
      "invoker_cold_snap_lod",
      "invoker_emp_lod",
      "invoker_forge_spirit_lod",
      "invoker_ghost_walk_lod",
      "invoker_ice_wall_lod",
      "invoker_sun_strike_lod",
      "invoker_tornado_lod",
      "jakiro_dual_breath",
      "jakiro_ice_path",
      "jakiro_liquid_fire",
      "jakiro_macropyre",
      "juggernaut_blade_dance",
      "juggernaut_blade_fury",
      "juggernaut_healing_ward",
      "juggernaut_omni_slash",
      "keeper_of_the_light_blinding_light_lod",
      "keeper_of_the_light_chakra_magic",
      "keeper_of_the_light_illuminate",
      "keeper_of_the_light_mana_leak",
      "keeper_of_the_light_recall_lod",
      "keeper_of_the_light_spirit_form",
      "kunkka_ghostship",
      "kunkka_tidebringer",
      "kunkka_torrent",
      "kunkka_x_marks_the_spot",
      "legion_commander_duel",
      "legion_commander_moment_of_courage",
      "legion_commander_overwhelming_odds",
      "legion_commander_press_the_attack",
      "leshrac_diabolic_edict",
      "leshrac_lightning_storm",
      "leshrac_pulse_nova",
      "leshrac_split_earth",
      "lich_chain_frost",
      "lich_dark_ritual",
      "lich_frost_armor",
      "lich_frost_nova",
      "life_stealer_feast",
      "life_stealer_infest",
      "life_stealer_control"  ,
      "life_stealer_open_wounds",
      "life_stealer_rage",
      "lina_dragon_slave",
      "lina_fiery_soul",
      "lina_laguna_blade",
      "lina_light_strike_array",
      "lion_finger_of_death",
      "lion_impale",
      "lion_mana_drain",
      "lion_voodoo",
      "lone_druid_rabid",
      "lone_druid_spirit_bear",
      "lone_druid_true_form",
      "luna_eclipse",
      "luna_lucent_beam",
      "luna_lunar_blessing",
      "luna_moon_glaive",
      "lycan_feral_impulse",
      "lycan_howl",
      "lycan_shapeshift",
      "lycan_summon_wolves",
      "magnataur_empower",
      "magnataur_reverse_polarity",
      "magnataur_shockwave",
      "magnataur_skewer",
      "medusa_mana_shield",
      "medusa_mystic_snake",
      "medusa_split_shot",
      "medusa_stone_gaze",
      "meepo_earthbind",
      "meepo_geostrike",
      "meepo_poof",
      "mirana_arrow",
      "mirana_invis",
      "mirana_leap",
      "mirana_starfall_lod",
      "morphling_adaptive_strike",
      "morphling_morph_agi",
      "morphling_morph_str",
      "morphling_replicate",
      "morphling_waveform",
      "naga_siren_ensnare",
      "naga_siren_mirror_image",
      "naga_siren_rip_tide",
      "naga_siren_song_of_the_siren",
      "necrolyte_death_pulse",
      "necrolyte_heartstopper_aura",
      "necrolyte_reapers_scythe",
      "necrolyte_sadist",
      "nevermore_dark_lord",
      "nevermore_necromastery",
      "nevermore_requiem",
      "nevermore_shadowraze1",
      "nevermore_shadowraze2",
      "nevermore_shadowraze3",
      "night_stalker_crippling_fear",
      "night_stalker_darkness",
      "night_stalker_hunter_in_the_night",
      "night_stalker_void",
      "nyx_assassin_impale",
      "nyx_assassin_mana_burn",
      "nyx_assassin_spiked_carapace",
      "nyx_assassin_vendetta",
      "obsidian_destroyer_arcane_orb",
      "obsidian_destroyer_astral_imprisonment",
      "obsidian_destroyer_essence_aura_lod",
      "obsidian_destroyer_sanity_eclipse",
      "ogre_magi_bloodlust",
      "ogre_magi_fireblast",
      "ogre_magi_ignite",
      "omniknight_degen_aura",
      "omniknight_guardian_angel",
      "omniknight_purification",
      "omniknight_repel",
      "oracle_false_promise",
      "oracle_fates_edict",
      "oracle_fortunes_end",
      "oracle_purifying_flames",
      "phantom_assassin_blur",
      "phantom_assassin_coup_de_grace",
      "phantom_assassin_phantom_strike",
      "phantom_assassin_stifling_dagger",
      "phantom_lancer_doppelwalk",
      "phantom_lancer_juxtapose",
      "phantom_lancer_phantom_edge",
      "phantom_lancer_spirit_lance",
      "phoenix_fire_spirits",
      "phoenix_icarus_dive",
      "phoenix_sun_ray",
      "phoenix_supernova",
      "puck_dream_coil",
      "puck_ethereal_jaunt",
      "puck_illusory_orb",
      "puck_phase_shift",
      "puck_waning_rift",
      "pudge_dismember",
      "pudge_flesh_heap",
      "pudge_meat_hook",
      "pudge_rot",
      "pugna_decrepify",
      "pugna_life_drain",
      "pugna_nether_blast",
      "pugna_nether_ward",
      "queenofpain_blink",
      "queenofpain_scream_of_pain",
      "queenofpain_shadow_strike",
      "queenofpain_sonic_wave",
      "rattletrap_battery_assault",
      "rattletrap_hookshot",
      "rattletrap_power_cogs",
      "rattletrap_rocket_flare",
      "razor_eye_of_the_storm",
      "razor_plasma_field",
      "razor_static_link",
      "razor_unstable_current",
      "riki_blink_strike",
      "riki_smoke_screen",
      "riki_backstab_lod",
      "rubick_fade_bolt",
      "rubick_null_field",
      "rubick_telekinesis",
      "sandking_burrowstrike",
      "sandking_epicenter",
      "sandking_sand_storm",
      "shadow_demon_disruption",
      "shadow_demon_shadow_poison",
      "shadow_demon_shadow_poison_release",
      "shadow_demon_soul_catcher",
      "shadow_shaman_ether_shock",
      "shadow_shaman_mass_serpent_ward",
      "shadow_shaman_shackles",
      "shadow_shaman_voodoo",
      "shredder_chakram",
      "shredder_reactive_armor",
      "shredder_timber_chain",
      "shredder_whirling_death",
      "silencer_curse_of_the_silent",
      "silencer_glaives_of_wisdom",
      "silencer_global_silence",
      "silencer_last_word",
      "skeleton_king_hellfire_blast",
      "skeleton_king_mortal_strike",
      "skeleton_king_reincarnation",
      "skeleton_king_vampiric_aura",
      "skywrath_mage_ancient_seal",
      "skywrath_mage_arcane_bolt",
      "skywrath_mage_concussive_shot",
      "skywrath_mage_mystic_flare",
      "slardar_amplify_damage",
      "slardar_bash",
      "slardar_slithereen_crush",
      "slardar_sprint",
      "slark_dark_pact",
      "slark_pounce",
      "slark_essence_shift",
      "slark_shadow_dance",
      "sniper_assassinate",
      "sniper_headshot",
      "sniper_shrapnel",
      "sniper_take_aim",
      "spectre_desolate",
      "spectre_dispersion",
      "spectre_haunt",
      "spectre_reality",
      "spectre_spectral_dagger",
      "spirit_breaker_charge_of_darkness",
      "spirit_breaker_empowering_haste",
      "spirit_breaker_greater_bash",
      "spirit_breaker_nether_strike",
      "storm_spirit_ball_lightning",
      "storm_spirit_electric_vortex",
      "storm_spirit_overload",
      "storm_spirit_static_remnant",
      "sven_gods_strength",
      "sven_great_cleave",
      "sven_storm_bolt",
      "sven_warcry",
      "techies_focused_detonate",
      "techies_land_mines",
      "techies_remote_mines",
      "techies_stasis_trap",
      "techies_suicide",
      "templar_assassin_meld",
      "templar_assassin_psi_blades",
      "templar_assassin_psionic_trap",
      "templar_assassin_refraction",
      "templar_assassin_trap",
      "terrorblade_conjure_image",
      "terrorblade_metamorphosis",
      "terrorblade_reflection",
      "terrorblade_sunder",
      "tidehunter_anchor_smash",
      "tidehunter_gush",
      "tidehunter_kraken_shell",
      "tidehunter_ravage",
      "tinker_heat_seeking_missile",
      "tinker_laser",
      "tinker_march_of_the_machines",
      "tiny_avalanche",
      "tiny_craggy_exterior",
      "tiny_grow_lod",
      "tiny_toss",
      "treant_eyes_in_the_forest",
      "treant_leech_seed",
      "treant_living_armor",
      "treant_natures_guise",
      "treant_overgrowth",
      "troll_warlord_battle_trance",
      "troll_warlord_berserkers_rage",
      "troll_warlord_fervor",
      "troll_warlord_whirling_axes_ranged",
      "tusk_frozen_sigil",
      "tusk_ice_shards",
      "tusk_snowball",
      "tusk_walrus_punch",
      "undying_decay",
      "undying_flesh_golem",
      "undying_soul_rip",
      "undying_tombstone",
      "ursa_earthshock",
      "ursa_enrage",
      "ursa_fury_swipes"  ,
      "ursa_overpower",
      "vengefulspirit_command_aura",
      "vengefulspirit_magic_missile",
      "vengefulspirit_nether_swap",
      "vengefulspirit_wave_of_terror",
      "venomancer_plague_ward",
      "venomancer_poison_nova",
      "venomancer_poison_sting",
      "venomancer_venomous_gale",
      "viper_corrosive_skin",
      "viper_nethertoxin",
      "viper_poison_attack",
      "viper_viper_strike",
      "visage_grave_chill",
      "visage_gravekeepers_cloak",
      "visage_summon_familiars",
      "warlock_fatal_bonds",
      "warlock_rain_of_chaos",
      "warlock_shadow_word",
      "warlock_upheaval",
      "weaver_geminate_attack",
      "weaver_shukuchi",
      "weaver_the_swarm",
      "weaver_time_lapse",
      "windrunner_focusfire",
      "windrunner_powershot",
      "windrunner_shackleshot",
      "windrunner_windrun",
      "wisp_overcharge",
      "wisp_relocate",
      "wisp_spirits",
      "wisp_tether",
      "witch_doctor_death_ward",
      "witch_doctor_maledict",
      "witch_doctor_paralyzing_cask",
      "witch_doctor_voodoo_restoration",
      "zuus_arc_lightning",
      "zuus_lightning_bolt",
      "zuus_static_field",
      "zuus_thundergods_wrath",
      "life_stealer_consume",
      "shadow_demon_demonic_purge",
      "shredder_chakram_2",
      "earth_spirit_petrify",
      "earth_spirit_stone_caller",
      "winter_wyvern_arctic_burn",
      "winter_wyvern_splinter_blast",
      "winter_wyvern_cold_embrace",
      "winter_wyvern_winters_curse",
      "life_stealer_assimilate",
      "morphling_hybrid",
      "nyx_assassin_burrow",
      "tusk_walrus_kick",
      "arc_warden_flux",
      "arc_warden_magnetic_field",
      "arc_warden_spark_wraith",
      "arc_warden_tempest_double",
      "death_prophet_spirit_siphon",
      "doom_bringer_infernal_blade",
      "faceless_void_time_dilation",
      "lone_druid_savage_roar",
      "riki_tricks_of_the_trade",
      "lone_druid_true_form_battle_cry",
      "brewmaster_earth_hurl_boulder",
      "brewmaster_earth_pulverize",
      "brewmaster_storm_wind_walk",
      "brewmaster_storm_dispel_magic",
      "brewmaster_fire_permanent_immolation",
      "brewmaster_storm_cyclone",
      "ogre_magi_unrefined_fireblast",
      "meepo_divided_we_stand",
      "tinker_rearm",
      "riki_permanent_invisibility",
      "ogre_magi_multicast",
      "earthshaker_aftershock",
      "alpha_wolf_command_aura"    ,
      "alpha_wolf_critical_strike"    ,
      "beastmaster_boar_poison"    ,
      "beastmaster_greater_boar_poison"    ,
      "big_thunder_lizard_frenzy"    ,
      "big_thunder_lizard_slam"    ,
      --"big_thunder_lizard_wardrums_aura"      ,              
      "black_dragon_splash_attack"    ,
      "black_dragon_fireball_lod"    ,
      "blue_dragonspawn_overseer_devotion_aura"    ,
      "blue_dragonspawn_overseer_evasion"    ,
      "blue_dragonspawn_sorcerer_evasion"    ,
      "centaur_khan_endurance_aura"    ,
      "centaur_khan_war_stomp"    ,
      "dark_troll_warlord_ensnare"    ,
      "dark_troll_warlord_raise_dead"    ,
      "enraged_wildkin_tornado"    ,
      "enraged_wildkin_toughness_aura"    ,
      "lone_druid_spirit_bear_demolish"    ,
      "lone_druid_spirit_bear_entangle"    ,
      "lone_druid_spirit_bear_return_lod"    ,
      "satyr_hellcaller_shockwave"    ,
      "satyr_hellcaller_unholy_aura"    ,
      "satyr_soulstealer_mana_burn"    ,
      "satyr_trickster_purge"    ,
      "necronomicon_archer_aoe_lod"    ,
      "necronomicon_archer_mana_burn_lod"    ,
      "necronomicon_warrior_last_will_lod"    ,
      "necronomicon_warrior_mana_burn_lod"    ,
      "roshan_slam"    ,
      "roshan_spell_block"    ,
      "roshan_spell_block_lod"    ,
      "roshan_bash"    ,
      "warlock_golem_flaming_fists"    ,
      "warlock_golem_permanent_immolation"    ,
      "warlock_golem_permanent_immolation_lod",
      "forest_troll_high_priest_heal"    ,
      "ghost_frost_attack"    ,
      "giant_wolf_critical_strike"    ,
      "gnoll_assassin_envenomed_weapon"    ,
      "granite_golem_hp_aura"    ,
      "harpy_storm_chain_lightning"    ,
      "kobold_taskmaster_speed_aura"    ,
      "lycan_summon_wolves_critical_strike"    ,
      "ogre_magi_frost_armor"    ,
      "polar_furbolg_ursa_warrior_thunder_clap"    ,
      "undying_tombstone_zombie_deathstrike"    ,
      "mud_golem_hurl_boulder"    ,
      "broodmother_poison_sting"    ,
      "visage_summon_familiars_stone_form"    ,
      "imba_dazzle_shallow_grave",
      "imba_omniknight_degen_aura"   ,
      "imba_omniknight_purification" ,
      "holdout_arcane_aura",
      "holdout_culling_blade",
      "holdout_gladiators_unite",
      "holdout_gods_strength",
      "holdout_omnislash",
      "zuus_thundergods_vengeance",
      "aether_range_lod"    ,
      "octarine_vampirism_lod"    ,
      "force_dash_lod"    ,
      "shards_of_truesight_lod"    ,
      "true_random_lod_1"   ,
      "true_random_lod_2"   ,
      "true_random_lod_3"   ,
      "true_random_lod_4"   ,
      "true_random_lod_5"   ,
      "true_random_lod_6"   ,
      "cherub_sleep_cloud"     ,
      "cherub_synthesis"     ,
      "cherub_explosive_spore"     ,
      "cherub_flower_garden"     ,
      "garden_white_flower_base"     ,
      "garden_red_flower_base"     ,
      "garden_pink_blossom_base"     ,
      "garden_blue_blossom_base"     ,
      "garden_yellow_daisy_base"     ,
      "garden_purple_lotus_base"     ,
      "zulf_cyclone_trap"     ,
      "zulf_jet_stream"     ,
      "zulf_gale_force"     ,
      "zulf_typhoon"     ,
      "imba_tower_aegis"  ,
      "imba_tower_atrophy"  ,
      "imba_tower_berserk"  ,
      "imba_tower_chrono"  ,
      "imba_tower_disease"  ,
      "imba_tower_essence_drain"  ,
      "imba_tower_fervor"  ,
      "imba_tower_force"  ,
      "imba_tower_forest"  ,
      "imba_tower_grievous_wounds"  ,
      "imba_tower_hex_aura"  ,
      "imba_tower_laser"  ,
      "imba_tower_machinegun"  ,
      "imba_tower_mana_burn"  ,
      "imba_tower_mana_flare"  ,
      "imba_tower_mindblast"  ,
      "imba_tower_multihit"  ,
      "imba_tower_nature"  ,
      "imba_tower_permabash"  ,
      "imba_tower_plague"  ,
      "imba_tower_reality"  ,
      "imba_tower_salvo"  ,
      "imba_tower_self_repair"  ,
      "imba_tower_sniper"  ,
      "imba_tower_spacecow"  ,
      "imba_tower_spell_shield"  ,
      "imba_tower_split"  ,
      "imba_tower_thorns"  ,
      "imba_tower_vicious"  ,

      }
    end

    if ability:GetAbilityName() == "chen_test_of_faith_teleport" and target:IsCreep() then
      -- Setting the table value one further
      if not chen_abilities_count then chen_abilities_count = 1 else chen_abilities_count =  chen_abilities_count + 1 end

      if chen_abilities_count > 1 then 
        target:RemoveAbility(chen_abilities[chen_abilities_count -1])
      end

      target:AddAbility(chen_abilities[chen_abilities_count])
      target:FindAbilityByName(chen_abilities[chen_abilities_count]):UpgradeAbility(true)
    end
  end
end                          

